### ISSUE TITLE
Better indentation for blade directive with complex multi-line options

### ISSUE THREAD

**Issue by cweiske** [fxbois/web-mode#1002]
Custom directives in blade templates often take many parameters. Currently they do not get indented at all:

```
@field([
'label' => 'Foo',
'values' => ['bar']
])
```

It would be nice if they would get indented the following way:

```
@field([
    'label' => 'Foo',
    'values' => ['bar']
])
```

Highlighting also does not work after the first `@field` line - the following lines are not highlighted at all.

Inside the `()` of a blade directive, PHP syntax highlighting should be used IMO.

**Comment by fxbois** [comment]
Have you identified other indentation issues ?

**Comment by cweiske** [comment]
Yes, I have: Nested directives do not always get indented.

This works:
```
@section('content')
    Foo
@endsection
```

But custom directives do not:
```
@sectionInner(['name' => 'Foo'])
<h1>foo</h1>
@endsectionInner
```

**Comment by fxbois** [comment]
@cweiske everything seems to work well with the last version of web-mode
