### ISSUE TITLE
Blade: Highlighting after @directive() broken

### ISSUE THREAD

**Issue by cweiske** [fxbois/web-mode#1004]
When a blade directive is used inside a line (not standalone), the highlighting after the directive is closed is broken:

![2018-06-20 emacs blade directive highlighting](https://user-images.githubusercontent.com/59036/41640670-c9e07a38-7462-11e8-8487-2ed247c23e61.png)

```
<span class="label">@lang('consumption.this_month')</span><span class="colon">:</span>
```

The closing `span` and the following tags on this line are not highlighted as HTML anymore. The `)` closing the directive should already reset the highlighting mode.

**Comment by fxbois** [comment]
@cweiske seems to work here. Are you sure you have the latest version of web-mode ?

**Comment by cweiske** [comment]
Oh, I was using a version from 2018-03-*. Sorry!
