### ISSUE TITLE
[js] switch keyword

### ISSUE THREAD

**Issue by Nondv** [fxbois/web-mode#1006]
Hi!

```javascript
function Switch() {
  return whatever;
}
```

In `web-mode` if I `tab` on the second line it will intend it to 4 spaces because of `Switch` name (normal indentation is set to 2).

**Comment by Nondv** [comment]
More than that. It appears that any name with "switch" within it triggers described behavior

**Comment by fxbois** [comment]
@Nondv fixed with last commit
