### ISSUE TITLE
function to transform single line tags to multi line?

### ISSUE THREAD

**Issue by JJPandari** [fxbois/web-mode#1009]
Does this function exist in web-mode already?  

It transforms tags from

```html
<div><span>text</span></div>
```

to

```html
<div>
  <span>
    text
  </span>
</div>
```

**Comment by DoMiNeLa10** [comment]
Great idea! I've been doing this sort of thing by hand, and this would speed things up for me.

**Comment by fxbois** [comment]
@JJPandari it is called ```web-mode-element-extract```
