### ISSUE TITLE
JSX after as arrow function body w/o parens or semi breaks indentation and highlighting

### ISSUE THREAD

**Issue by aaronjensen** [fxbois/web-mode#1010]
Example:

```js
const Foo = () =>
  <div>
test
</div>
```

If you end with a `;` or surround the jsx with parens starting on the variable declaration line, it works fine.

**Comment by fxbois** [comment]
@aaronjensen at the moment, the final ```;``` is required. It would require a lot of work to make it optional.

**Comment by aaronjensen** [comment]
I believe prettier tends to wrap it in parens, so this is probably fine for most people.
