### ISSUE TITLE
Left padding custom types don't allow setting nil (for  #766)

### ISSUE THREAD

**Issue by porglezomp** [fxbois/web-mode#1011]
#766 does exactly what I want for my JS, but the declared `:type` doesn't allow entering `nil` in the custom interface.

**Comment by fxbois** [comment]
you should enter 0

**Comment by porglezomp** [comment]
0 does something different from nil. 0 leaves it indented at the same amount as the tag, nil aligns it all the way to the left.

With 0:
```html
<html>
  <head>
    <script>
    alert("Hello");
    </script>
  </head>
</html>
```

With nil:
```html
<html>
  <head>
    <script>
alert("Hello");
    </script>
  </head>
</html>
```

**Comment by porglezomp** [comment]
Done, it's #1012
