### ISSUE TITLE
web-mode with Vue.js and stylus

### ISSUE THREAD

**Issue by M-Gregoire** [fxbois/web-mode#1013]
I'm using vue.js and [stylus](http://stylus-lang.com/) but web-mode is having a lot of trouble correctly indenting the CSS part.
_example.vue_ (This is what the correct indent should look likes. Copying it in web-mode breaks it)
```
<template>
</template>
<script>
</script>
<style lang="stylus" scoped>
   .test-class
     min-height: 100px
     .sub-test-class
       min-height: 150px
</style>
```

2 problems I've noticed : 

-  The *scoped* in `<style lang="stylus" scoped>` seems to break the ability of web-mode to detect the stylus CSS style (This is true with or without the stylus part. Please see [scoped css](https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles) in vue.js).
-  In Stylus, brackets are optional and the indentation alone is sufficient but web-mode constantly change : 
```
 .test-class
   min-height: 100px
   .sub-test
     min-height: 150px
```
to
```
 .test-class
   min-height: 100px
 .sub-test
   min-height: 150px
```

**Comment by fxbois** [comment]
@M-Gregoire it is now fixed

**Comment by M-Gregoire** [comment]
Awesome, thank you!
