### ISSUE TITLE
web-mode-dom-xpath return paths in all lower case

### ISSUE THREAD

**Issue by showgood** [fxbois/web-mode#1015]
for eg, we have a xml file with following content:
```xml
<Root>
    <child1>abc</child1>
    <Child2>def</child2>
</Root>
```

While cursor is on tag <Child2>, with command `web-mode-dom-xpath`, it would return `/root/child2` instead of `/Root/Child2`,  basically convert all the tags on the path to lower case instead of keeping its original ones.

**Comment by fxbois** [comment]
@showgood fixed on  master

**Comment by showgood** [comment]
thanks
