### ISSUE TITLE
Indentation for {| |} Flow "exact type" delimiters

### ISSUE THREAD

**Issue by keunwoo** [fxbois/web-mode#1016]
After extensive experimentation with various options, I've concluded that web-mode (via its derivative [flow-mode](https://github.com/syohex/flow-mode)) is currently the best option for editing Flow-typed JavaScript code that contains embedded JSX in Emacs. Thanks for writing such a great, flexible mode! I bet you didn't even know that this was the best mode for this purpose.

However, there's still one remaining pain point for me: [Flow exact object types](https://flow.org/en/docs/types/objects/#toc-exact-object-types), which have the form

```
type T = {|
    x: number,
|};
```

are currently indented improperly by web-mode. If I don't customize anything, I get this:

```
type T = {|
          x: number,
         |};
```

Oddly enough, if I customize `web-mode-indentation-params` with `("lineup-ternary" . nil)`, then I get this, which is an improvement:

```
type T = {|
    x: number,
    |};
```

I would love to be able to fix this last little thing.

Strictly speaking I suppose this is a flow-mode issue, but if you look at the source code for that mode, you can see that it basically delegates everything related to indentation to web-mode. All it really adds is some helper functions for invoking the Flow typechecker.

I'm happy to spend some time hacking on this myself, but from my initial look at the source for web-mode, the best way to obtain the indentation behavior that I want wasn't obvious to me. Adding a "flow" engine with additional control blocks or auto pairs doesn't seem to fix the issue for me, so I suspect that's the wrong track. [This stanza which parses some JavaScript syntax](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L7852) looks promising, but maybe you have some tips for how to do what I want in a clean way?

**Comment by keunwoo** [comment]
Well, I figured out one way to do it. It feels like a better way would be to hack the part of the code that handles indentation for curly braces to also treat {| |} as a curly brace pair, but anyway this seems to work. Let me know what you think.

**Comment by fxbois** [comment]
@keunwoo I've pushed a fix
