### ISSUE TITLE
Wrong indentation of PHP class methods with HTML code.

### ISSUE THREAD

**Issue by rin-kinokocan** [fxbois/web-mode#1019]
I wrote a PHP class with a method which outputs HTML.
To output HTML, I wrote HTML outside of php blocks.

What I expected was:
```
<?php
class Test{
    public function print_div(){
?>
    <div>div</div>
<?php
    }
}
?>
```
Actual indentation is:
```
<?php
class Test{
    public function print_div(){
?>
    <div>div</div>
<?php
}
}
?>
```
As you can see, the closing bracket of the class method is not indented.
I think this may be caused by ignorance of the first left bracket.
`class Test{ <-this one?`

 
If this issue is fixed, web-mode will surely be the best major mode ever!

I'm using web-mode version 16.0.15 on Emacs 25.1.1 (Linux).
The output of web-mode-debug was
> --- WEB-MODE DEBUG BEG ---
> versions: emacs(25.1) web-mode("16.0.15")
> vars: engine(nil) minor(nil) content-type("") file("*About GNU Emacs*")
> system: window(x) config("x86_64-pc-linux-gnu")
> colors: fg(nil) bg(nil) 
> minor modes: (buffer-read-only global-eldoc-mode desktop-save-mode winner-mode)
> vars:
> web-mode-enable-current-column-highlight=nil 
> web-mode-enable-current-element-highlight=nil 
> indent-tabs-mode=t 
> --- WEB-MODE DEBUG END ---
>

**Comment by fxbois** [comment]
@rin-kinokocan Hi I do not deal with this king of syntax.
Sorry
