### ISSUE TITLE
JavaScript wrong indentation for if, for, etc.

### ISSUE THREAD

**Issue by MetroWind** [fxbois/web-mode#1020]
If I put parenthesis in a new line after `if`, the parenthesis acquires an extra indentation. So instead of the normal

    if(true)
    {
        …

It indents to 

    if(true)
        {
            …

The same goes with `for`. This is probably wrong because in other cases like class and function definitions, the parenthesis is aligned with the line above.

I have web-mode version 16.0.15 on Emacs 26.1.

**Comment by fxbois** [comment]
@MetroWind it is now fixed

**Comment by MetroWind** [comment]
@fxbois Indeed! Thank you!
