### ISSUE TITLE
Indent of arrow functions in jsx refs

### ISSUE THREAD

**Issue by gormv** [fxbois/web-mode#1022]
Hi!

Is it possible to indent arrow functions with 2 spaces instead of 4?

I have following settings + prelude:

(setq web-mode-attr-indent-offset t)
(setq web-mode-code-indent-offset 2)
(setq web-mode-indent-style 2)

And want indent like this:

````js
<input
          type="file"
          ref={component => {
            this.inputFile = component; // <--- 2 spaces
          }}
````

But web-mode indent like this:

````js
 <input
          type="file"
          ref={component => {
              this.inputFile = component; // <--- 4 spaces
          }}
````
Thanks for help on correct setting for controlling this indent!

**Comment by fxbois** [comment]
@gormv it is now solved
