### ISSUE TITLE
substitute-key-definition: Lisp nesting exceeds ‘max-lisp-eval-depth’

### ISSUE THREAD

**Issue by brandelune** [fxbois/web-mode#1028]
I've used melpa version as well as the latest stable version, manually installed, and I keep running in the error. It goes away when I disable web-mode. Also, automatic tag closing used to work until recently and now I can't have it. The 2 phenomenons appeared at the same time.

**Comment by fxbois** [comment]
@brandelune can you try with an empty .emacs ?

**Comment by fxbois** [comment]
Please reopen when you have some more info

**Comment by brandelune** [comment]
Yes, will do. I'm sorry I was busy with work and right now I've opted for nxml, which is less practical. I'll get back to web-mode and investigate.
