### ISSUE TITLE
[blade] no indentation with @switch

### ISSUE THREAD

**Issue by alu-** [fxbois/web-mode#1029]
Seems that there is missing support for `@switch` in the blade engine.
Edit: Link indented example on [gist](https://gist.github.com/alu-/4d0d7846f3cf106d9fab218ccc894195)
```
@switch ($so_variable)
@case ("much switch")
@include ("very not indent")
{{ $so_variable }}
@break
@endswitch
```

**Comment by fxbois** [comment]
@alu- could you post an example (indented) on gist please.

**Comment by alu-** [comment]
> 
> 
> @alu- could you post an example (indented) on gist please.

Sure, here you go. https://gist.github.com/alu-/4d0d7846f3cf106d9fab218ccc894195
Whether or not line 2 (`@case`) should be indented or in same level as `@switch` I leave up to you.

**Comment by fxbois** [comment]
@alu- I've pushed a fix
