### ISSUE TITLE
Incorrect parsing in Razor

### ISSUE THREAD

**Issue by kschwarz1116** [fxbois/web-mode#1030]
I have the following in `temp.scala.html`:
`<a>@foo</a>`
and the following in my .emacs:
`(setq web-mode-engines-alist '(("razor" . "\\.scala\\.html")))`

It looks like web-mode is interpreting `@foo</a>` as a code block instead of just `@foo`.

<img width="108" alt="screen shot 2018-12-06 at 1 10 02 pm" src="https://user-images.githubusercontent.com/2141220/49603102-4e3f2700-f958-11e8-98e6-885459c492d4.png">

**Comment by fxbois** [comment]
@kschwarz1116 have you upgraded to the last version of web-mode ?

**Comment by kschwarz1116** [comment]
Looks like it works as expected in 20181208.2046 (but not 16). I'm going to close this.
