### ISSUE TITLE
Indentation for blade component aliases

### ISSUE THREAD

**Issue by gjm** [fxbois/web-mode#1034]
It would be nice to be able to, somehow, specify a set of component alias names so that they could be correctly  indented/nested.

For example, given two component aliases, `row` and `col`, the following code:
```
@row
@col
column 1
@endcol
@col
column 2
@endcol
@endrow
```

should be rendered as:

```
@row
  @col
    column 1
  @endcol
  @col
    column 2
  @endcol
@endrow
```

Is it possible to specify some list of component aliases for which indentation should work like this?

**Comment by fxbois** [comment]
@gjm the last commit brings this feature.
You can add control blocks with 
```
(setq web-mode-extra-control-blocks
      '(("blade" . ("row" "col"))))
```

**Comment by gjm** [comment]
Hi.

I've tried it but it doesn't work for me. I've setup web-mode using
use-package so maybe I'm doing something wrong. Here's my configuration
snippet:

(use-package web-mode
  :ensure t

  :mode (("\\.ctp\\'" . web-mode)
         ("\\.blade\\.php\\'" . web-mode)
         ("\\.s?css\\'" . web-mode))

  :config
  (setq web-mode-engines-alist
        '(("php"    . "\\.ctp\\'")
          ("blade"  . "\\.blade\\.")))

  (setq web-mode-extra-control-blocks
        '(("blade" . ("row" "col"))))

  (setq web-mode-enable-current-element-highlight t)
  (setq web-mode-enable-current-column-highlight t)

  (defun my-web-mode-hook ()
    "Customization."
    (setq web-mode-markup-indent-offset 4)
    (setq web-mode-css-indent-offset 4)
    (setq web-mode-code-indent-offset 4)
    (setq web-mode-style-padding 4)
    (setq web-mode-script-padding 4)
    (setq web-mode-block-padding 0)
    (setq web-mode-comment-style 2)
    (setq web-mode-enable-auto-pairing nil)
    (setq web-mode-enable-css-colorization t)
    (setq web-mode-enable-auto-expanding t)
    (setq web-mode-enable-html-entities-fontification t)

    (setq indent-tabs-mode nil)
    )

  (add-hook 'web-mode-hook  'my-web-mode-hook))


Thanks for your help.

Best regards.

Gonçalo Marrafa

**Comment by fxbois** [comment]
@gjm try to put the config line I showed you before ```(use-package web-mode ...```
