### ISSUE TITLE
Mustache - {{^ doesn't insert closing }}

### ISSUE THREAD

**Issue by tsutton** [fxbois/web-mode#1036]
Whereas typing `{{#` will automatically insert `}}`, `{{^` will not insert them. Mustache uses `{{^ }}` for what it calls inverted sections - see https://mustache.github.io/mustache.5.html.

Possibly relevant web-mode-debug:
versions: emacs(26.1) web-mode("16.0.17")
vars: engine("ctemplate") minor("ctemplate") content-type("html") file("c:/Users/Taylor Sutton/Dropbox/tmp.mustache")
system: window(w32) config("x86_64-w64-mingw32")
colors: fg(nil) bg(nil) 
minor modes: (global-eldoc-mode yas-minor-mode yas-global-mode shell-dirtrack-mode diff-auto-refine-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil

**Comment by fxbois** [comment]
@tsutton I've pushed a fix
