### ISSUE TITLE
lsp vs. web-mode - web-mode-indent-line inhibits modification hooks

### ISSUE THREAD

**Issue by cwhatley** [fxbois/web-mode#1039]
Problem setup:

* web-mode
* lsp-mode/lsp-ui (see issue: https://github.com/emacs-lsp/lsp-ui/issues/238)
* typescript-language-server (https://github.com/theia-ide/typescript-language-server)

I use web-mode to edit a TSX file.

LSP works by monitoring for buffer changes and sending the changes to the language server to drive flycheck/company, etc. This is all driven off of buffer modification hooks.

Since web-mode sets inhibit-modification-hooks to t in web-mode-indent-line, LSP gets out of sync with the buffer.

Is there a reason for the indent operation to suppress the modification hooks even though there is probably a file modification? Could the scope of the inhibit be more limited within web-mode-indent-line?

I am not sure how LSP can practically pull off sending incremental updates to the language server without these hooks firing.

Thanks!

**Comment by fxbois** [comment]
@cwhatley I've removed it ... let's now see if it triggers side effects (I do not remember why I set it)

**Comment by cwhatley** [comment]
Hi. I'm not seeing a change in that commit. 

I had been meaning to give you a PR for this. I just did: https://github.com/fxbois/web-mode/pull/1048

I've been using that for awhile and seems to help with the problem.

**Comment by fxbois** [comment]
@cwhatley you're right ... better with last commit
