### ISSUE TITLE
Highlight first argument of a specific function

### ISSUE THREAD

**Issue by Defacta** [fxbois/web-mode#1040]
Hello,

I have a php function which looks like this:

`__lg('Please upload a photo in Jpg format', 'Global', NULL, FALSE);`

This function can be call with only one argument like:

`__lg('My profile');`

Is it possible to modify the web-mode.el to highlight the text between the 2 single quotes of the first argument of my function __lg() ?

I would like it to be colored in #ff007c for exemple.

Thanks.

**Comment by fxbois** [comment]
@Defacta it should be highlighted as a string and you can customise string colors with ```web-mode-block-string-face```
