### ISSUE TITLE
web-mode jsx sometimes highlight and indentation error 

### ISSUE THREAD

**Issue by zhangjie2012** [fxbois/web-mode#1041]
I use `web-mode` write react(jsx), I found sometime `web-mode` become invalid. I must reset web-mode (`M-x web-mode ret`) make it right.

eg:

![image](https://user-images.githubusercontent.com/2450412/52945641-2be07580-33ad-11e9-89f0-136f96786cc2.png)

then I use shortcut key to indent it (`C-c C-i`).

![image](https://user-images.githubusercontent.com/2450412/52945739-64804f00-33ad-11e9-89be-3c7a70a6ae14.png)

Now, I reset web-mode(`M-x web-mode`, `C-c C-i`), It will show right.

![image](https://user-images.githubusercontent.com/2450412/52945789-7d890000-33ad-11e9-858f-092a844749f7.png)

I can't find some rules to recurrent this bug, I guess it with regard to jsx.

**Comment by fxbois** [comment]
@zhangjie2012 please poste your example on gist

**Comment by zhangjie2012** [comment]
no clear rules ...

**Comment by zhangjie2012** [comment]
I want reopen this issue. code example: 

import React from 'react'
import { Form, Modal, Input } from 'antd'

    @Form.create()
    export default class EditMachineForm extends React.Component {
      render() {
        const { form, visible, machine, showEditMachine } = this.props
        if (machine === null) {
          return null
        }

        const { appName, ip, hostname } = this.state
        return (
          <Modal
            title="Edit"
            maskClosable={false}
            closable={false}
            onOk={this.okHandle}
            onCancel={() => showEditMachine(false, null)}
            visible={visible}
            destroyOnClose
          >
            <Form colon={false} labelCol={{ span: 4 }} wrapperCol={{ span: 20 }} onSubmit={null}>
              <Form.Item label="AppName">
                {form.getFieldDecorator('appName', {
                  initialValue: appName,
                })(<Input value={appName} />)}
              </Form.Item>
              <Form.Item label="IP">
                {form.getFieldDecorator('ip', {
                  rules: [{ required: true }],
                  initialValue: ip,
                })(<Input value={ip} />)}
              </Form.Item>
              <Form.Item label="Site">
                {form.getFieldDecorator('site', {
                  rules: [{ required: true }],
                })(<Input />)}
              </Form.Item>
              <Form.Item label="rack">
                {form.getFieldDecorator('rack', {
                  rules: [{ required: true }],
                })(<Input />)}
              </Form.Item>
              <Form.Item label="location">
                {form.getFieldDecorator('location', {
                  rules: [{ required: true }],
                })(<Input />)}
              </Form.Item>
              <Form.Item label="hostname">
                {form.getFieldDecorator('hostname', {
                  rules: [{ required: true }],
                  initialValue: hostname,
                })(<Input disabled />)}
              </Form.Item>
            </Form>
          </Modal>
        )
      }
    }

When white code in `<Input disabled />` to `<Input value={value} disabled />` __may be__ recurrent this bug. 

Sorry, I do not know how to precise description this bug, but it is a crazy problem for me past 2 years coding in react (jsx).

**Comment by kristianhasselknippe** [comment]
I'm experiencing this as well. Seems to happen more often when I copy/paste some content around in the buffer, but haven't been able to find a consistent repro case.

**Comment by nathanstitt** [comment]
I also experience this fairly regularly.  It's pretty maddening because I haven't been able to create a repeatable test case.  It does seem to happen more often when code is copied and pasted but the only way to fix it seems to be to `web-mode-reload`

**Comment by zhangjie2012** [comment]
@nathanstitt 

I recommand [rjsx-mode](https://github.com/felipeochoa/rjsx-mode) replace  web-mode write js/jsx, web-mode just for html/css
