### ISSUE TITLE
web-mode react jsx attribute indent offset bug 

### ISSUE THREAD

**Issue by zhangjie2012** [fxbois/web-mode#1042]
expect:

![image](https://user-images.githubusercontent.com/2450412/52988970-65ac8d00-343c-11e9-8b9d-f8653d3f34a6.png)

actual:

![image](https://user-images.githubusercontent.com/2450412/52989015-9096e100-343c-11e9-870a-021eadc6d6c4.png)

**Comment by fxbois** [comment]
@zhangjie2012 please post you example on gist, it is easier for me to copy/paste

**Comment by zhangjie2012** [comment]
@fxbois 

a simple example:

```javascript
class NS {
  render() {
    return (
      <div>
        {loop.map(item => {
          return (
            <Tag
              key={item.id}
              >
              <Link to={link}>{item.name}</Link>
            </Tag>
          );
        })}
      </div>
    );
  }
}
```

**Comment by fxbois** [comment]
@zhangjie2012 I've pushed a fix

**Comment by zhangjie2012** [comment]
@fxbois Hi, this bug reappeared int version `16.0.0`? I remeber had fix.

```javascript
export default class Form extends React.Component {
  render () {
    return (
      <Form colon={false} labelCol={{ span: 4 }} wrapperCol={{ span: 20 }} onSubmit={null}>
        <Form.Item >
          {form.getFieldDecorator('company', {
             rules: [{ required: true, whitespace: true}],
          })(
             <Select
               showSearch
               >
               {companyList.map(item => {
                  return <Option key={item.key} value={item.key}>{item.value}</Option>
               })}
             </Select>
           )}
        </Form.Item>
      </Form>
    )
  }
}
```

**Comment by zhangjie2012** [comment]
I know ...

Before, I used `melpa`, but now, I use `melpa-stable`. `16.0.0` is older. update to `20190609.1917` fixed.

**Comment by zhangjie2012** [comment]
I know ...

Before, I used `melpa`, but now, I use `melpa-stable`. `16.0.0` is older. update to `20190609.1917` fixed.
