### ISSUE TITLE
defining keyboard macros fails with web-mode function C-c C-m & C-c C-e r

### ISSUE THREAD

**Issue by avocadoras** [fxbois/web-mode#1043]
I'm on macOS mojave & Emacs v 26.1.

I cannot call keyboard macros on the fly with web-mode. I'm trying to select a region with `C-c C-e r` and rename several tags. When I finish defining the macro, it gets called somewhere else. Please, see attached gif that describes the situation.
![kbd-macro-webmode-not-working](https://user-images.githubusercontent.com/36335687/53195401-3aac6f80-35db-11e9-9c12-ec4c03b2a959.gif)

**Comment by fxbois** [comment]
@avocadoras please try with an empty .emacs

**Comment by avocadoras** [comment]
@fxbois works now.
