### ISSUE TITLE
web-mode-attribute-insert errors if point isn't inside the tag (problems with easily adding a link)

### ISSUE THREAD

**Issue by zck** [fxbois/web-mode#1045]
I don't have deep knowledge of web-mode, so there may be better ways to do what I want than what I'm seeing.

The thing I want to do is insert an html link into a document. Since there isn't a command to do that, I figured I can do it by inserting an `a` element, then adding the `href` attribute.

So I pressed `C-c C-e i a<RET>` to run `web-mode-element-insert` and insert `<a>|</a>`, where `|` indicates point.

Then I pressed `C-c C-a i`, to run `web-mode-attribute-insert`, trying to add an attribute to the `a` element. I got an error `attribute-insert ** invalid context **`.

I can put in the attribute if I, after running `web-mode-element-insert`, go backwards a character.

But it would be nice if either of these two things happened:

1. There was a separate command to insert a link (there might be one, but if so I can't find it). This command would prompt for the target, put it in the `href` value, and leave point inside the element.
2. `web-mode-attribute-insert` looked for the enclosing tag, and added the attribute there.

Just as a point of comparison, org mode lets a link be inserted with only `C-c C-l`, which is far easier for such a common operation.

Thanks for reading!

**Comment by fxbois** [comment]
@zck you can enable ```web-mode-expanders``` and hit ```a/```
