### ISSUE TITLE
Bad highlighting of self-closing HTML elements 

### ISSUE THREAD

**Issue by markshep** [fxbois/web-mode#1046]
When `web-mode-enable-current-element-highlight` is `t` and the point is in a self-closing HTML element the opening tag name is highlighted as expected, but rather than the closing `/` being highlighted too the space immediately after the opening name is instead.  Example:

<img width="405" alt="screenshot 2019-02-26 at 11 15 43" src="https://user-images.githubusercontent.com/490067/53409498-f2b19200-39b8-11e9-924c-b9b7e2ebb39c.png">

Here's the output from web-mode-debug:

````
--- WEB-MODE DEBUG BEG ---
versions: emacs(26.1) web-mode("16.0.0")
vars: engine("razor") minor("razor") content-type("html") file("/Users/mark.sheppard/code/rambo-api-a/Rambo.Dashboard/Views/Health/Index.cshtml")
system: window(nil) config("x86_64-apple-darwin17.5.0")
colors: fg(nil) bg(nil)
minor modes: (global-eldoc-mode cl-old-struct-compat-mode helm-mode projectile-mode git-gutter-mode global-git-gutter-mode shell-dirtrack-mode async-bytecomp-package-\
mode global-git-commit-mode auto-revert-mode magit-auto-revert-mode diff-auto-refine-mode magit-file-mode global-magit-file-mode)
vars:
web-mode-enable-current-column-highlight=nil
web-mode-enable-current-element-highlight=t
indent-tabs-mode=t
--- WEB-MODE DEBUG END ---
````

**Comment by fxbois** [comment]
@markshep I've pushed a fix
