### ISSUE TITLE
Indentation in Rails erb templates inconsistent

### ISSUE THREAD

**Issue by alec-implicitdesign** [fxbois/web-mode#1047]
I think this problem is exacerbated by Ruby's lenient syntax.  Since function calls don't require parentheses, I get this:

    <%= render partial: 'some_partial',
    locals: {
        icon: nil,
        errors: [],
        title: 'Title'
    } %>

...instead of let's say having the `locals` parameter line up under the `partial` parameter.  (something I can't even get to work here)

Which is what I would get if I called the `render` function with parentheses.

Additionally, I would like to be able to mimic the behaviour of something like RubyMine, which, as far as I can tell, respects the indentation of the previous line.  So if I had:

    <%= render partial: 'some_partial', locals: { icon: nil,

...the next parameter, namely `errors`, would be indented to be right under `icon`.  Has anyone achieved this?

**Comment by fxbois** [comment]
@alec-implicitdesign could you post the snippet the way it should be indented please

**Comment by alec-implicitdesign** [comment]
I believe the following is at least in line with the behaviour one would expect if `render` was called with parentheses:

    <%= render partial: 'some_partial',
               locals: {
                   icon: nil,
                   errors: [],
                   title: 'Title'
               }
    %>

...and this would be the behaviour if the indentation of the previous line was respected:

    <%= render partial: 'some_partial', locals: { icon: nil,
                                                  errors: [],
                                                  title: 'Title'
                                                }
    %>

...but those are admittedly two different criteria.
