### ISSUE TITLE
set indent offset per-project?

### ISSUE THREAD

**Issue by titaniumbones** [fxbois/web-mode#1049]
First, thanks for web-mode, which has improved my life immeasurably. Without it, I might have given up editing html in emacs entirely. 

Most of my work in HTML is small fixes to other people's projects on github.  In these cases I don't have control over the author's indentation preferences. I would really like to be able to set the value of the various `indent-offset` variables on a per-project basis so that I don't repeatedly forget to reset the value when I open a file and make some small bugfix-level edits, which then end up screwing up the author's indentation.  Is there a way to do this that I'm missing?  Thank you!!

**Comment by fxbois** [comment]
@titaniumbones I am not an expert of this. You might have more answers on Emacs Stackoverflow

**Comment by titaniumbones** [comment]
@fxbois I am currently experimenting with dir-local variables, and this seems to work.  From the root of a project/git repo, simply call `add-dir-local-variable` and follow the prompts, then save `.dir-locals.el` when it opens.  

[this issue from projectile](https://github.com/bbatsov/projectile/issues/139) has a long discussion of the problem, and includes some alternative suggestions.  

leaving open for now in case you want to add some docs or something, but please feel free to close.  Thank you!

**Comment by fxbois** [comment]
@titaniumbones I have no experience with this.
Do not hesitate to add some comments if you found something new

**Comment by madscientist** [comment]
Have you investigated using editorconfig https://editorconfig.org/ ?  It has an emacs mode that will read editor config files (and many other IDEs have built-in support for this so it's portable).  It doesn't allow you to customize very many things unfortunately, but one of the few it DOES support is indent offest.
