### ISSUE TITLE
Autoclose handlebars elements?

### ISSUE THREAD

**Issue by vmalloc** [fxbois/web-mode#1050]
I really like that web-mode autocloses HTML elements upon hitting `/`. Is it possible to have it autoclose handlebars elements? E.g. when writing:
```
{{#if something}}
...
{{/
```
Is it possible that in the above case it autocompletes the bottom tag to `{{/if}}`?

Thanks in advance!

**Comment by fxbois** [comment]
have you tried ```web-mode-block-close``` ?

**Comment by vmalloc** [comment]
@fxbois doh! that's perfect -- and I feel stupid now. Thanks!
