### ISSUE TITLE
Web-Mode Does Not Work in Emacs 24

### ISSUE THREAD

**Issue by artforlife** [fxbois/web-mode#1051]
I tried the web-mode in latest emacs-snapshot (Emacs 27.0.50), and it seems to work. However, it does not seem to work in Emacs 24. Whenever I run `M-x web-mode` to enable the mode, I receive the following error in the minibuffer.

`Invalid byte opcode: op=183, ptr=418`

Here are the pertinent configurations from `.emacs`

```
(add-to-list 'load-path "/home/user/.emacs.d/elpa/web-mode-20190301.1700/")
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.js?\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.jsx?\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.css?\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.scss?\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.xml?\\'" . web-mode))
(web-mode)


```

**Comment by DoMiNeLa10** [comment]
Have you tried deleting byte-compiled code and recompiling it from Emacs 24? Emacs' byte-compiler isn't backwards compatible.

**Comment by artforlife** [comment]
@DoMiNeLa10 , I have just tried it via `M-x byte-recompile-directory` on `~/.emacs.d/`, and it did not solve the issue.

**Comment by fxbois** [comment]
@artforlife what version of emacs ?
