### ISSUE TITLE
lit-html support in javascript?

### ISSUE THREAD

**Issue by swans-one** [fxbois/web-mode#1052]
I'm using [lit-html](https://github.com/Polymer/lit-html) to do html templating inside javascript. A simple example of a web-component I might write would look like:

```javascript
import { html, render } from 'lit-html';

const myTemplate = (el) => html`
  <style>
    h1 {
      font-size: ${el.titleSize}em;
    }
    .square {
      height: ${el.size}px;
      width: ${el.size}px;
      background-color: ${el.color};
    }
  </style>
  <div>
    <h1> My Web Component </h1>
    <div class="square">
    </div>
  </div>
`

export class MyComponent extends HTMLElement {
    constructor() {
        super();
        this.root = this.attachShadow({mode: 'open'});
        this.color = "blue";
        this.size = 12
        this.titleSize = 1.2;
        this.render();
    }

    render() {
        render(myTemplate(this), this.root)
    }
}
customElements.define('my-component', MyComponent)
```

It would be amazing if web-mode were able to highlight, indent, etc, inside the `html` template literal. For example, this [VS Code extension](https://marketplace.visualstudio.com/items?itemName=bierner.lit-html) allows for this sort of highlighting.

Is this something that is possible in web-mode?

**Comment by fxbois** [comment]
@swans-one Hi, it is a recurring feature request but really difficult to implement.
I hope to have time someday to work on this.

**Comment by swans-one** [comment]
Hi @fxbois, that's totally understandable. I really appreciate the project and all your hard work on it! Is there any way I could help on this feature?

**Comment by fxbois** [comment]
@swans-one I'll take care of the indentation but for the highlighting it is an other story. I really need to think about it.

**Comment by andykais** [comment]
Not adding any rush to this feature, if it is possible, we will wait @fxbois, but Ill still give my two cents about the interface:

vim has some somewhat buggy support for this feature.
- https://github.com/cdata/vim-tagged-template
- https://github.com/Quramy/vim-js-pretty-template

Ideally though, web-mode would provide a similar interface. E.g.

```elisp
(setq web-mode-javascript-tagged-templates
  '(("graphql" . "gql")
   ("html" . "html")))
```

which would highlight the following js code
```js
const str = html`
<div>hello world</div>
`

const query = gql`
{
  hero {
    name
  }
}
`
```

**Comment by xaiki** [comment]
looks like a duplicate of: https://github.com/fxbois/web-mode/issues/999
maybe all these bugs should be rename to `support template literals` ?

**Comment by andykais** [comment]
Ive done a bit more research and discovered two libraries called `mmm-mode` and `polymode` which are created specifically for this functionality. I wont repeat myself here, so if youre curious in how they work, look at this stack answer or the article I originally got my info from:

https://emacs.stackexchange.com/questions/37918/how-to-highlight-graphql-template-literals-gql-in-jsx-files
https://vxlabs.com/2014/04/08/syntax-highlighting-markdown-fenced-code-blocks-in-emacs/

Im not sure how this will play into web mode, but it can be used in addition to it now.

**Comment by fxbois** [comment]
I've pushed some support : see
https://github.com/fxbois/web-mode/issues/1128

**Comment by swans-one** [comment]
Really excited to see this! Just playing with it now. I have a couple questions about the faces. I'll add a question there.

Thanks for the update!
