### ISSUE TITLE
Handle #attr=""

### ISSUE THREAD

**Issue by phenix-factory** [fxbois/web-mode#1057]
I m currently using web-mode to edit Angular2 component.
In Angular 2, sometimes you have to write html like this : 

`<form #f="ngForm" (ngSubmit)="saveDocument()">`

But it break the syntax color : 

![image](https://user-images.githubusercontent.com/1810149/56793116-85c94580-680b-11e9-9e55-86d7a9e126df.png)

I m using Spacemacs with spacemacs-dark theme, but it's not working with the monokai theme too.
Fun fact : If i delete the # the color are back and i can safely add the # again (the color stays)

**Comment by fxbois** [comment]
@phenix-factory where is the specification of this # attr syntax ?

**Comment by phenix-factory** [comment]
@fxbois you can find it inside the angular documentation : https://angular.io/guide/template-syntax#template-reference-variables--var-

**Comment by fxbois** [comment]
@phenix-factory could you post your exemple on gist please

**Comment by phenix-factory** [comment]
Sur ! Here is a gist (simplified) gist. I can reproduce the problem with it :

https://gist.github.com/phenix-factory/cf5d78b438458b0b52933763efef214d

**Comment by fxbois** [comment]
@phenix-factory should be ok now

**Comment by phenix-factory** [comment]
I cannot reproduce this issue. Thank you @fxbois !
