### ISSUE TITLE
Is there a way to get current region major mode name?

### ISSUE THREAD

**Issue by fetatefog** [fxbois/web-mode#1058]
For example, if my cursor is inside the style tag, then I want to get CSS-Mode or so and if i am inside div in the body tag, then it should output as HTML-mode.
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
  <title>My first styled page</title>
  <style type="text/css">
  body {
    color: purple;
    background-color: #d8da3d }
  </style>
</head>

<body>
    <div></div>
</body>
</html>

**Comment by DoMiNeLa10** [comment]
`web-mode` is a single major mode, so you referencing these major modes makes no sense. There's `web-mode-language-at-pos`, which returns a string with the language at point.

**Comment by fetatefog** [comment]
Good, this is what i really need. Thanks !!

**Comment by cuhabaho** [comment]
@DoMiNeLa10, I have tried **web-mode-language-at-pos** and it works perfectly fine when web-mode is enable as a major mode. But can I use *web-mode-language-at-pos* without enable web-mode?

**Comment by DoMiNeLa10** [comment]
@cuhabaho Considering that this function looks at data from font locking and internal variables kept by `web-mode`, it won't. You could try writing a function that somehow enables `web-mode` and runs this command after letting it font-lock the buffer, and there are different ways to achieve that (switching in the same buffer (which isn't the best solution) or creating another buffer and then setting up `web-mode` there. I don't think it's a good idea, though, as it would probably end up being pretty slow.

I'm suspecting that the best solution to your problem depends on what you want to achieve.
