### ISSUE TITLE
Support { } bracket autocompletion for JSX

### ISSUE THREAD

**Issue by saevarb** [fxbois/web-mode#1060]
Hello.

It looks like web-mode supports choosing between single and double quotes for inserting quotes automatically after = in a tag. It would be very useful to have support for a third possibility, namely { } brackets for JSX. 

Perhaps it would also be a good idea to make web-mode automatically choose this third mode whenever a .jsx/.tsx file is opened, since in the general case, brackets are the most flexible: 

If I want to type a string, I type my `{"string inside the brackets like this"}` and presumably get auto-completion for those quotes via other means(like smartparens).
If I want to write a JS expression, then I can just type it immediately and don't have to delete the quotes and then insert `{}`.

I took a look at the code, and as far as I can see the required changes would consist of 

1. Adding a third possibility to the `web-mode-auto-quoting-style` `defcustom`
2. Handling the third possibility in the one place you dispatch on that variable

If there isn't anything else I'm missing, I can submit a pull request later this evening when I have time to take a closer look.

**Comment by DoMiNeLa10** [comment]
I don't think this functionality should demand the use of the `.jsx` or `.tsx` extension for files, as this is controversial, and Facebook recommends sticking with `.js` for JSX files. Considering that unquoted tags aren't valid in JavaScript, completing inside of any JavaScript context should be fine.

**Comment by fxbois** [comment]
@saevarb Hello ok for a patch to offer a third auto-quoting-style.

**Comment by linchen2chris** [comment]
I did a little hack in my local file change line 10928 \"\" => {}, then recompile, works fine in tsx file
        (if (= web-mode-auto-quote-style 2)
            (insert "''")
--->          (insert "{}"))

**Comment by fxbois** [comment]
@saevarb it is now available
