### ISSUE TITLE
Broken web-mode.el encoding

### ISSUE THREAD

**Issue by wavexx** [fxbois/web-mode#1065]
Attempting to update web-mode today from melpa failed.
The encoding of web-mode.el doesn't seem to be utf-8.

**Comment by fxbois** [comment]
anyone has an idea about this ?

**Comment by wavexx** [comment]
Mmh, explicitly giving utf-8 to package.el makes it pass. When opening the file from the repository I don't have any decoding problem, and the package file from melpa seems to be correct as well.

Maybe it's actually a bug in emacs/package.el. I sent an email  to the emacs-devel list.

**Comment by DoMiNeLa10** [comment]
Considering that character encoding is explicitly set via a comment:

https://github.com/fxbois/web-mode/blob/e1c391da4bf6e7948f632b653991ceeda969a03f/web-mode.el#L2

This sounds like a bug to me without a doubt.

**Comment by wavexx** [comment]
On Fri, May 24 2019, DoMiNeLa10 wrote:
> https://github.com/fxbois/web-mode/blob/e1c391da4bf6e7948f632b653991ceeda969a03f/web-mode.el#L2
>
> This sounds like a bug to me without a doubt.

There's no doubt, but where? At first I thought the source encoding was
broken. But it's not. Encoding detection while opening is also working.
And the file itself is not corrupted after being downloaded. HTTP
headers are good. Maybe it's "url" not setting buffer properties right
after the file has been downloaded. But this seems to be the only
package trigger this issue, as I failed to reproduce a simpler test
case.

I'm running emacs rebuilt from git. What are you using DoMiNeLa10?

**Comment by DoMiNeLa10** [comment]
Right now I install `web-mode` directly from the master branch of this repository via `straight.el`. The bug I'm pointing to is probably related to whatever package manager OP is using, which is likely the default Emacs one.

**Comment by wavexx** [comment]
Fixed in git: https://lists.gnu.org/archive/html/emacs-devel/2019-05/msg00880.html
