### ISSUE TITLE
support for svelte

### ISSUE THREAD

**Issue by knobo** [fxbois/web-mode#1066]
Support for svelte would be nice. 

Some examples of code: https://svelte.dev/examples

Example of what needs to be supported is for example logic in the templates:
``` html
{#await promise}
	<p>...waiting</p>
{:then number}
	<p>The number is {number}</p>
{:catch error}
	<p style="color: red">{error.message}</p>
{/await}
```
and maybe highlight use of $ to autosubscribe to `stores`.

``` html
<script>
   import mylist from 'mystore.js'
</script>

{#each $mylist as element}
    <p>mylist is automaticaly subscribed and unsubscribed on mount/unmount</p> 
{/each}
```
 
interpolation can be done with or without quotes
``` 
<input bind:value={name}> === <input bind:value={"name"}>
```

Special elements example (adds css to global head tag)
```
<svelte:head>
	<link rel="stylesheet" href="tutorial/dark-theme.css">
</svelte:head>
```

**Comment by VelikiiNehochuha** [comment]
https://github.com/fxbois/web-mode/pull/1074

results looks like 
![Screenshot_2019-07-19_23-48-43](https://user-images.githubusercontent.com/9156442/61576752-7560f800-aae6-11e9-9a7e-d25321257267.png)
