### ISSUE TITLE
Support for leex files

### ISSUE THREAD

**Issue by ankhers** [fxbois/web-mode#1069]
Elixir's Phoenix recently added `.leex` files, which act the same as `.eex` files which is already supported. 

I am more than happy to submit a PR for this, but I just wanted to make sure I make the proper adjustments. It seems to me that I just need to modify [this](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L912) regex to include `.leex`? Or is there more to it?

As an aside, `.eex` files can be used for anything really and will not always be html files. The naming convention is `foo.html.eex` for HTML files. Should the regex be modified for that, or would it be preferable to keep it as is?

**Comment by fxbois** [comment]
@ankhers yes you can replace ```("elixir"           . "\\.eex\\'")``` by ```("elixir"           . "\\.l?eex\\'")```
