### ISSUE TITLE
Blade engine won't correctly indent {!! Form::open() !!} and {!! Form::close() !!} directives

### ISSUE THREAD

**Issue by mateusfccp** [fxbois/web-mode#1071]
Example: 

```blade
{!! Form::open(['method' => 'post']) !!}
{!! Form::hidden('input', 0) !!}
{!! Form::close() !!}
```

The expected behaviour was:

```blade
{!! Form::open(['method' => 'post']) !!}
    {!! Form::hidden('input', 0) !!}
{!! Form::close() !!}
```

**Comment by fxbois** [comment]
@mateusfccp is it specific to your project ? If not could you provide a pointer towards the documentation online please

**Comment by mateusfccp** [comment]
@fxbois It has been a while since I last used blade. The issue has been opened on 2019-06-30, and I quit my last job on 2019-08-06. Since then, I don't work with PHP anymore, so I'm not really using `web-mode` in any project, thus I can't answer your question.

As no one else stated to have the same issue, I'm closing it by now, until someone have the same problem again.

Thanks.
