### ISSUE TITLE
Bad TypeScript indentation after method call

### ISSUE THREAD

**Issue by Ptival** [fxbois/web-mode#1072]
In some `.tsx` file:

```
class Class {
    method() {
        // GOOD
        nodeSel
            .enter()
            .append('circle')
        const nodeSel = svg.selectAll('circle')
        // BAD
        nodeSel
                           .enter()
                           .append('circle')
    }
}
```

Expected: same indentation before and after the `selectAll` method call
Actual: the indentation is way off after the method call

This makes web-mode unfortunately irritating to use when working on TypeScript files.

**Comment by DoMiNeLa10** [comment]
Just out of curiosity, does adding semicolons help?

**Comment by Ptival** [comment]
Yes, it indents properly in the presence of semicolons.

**Comment by fxbois** [comment]
@Ptival web-mode does integrate a real js/ts parser and without semicolons  indentation may not work. Sorry not to be able this issue.
