### ISSUE TITLE
TAB in selected area with folded content breaks indentation

### ISSUE THREAD

**Issue by pksadiq** [fxbois/web-mode#1073]
Pressing TAB (`indent-for-tab-command`) on an area where the content is folded with `web-mode-fold-or-unfold` results in broken indentation.

Say for example, for a properly indented XML file `test.xml` with the content:

```xml
<child>
  <object class="GtkButton">
    <property name="visible">1</property>
  </object>
</child>
```

folding the content with `web-mode-fold-or-unfold`, selecting the whole buffer, and indenting with TAB results in the following (see second line indentation):

```xml
<child>
    <object class="GtkButton">
      <property name="visible">1</property>
  </object>
</child>
```

Thanks

**Comment by fxbois** [comment]
@pksadiq I've pushed a fix
