### ISSUE TITLE
在web-mode中copy内容时文件会被自动格式化

### ISSUE THREAD

**Issue by zhyuanyuan** [fxbois/web-mode#1075]
hi，all。
     I am a Chinese.that English just so so. I try my best to describe my probleam.

I am use vue to develop program,when I copy some words of use web-mode. and web-mode auto format my code in all page. when the page is so large and waste of my time. so I think this is web-mode's bug or web-mode can setting and I not found.I do not this,I want to copy words not format my code in other codes,Can you help me to solve this problem? thinks!

**Comment by DoMiNeLa10** [comment]
Take a look [here](https://github.com/fxbois/web-mode/issues/894). You'll want to customize `web-mode-enable-auto-indentation`.
