### ISSUE TITLE
[question] Auto closing brackets/parentheses in javascript part?

### ISSUE THREAD

**Issue by siegy22** [fxbois/web-mode#1076]
I wondered if there's a flag to enable auto closing brackets and parentheses in the `<script>` part of a HTML template. Similar to the `web-mode-auto-close-style`, but not for tags.

**Comment by DoMiNeLa10** [comment]
I recall trying to implement this at one point, and giving up. I think this should tap into the built-in `electric-pair-mode` to make configuration intuitive.

**Comment by siegy22** [comment]
Alright, thanks! The thing is, if I enable the `electric-pair-mode`, this happens:

![Kapture 2019-07-30 at 9 54 41](https://user-images.githubusercontent.com/8779283/62111090-1b172280-b2b0-11e9-807d-b671c27c8713.gif)

It feels like it's a mix of `web-mode` and `electric-pair-mode` :/

**Comment by fxbois** [comment]
@siegy22 you should disable ```web-mode-auto-pairs```
You can't have both
