### ISSUE TITLE
Misbehavior of forward/backward-sexp and up/down-list?

### ISSUE THREAD

**Issue by AmaiKinono** [fxbois/web-mode#1078]
Hi. I found web-mode handles balanced expressions in a kind of "partly" way. For example, `mark-sexp` command works great, but `forward/backward-sexp` command can let you go out of current expression (but it doesn't let you go in. I found this inconsistent behavior annoying). Compare this behavior to `emacs-lisp-mode`:

![Peek 2019-08-06 12-27](https://user-images.githubusercontent.com/28714352/62511310-93985900-b845-11e9-915c-f6b1eee9a590.gif)

Besides, `up-list` does not go up by one level. It goes straight to the end of the buffer:

![Peek 2019-08-06 12-32](https://user-images.githubusercontent.com/28714352/62511445-508ab580-b846-11e9-952d-6d204fdeb795.gif)

`down-list` does not work too. So that means I can't go into a balanced expression using any of the sexp commands.

*Update:* Actually I am just starting to use these sexp commands. I tried in other modes, and found that the point will be blocked by parenthesis/brackets/curly brackets, but never by other syntactic delimiters like html tags, python's indentations. So maybe this is the common behavior and I just misunderstood it.

Feel free to close this issue, but I would like to hear your thought if you are willing to.

**Comment by fxbois** [comment]
@AmaiKinono you can use ```web-mode-element-parent```
