### ISSUE TITLE
Web mode incorrectly reads the content type of mjs-files as html

### ISSUE THREAD

**Issue by davorb** [fxbois/web-mode#1081]
I'm trying to get web-mode to read mjs-files as jsx or js files. I did this by adding

```
(add-to-list 'auto-mode-alist '("\\.mjs\\'" . web-mode))
```

The problem is when I eval `web-mode-content-type`, I get `html`. How do I fix this?

**Comment by kmcclosk** [comment]
This can be added to your init.el:
(setq web-mode-content-types-alist
	  '(("jsx" . "\\.[c|m]js[x]?\\'")))

**Comment by davorb** [comment]
@kmcclosk thank you! that fixed my issue.
