### ISSUE TITLE
Indent JS concatenated calls

### ISSUE THREAD

**Issue by apiraino** [fxbois/web-mode#1082]
Hi,

sorry if this has been asked in past, I see similar issues closed in the past. I'm not sure how to indent this code to 2 spaces instead of 4:

From this:
```
this.$axios
    .get('http://....')                 
    .then(response => {...})
```

To this:
```
this.$axios
  .get('http://....')                 
  .then(response => {...})
```

Hints?

Thanks!

**Comment by fxbois** [comment]
@apiraino try
``` (add-to-list 'web-mode-indentation-params '("lineup-calls" . nil))```

**Comment by apiraino** [comment]
thank you @fxbois I'll try as soon as I'll have a chance! (and will confirm closing the issue)

**Comment by apiraino** [comment]
ok, could finally test your suggestion.

First, I had to figure out where exactly to set that variable. In the end I've set that param to `nil` at [this line](https://github.com/fxbois/web-mode/blob/cd000fcfce97152f8b831b7eef4ea0d0b1eed11a/web-mode.el#L823).

And it works!

So now I have:
```
(defvar web-mode-indentation-params
  '(("lineup-args"       . t)
    ("lineup-calls"      . nil) ;; <--- changed this
    ("lineup-concats"    . t)
    ("lineup-quotes"     . t)
    ("lineup-ternary"    . t)
    ("case-extra-offset" . t)
    ))
```


But why? And is that the correct fix?

**Comment by fxbois** [comment]
@apiraino put ```(add-to-list 'web-mode-indentation-params '("lineup-calls" . nil))``` in your web-mode web-mode-hook
