### ISSUE TITLE
*-padding global variables are not respected

### ISSUE THREAD

**Issue by siegy22** [fxbois/web-mode#1083]
Emacs version: 26.3 (9.0)
web-mode version: 20190625.1951

```
web-mode-script-padding is a variable defined in ‘web-mode.el’.
Its value is 2
Original value was 1
Local in buffer AddContractModal.vue; global value is 0
```

all `*-padding` variables do not respect their global values.

My (spacemacs) setup:
https://github.com/siegy22/dotfiles/blob/master/spacemacs#L43-L49

The `web-mode-markup-indent-offset` does work however:

```
web-mode-markup-indent-offset is a variable defined in ‘web-mode.el’.
Its value is 2
Original value was 4
Local in buffer AddContractModal.vue; global value is the same.
```

I recently updated all of my spacemacs packages (including web-mode) but I'm not able to tell from which version to which one.

**Comment by DoMiNeLa10** [comment]
How do you set these variables up? Do you use a hook, or do you just set them before `web-mode` is loaded?

**Comment by siegy22** [comment]
@DoMiNeLa10 Have a look at my spacemacs config file I linked 😄 
http://develop.spacemacs.org/doc/DOCUMENTATION.html#setting-configuration-layers-variables

I think this way, the variable gets set globally. So not in a hook after initiating web-mode

**Comment by siegy22** [comment]
My current workaround is to add a `web-mode-hook`: 

```
  (add-hook 'web-mode-hook
            (lambda ()
              (setq web-mode-script-padding 0)
              (setq web-mode-style-padding 0)))
```
