### ISSUE TITLE
JSX with Vue

### ISSUE THREAD

**Issue by sollidsnake** [fxbois/web-mode#1086]
JSX inside Vue doesn't seem work properly. Take the following code, for example:

```html
<script>
export default {
  render(h) {
    return (
      <h1>Hello</h1>
    )
  }
}
</script>
```

Web mode seems to treat the JSX inside render as plain Javascript, like when you try to close some tag and `web-mode` closes the script tag at the top of the file.

**Comment by fxbois** [comment]
add ```type="text/jsx"``` in the ```<script>``` tag

**Comment by sollidsnake** [comment]
I tried that, but it also doesn't work. It does recognizes the JSX code, but when you try to write plain Javascript below the JSX, it seems to treat everything as JSX instead of Javascript.

**Comment by fxbois** [comment]
@sollidsnake please post a full example on gist

**Comment by sollidsnake** [comment]
```html
<script type="text/jsx">
export default {
  render() {
    return (
      <div></div>
    )
  }
  // try writting javascript code here
}
</script>
```

Using the code above, try writting some javascript code after the render method. `web-mode` seems to understand the code as JSX instead of Javascript. I recorded a gif showing this issue. As you can in the gif, when you restart web mode, it seems to parse correctly, but as you try to write the code, it doesn't work as as expected.

![vue-jsx](https://user-images.githubusercontent.com/1778350/65608330-6f731180-df84-11e9-8b57-d5ca6ce2bf5c.gif)

**Comment by fxbois** [comment]
@sollidsnake could you try with the last version please
