### ISSUE TITLE
Cannot highlight jinja template even though web-mode-engines-alist is set

### ISSUE THREAD

**Issue by frederichchen** [fxbois/web-mode#1087]
I am using web-mode to develop python flask application, which uses jinja2 templates(.html files). My config is as below:

```
(defun my-web-mode-config ()
    (setq web-mode-markup-indent-offset 2
	web-mode-css-indent-offset 2
	web-mode-code-indent-offset 2
	web-mode-style-padding 2
	web-mode-script-padding 2
	web-mode-enable-auto-pairing t
	web-mode-enable-css-colorization t
	web-mode-enable-current-element-highlight t
	web-mode-enable-current-column-highlight t
	web-mode-enable-css-colorization t
	web-mode-enable-auto-pairing nil)
    (setq web-mode-engines-alist
	'(("django"    . "\\.html\\'"))))

(add-hook 'web-mode-hook 'my-web-mode-config)
```
When I open the template, the tags like {% block contents %} are not highlighted. But when I M-x web-mode-set-engine and choose "django", they are highlighted.I am using GNU Emacs 26.3 under archlinux.

**Comment by fxbois** [comment]
@frederichchen the lines 
```(setq web-mode-engines-alist
	'(("django"    . "\\.html\\'")))```
should be placed out of the hook

**Comment by frederichchen** [comment]
You mean I should delete the line: (set web-mode-engines-alist ...) ? I deleted this, but I cannot have my jinja2 template highlighted. Could you please explain how to fix this in detail? Thanks!
