### ISSUE TITLE
HTML attributes indent weird with indent-tabs-mode

### ISSUE THREAD

**Issue by nobody-famous** [fxbois/web-mode#1088]
I have an HTML tag like this,

    <tag
        a="b"
        c="d"
        e="f"
    >

If I have indent-tabs-mode set to t and indent the buffer, it toggles between the above and this,

    <tag
        a="b"
           c="d"
           e="f"
    >

It doesn't do that if indented with spaces and indent-tabs-mode set to nil.

**Comment by fxbois** [comment]
@nobody-famous I do not use indent-tabs-mode. Perhaps you should ask for some help on emacs stackoverflow

**Comment by nobody-famous** [comment]
OK, I'll go ahead and close this out. Between this bug and one other I found with this package, Emacs is unusable for web development. I've switched back to VSCode.
