### ISSUE TITLE
Request for ExpressionEngine templates

### ISSUE THREAD

**Issue by 8cylinder** [fxbois/web-mode#1092]
I would like like support for ExpressionEngine templating.  (Btw, if you have documentation on how to add an engine to web-mode please point me to that).

- EE Documentation: https://docs.expressionengine.com/latest/templates/language.html
- Simple example: https://gist.github.com/8cylinder/ee99205620d29684787fb9f0956e7099
- Complex example: https://gist.github.com/8cylinder/f8a499c2bde2cbea8673cdc22213aa5e

The language consists of single braces with a keyword and optional attribute/value pairs.  The keyword can be multiple keywords joined with a colon.
```
{!-- This is a comment. --}
{something}
{something:another:this this="that" another="thing"}
```
Variables can have closing tags as well.  This might be a loop over a list of entries.
```
{something}{loop_value}{/something}

{something:another:this this="that" another="thing"}
  {loop_value}
{/something:another:this}
```

The attributes can be wrapped as well.
```
{something:another:this
  this="that"
  another="thing"
}
  {loop_value}
{/something:another:this}
```

The only language construct that you can tell is a loop by looking at the tag itself is the `if` tag.
https://docs.expressionengine.com/latest/templates/conditionals.html
```
{if x == 2}
  <div></div>
{if:elseif something}
  <div></div>
{if:else}
  <div></div>
{/if}
```
The only way to tell if a variable is part of a loop is to look ahead to see if there is a matching closing tag.  Its possible that it wouldn't be worth the effort to make indenting works for variable pairs, since for every variable you would have to scan the doc for a possible match.
```
{variable_with_no_closing_pair}

{variable_with_closing_pair}
  <div>lots of content in page</div>
  ...
{/variable_with_closing_pair}
```
Btw, thanks for the truly awesome web-mode!

**Comment by fxbois** [comment]
@8cylinder So the only way to know if I should indent below a {xxx} block is looking forward to see if there is closing {/xxx} ?
If it is the case I would only implement indentation for condition blocks (if, etc.)

**Comment by 8cylinder** [comment]
That's correct, the only way to tell if it should be indented is to look ahead, so I think its reasonable to not indent them (its not a very well designed language).  That would probably be an expensive operation on large files.

I'm still learning it but as far as I can tell, the `if`, `if:else`, `if:elseif`, `/if` constructs is the only one you can tell by looking at itself.

Although It just occurred to me that instead of looking forward on every `{xxx}` to find a possible match, it would be better to look _backwards_ from every `{/xxx}` since then you would be guaranteed a match.  That being said, I'm fine if you don't bother since you would probably have to write a bunch of custom code for this template language that wouldn't be usable for any other template language.

**Comment by fxbois** [comment]
@8cylinder the last commit provides some compatibility
