### ISSUE TITLE
Indenting javascript inconsistent

### ISSUE THREAD

**Issue by edsprofile** [fxbois/web-mode#1093]
Inconsistent indenting in if/else when using braces, everything seems to work like the if statement in the GIF the only inconsistency I found was in the else part.

![Peek 2019-10-29 19-25](https://user-images.githubusercontent.com/31055689/67824084-98565d00-fa82-11e9-91c1-7f2993d504be.gif)

--- WEB-MODE DEBUG BEG ---
versions: emacs(26.3) web-mode("16.0.24")
vars: engine("none") minor("none") content-type("javascript") file("/home/ee/Documents/Udemy Web Development Course/Projects/Section_21/patatapClone/test.js")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (visual-line-mode global-visual-line-mode global-eldoc-mode display-line-numbers-mode global-display-line-numbers-mode electric-pair-mode show-paren-mode shell-dirtrack-mode async-bytecomp-package-mode global-git-commit-mode magit-auto-revert-mode diff-auto-refine-mode global-magit-file-mode emmet-mode override-global-mode helm-autoresize-mode helm-mode projectile-mode which-key-mode beacon-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---

--- web-mode in my init.el -----
(use-package web-mode
  :ensure t
  :config
  (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.css?\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.js\\'" . web-mode)))

(defun my-web-mode-hook ()
  "Hook for Web mode."
  (setq web-mode-enable-auto-quoting nil)
  (setq web-mode-indent-style 4)
  (web-mode-use-tabs)
  (setq web-mode-markup-indent-offset 4)
  (setq web-mode-css-indent-off 4)
  (setq web-mode-code-indent-offset 4)
  (setq web-mode-script-padding 4)
  (setq web-mode-enable-css-colorization t))
(add-hook 'web-mode-hook  'my-web-mode-hook)

**Comment by fxbois** [comment]
@edsprofile fix with last commit. Thx for the report
