### ISSUE TITLE
Indenting anonymous function in js

### ISSUE THREAD

**Issue by edsprofile** [fxbois/web-mode#1096]
Not sure if there is a setting to change this or if it is a bug.
I have also added the indent debug information under the web mode debug.

The braces indent when they are on their own line. (see GIF)
I was expecting the braces in the anonymous function to be the same as second function.
(second function from the top)

![Peek 2019-11-03 13-41](https://user-images.githubusercontent.com/31055689/68092585-9fde8300-fe41-11e9-837e-9bc97481157c.gif)

Similar to this I submitted a few days ago which was fixed thank you, I added it just in case you find it useful. 
[https://github.com/fxbois/web-mode/issues/1093](url)

--- WEB-MODE DEBUG BEG ---
versions: emacs(26.3) web-mode("16.0.25")
vars: engine("none") minor("none") content-type("javascript") file("/home/ee/Documents/playground/test.js")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (global-eldoc-mode display-line-numbers-mode global-display-line-numbers-mode electric-pair-mode show-paren-mode shell-dirtrack-mode async-bytecomp-package-mode global-git-commit-mode magit-auto-revert-mode diff-auto-refine-mode global-magit-file-mode emmet-mode override-global-mode helm-autoresize-mode helm-mode projectile-mode which-key-mode beacon-mode whitespace-mode flyspell-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---
I420(114) javascript-indentation
I250(145) closing-paren
I420(147) javascript-indentation
I250(148) closing-paren
I370(145)
I420(151) javascript-indentation
I250(163) closing-paren
I420(171) javascript-indentation

--- MY INIT.EL WEB MODE SETTINGS ---
(use-package web-mode
  :ensure t
  :config
  (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.css?\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.js\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.php\\'" . web-mode)))

(defun my-web-mode-hook ()
  "Hook for Web mode."
  (setq web-mode-enable-auto-quoting nil)
  (setq web-mode-enable-css-colorization t)
  (setq truncate-lines t))
(add-hook 'web-mode-hook  'my-web-mode-hook)

**Comment by fxbois** [comment]
@edsprofile I've pushed a fix
