### ISSUE TITLE
Bad indentation with tsx

### ISSUE THREAD

**Issue by georgebihtas** [fxbois/web-mode#1097]
I have a .tsx file and a function that returns some html. It starts like:

`return <div className=...`

Then at some point I have a component with many arguments so I have to split them vertically. I get the following indentation 

![tsx1](https://user-images.githubusercontent.com/22296510/68529787-2390e780-02fa-11ea-977d-59fc40f8374e.png)

instead of 

![tsx2](https://user-images.githubusercontent.com/22296510/68529793-2db2e600-02fa-11ea-8c0a-28769b99b3a9.png)

Looks like the `data` argument is indented more to the left than it should and the rest of the arguments are indented based on  the open curly brace of `data={data}`

I run  `GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian`. 

`tide` is also part of my `tsx` setup.

**Comment by georgebihtas** [comment]
Updates: 

I don't have this issue with other files/similar cases. Only with this file. It's a long file compared to others (388 lines) and it has an interchanging mixture of html, typescript.

Another thing I have just observed: If I set the buffer to `html-mode` then the indentation issue is fixed.

**Comment by fxbois** [comment]
@georgebihtas please post the example on gist

**Comment by georgebihtas** [comment]
@fxbois 

https://gist.github.com/georgebihtas/0387ded70ea10f9f5e3daba58ab590c2

Please let me know it does the job for you

A couple of pics indicating this weird behaviour using the `gist` code above

![tsx1](https://user-images.githubusercontent.com/22296510/68580981-69bb8780-046f-11ea-9927-63bb5f24afcf.png)

![tsx2](https://user-images.githubusercontent.com/22296510/68580985-6d4f0e80-046f-11ea-8627-f222e19b44bd.png)

In case it helps, I have tried a lot of things to find any possible conflicts with other packages e.g. updating different versions of `tide`, `web-mode`, disabling `electric-indent` etc.

**Comment by AllanJian** [comment]
@fxbois 

I have same problem in jsx.

if write jsx tags as return of arrow functions () => (<xxx></xxx>), the indentation always be bad for attributes. 

simple code here:


```
import React from 'react';

export default class App extends React.Component<any, any> {
  render() {
    return (
      <div>
        <div>
          <div
            onClick={() => (
              <div
                data="1"
                      data1="1"
                      data2="1"
                      data2="1"
                      data3="1"
              />
            )}
          />
        </div>
      </div>
    );
  }
}

```

but, if the arrow function return like this, indents will be good.

```
import React from 'react';

export default class App extends React.Component<any, any> {
  render() {
    return (
      <div>
        <div>
          <div
            onClick={() => {
              return (
                <div
                  data="1"
                  data1="1"
                  data2="1"
                  data2="1"
                  data3="1"
                />
              );
            }}
          />
        </div>
      </div>
    );
  }
}

```
And, there are some other problems of indentation.
```
// bad indentation of '?' for eslint
export default class App extends React.Component<any, any> {
  render() {
    return (
      <div>
        {true
        ? <div/>
        : ''
        }
      </div>
    );
  }
}
// I put a space before condition, so '?' indent right
export default class App extends React.Component<any, any> {
  render() {
    return (
      <div>
        { true
          ? <div />
          : ''
        }
      </div>
    );
  }
}

// attribute indent bad for eslint
export default class App extends React.Component<any, any> {
  render() {
    return (
      <div>
        { true
          ? <div
              a="1"
              b="2"
          />
          : ''
        }
      </div>
    );
  }
}
// I have to use () to resolve
export default class App extends React.Component<any, any> {
  render() {
    return (
      <div>
        { true
          ? (
            <div
              a="1"
              b="2"
            />
          )
          : ''
        }
      </div>
    );
  }
}

```

please forgive my English
