### ISSUE TITLE
Syntax of single quote in PHP

### ISSUE THREAD

**Issue by nerton** [fxbois/web-mode#1098]
When using web-mode for PHP the syntax of single quote is punctuation. It should be quote like for double quote.

**Comment by fxbois** [comment]
@nerton please post a screenshot

**Comment by nerton** [comment]
I can't post a sreenshot, because it generally works well, behaves as a string. But there are strange behaviors. For example, try selecting a text and type " to surround it with quotes. It works. Try the same with single quote and you see that it overwrites the string. So it does not always work as a string delimiter.

I investigated a problem and found that single quote does not have string syntax in a php file with web mode. You can check it by evalling these:

```
(char-to-string (char-syntax ?")) 
->  "  (quote)
(char-to-string (char-syntax ?'))
 -> . (punctuation)

```

Changing the syntax of single quote to punctuation solves the problem:

> (modify-syntax-entry ?' "\\"")

**Comment by DoMiNeLa10** [comment]
It is worth noting that doing this will break typing text into plain HTML, especially if it ends up getting paired.

**Comment by fxbois** [comment]
@nerton in fact I really do not understand what you want

**Comment by nerton** [comment]
> 
> @nerton in fact I really do not understand what you want

I don't know if you are familiar with the concept of syntax tables in emacs. They describe character roles in the buffer, so other emacs packages can provide syntactic operations which can work in any buffer which sets up the syntax properly. [More info here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Tables.html).

One such operation is surrounding code with delimiters. Like when you select a part of the code and press ( then it surrounds it with parens without having to insert the open and close paren separately. It also works for [] and other parens too, including string quotes, so you can select a text in the buffer, press double quote (") and it surrounds the string with " delimiters. 

This should also work for single quotes (') in PHP buffers, because single quote is a string delimiter in PHP. But web-mode sets the syntax of single quote improperly to punctuation ([see syntax classes here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Class-Table.html#Syntax-Class-Table)) which breaks this feature (if you select and string a type a single quote then it overwrites the string instead of surrounding it).

So I'd like you to set the syntax of single quote to string delimiter in web-mode PHP buffers, so other packages which rely on emacs syntax descriptors can work together properly with web-mode.

**Comment by fxbois** [comment]
@nerton understood !
it is not really possible. I can have a Js string which will embed a php string.

**Comment by nerton** [comment]
> 
> 
> @nerton understood !
> it is not really possible. I can have a Js string which will embed a php string.

Isn't it the same with double quotes? You can have a double quoted string in js which embeds a php string. What's the difference?
