### ISSUE TITLE
Javascript comment delimiter face

### ISSUE THREAD

**Issue by gaudecker** [fxbois/web-mode#1100]
I'd like to humbly request an addition of `web-mode-javascript-comment-delimiter-face` to web-mode's faces.

It should match both single and multi line comment delimiters.

```javascript
// Comment
```
Comment delimiter should be `//`.

```javascript
/**
 * Comment
 */
```

Comment delimiter should be `/**` (or `/*`), ` * `, and ` */`.

**Comment by fxbois** [comment]
@gaudecker not sure to understand what you want.
Could you provide a screenshot that could illustrate that ?

**Comment by gaudecker** [comment]
<img width="578" alt="Screen Shot 2020-02-24 at 9 00 45 AM" src="https://user-images.githubusercontent.com/872609/75133621-2b776a80-56e4-11ea-9319-92eee32741e1.png">

As you can see from this image, the comment delimiters are monospaced while the actual comment (aside from the markup) is proportional.

My proposal was to define separate faces for the delimiters and the content.

Hope this clears things.

**Comment by fxbois** [comment]
I've started to look at this and it is too complicated because I have too much ways of commenting things ( ... many template engines have their own delimiters)
