### ISSUE TITLE
Support top-level indentation of Razor code blocks

### ISSUE THREAD

**Issue by rpoddighe** [fxbois/web-mode#1101]
It would be great if web-mode supported indenting Razor code blocks. For me, the top-level indentation within a Razor code block doesn't seem to work.

Expected indentation:
``` razor
@{
  var foo = 1;
  
  if (foo == 1) {
    foo = 2;
  }
}
```

Actual indentation:
``` razor
@{
var foo = 1;
  
if (foo == 1) {
  foo = 2;
}
}
```

Please correct me if I'm totally missing something.

**Comment by fxbois** [comment]
@rpoddighe I've pushed a fix (use ```web-mode-block-padding```)
