### ISSUE TITLE
HTML5 truly supports unqouted attribute values but web-mode doesn't highlight them properly.

### ISSUE THREAD

**Issue by roket1428** [fxbois/web-mode#1103]
I think the title contains all the information.
Actual:
![](https://0x0.st/z0YB.jpg)
Expected:
![](https://0x0.st/z0YM.jpg)

**Comment by fxbois** [comment]
@roket1428 web-mode deals with unquoted attributes from the beginning

**Comment by roket1428** [comment]
> @roket1428 web-mode deals with unquoted attributes from the beginning
So weird. As you can see at the picture, it clearly didn't show it as green as it should. Now tested it, it clearly does support. I have no idea why is that. Sorry for that, I'm closing it.
