### ISSUE TITLE
Strange indent behavior in Vue

### ISSUE THREAD

**Issue by gary-ruizhang** [fxbois/web-mode#1104]
When writing Vue, the indentation become 1 space inside <script> and <style> . My config is 2 spaces.
<img width="820" alt="Screen Shot 2019-12-22 at 10 52 10" src="https://user-images.githubusercontent.com/32344731/71316349-6e7d4d80-24a9-11ea-9841-0a81d1bdaebc.png">
inside <script>
<img width="600" alt="Screen Shot 2019-12-22 at 10 50 59" src="https://user-images.githubusercontent.com/32344731/71316362-9bc9fb80-24a9-11ea-8f55-4dce57957fab.png">
inside <style>
<img width="317" alt="Screen Shot 2019-12-22 at 10 51 38" src="https://user-images.githubusercontent.com/32344731/71316367-a4223680-24a9-11ea-8f04-64239dfcfa66.png">
inside \<template\> everything works fine
<img width="309" alt="Screen Shot 2019-12-22 at 10 57 24" src="https://user-images.githubusercontent.com/32344731/71316389-ef3c4980-24a9-11ea-9a0f-981e4f5c4298.png">

**Comment by VelikiiNehochuha** [comment]
try set, too
``` lisp
(setq web-mode-style-padding 2)
(setq web-mode-script-padding 2)
```

**Comment by fxbois** [comment]
@gary-ruizhang look at ```web-mode-script-padding``` and ```web-mode-style-padding```
