### ISSUE TITLE
[Question] Associate script[lang="ts"] with typescript

### ISSUE THREAD

**Issue by chrunchyjesus** [fxbois/web-mode#1105]
Not sure whether I should have asked here or at `lsp-mode`.

Does `web-mode` assiciate `<script lang="ts">` blocks with typescript? I am currently inside a `.svelte` component and use it in combination with typescript. However, the typescript block gets associated with javascript instead.

**Comment by fxbois** [comment]
@chrunchyjesus could you provide a full example on gist please

**Comment by chrunchyjesus** [comment]
You mean my emacs config or the svelte file? For my emacs config I am using [doom emacs](https://github.com/hlissner/doom-emacs). The only modifications I have done are these:
```elisp
(add-to-list 'auto-mode-alist '("\\.svelte\\'" . web-mode))
(defun my-web-mode-hook ()
  "Hooks for Web mode."
  (setq web-mode-indent-style 4)
  (setq web-mode-markup-indent-offset 4)
  (setq web-mode-css-indent-offset 4)
  (setq web-mode-code-indent-offset 4)
  (setq web-mode-style-padding 4)
  (setq web-mode-script-padding 4)
  (setq web-mode-block-padding 0)
  (setq web-mode-part-padding 4))
(add-hook 'web-mode-hook  'my-web-mode-hook)
```

As for a sample svelte file:

```html
<script lang="ts">
    let inputElement: HTMLInputElement // from lsp-mode: js: 'types' con only be used in a .ts file
</script>

<label class="container">
    <input type="text" bind:this={inputElement} >
</label>
```

**Comment by fxbois** [comment]
@chrunchyjesus the last commit provides should provide some compatibility

**Comment by chrunchyjesus** [comment]
Thanks. :)

I am not sure if it works though. `web-mode-reveal` on the `1105.html` file tells me that it is javascript.

```
[point=20 engine="none" minor="none" content-type="html" language-at-pos="javascript"]
tag-beg(nil) tag-end(nil) tag-name(nil) tag-type(nil) tag-attr(nil) tag-attr-beg(nil) tag-attr-end(nil) part-side(javascript) part-token(nil) jsx-beg(nil) jsx-end(nil) jsx-depth(nil) block-side(nil) block-token(nil) block-controls(nil) block-beg(nil) block-end(nil) syntax-table(nil) font-lock-face(nil) face(highlight-indent-guides-character-face) 
```

**Comment by fxbois** [comment]
@chrunchyjesus at the moment I treat ts like js

**Comment by chrunchyjesus** [comment]
Hm. Okay, thanks.
