### ISSUE TITLE
Auto-closing does not work with outshine

### ISSUE THREAD

**Issue by noctuid** [fxbois/web-mode#1107]
[outshine](https://github.com/alphapapa/outshine) remaps `self-insert-command` to `outshine-self-insert-command`. `web-mode-on-post-command` checks that the command is `self-insert-command`, so auto-closing and auto-quoting do not work with `outshine-mode` enabled. Additionally checking if the command is `(key-binding [remap self-insert-command])` would probably work to fix issues like this.

**Comment by fxbois** [comment]
@noctuid could you provide a patch ?

**Comment by fxbois** [comment]
@noctuid please reopen if you can provide a fix
