### ISSUE TITLE
web-mode-attribute-previous/next won't recognize some Vue props and events

### ISSUE THREAD

**Issue by svenssonaxel** [fxbois/web-mode#1108]
**To reproduce:**
* Put the following in mwe.Vue:
```
<template>
  <div
    v-show="val1"
    class="val2"
    @click="val3"
    @click.prevent="val4"
    :prop="val5"
    v-on:keydown="val6"
    @keydown="val7"
    v-on:keydown.enter="val8"
    @keydown.enter="val9"
  />
</template>
```
* Open the file in emacs and activate `web-mode`
* Go to the beginning of the buffer
* Repetedly execute `web-mode-attribute-next`

**Expected:**
* All 9 lines with attributes, including Vue props and events, are visited in turn

**Actual:**
* Lines containing `val3`, `val5` and `val7` are skipped.

**Version info:**
* GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-23, modified by Debian
* web-mode cd000fc

**Comment by fxbois** [comment]
@svenssonaxel the last commit should fix the issue
