### ISSUE TITLE
tag new release?

### ISSUE THREAD

**Issue by thkoch2001** [fxbois/web-mode#1112]
Could you please bless some commit with a release tag? I would like to update the Debian package and it makes it easier for me if I can just refer to a Git tag as a version you like people to use.
There is no problem in adding a new tag every few weeks.

Thank you!

**Comment by fxbois** [comment]
@thkoch2001 Hello, what kind of tag should I use ? The version ?
(any doc online about that ?)

**Comment by fxbois** [comment]
@thkoch2001 please reopen when you can provide some more info

**Comment by thkoch2001** [comment]
Just the version number would be fine, e.g.

    git tag 16.0.29 $COMMITID

If you have a GPG key than you also sign your tag:

    git tag -s 16.0.29 $COMMITID

**Comment by thkoch2001** [comment]
I can't re-open an issue in this repo.

**Comment by fxbois** [comment]
in fact I already use tags and release:
https://github.com/fxbois/web-mode/releases

**Comment by thkoch2001** [comment]
Yes, you already use tags and releases. But could you please tag a **new** release? The current version 16 is two years old and a lot has changed since then.

The "version:" field in web-mode.el is "16.0.29", not just "16" as the last git tag.

**Comment by fxbois** [comment]
@thkoch2001 ok, understood.
I'll finish the last patches and provide a new release.
