### ISSUE TITLE
Attribute name appears in minibuffer on every keystroke following "better attr lexing"

### ISSUE THREAD

**Issue by JacksonGariety** [fxbois/web-mode#1115]
Something in [this commit](https://github.com/fxbois/web-mode/commit/b41b1f6bfdfbfc433b80c8ce8e3a0dc4c9cbf260) has caused the name of the last 
HTML attribute in the active buffer to print in the minibuffer with every keystroke. The computation is so intense that my CPU fan starts to spin if I type a lot.

**Comment by fxbois** [comment]
@JacksonGariety you're right ... sorry for that

**Comment by JacksonGariety** [comment]
@fxbois no worries! it was exciting to see emacs working so hard.

**Comment by fxbois** [comment]
@JacksonGariety in fact there are more debugs that were left... it will be corrected in the next commit !
