### ISSUE TITLE
Syntax highlighting broken in react-mode when JSX missing semicolon

### ISSUE THREAD

**Issue by radamant** [fxbois/web-mode#1117]
There is an issue w/ syntax highlighting in react-mode. This issue does not present when all lines end with semicolons.

**Screenshot from emacs:**
<img width="737" alt="image" src="https://user-images.githubusercontent.com/12339/76130869-27d7c380-5fc1-11ea-8a3c-24c5d40e8061.png">

You can see that the syntax highlighting is no longer correct starting on the line where `FormGroup` is defined in this example.

**Sample code:**
```jsx
import React from "react";
import { Text, View } from '@react-pdf/renderer';

const Group = ({children}) => <View>{children}</View>

const FormGroup = ({children}) => <View>{children}</View>

const FormText = ({children}) => <Text>{children}</Text>

export default () => (<Group>
  <FormGroup>
    <FormText>Some text</FormText>
  </FormGroup>
</Group>)
```

**Comment by fxbois** [comment]
@radamant web-mode does not have a real js parser ... 
semicolons are currently required at the end of lines
