### ISSUE TITLE
Editing JSX is generally very slow

### ISSUE THREAD

**Issue by JacksonGariety** [fxbois/web-mode#1126]
Web-mode performs quite well on HTML files, as well as JavaScript files. But editing JSX is very slow for some reason, especially when indenting/making returns. I'm willing to disable some fontification features in order to gain performance. I have this in my emacs file:

```elisp
  (setq web-mode-code-indent-offset                   2
        web-mode-markup-indent-offset                 2
        web-mode-css-indent-offset                    2
        web-mode-enable-html-entities-fontification   nil
        web-mode-enable-block-face                    nil
        web-mode-enable-comment-annotation            nil
        web-mode-enable-comment-interpolation         nil
        web-mode-enable-control-block-indentation     nil
        web-mode-enable-css-colorization              nil
        web-mode-enable-current-column-highlight      nil
        web-mode-enable-current-element-highlight     nil
        web-mode-enable-element-content-fontification nil
        web-mode-enable-heredoc-fontification         nil
        web-mode-enable-inlays                        nil
        web-mode-enable-optional-tags                 nil
        web-mode-enable-part-face                     nil
        web-mode-enable-sexp-functions                nil
        web-mode-enable-sql-detection                 nil
        web-mode-enable-string-interpolation          nil
        web-mode-enable-whitespace-fontification      nil
        web-mode-enable-auto-expanding                nil
        web-mode-enable-auto-indentation              nil
        web-mode-enable-auto-closing                  nil
        web-mode-enable-auto-opening                  nil
        web-mode-enable-auto-pairing                  nil
        web-mode-enable-auto-quoting                  nil)
```

But it doesn't seem to have any affect on performance, and ~~I can't even tell if any features are actually being disabled~~. (EDIT: it appears there is no setting to disable JSX syntax highlighting.)

In any event, what can I do to get faster JSX?

**Comment by fxbois** [comment]
could you post your example on gist please (one that triggers slowness)

**Comment by JacksonGariety** [comment]
@fxbois my code is private, but I googled "jsx example" and found this document: https://github.com/gothinkster/react-redux-realworld-example-app/blob/master/src/components/Editor.js

If you put your cursor on line 133 and hold the return key, you will see that emacs locks up.

It may also be important to note that the lag isn't simply correlated with the amount of elements in the document. Removing attributes from elements seems to improve performance, and nesting elements seems to make things worse, but a long document is not necessary unperformant.

**Comment by fxbois** [comment]
@JacksonGariety could you try with the last version ?

**Comment by JacksonGariety** [comment]
Unfortunately, performance when editing the file posted above is much the same for me on today's web-mode version `20200424.1153`.

**Comment by fxbois** [comment]
@JacksonGariety it must be related to your config.
When I hit renter at the place you mention, it is instantaneous on my site

**Comment by JacksonGariety** [comment]
@fxbois if you hold the enter key, I think you will see that `web-mode` has trouble making new lines fast enough to keep up. As the file gets larger than the one I posted above, it gets worse.

If it's too difficult to improve performance, is there a way we can disable some jsx niceties? Maybe disabling syntax highlighting on JSX markup tags?

**Comment by fxbois** [comment]
@JacksonGariety force the content-type as javascript (not jsx)
see ```web-mode-content-types-alist```
