### ISSUE TITLE
When work with lsp-mode, right side quote of inserted snippet lost

### ISSUE THREAD

**Issue by chunlinyao** [fxbois/web-mode#1127]
When I enable lsp-mode, inputed some prefix of attribute, the dropdown show candidate, If I selected on attribute and press enter key, the snippet inserted into buffer like `foo=" `,  it should insert `foo=""`.

The right side quote lost, and caret is one space between the left quote. I tested lsp-mode with HTML mode, it can insert attribute correctly, so I think there maybe some issue in web-mode.

**Comment by fxbois** [comment]
lsp-mode is not compatible with web-mode

**Comment by chunlinyao** [comment]
Maybe it is related to yasnippet, When insert snippet like `<a href="$1">$2</a>`. This patch can resolve it.
```
-- web-mode.el.orig	2020-08-13 20:20:45.000000000 +0800
+++ web-mode.el	2020-08-11 14:05:56.000000000 +0800
@@ -11488,7 +11488,8 @@
         (backward-char)
         (setq auto-quoted t))
        ((and (eq char ?\")
-             (eq (char-after) ?\"))
+             (eq (char-after) ?\")
+             (not (eq (char-before (- pos 1)) ?\=)))
         (delete-char 1)
         (cond
          ((looking-back "=\"\"" (point-min))
```
