### ISSUE TITLE
CSS in JS

### ISSUE THREAD

**Issue by stevemolitor** [fxbois/web-mode#1128]
How can I extend `web-mode` to support CSS in JS? There are several different ways to do it, depending on which library you use, but for example using emotion you might have something like this in a `.jsx` or `.tsx` file:

```tsx
const myStyle = css`
  font-size: 16px;
  max-width: 560px;
  margin: 0 auto;
`;
```

I'd like to highlight everything inside the backticks block as CSS.

Happy to contribute if you can point me in the right direction. Thanks!

**Comment by fxbois** [comment]
I last commit brings this.
You can customise 3 new faces : ```web-mode-interpolate-color1-face```, ```web-mode-interpolate-color2-face```, ```web-mode-interpolate-color3
<img width="596" alt="emacs-literal" src="https://user-images.githubusercontent.com/959622/79672076-2a882400-81cf-11ea-9fae-4f94954f155b.png">
-face```

**Comment by swans-one** [comment]
Hey @fxbois , this is awesome. A couple questions though:

it looks like only one of those three faces is actually used in the highlighting. You use `web-mode-interpolate-color1-face` in [this block](https://github.com/fxbois/web-mode/commit/989c0beda50cb90324acaf67ba08ed81cd7984fa#diff-65d99b4476be4737f539e1bc19325383R6827), which colorizes html tag names and css property names. Also,` web-mode-variable-name-face` still colorizes `${expressions}` in the template string. 

But it seems like `web-mode-interpolate-color2-face` and `web-mode-interpolate-color3-face` are currently unused. Is that intentional? In my dream world, I'd love it if they could style html tag brackets and attribute names.

Thanks again!

**Comment by fxbois** [comment]
@swans-one I can do this (bracket and attr names)

**Comment by fxbois** [comment]
@swans-one the last commit brings this

**Comment by stevemolitor** [comment]
@fxbois Last commit works great for me, thanks!

How would I get `company-mode` css completion working when editing CSS in JS? Thanks.

**Comment by fxbois** [comment]
@stevemolitor I do not use ```company-mode``` and can not help you on this

**Comment by stevemolitor** [comment]
Sorry this is a little off topic, but in case anyone else stumbles across this:

The new `web-mode-is-css-string` function will help setup `company-mode` to setup company completion. 

For example, I use `tide-mode`, and my `company-mode` backends when editing tsx files are `company-tide` and `company-css` in that order. I can advise `company-tide` to return `nil` from the company `prefix` command, which tells company to try the next backend, `company-css`:

```elisp
(defun company-tide-advice (orig-fun &rest args)
  (if (and (eq (nth 0 args) 'prefix) (web-mode-is-css-string (point)))
      'nil
    (apply orig-fun args)))
(advice-add 'company-tide :around #'company-tide-advice)
```

There's probably a better way to do it, but anyways `(web-mode-is-css-string (point))` gives you the context to know if you should try CSS completion or not.

**Comment by Sleepful** [comment]
I'm not getting highlighting inside 
```jsx
const style = css`
  color: hotpink;
`
```
no idea why :( 
I'm on commit `60ffd878c4371644bd964f00fea38054645e3e47` , so this one https://github.com/fxbois/web-mode/commit/60ffd878c4371644bd964f00fea38054645e3e47, which should include the highlighting, I don't get it

**Comment by Sleepful** [comment]
Ok i had to customize `web-mode-interpolate-color1-face`, I was confused because the face is the same as the string color. Changing its color highlights css properties. `${x}` part of the example gets highlighted automatically with on customization of any face tho.
```css
const myStyle = css`
  font-size: ${x}px;
  max-width: 560px;
  margin: 0 auto;
`;
```

**Comment by Sleepful** [comment]
it would be nice if it used a different face than `web-mode-javascript-string-face` for the values of the css though, currently they are the same color as strings and it can't be changed without affect strings in other parts
