### ISSUE TITLE
Update `web-mode-language-at-pos` to consider CSS in JS 

### ISSUE THREAD

**Issue by stevemolitor** [fxbois/web-mode#1130]
I _think_ `web-mode-language-at-pos` needs to be updated to consider CSS in JS - see #1128.

I had to add the following advice to `web-mode-language-at-pos` to help get `company-mode` completion to work:

```elisp
(defun web-mode-language-at-pos-advice (orig-fun &rest args)
  (let ((pos (or (car args) (point))))
    (or (and (web-mode-is-css-string pos) "css")
        (apply orig-fun args))))
(advice-add 'web-mode-language-at-pos :around #'web-mode-language-at-pos-advice)
```

I needed to do that because [`company-css.el`](https://github.com/company-mode/company-mode/blob/master/company-css.el#L424) calls `web-mode-language-at-pos`. I'm guessing other things like web-mode comment formats will also depend on `web-mode-language-at-pos` correctly detecting CSS in JS but I haven't tested. 

See [this issue comment](https://github.com/fxbois/web-mode/issues/1128#issuecomment-619205792) for more context.

**Comment by fxbois** [comment]
@stevemolitor the way web-mode works, it wouldn't make sense to do that. It is better that you do this on your code.
