### ISSUE TITLE
Support of helper tags for indentation of JavaScript in Mojolicious templates

### ISSUE THREAD

**Issue by smonff** [fxbois/web-mode#1132]
Hi,

I use `web-mode` for editing Mojolicious (Perl) templates. If I use a standard `<script></script>` tag, no problem, I have indentation and syntax coloring:

```javascript
<script>
 $(function() {
   $('#select-year select').change(function() {
     $('#select-year').attr('action', '/' + this.value );
     $('#select-year').submit();
   });
 });
</script>
```
The issue is that Mojolicious allow the use of some [*tag helpers*](https://mojolicious.org/perldoc/Mojolicious/Plugin/TagHelpers#javascript) that generate the tags and all the attributes boilerplate:

```
%= javascript begin
  $(function() {
  $('#select-year select').change(function() {
  $('#select-year').attr('action', '/' + this.value );
  $('#select-year').submit();
  });
  });
% end
```

In this case, no indentation nor syntax coloring, and if I do the indentation by hand it is un-indented automatically (because `web-mode` does it's work fine :D). Too bad because the code looks better with correct indentation but Mojolicious tag helpers are also fine!

**Comment by fxbois** [comment]
@smonff I've pushed a fix

**Comment by smonff** [comment]
Thank you very much for your work! I will give it a try today.

**Comment by smonff** [comment]
It works perfectly! 

Should have told you before, but there is a very similar situation for a [`%= stylesheet` helper](https://mojolicious.org/perldoc/Mojolicious/Plugin/TagHelpers#stylesheet) that could be handled too. 

I'll look at the `web-mode` code and will try to send a patch. If I won't be able to do it (my elisp capacities are very limited), I'll provide a detailed ticket about it so hopefully the `Mojo::Template` Embedded Perl support could be improved.
