### ISSUE TITLE
Wrap and indent html attributes each on a new line

### ISSUE THREAD

**Issue by mustaqimM** [fxbois/web-mode#1133]
Hi there, is it possible to auto indent html attributes each on a new line?

Like from this:
![image](https://user-images.githubusercontent.com/24436622/81182441-506a4280-8f9d-11ea-8981-5357b366d452.png)

to something like this:
![image](https://user-images.githubusercontent.com/24436622/81182585-81e30e00-8f9d-11ea-96f9-9b6d0b552995.png)

**Comment by jsmestad** [comment]
Also wondering about this :)

**Comment by NateEag** [comment]
I'd use this if `web-mode` supports it.

I prefer to format my HTML with the first attribute immediately following the tag name, and others wrapped / indented to match:

```html
<a id="foobar"
   class="class1 class2"
   href="https://www.example.com">link</a>
```

Just my $0.02.

**Comment by fxbois** [comment]
@mustaqimM you mean you want a command that does this ?

**Comment by mustaqimM** [comment]
Ya, which could work something like this:
https://github.com/dannyconnell/vscode-split-html-attributes
or `electric-newline-and-maybe-indent`

**Comment by ianpan870102** [comment]
I suggest incorporating Prettier into your editor. Maybe format-on-save can solve it

**Comment by fxbois** [comment]
I’ll work on this.
