### ISSUE TITLE
No indentation allowed for inline <script> tag?

### ISSUE THREAD

**Issue by sontek** [fxbois/web-mode#1139]
Hello, I'm coding some HTML that looks like this (its in a .ejs file if that matters):

```
<!doctype html>
<html lang="en">
    <head>
        <title>Introduction to WebRTC</title>
    </head>
    <body>
        <video autoplay></video>
        <script>
       *
        </script>
    </body>
</html>
```

My cursor is on the `*`.   I'm trying to hit Tab here to indent to start coding the body of the script tag and it refuses to move.  It just doesn't do anything at all.  Interestingly, if I'm on the `<script>` tag and I say "insert line below" it does in fact indent it the way I expect.

So I have 2 questions:

1.  Can I get it to allow me to indent inside inline script tags?
2.  Can I get it to never refuse to do something I request of it?  I'd prefer it always indent if I request it to.  For example, if I opened a <div> and hit tab twice, I'd prefer if it did 2 indentations rather than refusing to do so. 

Thanks!

**Comment by sontek** [comment]
This has gotten much worse as I coded, I'm not sure whats going on now but I can't get it to match the formatting of the code at all, the code is all aligned on 4 spaces inside the inline and even "insert line below" has started outdenting to the weird location:


![Jun-08-2020 12-35-22](https://user-images.githubusercontent.com/151924/84056697-93e11380-a984-11ea-8f29-4c9cb649b40d.gif)

**Comment by sontek** [comment]
Sometimes it just fills in and autocompletes stuff that is not relevant to what I'm typing.  For example, if I want to write a new listener:

![Jun-08-2020 12-47-57](https://user-images.githubusercontent.com/151924/84057885-5c736680-a986-11ea-8737-301e77cba2b3.gif)

See how it added the `sendMessage` in there while I was typing?

**Comment by fxbois** [comment]
@sontek please try with an empty .emacs

**Comment by sontek** [comment]
At least with the indentations, its the same:

![Jun-08-2020 14-43-39](https://user-images.githubusercontent.com/151924/84068112-7ddc4e80-a996-11ea-8c73-3c86da71ee84.gif)

**Comment by sontek** [comment]
ok, with an empty one its just wanting to use 2 characters instead of 4 and it won't let him hit tab a second time to go to 4.   Can I tell it not to refuse to do what I want?   I like having some sane defaults but if it can't detect the format of the code then it'd be nice to have it not try to force the default, just suggest it

**Comment by sontek** [comment]
It doesn't indent the second curly though:

![Jun-08-2020 14-49-43](https://user-images.githubusercontent.com/151924/84068676-58037980-a997-11ea-8a5b-725c7c2a7bd6.gif)

**Comment by sontek** [comment]
HTML I'm using inside the `.ejs` file
```
<!doctype html>
<html lang="en">
    <head>
        <title>Introduction to WebRTC</title>
    </head>
    <body>
        <div>
            Video: <select id="camera"></select>
        </div>
        <script>
        </script>
    </body>
</html>
```
