### ISSUE TITLE
Edit closing tags

### ISSUE THREAD

**Issue by sggutier** [fxbois/web-mode#1144]
Is there a way of editing the closing tags automatically, like in PhpStorm?

![indekso](https://user-images.githubusercontent.com/5473302/84957360-a49a3380-b0c0-11ea-8128-8ce90c149ce8.gif)

**Comment by fxbois** [comment]
You can use the command web-mode-element-rename

**Comment by NateEag** [comment]
I use [auto-rename-tag-mode for the behavior in your GIF](https://github.com/jcs-elpa/auto-rename-tag).

**Comment by sggutier** [comment]
> I use [auto-rename-tag-mode for the behavior in your GIF](https://github.com/jcs-elpa/auto-rename-tag).

This seems to be able to able to modify it, but it breaks highlighting and `web-mode-navigate`.

![indekso](https://user-images.githubusercontent.com/5473302/85042998-7e70a400-b151-11ea-9f1c-647f82bd99fd.gif)
