### ISSUE TITLE
Ignore Front Matter Data in templates

### ISSUE THREAD

**Issue by azzamsa** [fxbois/web-mode#1145]
I this [an issue](https://github.com/fxbois/web-mode/issues/123) that related to this problem. But I can't find the solution, or related commit except this [one](https://github.com/fxbois/web-mode/commit/3621cf7b6aa5e8faf7036ce5877a5a7e7f5547aa)

I am using the latest revision of web-mode. But whenever I type anything in the yaml front-matter, web-mode always indent those line. Is there any way for web-mode to ignore everything in front-matter?

![Peek 2020-07-09 06-14](https://user-images.githubusercontent.com/17734314/86979428-7ed9e900-c1ab-11ea-9e69-a5bc5d6ea72c.gif)

I think setting `web-mode-engines-alist` to liquid or nunjucks doesn't help, since it's already [the default](https://github.com/fxbois/web-mode/blob/60ffd878c4371644bd964f00fea38054645e3e47/web-mode.el#L883)

The best that web-mode can do is ignore the front-matter at all.

notes:
- [Eleventy frontmatter](https://www.11ty.dev/docs/data-frontmatter/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

Thank you for web-mode.

**Comment by fxbois** [comment]
@azzamsa you can use ```(setq web-mode-enable-front-matter-block t)``` for the files you want. You should enable this in your .emacs in a hook that test the extension or the path of the file

**Comment by azzamsa** [comment]
Worked like a charm!.

Thank you so much for web-mode.
