### ISSUE TITLE
[Documentation] Add full list of web-mode-enable-auto-* to FAQ

### ISSUE THREAD

**Issue by sdubinsky** [fxbois/web-mode#1146]
In the FAQ, it says that starting Emacs in terminal mode will disable autopairs, then it suggests: 

> add (setq web-mode-enable-auto-closing t) and (setq web-mode-enable-auto-pairing t) in your .emacs 

I think there are a couple enable auto-* variables missing, and it would be helpful to have them added to the FAQ as well:

  (setq web-mode-enable-auto-expanding t)
  (setq web-mode-enable-auto-opening t)
  (setq web-mode-enable-auto-quoting t)

**Comment by fxbois** [comment]
ok, done.
