### ISSUE TITLE
Unquoted html attributes not parsed properly

### ISSUE THREAD

**Issue by 12Me21** [fxbois/web-mode#1150]
In unquoted html attributes, web-mode seems to allow any characters except < > / and space, when it should be any characters except " ' \` = > < and space:

https://www.w3.org/TR/2012/WD-html-markup-20120329/syntax.html#attr-value-unquoted
> In addition to the general requirements for attribute values, an unquoted attribute value has the following restrictions:
>
> - must not contain any literal space characters
> - must not contain any """, "'", "=", ">", "<", or "`", characters
> - must not be the empty string

![image](https://user-images.githubusercontent.com/4053256/90987295-dc59a780-e557-11ea-9d83-6d6bfe00f73b.png)

**Comment by fxbois** [comment]
@12Me21 I've pushed a fix

**Comment by 12Me21** [comment]
I believe this was fixed for a while, but now there's a new bug:
The last character of an unquoted attribute is not highlighted if it's next to the `>`
![image](https://user-images.githubusercontent.com/4053256/116613548-c9794d00-a906-11eb-8c7e-ebd66f594ca6.png)

**Comment by lcoq** [comment]
@fxbois FYI replacing `2` to `1` on [this line](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L5646) seems to fix the bug mentionned by @12Me21 , but I'm not sure if this is the right way to fix this.

```
(setq val-end (- val-end 1))
```

**Comment by fxbois** [comment]
should be fixed with last commit
thx for the report and sorry for the delay
