### ISSUE TITLE
Property/attribute comments in JSX nodes

### ISSUE THREAD

**Issue by angrybacon** [fxbois/web-mode#1152]
This is an older issue that was closed: #904

I'm using `web-mode` together with `.tsx` files. I'm working on a new project where there are ESLint comments in JSX nodes.

```jsx
<script
  // eslint-disable-next-line react/no-danger
  dangerouslySetInnerHTML={{something}}
/>
```

AFAIK this could also be written like so:

```jsx
<script
  /* eslint-disable-next-line react/no-danger */
  dangerouslySetInnerHTML={{something}}
/>
```

Those 2 comments both get the following face instead `web-mode-html-attr-name-face`. And `M-;` comments using `{/* asdf */}` (syntax error) instead of either `// asdf` or `/* asdf */`.

(the indent is also wrong)

![image](https://user-images.githubusercontent.com/5608624/93600599-30717380-f9c0-11ea-8ae8-af384926bf76.png)

Is it a bug or a feature that I missed and misconfigured?

**Comment by fxbois** [comment]
quite difficult to solve ... moreover I think a tree sitter mode for jsx/tsx might soon be better suited than web-mode
