### ISSUE TITLE
JSP: autocompletion of imported classes not showing up in jsp tag

### ISSUE THREAD

**Issue by Narice** [fxbois/web-mode#1155]
As said in the title, the autocompletion of imported classes doesn't work in web-mode, here is an example:
![image](https://user-images.githubusercontent.com/31109099/95443313-b5670180-095c-11eb-83eb-27231aed45b9.png)
And here is the same thing but in netbeans:
![image](https://user-images.githubusercontent.com/31109099/95443446-dc253800-095c-11eb-9ee7-4ed8bcc07523.png)
I don't really want to keep using netbeans for editing the actual files, so I was looking for a way to do this in emacs.
I search online and it seems that web-mode was the correct way of editing jsp files.
I also tried lsp-mode for java, which works great for java files, but does not work for jsp files.
I'll use netbeans for now but it would be great if I could go back to the god of editors x)

**Comment by fxbois** [comment]
@Narice Hello,
I have no knowledge about this. Perhaps you should try on emacs stackoverflow
