### ISSUE TITLE
Allow curly brace indentation

### ISSUE THREAD

**Issue by tim-janik** [fxbois/web-mode#1160]
Before v17, I could use web-mode with the GNU coding style (approximately) , in particular curly brace indentation [1]:

~~~js
  if (cond)
    {
      code_block();
    }
  for (i in array)
    {
      code_block();
    }
~~~

The changes for #1020 and #1053 broke the indentation for me.

Please add a setting to allow curly brace indentation again, i.e. conditionalize this part in web-mode.el:

~~~el
            (if (looking-at-p "{") ;; #1020, #1053                                                                                                                  
                (setq offset tmp)
              (setq offset (+ tmp web-mode-code-indent-offset)))
            )
~~~

I don't care what the default is, as long as I can turn GNU coding style like behaviour on... ;-)

[1] [Formatting Your Source Code](https://www.gnu.org/prep/standards/standards.html#Formatting)

**Comment by fxbois** [comment]
@tim-janik you can now user ```(setq web-mode-enable-curly-brace-indentation t)```

**Comment by tim-janik** [comment]
> @tim-janik you can now use `(setq web-mode-enable-curly-brace-indentation t)`

Thank you, there's an issue with if else in this mode however. It fails to format the curly brace after the 'else' correctly, i.e. it produces this:

```js
  if (1)
    {
      x();
    }
  else
  {
    y();
  }
```

**Comment by fxbois** [comment]
I've pushed a fix
