### ISSUE TITLE
expand-region contract for web-mode

### ISSUE THREAD

**Issue by jcs090218** [fxbois/web-mode#1161]
Is there a function that is opposite to `web-mode-mark-and-expand`? I'm not able to contract region using package `expand-region`! Thank you!

**Comment by fxbois** [comment]
@jcs090218 web-mode.el does not provide this
What would be the exact description of this ?

**Comment by jcs090218** [comment]
Sorry, I guess I was wrong about this. I think expand-region take care of it on it's own! Thanks!
