### ISSUE TITLE
JSX slow input

### ISSUE THREAD

**Issue by cbmarc** [fxbois/web-mode#1162]
**Emacs:** DOOM Emacs v.2.0.9 on Emacs 27.
**OS:** MacOS Catalina 
**Gist:** https://gist.github.com/cbmarc/c83f55f07bc20d4739f84a0f01d963ed

When editing JSX with web-mode, if you type somewhere within a tag, it starts lagging on input a lot (text appearing way after I type it). This happens when you start typing in classNames, for instance. One good way to try it out is to type something in a className, delete it or undo, and type again. After a while the mode will be generally slow.

I have profiled emacs when this happened and have gotten some interesting results:
![image](https://user-images.githubusercontent.com/1654802/97573613-5429cf80-19ea-11eb-90fd-e052f06ce5dd.png)

So it seems this might be related to the way web-mode applies fontification or the way it scans jsx tags. If I take into consideration that web-mode seems to work super snappy in large html files when doing the same, I would say it has more to do with jsx tag scanning.

Here are my **web-mode-debug** results:
[web-mode.debug.txt](https://github.com/fxbois/web-mode/files/5458298/web-mode.debug.txt)

If you want me to provide anything more or test something, just tell me.

If you want to see it in action: https://youtu.be/uj9HuJiF67A

**EDIT:** tested on my other laptop with Manjaro Linux and I experience the same issue. Wanted to test this to discard a mac specific emacs issue.

**Comment by nuymax** [comment]
Me too

**Comment by fxbois** [comment]
@cbmarc I've just checked on my MacBook Pro (2017) and I don't manage to trigger the bug.
Have you tried to update web-mode ?

**Comment by akrger** [comment]
Can confirm this bug. I can reliably reproduce it by inserting newlines directly after the first `div` tag. With web-mode, it is laggy, while the insertions runs smoothly without web-mode.

I'm also using Doom emacs and macOS. I updated web-mode to this revision: a3ce21f795e03c7a5489a24b2b3c4fce2d7a2f59

The same issue is happening on Fedora, too.

**Comment by fxbois** [comment]
and without doom emacs ?

**Comment by akrger** [comment]
I opened the example gist with the Doom sandbox (vanilla Doom, only Doom core).
Inserting newlines went smoothly, until I activated web-mode.

**Comment by fxbois** [comment]
ok but without doom ?

**Comment by akrger** [comment]
The same, as I said in the previous post.

**Comment by fxbois** [comment]
I don't know what is vanilla doom or doom core.
Use only emacs with an empty .emacs

**Comment by akrger** [comment]
I also used web-mode with an empty Emacs config, but the same problem persists.

**Comment by akrger** [comment]
Can confirm that the slowness also appears on Fedora 34.

**Comment by angelporo** [comment]
me to
