### ISSUE TITLE
Incorrect commenting in ASP classic

### ISSUE THREAD

**Issue by madhat2r** [fxbois/web-mode#1164]
When commenting `asp` blocks there are two issues.

1. The beginning comment is a double single quote `''` instead of a single one `'`
2. Un-commenting does not work

``` asp
<%
set objBrowserCapabilities = Server.CreateObject("MSWC.BrowserType")
bCookiesSupported = objBrowserCapabilities.cookies
session("sGotoPage") = ""
'if bDebug then
'	response.write bCookiesSupported
'	response.write Session.SessionID 
'	response.end
'end if
%>
<% '^^^ End Startup Code %>

<html>
	<body>
		<div>
			Test
		</div>
	</body>
</html>

```

**Comment by fxbois** [comment]
@madhat2r what do you mean "The beginning comment" ?

**Comment by madhat2r** [comment]
@fxbois Sorry if I wasn't clear. What I mean is that the character that signifies a start of a comment is using two single quotes instead of one.

**Comment by fxbois** [comment]
@madhat2r I've pushed a fix

**Comment by madhat2r** [comment]
Thanks @fxbois , the commenting and uncommenting works now.
