### ISSUE TITLE
How to enable pug syntax highlight for vue.js?

### ISSUE THREAD

**Issue by Artawower** [fxbois/web-mode#1165]
Hello, thanks a lot for your mode, it's very helpful! 

I faced problem with template highlighting (pug) for vue js, and i don't know how can i enable that, i saw this [issue](https://github.com/fxbois/web-mode/issues/1014), but i haven't comprehension about configuration.

my configuration:
```
(require 'eglot)
(require 'web-mode)
(define-derived-mode custom-vue-mode web-mode "VueJS"
(add-to-list 'auto-mode-alist '("\\.vue\\'" . custom-vue-mode))
(add-hook 'custom-vue-mode-hook #'eglot-ensure)
(add-to-list 'eglot-server-programs '(custom-vue-mode "vls"))
```

Now its looks like this
![image](https://user-images.githubusercontent.com/16963833/99280706-b2f0a500-2842-11eb-823e-3f4451ae25b9.png)

I also have tried use jade, but i didn't achieve appropriate result. Now i forced to use manual mode for pug and vue (might be can i automate this process when cursor join to template mode and enable web-mode after leaving?)

**Comment by fxbois** [comment]
@Artawower please post your example on gist

**Comment by Artawower** [comment]
```
<template lang="pug">
  div.test
    a.link {{ a  }}
</template>

<script>
export default {
  data() {
    return {
      a: 4
    };
  },
  methods: {
    someMethod() {
      this.logSomething();
    },
    logSomething() {
      this.asdasdasd();
      a = 4;
      return;
    }
  }
};
</script>

<style lang="scss">
.con {
  .link {
    color: red;
  }
}
</style>
```

**Comment by fxbois** [comment]
@Artawower I've pushed a fix

**Comment by Artawower** [comment]
Thank your very much. Can I change the pug color palette? Because the new tags and attributes now have the same color?
![изображение](https://user-images.githubusercontent.com/16963833/103176986-390efb00-4887-11eb-8f32-61e83791f080.png)
For example, when i use pug mode:
![изображение](https://user-images.githubusercontent.com/16963833/103177005-4deb8e80-4887-11eb-8bb3-fff880faadf2.png)

**Comment by fxbois** [comment]
not really I would need to have the complete documentation of the syntax.
