### ISSUE TITLE
Having to reload web-mode often to "refresh" the syntax highlighting. Any workaround?

### ISSUE THREAD

**Issue by DougBeney** [fxbois/web-mode#1168]
Quite often I will do something in the code and the syntax highlighting will stop working. To fix it, I have to run `web-mode` again. This has bugged me quite a bit and I'm wondering if there's a good workaround.

![example](https://i.imgur.com/927BTkb.png)

In this case, I started typing my code without the `<?php` at the beginning. So, rightfully so the code did not highlight. Then, I added the `<?php` at the beginning and it did not automatically update. I had to re-run the `web-mode` function.

**Comment by fxbois** [comment]
I've pushed a fix for this special case
