### ISSUE TITLE
Svelte script indentation on empty object

### ISSUE THREAD

**Issue by cam-stitt** [fxbois/web-mode#1169]
I am getting a pretty unique issue regarding indentation within Svelte `<script>` blocks, specifically when I have an empty object nested inside a function or anything else. If the empty object is at the top level of the `<script>`, it indents fine.

![2020-12-17 08 57 54](https://user-images.githubusercontent.com/186643/102416809-41c12f00-4046-11eb-9abe-a28faa1b59b8.gif)

My current configuration is:

```
(web-mode-code-indent-offset 2)
(web-mode-markup-indent-offset 2)
(web-mode-css-indent-offset 2)
(web-mode-style-padding 2)
(web-mode-script-padding 2)
(web-mode-enable-css-colorization 0)
(web-mode-auto-quote-style 2)
```

However, I override `code-indent-offset` within `.dir-locals` to be 4.

Oddly, if I put a space inside of the empty braces, indentation on the following line works fine.

**Comment by fxbois** [comment]
@cam-stitt can you publish your example on gist please

**Comment by cam-stitt** [comment]
Apologies, I am on holidays at this point. Thanks for getting the issue sorted.
