### ISSUE TITLE
Add web-mode to Emacs/Elpa

### ISSUE THREAD

**Issue by Sasanidas** [fxbois/web-mode#1170]
Web-mode seems like a huge improvement compare to html-mode in term of functionality.
Would you be interested into adding this package to the Emacs or to ELPA repository?

**Comment by UwUnyaa** [comment]
What about the legal side of things? Wouldn't anyone involved in this project have to sign off on this?

**Comment by Sasanidas** [comment]
> What about the legal side of things? Wouldn't anyone involved in this project have to sign off on this?

Yes, all the people involve in the project that had contribute a substantial amount of code (I think is more than 15 lines) would need to sign paper for the FSF.

**Comment by fxbois** [comment]
@Sasanidas Hi, web-mode.el is already on MELPA and it seems to please a lot of people.
Moreover I've seen many times on emacs ml that core developers think that their approach (multi mode) is better than mine.

**Comment by Sasanidas** [comment]
> @Sasanidas Hi, web-mode.el is already on MELPA and it seems to please a lot of people.
> Moreover I've seen many times on Emacs ml that core developers think that their approach (multi mode) is better than mine.

I see, well I think the functionality of both modes (mhtml and web-mode) is a little bit overlapping in some areas, but I just love the way web-mode move around in the HTML buffer.

Would you mind if I took these movement capabilities and ported to the Emacs core html/mhtml mode? (assuming that the core developers agree with those additions)

In any case, thanks for this amazing package.

**Comment by fxbois** [comment]
@Sasanidas You can try but i don't think you'll be able navigate the buffer the same way with a multi mode

**Comment by Sasanidas** [comment]
> @Sasanidas You can try but i don't think you'll be able navigate the buffer the same way with a multi mode

You maybe are right, I will try it at least with the simple html/css files :+1: 
Thank you
