### ISSUE TITLE
Add support of line statement in django engine

### ISSUE THREAD

**Issue by drmgc** [fxbois/web-mode#1171]
First of all, thanks for this really useful mode :)

There is such a nice feature as [Line statements](https://jinja.palletsprojects.com/en/2.11.x/templates/#line-statements), that allows to write
``` jinja2
<ul>
# for item in seq
    <li>{{ item }}</li>
# endfor
</ul>
```
instead of
```jinja2
<ul>
{% for item in seq %}
    <li>{{ item }}</li>
{% endfor %}
</ul>
```

It would be really great, if it was supported by `web-mode`

**Comment by fxbois** [comment]
@drmgc I've committed a fix

**Comment by drmgc** [comment]
@fxbois Thanks a lot! :3

**Comment by drmgc** [comment]
Found a couple of issues:

- Line statements colored properly only in
```jinja2
#macro input(field)
	{{ field.label }}
	{{ field(**kwargs) }}
#if field.errors
		<ul class="errors">
#for e in field.errors
				<li>{{ e }}</li>
#endfor
		</ul>
#endif
#endmacro
```
Though, jinja2 accepts also
```jinja2
#macro input(field)
	{{ field.label }}
	{{ field(**kwargs) }}
	#if field.errors
		<ul class="errors">
			# for e in field.errors
				<li>{{ e }}</li>
			# endfor
		</ul>
	#endif
#endmacro
```
- Also, indentation of statement with `#` also does nothing. It sticks to beginning of the line

- Secondly, strings in expressions like `#import 'forms.j2' as f` are colored improperly
