### ISSUE TITLE
Phoenix Liveview ~L sigil with polymode

### ISSUE THREAD

**Issue by Folo23** [fxbois/web-mode#1172]
Hi @fxbois,

I've been really enjoying using `web-mode`, thank you for all of the work you've put into it!

I've been trying to use `web-mode` in conjunction with `polymode` to provide syntax highlighting in Phoenix Liveview `~L` sigils, as described [here](https://blog.evalcode.com/phoenix-liveview-inline-syntax-highlighting-for-emacs/). I've copied the source in shown that link into my `init.el` directly, and also have the `web-mode` package loaded.

I've noticed that `web-mode` won't be applied to the first sigil in a buffer when it is first opened. If I later alter some part of the first `~L` sigil, `web-mode`'s syntax highlighting will be correctly applied.

Here is a screenshot of how an Elixir module with 2 `~L` sigils looks when it is first loaded:

<img width="433" alt="Web-mode_sigil_syntax_highlighting" src="https://user-images.githubusercontent.com/19210175/104994829-38cfce80-59f3-11eb-9aa6-0a45ced01a81.png">

When I open that file after having run `web-mode-toggle-tracing`, I get the following output in the `Messages` buffer:

```
** tracing on ** point(145) web-mode-change-beg(nil) web-mode-change-end(nil) web-mode-skip-fontification(nil)
LSP :: Connected to [elixir-ls:62754 status:starting].
extend-region: font-lock-beg(54) font-lock-end(209) web-mode-change-beg(1) web-mode-change-end(280) web-mode-skip-fontification(nil)
scan: beg(1) end(280) web-mode-change-beg(1) web-mode-change-end(280)
(jit-lock--run-functions 54 209) [span 54 209  test.ex[web]] -> (font-lock-default-fontify-region 54 209): Args out of range: 1, 1
extend-region: font-lock-beg(227) font-lock-end(262) web-mode-change-beg(nil) web-mode-change-end(nil) web-mode-skip-fontification(nil)
extend-region: font-lock-beg(227) < web-mode-change-beg(nil)
extend-region: font-lock-end(262) > web-mode-change-end(nil)
scan: beg(227) end(262) web-mode-change-beg(227) web-mode-change-end(262)
invalidate-region: point(227) reg-beg(227) reg-end(262)
fontify: point(227) limit(262)
```

Please let me know if there's anything else I can do to help diagnose this, and thanks again for this very useful package.

**Comment by fxbois** [comment]
Hi,
web-mode is already a multi mode per se so using a multi mode inside an other multi mode will be a nightmare to debug. I can provide help but wont try to debug this.
