### ISSUE TITLE
web-mode-enable-auto-* features only enabled in graphic mode

### ISSUE THREAD

**Issue by lbolla** [fxbois/web-mode#1175]
Is there a technical reason why the various "auto-*" features, like `web-mode-enable-auto-closing` are only enabled on graphical emacs?
See the definition:
```
(defcustom web-mode-enable-auto-closing (display-graphic-p)
  "Auto-closing."
  :type 'boolean
  :group 'web-mode)
```
They seem to work fine even on non-graphical emacs, so I find it surprising.

**Comment by UwUnyaa** [comment]
IIRC, it's related to pasting into terminal, especially from the X clipboard, where Emacs can't tell the difference between pasting and manual typing, causing issues with automatic pairing.

**Comment by lbolla** [comment]
@UwUnyaa Thank you for the historical note. I would argue that typing is much more common way of writing html than pasting, so default settings that make it easier should be preferred.

**Comment by fxbois** [comment]
@UwUnyaa you're right ... it is related on pasting issues on terminal.
