### ISSUE TITLE
Web-mode doesn't support vue-i18n translations

### ISSUE THREAD

**Issue by phenix-factory** [fxbois/web-mode#1178]
*I first reported this to [Spacemacs](https://github.com/syl20bnr/spacemacs/issues/14352), but it seams that it should be a web-mode feature.*

If you work with vue.js and translations, you will probably end up using [vue-i18n](http://kazupon.github.io/vue-i18n/guide/sfc.html#basic-usage). It add support for in component translation using a i18n section (same level as the script and style section).
i18n section would contain a json translation looking like this:

```html
<i18n>
{
  "en": {
    "hello": "hello world!"
  },
  "ja": {
    "hello": "こんにちは、世界！"
  }
}
</i18n>
```

It also support YAML:

```html
<i18n>
en:
  hello: "hello world!"
ja:
  hello: "こんにちは、世界！"
</i18n>
```

Could be nice to support this !

Thank you for web-mode !

**Comment by phenix-factory** [comment]
@fxbois Hello there,

I don't understand, this is marked "completed" but I don't see a commit for this and my test was inconclusive.
If you don't want to support this feature, I get it, don't worry.

**Comment by fxbois** [comment]
@phenix-factory I've pushed a fix for the json version

**Comment by phenix-factory** [comment]
@fxbois Nice !
I just tested the last version and it works as expected, thank you very much !
