### ISSUE TITLE
ERB often loses highlight

### ISSUE THREAD

**Issue by otavioschwanck** [fxbois/web-mode#1182]
When using erb, its constantly loses highlight.  I have to use C-x C-v to fix temporarily. 

Demo:
![erb lose highlight](https://user-images.githubusercontent.com/9551316/109453368-a1698c80-7a30-11eb-8c46-10129071f717.gif)

its random, occurs when i do some action or something happens like revert chunk, edit something and the lint shows some message, etc.

**Comment by fxbois** [comment]
@otavioschwanck what are the versions of web-mode.el and of emacs ?
It would be useful to tell me if it triggers the last version of both

**Comment by otavioschwanck** [comment]
> @otavioschwanck what are the versions of web-mode.el and of emacs ?
> It would be useful to tell me if it triggers the last version of both

I'm using doom.

```
    Package: web-mode
     Source: Straight
     Pinned: 8ef47935d638902ba35a557cae5edd6ab6ab1346
      Build: grafted, HEAD -> master 8ef4793 2021-01-31 18:58:25 +0100
             Build location: ~/.emacs.d/.local/straight/build-27.2/web-mode/
             Repo location: ~/.emacs.d/.local/straight/repos/web-mode/
     Recipe: (:type git :flavor melpa :host github :repo "fxbois/web-mode" :package "web-mode" :local-repo "web-mode")
                Homepage: https://web-mode.org
    Modules: Declared by the following Doom modules:
             :lang web (no readme)
    Configs: This package is configured in the following locations:
             modules/lang/web/+html.el:3:(use-package! web-mode
             modules/lang/web/+html.el:157:(after! web-mode
``` 

Emacs version is 27.2.  Tested on 28 and 26, same problem

**Comment by eddieh** [comment]
This is happening to me as well.

Emacs: 
GNU Emacs 27.2 (build 1, x86_64-apple-darwin19.6.0, Carbon Version 162 AppKit 1894.6) of 2021-04-15
(this is the Yamamoto Mitsuharu's Mac port provided by https://github.com/railwaycat/homebrew-emacsmacport)

web-mode:
Version: 17.0.0
Package-Version: 17
Package-Commit: d115f8dc3052e5779938d782d9cdaa4533ef20ff

**Comment by fxbois** [comment]
@eddieh can you reproduce this and provide a video ?
