### ISSUE TITLE
Error occurred when `web-mode-extra-control-blocks` is set .

### ISSUE THREAD

**Issue by morishoji** [fxbois/web-mode#1183]
Error occurred when `web-mode-extra-control-blocks` customize value is set .

`web-mode-extra-control-blocks` defined as
```elisp
  :type '(alist :key-type string :value-type string)
```
but this value is used at below source code,

```elisp
  (append
   (cdr (assoc "blade" web-mode-extra-control-blocks))
   '("component" "foreach" "forelse" "for" "if" "section" "slot" "switch" "unless" "while")
   )
```
I think the value-type of `alist` needs `list` of `string`, not simple `string`. 

I edited my local `web-mode.el` like below for fix.

```elisp
  :type '(alist :key-type string :value-type (repeat string))
```

**Comment by fxbois** [comment]
thank you
