### ISSUE TITLE
Styled components are not syntax highlighted

### ISSUE THREAD

**Issue by stevemolitor** [fxbois/web-mode#1185]
There is no CSS syntax highlighting of style components inside a .tsx file (using `web-mode`):

![](https://cdn.zappy.app/fe07a419d688e12613952702cab63505.png)

In a .css file with `web-mode` I get more syntax highlighting:

![](https://cdn.zappy.app/b5ba845fa0b23f9866cc4a930da54556.png)

Re #824, it was closed but I don't think it ever added support for syntax highlighting.

@fxbois Happy to take a stab at this if you can point me in the right direction.

**Comment by danieljamesross** [comment]
I would love this feature too.

**Comment by ikapo** [comment]
Any update on this?
