### ISSUE TITLE
Loosing highlight / context often in plain html

### ISSUE THREAD

**Issue by yurkobb** [fxbois/web-mode#1186]
Created a quick test case ([video](https://user-images.githubusercontent.com/479389/114303273-f4c20680-9ad5-11eb-95d0-0dbeacf023f9.mp4), [gist](https://gist.github.com/yurkobb/c30dd352d00c4e63ba0850759ac51c0b)) with plain html. In this case I pasted a block of plain text; but I think it happens in other cases too - hard to tell in fact, but several times a day at least.

One thing I notice often is that when the highlight is confused, then I hit `</` the auto-guessed closing tag is one level higher that it should be. (In my case it guessed `body` when it should have been `h1`).

https://user-images.githubusercontent.com/479389/114303273-f4c20680-9ad5-11eb-95d0-0dbeacf023f9.mp4

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(27.1) web-mode("17.0.0")
vars: engine("none") minor("none") content-type("html") file("/home/public_html/anabasis/index.html")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (global-eldoc-mode winner-mode show-paren-mode ivy-mode yas-minor-mode yas-global-mode shell-dirtrack-mode pyvenv-mode async-bytecomp-package-mode global-git-commit-mode auto-revert-mode magit-auto-revert-mode magit-file-mode global-magit-file-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
can not reproduce the issue
please try with last version
