### ISSUE TITLE
Support for <page-query> GraphQL tag in Vue files

### ISSUE THREAD

**Issue by cimocimocimo** [fxbois/web-mode#1189]
I saw that GraphQL indentation is supported in JSX files https://github.com/fxbois/web-mode/issues/866

Wondering if this is possible for Vue files with GraphQL queries as well? This is an example from the Gridsome docs:
```
<template>
  <div>
    <div v-for="edge in $page.posts.edges" :key="edge.node.id">
      <h2>{{ edge.node.title }}</h2>
    </div>
  </div>
</template>

<page-query>
query {
  posts: allWordPressPost {
    edges {
      node {
        id
        title
      }
    }
  }
}
</page-query>
```

Apologies in advance if this is possible through configuration alone.

Thank you!

**Comment by fxbois** [comment]
@cimocimocimo can you provide a link about the specs ?

**Comment by cimocimocimo** [comment]
Sorry, I thought I had included the link to the docs: [How to query with GraphQL](https://gridsome.org/docs/querying-data/#how-to-query-with-graphql)

Essentially, I'm looking for the Graph QL query in the <page-query> tags to be properly indented. When using web-mode currently all the text between the <page-query> tags is not indented at all but flush to the left side.

Please let me know if you need any more info.

**Comment by sunilw** [comment]
Jumping in to say that this would be useful for frameworks other than vue.

At the moment I'm using composing graphql in files that are both in modern js and jsx.
Having decent indentation for graphql in web-mode would be fantastic.

This is an example of the syntax I'm working with:

```
exports.createPages = async ({ actions, graphql, reporter }) => {
  const result = await graphql(`
    {
      allWpPost {
        nodes {
          id
          uri
        }
      }
    }
  `)
}

```
