### ISSUE TITLE
Wrong syntax highlight in CSS

### ISSUE THREAD

**Issue by PoSayDone** [fxbois/web-mode#1190]
Why is syntax highlight in emacs is so different to other text editors, such as im or vscode?
I use One Dark theme.

Emacs
![screenshot_20210515_185745](https://user-images.githubusercontent.com/29358657/118354809-61716a80-b586-11eb-9bd8-f6a1ebac79b2.png)
Vim
![screenshot_20210515_185654](https://user-images.githubusercontent.com/29358657/118354818-66361e80-b586-11eb-90fe-e041517e6713.png)
Vscode
![screenshot_20210515_190418](https://user-images.githubusercontent.com/29358657/118354844-78b05800-b586-11eb-8a4a-bea2c8657a2c.png)

**Comment by fxbois** [comment]
you can customise it

**Comment by PoSayDone** [comment]
> you can customise it

Sorry for a stupid question, but can you give link to the docs or smth to learn how to do this

**Comment by fxbois** [comment]
you can start on web-mode.org and look at the various faces
