### ISSUE TITLE
jsdoc fill-paragraph support

### ISSUE THREAD

**Issue by glyph** [fxbois/web-mode#1205]
To follow up from #945, `M-q` in a jsdoc comment (particularly one with a left-fringe of asterisks) really messes it up right now.

**Comment by soywod** [comment]
+1 here. I noticed that `typescript-mode` and `js-jsx-mode` do it correctly, so the logic already exists, it just needs to be added to `web-mode`. If I have some time I will try to dig and propose a PR.
