### ISSUE TITLE
html indenation between javascript backticks not working

### ISSUE THREAD

**Issue by MPE2016** [fxbois/web-mode#1213]
L.S.,

As far as I understand it, html should still be properly indented when working between javascript backticks, but this is not happening with me, and I have no idea where to look. I am on version 17 of web-mode. Any ideas?

All the best,

MPE

**Comment by MPE2016** [comment]
Ah, of course I found the answer after I posted this:). Nothing wrong with web-mode, I just wasn't paying attention.

**Comment by iambumblehead** [comment]
@MPE2016 I am having this same issue. Do you remember the solution by any chance?
