### ISSUE TITLE
Improvements for Elixir .heex

### ISSUE THREAD

**Issue by aparkerdavid** [fxbois/web-mode#1215]
In a heex template, web-mode should be able to recognize tags with leading periods, e.g. `<.some_component>` , `</.some_component>`, `<.some_component />`.

Inside of tags, curly braces should be handled as EEX code delimiters. e.g. `<div class={some_function(@something)}>`

**Comment by Cgboal** [comment]
I would also like this feature, it makes working with heex filex very difficult without it, especially in cases where components are heavily used such as here: 

<img width="653" alt="image" src="https://user-images.githubusercontent.com/4704380/147795565-c454918d-672e-49f0-bd01-2f1448d5c078.png">

Syntax highlighting doesn't work, nor does formatting. 

I don't know elisp (I know other lisps though), but I would be happy to take a look at implementing what's required to make this work if you can point me in the right direction.

**Comment by vfsoraki** [comment]
I also want this.

For the time being, is there anyway to make it consider `.` and `:` legit characters for tag names?

**Comment by knoebber** [comment]
I'd also appreciate this feature :+1: Also, thank you web-mode maintainers for work thus far!

**Comment by fxbois** [comment]
@Cgboal could you provide your example on gist please

**Comment by knoebber** [comment]
@fxbois https://gist.github.com/knoebber/0834d29b8a5f0710de239041e6a7627b

**Comment by jsmestad** [comment]
While this is being worked on, [here is an option](https://blog.evalcode.com/elixir-heex-highlighting-in-emacs/) to create a derived mode for `.heex` files that uses tree-sitter.

**Comment by NatTuck** [comment]
This doesn't seem to be working for me even with the latest commit.
