### ISSUE TITLE
web-mode-fontify-tags: Wrong type argument: number-or-marker-p, nil

### ISSUE THREAD

**Issue by ibytao** [fxbois/web-mode#1219]
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  web-mode-fontify-tag()
  web-mode-fontify-tags(17654 17908 3)
  web-mode-fontify-part(1 19786)
  web-mode-fontify(19786)
  font-lock-fontify-keywords-region(1 19786 nil)
  font-lock-default-fontify-region(1 19786 nil)
  font-lock-fontify-region(1 19786)
  #f(compiled-function (beg end) #<bytecode -0x194faac3fe2270c7>)(1 19786)
  font-lock-ensure()
  web-mode-buffer-fontify()
  web-mode-set-content-type("jsx")
  (if (equal web-mode-content-type "javascript") (web-mode-set-content-type "jsx") (message "now set to: %s" web-mode-content-type))
  (lambda nil (if (equal web-mode-content-type "javascript") (web-mode-set-content-type "jsx") (message "now set to: %s" web-mode-content-type)) (if (string-equal "tsx" (file-name-extension buffer-file-name)) (progn (lsp))) (if (string-equal "js" (file-name-extension buffer-file-name)) (progn (setup-tide-mode))))()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook web-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook web-mode-hook))
  run-mode-hooks(web-mode-hook)
  web-mode()
  set-auto-mode-0(web-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer index.js> "~/Workspace/decision-engine/pages/decision/set/rul..." nil nil "~/Workspace/decision-engine/pages/decision/set/rul..." (287530128 16777223))
  find-file-noselect("/Users/nemo/Workspace/decision-engine/pages/decisi..." nil nil nil)
  find-file("/Users/nemo/Workspace/decision-engine/pages/decisi...")
  #f(compiled-function (f) #<bytecode 0x46fd1861d9db028>)("/Users/nemo/Workspace/decision-engine/pages/decisi...")
  ivy-call()
  ivy-read("Recentf: " ("/Users/nemo/Workspace/decision-engine/pages/decisi..." "/Users/nemo/.emacs.d/config.org" "/Users/nemo/.emacs.d/elpa/web-mode-20210902.1615/w..." "/Users/nemo/Workspace/decision-engine/pages/decisi..." "/Users/nemo/Workspace/decision-engine/pages/decisi..." "/Users/nemo/Workspace/decision-engine/pages/decisi..." "/Users/nemo/Workspace/decision-engine/components/c..." "/Users/nemo/Workspace/decision-engine/pages/_app.j..." "/Users/nemo/Workspace/decision-engine/pages/login/..." "/Users/nemo/Projects/next-chakra/pages/login/index..." "/Users/nemo/Projects/next-chakra/node_modules/@typ..." "/Users/nemo/Projects/next-chakra/package.json" "/Users/nemo/Workspace/cloud-pro/node_modules/axios..." "/Users/nemo/Workspace/cloud-pro/utils/fetch.js" "/Users/nemo/Projects/next-chakra/tsconfig.json" "/Users/nemo/Workspace/cloud-pro/utils/config.js" "/Users/nemo/Workspace/cloud-pro/pages/collection/r..." "/Users/nemo/Workspace/decision-engine/utils/fetch...." "/Users/nemo/Workspace/decision-engine/node_modules..." "/Users/nemo/Workspace/decision-engine/pages/decisi..." "/Users/nemo/Workspace/cloud-pro/pages/_app.js" "/Users/nemo/go/src/base/main.go" "/Users/nemo/Workspace/kscb-wx/pages/apply/index/in..." "/Users/nemo/Workspace/kscb-wx/app.js" "/Users/nemo/Projects/next-chakra/next-env.d.ts" "/Users/nemo/Projects/next-chakra/pages/_app.tsx" "/Users/nemo/Projects/next-chakra/.prettierrc" "/Users/nemo/Workspace/decision-engine/themes/index..." "/Users/nemo/Workspace/decision-engine/package.json" "/Users/nemo/Workspace/decision-engine/node_modules..." "/Users/nemo/Projects/next-chakra/pages/index.tsx" "/Users/nemo/Workspace/cloud-pro/next.config.js" "/Users/nemo/Workspace/cloud-pro/components/NextNPr..." "/Users/nemo/Workspace/cloud-pro/package.json" "/Users/nemo/Workspace/cloud-pro/server.js" "/Users/nemo/Workspace/kscb-h5/pages/_app.js" "/Users/nemo/Projects/spring-boot/demo/pom.xml" "/Users/nemo/Projects/spring-boot/demo/src/main/jav..." "/Users/nemo/Workspace/cloud-pro/lib/menu.js" "/Users/nemo/Workspace/decision-engine/Dockerfile" "/Users/nemo/Projects/spring-boot/demo/src/test/jav..." "/Users/nemo/Projects/first_flutter_app/lib/main.da..." "/Users/nemo/Projects/spring-boot/demo/src/main/jav..." "/Users/nemo/Workspace/decision-engine/pages/decisi..." "/Users/nemo/Workspace/decision-engine/pages/decisi..." "/Users/nemo/Workspace/decision-engine/pages/decisi..." "/Users/nemo/Workspace/decision-engine/pages/system..." "/Users/nemo/Workspace/decision-engine/pages/decisi..." "/Users/nemo/Workspace/kscb-wx/components/ticket-ce..." "/Users/nemo/Workspace/kscb-wx/components/ticket-ce..." ...) :action #f(compiled-function (f) #<bytecode 0x46fd1861d9db028>) :require-match t :caller counsel-recentf)
  counsel-recentf()
  funcall-interactively(counsel-recentf)
  call-interactively(counsel-recentf nil nil)
  command-execute(counsel-recentf)

**Comment by UwUnyaa** [comment]
Can you provide more details and try with a minimal init file? It seems you're using macOS, and loading some config from an org file based on information provided. Mentioning the emacs version in use would also be nice.
