### ISSUE TITLE
TSX Comment formats issue

### ISSUE THREAD

**Issue by ZelCloud** [fxbois/web-mode#1225]
I'm trying to set it so web-mode uses single line comments for regions of JavaScript and TypeScript code inside a tsx or jsx file, while still using the correct comment syntax for the jsx/tsx html portion.

I've tried setting the web-mode-comment-formats variable, but I'm not getting the desired behavior.

If I set web-mode-comment-formats for JavaScript and typescript like so

```elisp
(setq-default web-mode-comment-formats
	'(
	  ("javascript" . "//")
	  ("typescript" . "//")
	 )
	)
```

Inside my tsx file, I get this behavior:

```tsx
function Sample() {

	/* function Test() {
	 * console.log("Ipsum");
	 * } */ - Wrong syntax should be //

	return (
	<div>
		{/* <p>ipsum</p> */} - Correct comment sytnax here
	</div>
	)
}
```

If I set the jsx tsx comment in web-mode-comments-formats like so

```elisp
(setq-default web-mode-comment-formats
	'(
	  ("javascript" . "//")
	  ("typescript" . "//")
	  ("jsx" . "//")
	  ("tsx" . "//")
	 )
	)
```

I get this behaviour

```tsx
function Sample() {

	// function Test() {
	//  console.log("Ipsum");
	// }  - Correct syntax

	return (
	<div>
		// <p>ipsum</p> - completely wrong syntax doesn't work for jsx / tsx
	</div>
	)
}
```

What I want ideally is

```tsx
function Sample() {

	// function Test() {
	//  console.log("Ipsum");
	// }  - Correct single line syntax

	return (
	<div>
		{/* <p>ipsum</p> */} - Correct comment sytnax here
	</div>
	)
}
```

I'm not sure if this is a bug, or if there's something I'm missing with web-mode-comment-formats. Any help would be appreciated.

**Comment by UwUnyaa** [comment]
`//` comments inside of JSX aren't just "wrong", they won't work as comments at all.

**Comment by ZelCloud** [comment]
> `//` comments inside of JSX aren't just "wrong", they won't work as comments at all.

Yes, you're right. That was poor wording on my part the ```//``` comment sytnax doesn't work at all for jsx / tsx.

**Comment by zhaozhemin** [comment]
I've noticed another issue. Commenting out an argument should look like

    <Foo
      // bar={baz}
    />

instead of

    <Foo
      {/* bar={baz} */}
    />

**Comment by P233** [comment]
I also get incorrect indentation of multiple line comments, for example:

```typescript
function() {
  let a = 1;
  let b = 2;
  let c = 3;
}
```

when I seleceted the three variables declaration lines and then press <kbd>M-;</kbd>, I got:

```typescript
function() {
  // let a = 1;
// let b = 2;
// let c = 3;
}
```
