### ISSUE TITLE
indentation of nunjucks `{% set varname %}` **blocks** (i.e., not `{% set varname = value %}`)

### ISSUE THREAD

**Issue by dse** [fxbois/web-mode#1226]
In nunjucks templates where `web-mode-engine` is `django`, `{% set %}` blocks are not indented correctly.<br>
Note that I am specifically referring to when `{% set %}` is supplied only with a variable name, not with the equal sign nor a value.<br>
`{% set var = val %}` does not start a block and indentation of subsequent code is correct in that case.

Before (all lines have indentation):
```
    {% set foo %}
    bar
    {% endset %}
```

Expected results after indentation:
```
{% set foo %}
    bar
{% endset %}
```

Actual results:
```
{% set foo %}
bar
    {% endset %}
```

Perhaps another minor template engine (like jinja) needs to be created?

**Comment by fxbois** [comment]
done with last commit
