### ISSUE TITLE
Issue with unquoted HTML attribute values defined in another language

### ISSUE THREAD

**Issue by lcoq** [fxbois/web-mode#1229]
### Theory

HTML unquoted attribute values defined in a non-HTML language are not considered as valid attribute values.
Therefore the HTML parser expects next string to define the attribute value.

### Consequences

It produces both syntax **highlighting** issue and **indentation** issue, at least with ERB and HBS templates, but I'm pretty sure this appears **with every language** combined with HTML.

### Example

![web-mode-erb-invalid](https://user-images.githubusercontent.com/463884/155122112-2b2c47b3-9251-4e87-8462-fc150cb2dff1.png)

![web-mode-hbs-invalid](https://user-images.githubusercontent.com/463884/155122117-a0a41dcb-8fa0-42fc-9eac-177ea32b6a54.png)

In the examples above, `bar="baz"` has 2 problems : 

1. Highlighting issue : the face used is `face(web-mode-html-attr-value-face)`
2. Indentation issue : it should start at the same indentation as `foo`

### Related specs : 

- [HTML Unquoted attribute-value syntax](https://www.w3.org/TR/2012/WD-html-markup-20120329/syntax.html#attr-value-unquoted)

### Related issues :

- #1150 
- #1136

**Comment by fxbois** [comment]
please post the examples on gist

**Comment by lcoq** [comment]
ERB : https://gist.github.com/lcoq/57e3dafe3519a1ee145fabdf57ecf90f
HBS : https://gist.github.com/lcoq/647b0f89219404518425d0bb3e2cb4c9

**Comment by fxbois** [comment]
I've pushed a fix
