### ISSUE TITLE
Support Nimja template engine

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [fxbois/web-mode#1234]
Hi,

I'm using the [Nimja](https://github.com/enthus1ast/nimja) Nim template engine with the `jinja2` `web-mode-engine` configured for the `.nwt` (Nim web template) file extension as follows

```elisp
(add-to-list 'auto-mode-alist '("\\.nwt\\'" . web-mode))
(setq web-mode-engines-alist '(("jinja2" . "\\.nwt\\'")))
```
This setup works quite fine. Thank you!

Could you consider adding the `nimja` `web-mode-engine` for the `.nwt` file extension?

Below follows the list of issues when using `jinja2` with Nimja
- Add support for keywords `while`, `importnwt`, `proc`, `func`, `end`
- Support highlighting of all keywords in the whitespace control brackets
    - Works correctly `{% if ... %}` the `if` keyword is highlighted correctly and identation works
    - Should be fixed `{%- if ... %}` the `if` keyword is not highlighted and identation does not work

Thank you very much,
Vlad

**Comment by fxbois** [comment]
please post on gist a full example that would use all syntax elements of this template engine please
