### ISSUE TITLE
ERB - syntax highlighting issue with css colorization

### ISSUE THREAD

**Issue by abdelbk** [fxbois/web-mode#1235]
I'm new to `web-mode` and having some syntax highlighting issues with `.erb` files. The whole line gets colored in green in my case :

<img width="360" alt="Capture d’écran 2022-03-26 à 13 24 08" src="https://user-images.githubusercontent.com/2431171/160239397-7d2be8f1-8b09-4f9d-a9c5-e8f161703ca1.png">

My configuration is the following :
```elisp
(use-package web-mode
  :ensure t
  :config
    (add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode)))
```

**Comment by fxbois** [comment]
please post the full example on gist

**Comment by abdelbk** [comment]
The view is pretty complex and I can't post the full code here.
I'm closing this issue until I'm able to reproduce it with some sample code.
