### ISSUE TITLE
Add support for Anki templating

### ISSUE THREAD

**Issue by TheBlackBeans** [fxbois/web-mode#1246]
Hello,
after passing some time on an Anki forum, I realized lots of people edited Anki templates in external editors (including Emacs, which already has an anki minor mode that makes the bridging), so I though it made sense requesting for it to be supported in `web-mode`. For information, Anki is a memorizing application, which relies on webviews, and so it has a templating mechanism on top of regular HTML / CSS / JS. The [documentation](https://docs.ankiweb.net/#/) about the [templating specs](https://docs.ankiweb.net/templates/fields.html) can be found on the [website](https://apps.ankiweb.net/).

**Comment by fxbois** [comment]
Could you post an example on gist that contains many of the features of the template language please

**Comment by fxbois** [comment]
@TheBlackBeans what is the file extension for those templates ?

**Comment by fxbois** [comment]
I've pushed a commit to support .anki templates

**Comment by fxbois** [comment]
yes of course, it is important to make this known by the AnkiWeb community

**Comment by cicerojones** [comment]
I hope no one minds my linking in this thread to that very post, for those who are interested:

[https://forums.ankiweb.net/t/anki-templates-support-for-emacs-web-mode/20793](https://forums.ankiweb.net/t/anki-templates-support-for-emacs-web-mode/20793)



> Fantastic! I'll test it myself, of course, but I'll also make a post on the forum (forums.ankiweb.net if you're interested) so those interested will be able to provide feedback.
