### ISSUE TITLE
A method to extend web-mode-html-entities

### ISSUE THREAD

**Issue by kationscramblowitch** [fxbois/web-mode#1254]
Hello. So, I've recently started implementing a function to decode html-encoded strings. I didn't go too far into it, as I've found a better alternative for my task, but in the process I've been disappointed with how little entities there are in web-mode-html-entities. I've fetched my own collection via this.
```
(defvar html-entities-data
      (request "https://html.spec.whatwg.org/entities.json"
	:type "GET"
	:parser
	(lambda ()
	  (let ((json-object-type 'hash-table))
	    (json-read)))
  :success
  (cl-function
   (lambda (&key data &allow-other-keys)
     (set 'html-entities-data data)))))
```
I know I'm not doing a very good job here, as the request should be in a update-html-entities function, but regardless I've thought that perhaps you'll not mind expanding the list of entities? It's your choice.

**Comment by fxbois** [comment]
your method is perfect for anyone needing a full coverage.
I might accept new entities case by case but will never put all the entities in the source code.
Thank you for your contribution
