### ISSUE TITLE
Typescript indentation fails after a comment ending with a dot

### ISSUE THREAD

**Issue by UndeadKernel** [fxbois/web-mode#1256]
In typescript, a code line that follows a comment that ends with a dot fails to indent correctly.
Take this as an example:
```js
// This is a comment with a dot at the end.
  let var = "wrong indentation";

// This is a comment without a dot at the end
let var = "correct indentation";
```

**Comment by fxbois** [comment]
should be fixed with last commit

**Comment by UndeadKernel** [comment]
Thank you @fxbois. Your work is very much appreciated!
