### ISSUE TITLE
The highlighting style of previous close tag doesn't disappear.

### ISSUE THREAD

**Issue by alanaudi** [fxbois/web-mode#1257]
## Version
`efa853e`

## Description
The highlighting style of previous close tag won't disappear if moving to self closed tag next.

## Screenshot
<img width="594" alt="image" src="https://user-images.githubusercontent.com/12343599/200095804-39963498-1dc0-459f-b16f-789ccc963265.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/12343599/200095816-fa766117-9329-4123-ab9b-8f13a02c0997.png">
<img width="987" alt="image" src="https://user-images.githubusercontent.com/12343599/200106412-35c06362-473d-4be9-99a2-9a4b01ca109a.png">

**Comment by fxbois** [comment]
what is your config for this ?

**Comment by fxbois** [comment]
solved with last commit

**Comment by alanaudi** [comment]
@fxbois sorry for late reply, I use the default [web module of doomemacs](https://github.com/doomemacs/doomemacs/blob/d5ccac5d71c819035fa251f01d023b3f94b4fba4/modules/lang/web/packages.el#L9).
I'm not really sure about how this framework did it.
Thanks for your reply and solving this issue !
