### ISSUE TITLE
Matching Curly braces inside function in JavaScript template literals

### ISSUE THREAD

**Issue by jcubic** [fxbois/web-mode#1258]
I have this case:

I work with styled-components in ReactJS and I have this code:

```javascript
const Components = styled.li`

  ${(props) => props.hoverEffect && `
    &:hover {
      background: #f4f4f4;
      color: #333333;
      &:after {
        background: #f4f4f4 !important;
      }
    }`
  }
`;
```

This works fine, but when I use destructure of props in a function:
```javascript
const Components = styled.li`

  ${({hoverEffect}) => hoverEffect && `
    &:hover {
      background: #f4f4f4;
      color: #333333;
      &:after {
        background: #f4f4f4 !important;
      }
    }`
  }
`;
```

The coloring is broken because closing brace after `hoverEffect` is closing embedded value in the template literal. It needs to handle matching parenthesis inside JavaScript code inside the escape value of template literals.

**EDIT:** it seems that both examples are broken but in a different ways. Backtick inside `${ }` closes backtick from the beginning.

**Comment by fxbois** [comment]
sorry but too difficult to deal with

**Comment by tobiasBora** [comment]
Too bad template literals have no good support in emacs… I have a similar issue with nested template literals that emacs struggle to indent:
```

      const ListShuffler = () => {
        const [data, setData] = useState([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
        const shuffleList = () => setData(shuffle(data));
        useEffect(() => shuffleList(), []);
        return (
          html`<${Flipper} flipKey=${data.join('')} spring=${{ stiffness: 30, damping: 12 }}>
            <ul className="list">
              ${data.map(d => (
                html`<${Flipped} key=${d} flipId=${d}>
                  <li>${d}</li>
              <//>`
      ))}
      </ul>
      <//>`
      )
      }
```

**Comment by jcubic** [comment]
Template literals are just strings, this is not a real code that can be indented. My case is about syntax highlighting, which is totally different issue.
