### ISSUE TITLE
Feature request, Antlers template support

### ISSUE THREAD

**Issue by 8cylinder** [fxbois/web-mode#1262]
Hi, I would like to request Antlers support in web-mode.  This is the templating language for the [Statamic](https://statamic.com/) cms.  The following has been taken from [Statamic's antlers documentation](https://statamic.dev/new-antlers-parser).

If you need any more info, I'll be glad to trackdown what ever you need.

## Delimiters

- `{{ }}` The basic and primary delimiter pair, used to render variables, evaluate expressions, call Tags, and do almost all core Antlers things.
- `{{? ?}}` and `{{$ $}}` Allow you to write, execute, and echo PHP.  I guess ideally these would use php syntax highlighting, but its not important.
- `{{# #}}` Are for code comments.

## Tags

These are all acceptably formatted tags.

- `{{ perfectenschlag }}`
- `{{squished}}`
- `{{ some_variabler | upper }}`
- `{{ nav :from="segment_1" }}`
- `{{ collection:blog limit="{entry_limit ?? 10}" }}`
- ```
  {{
    testimonials
    limit="5"
    order="username"
  }}
  ```
- `{{playSad_Tromb0ne            }}`

Variable must start with an alpha character or underscore (`a-zA-Z_`), followed by any number of additional uppercase or lowercase alphanumeric characters, hyphens, or underscores (`a-zA-Z_0-9`). Spaces or other special characters are not allowed.

## Indenting

If:

``` antlers
{{ if meta_title }}
  {{ meta_title }}
{{ elseif title }}
  {{ title }}
{{ else }}
  {{ site:name }}
{{ /if }}

{{ if neighbor == "Kramer" }}
  <p>These pretzels are making me thirsty!</p>
{{ elseif neighbor == "Newman" }}
  <div>
    <p>Hello...Newman.</p>
  </div>
{{ else }}
  <!-- Who are you? -->
{{ /if }}

```

Unless:

``` antlers
{{ unless logged_in }}
  You see a large wardrobe in front of you.
{{ /unless }}
```

Switch:

``` antlers
{{ size = 'lg' }}

<div style="{{ switch
  (
    (size == 'sm') => '(min-width: 768px) 35vw, 90vw',
    (size == 'md') => '(min-width: 768px) 55vw, 90vw',
    (size == 'lg') => '(min-width: 768px) 75vw, 90vw',
    (size == 'xl') => '90vw',
    () => '100vw'
  )
}}">

Results in: <div style="(min-width: 768px) 75vw, 90vw">
```

### More complicated

Unfortunately any tag can have a closing tag.  It's probably not realistic to try and find a closing tag for all the variables since there is know way to tell if it is iterable or not, but, if you do have a way to do that, that would be awesome.

``` antlers
{{some_things}}
  <li>"value" is a built in variable in antlers: {{value}}</li>
{{/some_things}}
```

**Comment by fxbois** [comment]
The last commit brings some compatibility

**Comment by 8cylinder** [comment]
Thanks, that works great!  
Web-mode is hands down my favorite emacs mode and makes my life better.
