### ISSUE TITLE
code reformatting?

### ISSUE THREAD

**Issue by xeruf** [fxbois/web-mode#1264]
Thank you for this great mode!

Is there a way to reformat code/buffers?

**Comment by fxbois** [comment]
You can use ```web-mode-reload```

**Comment by xeruf** [comment]
I was referring to code reformatting, such as adding missing spaces and indentation, this does not seem to anything.

**Comment by fxbois** [comment]
```CTRL-x h``` and ```TAB```

**Comment by xeruf** [comment]
Thank you :)
