### ISSUE TITLE
lsp-tailwindcss features not working

### ISSUE THREAD

**Issue by djs42012** [fxbois/web-mode#1267]
Hello,

I am successfully connecting to the tailwindcss lsp server in `web-mode`, however completions and hover information are not working.
Everything works as intended if I use `html-mode` or `rjsx-mode`. 

Attached is a what I see for `lsp-describe-session` in `web-mode` as well as the functionality I am missing, shown in `rjsx-mode`.

![2023-01-30-204345_540x257_scrot](https://user-images.githubusercontent.com/93899859/215638518-79b5276b-f960-4656-b1cc-cc1c9d35e4c9.png)
![2023-01-30-204432_713x129_scrot](https://user-images.githubusercontent.com/93899859/215638522-79190747-5a96-4c3d-9d34-f239439a8807.png)

**Comment by fxbois** [comment]
Sorry but I do not use tailwindcss ... Do not hesitate to investigate and contribute on this subject
