### ISSUE TITLE
PHP array indentation still an issue

### ISSUE THREAD

**Issue by ahihi** [fxbois/web-mode#1268]
the issue described in https://github.com/fxbois/web-mode/issues/1249, https://github.com/fxbois/web-mode/issues/1212 is still happening with web-mode 17.3.8, producing results like

```php
$x = [
    'a' => 0,
        'b' => 1,
        'c' => 2
];

$y = array(
    'a' => 0,
        'b' => 1,
        'c' => 2
);

function_call(
    $arg0,
        $arg1,
        $arg2
);
```

in particular, it occurs with the `lineup-args` indentation param being set to `nil`.

it seems the first element/argument after the opening bracket is indented as `bracket-indentation`, while the following ones are `block-args`, which causes the indentation level to increase when `lineup-args` is disabled.

**Comment by fxbois** [comment]
should be fixed with last commit

**Comment by ahihi** [comment]
it is indeed, thank you!
