### ISSUE TITLE
Elixir LiveView <.tag> syntax

### ISSUE THREAD

**Issue by marcinkoziej** [fxbois/web-mode#1269]
Hi!

Struggling for second hour to make `<.tagsstartingwithadot>` be recognized as tags, and closed properly. 
Could you please point me to the right way to do this? 
Tried modyfing `web-mode-(start-)tag-regexp` as well as `web-mode-engine-*` for elixir language, but without results.

**Comment by andyleclair** [comment]
I am also having this issue. I see [this issue](https://github.com/fxbois/web-mode/issues/1215) was closed back in Dec. '22, but what I'm seeing looks like this

![image](https://user-images.githubusercontent.com/109716/220232049-e9e4481d-a19b-4ad4-b2fb-b753b08c9be7.png)

I can see that the `<.` part is highlighted but the formatting looks wrong.

For example, this is what that file looks like in VS code

![image](https://user-images.githubusercontent.com/109716/220232275-cc9ab3a8-b600-46bf-b5b3-bf0223100ba8.png)

**Comment by fxbois** [comment]
@andyleclair  could you a post a link where this synthax is explained please

**Comment by andyleclair** [comment]
https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#sigil_H/2

**Comment by andyleclair** [comment]
The general docs for `Phoenix.Component` may be helpful to you https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#content

**Comment by fxbois** [comment]
I may reverse if it triggers bugs
