### ISSUE TITLE
Interpolation is causing tags to not match in svelte engine.

### ISSUE THREAD

**Issue by knarkzel** [fxbois/web-mode#1273]
Also happens with inline functions.

![2023-03-29-225951_1802x533_scrot](https://user-images.githubusercontent.com/85593302/228666648-a7a1c994-38a8-4579-ab80-4315c49dbb73.png)

Configuration:

```elisp
(use-package web-mode
  :mode (("\\.svelte\\'" . web-mode))
  :hook ((web-mode . emmet-mode)
         (web-mode . lsp-deferred))
  :custom
  (web-mode-part-padding 0)
  (web-mode-markup-indent-offset 2)
  :straight t)
```

**Comment by fxbois** [comment]
could you update with last version and explain more precisely the issue
