### ISSUE TITLE
Automatic insersion of quotes in attribute in JSX

### ISSUE THREAD

**Issue by jcubic** [fxbois/web-mode#1277]
I write a lot of JSX (React) and I often write code like this:

```jsx
<Item something={something}>

</Item>
```

And it's really annoying that Web-mode inserts `=""` when you press `=`, I need to delete what web-mode is inserting almost every time, since props are more common than normal attributes. Is there a way to turn it off? In JSX you sometimes use `""` and sometimes `{}`.

**Comment by yugaego** [comment]
Disable `web-mode-enable-auto-quoting`. F.i.

```
(setq web-mode-enable-auto-quoting nil)
```

or in `*Customize*` UI reaching it with `M-x customize-group` <kbd>RET</kbd> `web-mode`. There, you can find a list of all custom options provided by the mode.

Note that the question better matches [Discussions](https://github.com/fxbois/web-mode/discussions), imo.

**Comment by jcubic** [comment]
Thanks, I wanted to ask on the Discussions but they are empty.
