### ISSUE TITLE
Error in post-command-hook (web-mode-on-post-command): (void-function count-invisible-character-ranges)

### ISSUE THREAD

**Issue by Ziqi-Yang** [fxbois/web-mode#1282]
When I enter web-mode, I can see this error message in the minibuffer:
```
Error in post-command-hook (web-mode-on-post-command): (void-function count-invisible-character-ranges)
```
I believe the error comes from the call of `count-invisible-character-ranges` in this line:  
https://github.com/fxbois/web-mode/blob/44c6bfa3626f476750ed3c1c0d253607c1606716/web-mode.el#L7994

By searching the whole project, I cannot find the definition of this function.

This error leads to features like `auto-closing` and `auto-opening` not work. 

BTW, much appreciate for your hard working and continuous contribution on this awesome project! <3

**Comment by varna9000** [comment]
+1

**Comment by fxbois** [comment]
I've pushed a fix
