### ISSUE TITLE
A problem with electric-pair-mode

### ISSUE THREAD

**Issue by kjnez** [fxbois/web-mode#1284]
When using the Django engine in web-mode and electric-pair-mode, there's an extra `}`. For example, initially the cursor is just after %:
```html
{%I}
```
And when hitting the Space key, it becomes
```html
{% I %}}
```

**Comment by fxbois** [comment]
It is related to an other minor mode I think

**Comment by kjnez** [comment]
Made an edit, before hitting Space, it should be `{%I}`.

**Comment by kjnez** [comment]
This can be partially solved with `(add-hook 'web-mode-hook (lambda () (electric-pair-local-mode -1)))`, which disables electric-pair-local-mode in web-mode.
