### ISSUE TITLE
Not included in Emacs by default

### ISSUE THREAD

**Issue by SkylarLK** [fxbois/web-mode#1285]
## The issue: 
Web Mode is a third-party install and is not included in default vanilla Emacs, despite being more functional than HTML mode. Web Mode is good enough to replace the default HTML mode in Emacs. It would be useful for you to submit Web Mode to be included in the Emacs installation by default.
## The fix: 
Go to the GNU Emacs contributing guide [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Contributing.html) and follow their guidelines.

### Just in case I need to, I will provide the output of `M-x web-mode-debug`:
`--- WEB-MODE DEBUG BEG ---
versions: emacs(28.2) web-mode("17.3.9")
vars: engine(nil) minor(nil) content-type("") file("*doom*")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (size-indication-mode buffer-read-only window-divider-mode show-paren-mode global-eldoc-mode general-override-mode override-global-mode +popup-mode evil-local-mode evil-mode solaire-mode solaire-global-mode doom-modeline-mode persp-mode global-flycheck-mode undo-fu-mode undo-fu-session-global-mode ws-butler-global-mode smartparens-global-mode winner-mode hl-line-mode gcmh-mode evil-snipe-local-mode evil-snipe-override-local-mode evil-snipe-mode evil-snipe-override-mode evil-escape-mode evil-goggles-mode marginalia-mode vertico-mode company-mode global-company-mode better-jumper-local-mode better-jumper-mode savehist-mode which-key-mode emmet-mode yas-minor-mode yas-global-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---`

**Comment by fxbois** [comment]
I prefer to stay like this. Less constraints
