### ISSUE TITLE
HTML attributes misaligned on different lines

### ISSUE THREAD

**Issue by sphakka** [fxbois/web-mode#1288]
Maybe I'm missing something about lineup args, etc. I have these in my `.emacs`:
```lisp
(add-to-list 'web-mode-indentation-params '("lineup-args" . nil))
(add-to-list 'web-mode-indentation-params '("lineup-calls" . nil))
(add-to-list 'web-mode-indentation-params '("lineup-concats" . nil))
(add-to-list 'web-mode-indentation-params '("lineup-ternary" . nil))
```
Still, with plain HTML, I can't manage to stop attrs to (mis)align on different lines. This is what happens:
1. Write a first line, then (`|` is the cursor) hit enter: the cursor is correctly indented by one tab:
    ```html
    <div class="foobar" 
        |
    ```
1. Keep writing on the next line:
    ```html
    <div class="foobar" 
        id="quux"|
    ```
2. As soon as enter is hit, the second line gets misaligned like this:
    ```html
    <div class="foobar" 
               id="quux"
    ``` 
That's, ahem... ugly! How to prevent it?

BTW, even when lineup alignment is desired, IMO, it would be nicer to have attributes on multiple lines to get aligned (whenever possible -- I guess it might be really complicated!) at the `=` sign:
```html
<div class="foobar" 
        id="quux"
```

**Comment by fxbois** [comment]
try with an empty .emacs

**Comment by sphakka** [comment]
After much head scratching, here comes the bug. It has nothing to do with lineup settings and it happens with minimal `.emacs`:
```lisp
(require 'web-mode)

(setq-default tab-width 4)

(add-hook
 'web-mode-hook
 (lambda ()
   (setq indent-tabs-mode t)
   (web-mode-use-tabs)
   ))
```
The culprit is `(web-mode-use-tabs)` -- removing it, brings back the expected behavior.

**Comment by fxbois** [comment]
There is issues with tab alignment. Would be happy to review a patch.
