### ISSUE TITLE
Need to constantly use `web-mode-dom-normalize`

### ISSUE THREAD

**Issue by kjnez** [fxbois/web-mode#1290]
When I edit HTML files (with django template), I find that I have to use `web-mode-dom-normalize` every so often. If I don't do that, the following will happen (| denotes the cursor):

```html
<div class="flex">
...
</div|
```
After hitting ">", it becomes this
```html
<div class="flex">
...
</div>    |
```
Note the space between ">" and the cursor. If I hit backspace delete, it becomes this
```html
<div class="flex">
...
</div    |
```
Note that the space still exists. And if I hit ">" again, it becomes this
```html
<div class="flex">
...
</div>    |
```

Basically, the space will always be there and cannot be deleted. Using `web-mode-dom-normalize` solves this problem but I doubt this is the desired behavior.

Sometimes there will be the space regardless of whether I'm near the end of the `div`.

**Comment by fxbois** [comment]
do you use TAB as indentation char ?

**Comment by kjnez** [comment]
Yes, my `indent-tabs-mode` is `t`.

**Comment by kjnez** [comment]
Also, I don't know how exactly this unwanted behavior is triggered but one way can be this (| is the cursor):
```html
<div>
...
</div>
<|
<div>
...
</div>
```
If I hit "d", it becomes
```html
<div>
...
</div>
<d        |
<div>
...
</div>
```

**Comment by fxbois** [comment]
web-mode does not handle well indentation with tabs.
Do not hesitate to provide a patch for this

**Comment by kjnez** [comment]
For anyone running into the same problem, this can be partially solved by
```elisp
(add-hook 'web-mode-hook (lambda () (indent-tabs-mode -1)))
```
