### ISSUE TITLE
Is there a variable to set the color of left fringe

### ISSUE THREAD

**Issue by kjnez** [fxbois/web-mode#1291]
I'm using a dark theme and the left fringe of a block is not apparent. I wonder if I can change the color of the fringe in web-mode?

**Comment by fxbois** [comment]
please post a screenshot with an arrow to point to the zone you are writing about

**Comment by kjnez** [comment]
Here it is:
![demo](https://github.com/fxbois/web-mode/assets/16110811/c3fbff32-8200-4b03-850c-819b303c5b2b)

**Comment by fxbois** [comment]
web-mode-current-column-highlight-face
