### ISSUE TITLE
Incorrect indentation in blade templates

### ISSUE THREAD

**Issue by danipardo** [fxbois/web-mode#1292]
When I indent a blade.php file, the indentation is broken:

![image](https://github.com/fxbois/web-mode/assets/11294702/99dad84d-4325-4a5c-ae46-a63d5da45f5b)

If I switch to html-mode though, it gets better:

![image](https://github.com/fxbois/web-mode/assets/11294702/e27aa416-dd95-449e-ac42-7c0df7cd7c6b)

**Comment by cweiske** [comment]
How was this fixed? I don't see any explanation or referenced commit.

I also experienced this with `20231225.1458`, while the update to `20240315.1838` fixed it.

**Comment by danipardo** [comment]
This ticket got closed without any comment or explanation, so I was left without a clue. But last week, I tried with a blank .emacs.d configuration, installed web-mode, and the indentation worked correctly and much faster than before. 
So the only thing I can suggest is to check your config, maybe there are other modules that are interfering?

**Comment by fxbois** [comment]
The commit is this one
https://github.com/fxbois/web-mode/commit/10f1269ab1007ab3d5fe018c83bb82c979617bfd

**Comment by cweiske** [comment]
Thanks - this was apparently the same problem as #1300.
