### ISSUE TITLE
use of save-mark-and-excursion requires more recent version of emacs than declared

### ISSUE THREAD

**Issue by wgmitchener** [fxbois/web-mode#1293]
Version 17.3.15 of web-mode.el uses a macro called save-mark-and-excursion.
The file is marked with
;; Package-Requires: ((emacs "23.1"))
However, that macro is not available in emacs 24.3.1, which I'm using on an old machine. The emacs package manager installs this new version of web-mode, but the package fails to work, giving an error about save-mark-and-excursion when you try to activate web-mode while visiting a file.

**Comment by fxbois** [comment]
I've restored the previous behavior

**Comment by hrehfeld** [comment]
This change caused a bug where enabling `web-mode-enable-current-column-highlight` causes the mark to be messed with. please revert and require recent emacs version (or disable the feature on older versions that don't have this macro)

**Comment by fxbois** [comment]
done with last commit

**Comment by hrehfeld** [comment]
Thanks a bunch!
