### ISSUE TITLE
You can't use atomic group in PHP regex

### ISSUE THREAD

**Issue by jcubic** [fxbois/web-mode#1295]
This is valid syntax in PHP regex:

```php
$re = '/(?>foo)/';
```

The `?>` is a valid syntax inside the string. But web-mode marks it as the end of PHP code and makes everything after look like fundamental mode. This syntax is [atomic group](https://www.regular-expressions.info/atomic.html).

I'm not sure if you can do anything with this, but without handling this the code needs to be modified just to work with web-mode in Emacs.

The option is to use:

```php
$re = '/(?' . '>foo)/';
```

But this is just a hack to make web-mode happy.

**Comment by fxbois** [comment]
Hi, it has already been reported. Too difficult to solve.
