### ISSUE TITLE
Weird error in JSX when using a comma after a tag

### ISSUE THREAD

**Issue by jcubic** [fxbois/web-mode#1299]
Got this code:

```jsx
export function Component(): JSX.Element {
  return (
    <p>
      You can disable this mechanism with
      <a href="http://tinyurl.com/CSP-disable">Chrome Extension</a>,
    but you do this on your own risk.
    </p>
  );
}
```

The comma after `<a>` tag makes the rest of the text like JavaScript code. Because `do` and `this` are highlighted as keywords. But the real issue is the indentation.

![Przechwycenie obrazu ekranu_2024-02-26_19-47-22](https://github.com/fxbois/web-mode/assets/280241/e961c269-d7ea-49de-901a-ef3c765f0078)

**Comment by fxbois** [comment]
should be fixed with last commit

**Comment by jcubic** [comment]
Can confirm it works.
