### ISSUE TITLE
Incorrect indentention and highlight in blade templates 

### ISSUE THREAD

**Issue by leafbel** [fxbois/web-mode#1300]
Using the file in the [web-mode/tests/test.blade.php](https://github.com/fxbois/web-mode/blob/master/tests/test.blade.php) i get this result in a buffer with web-mode and blade engine setup:

![image](https://github.com/fxbois/web-mode/assets/71148349/aeea02bc-fd92-4f5b-9ff9-a624a246c95f)

edit: making some more tests it looks like the problem is caused by blade directives that don't use a closing tag (e.g. `@lang('consumption.this_month')` or `@section('box-content')`) 

--- WEB-MODE DEBUG BEG ---
versions: emacs(29.2) web-mode("17.3.18")
vars: engine("blade") minor("blade") content-type("html") file("/tmp/asdsd.blade")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (visual-line-mode window-divider-mode electric-quote-mode show-paren-mode eldoc-mode global-eldoc-mode override-global-mode repeat-mode electric-pair-mode shell-dirtrack-mode global-auto-revert-mode savehist-mode which-key-mode brazilian-holidays-mode server-mode magit-auto-revert-mode global-git-commit-mode vertico-mode marginalia-mode doom-modeline-mode flymake-mode global-org-modern-mode org-edna-mode pdf-occur-global-minor-mode goggles-mode denote-rename-buffer-mode winner-mode jinx-mode global-jinx-mode corfu-mode corfu-popupinfo-mode sideline-mode mu4e-modeline-mode emmet-mode)
vars:
web-mode-enable-current-column-highlight=t 
web-mode-enable-current-element-highlight=t 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
should be fixed with last commit

**Comment by leafbel** [comment]
I've just tried the latest commit and it's working!
Thanks for the fix and congratulations on a great package!
