### ISSUE TITLE
RFE: support Pandoc HTML template syntax

### ISSUE THREAD

**Issue by sphakka** [fxbois/web-mode#1305]
Pandoc uses yet another [HTML template syntax](https://pandoc.org/chunkedhtml-demo/6.1-template-syntax.html).
No idea if that's based on any know engine. In a nutshell, two syntax variants are possible:
```
$if(variable)$
This is $variable$
$endif$
```
or (my preferred one):

```
${if(variable)}
This is ${variable}
${endif}
```
Could web-mode support it? It would be awesome :-)

**Comment by fxbois** [comment]
Try to share on gist an example with all the different syntax please

**Comment by fxbois** [comment]
seems similar to the ```marko``` engine. You can try that

**Comment by sphakka** [comment]
Yeah, `marko` looks fine, thanks!

**Comment by fxbois** [comment]
@sphakka I've added ```pandoc``` as synonym of ```marko```
