### ISSUE TITLE
Indent offset not respected when pressing `tab` on a marked region

### ISSUE THREAD

**Issue by jjnilton** [fxbois/web-mode#1306]
It seems that when pressing <kbd>Tab</kbd> on a marked region, it uses the function `(indent-for-tab-command)` and does not respect the indent offset set in Web Mode, but if I press <kbd>Tab</kbd> on a line without marking a region, it works as expected.

**Comment by fxbois** [comment]
Could you try to investigate ?

**Comment by fxbois** [comment]
seems to work here ... perhaps try with an empty .emacs
