### ISSUE TITLE
Indentation error for JSX fragment

### ISSUE THREAD

**Issue by jcubic** [fxbois/web-mode#1310]
There is an error in indentation:

```jsx
function App() {
  return (
    <>
      <a href="https://example.com">
        <img/>
      </a>
    <div>
    </div>
    </>
  );
}
```

The `<div>` is not indented the same as `<a>` and closing fragment is not in color:

![Przechwycenie obrazu ekranu_2024-05-18_19-03-43](https://github.com/fxbois/web-mode/assets/280241/0867d318-9e41-485a-ba36-7b73907c5695)

**Comment by jcubic** [comment]
Another example:

```jsx
const Translations = () => {
  const { t } = useTranslation("coi-platform-translations", {
    keyPrefix: keyPrefixes.main,
  });
  return (
    <>
      <Alert severity="info" icon={false}>
        <AlertTitle>{t("info_title")}</AlertTitle>
    <Typography variant="body2">{t("info_description")}</Typography>
    </Alert>
    <EditForm />
    </>
  );
};
```

This is part of real application.

**Comment by fxbois** [comment]
I won't work on this

**Comment by jcubic** [comment]
Even if I donate some money? This is pretty common in React.

**Comment by fxbois** [comment]
We can discuss ;)

**Comment by jcubic** [comment]
How much you want to fix this? 10-20? 50 USD is max I can pay.

I can't sponsor you, since I myself had one sponsor for $1 USD I think it was something like $10 per month, but it seems he changed the tier. And it's too small to even get the money (you need at least 1 euro).

**Comment by coun7zer0** [comment]
The solution I found for this was to use the version of **web-mode** from the MELPA Stable repository:
```emacs-lisp
  (setq package-archives
	  '(("gnu" . "https://elpa.gnu.org/packages/")
	    ("melpa" . "https://melpa.org/packages/")
	    ("nongnu" . "https://elpa.nongnu.org/nongnu/")
	    ("melpa-stable" . "https://stable.melpa.org/packages/")))
  (setq package-archive-priorities
	'(("gnu" . 10)
	  ("melpa" . 8)
	  ("nongnu" . 4)
	  ("melpa-stable" . 0)))
```
And this is my configuration to install it using **use-package**:
```emacs-lisp
  (use-package web-mode
    :ensure t
    :pin melpa-stable
    :commands web-mode)
```

**Comment by jcubic** [comment]
Yes it seems that the indentation works. I used version from Melpa and was updating the git repo that I had on disk that was not used.

```jsx
export default function Home() {
  return (
    <>
      <div/>
      <p>
        <span/>
      </p>
      <div></div>
    </>
  )
```

one minor things is that the closing `</>` is not in color but I can live with that.

**Comment by fxbois** [comment]
It is now fixed.

**Comment by jcubic** [comment]
I just update web-mode, it's better but not 100% correct.

```
  return (
    <>
      <Card onSubmitAction={fetchFirstCommit} />
      {loading && <Text>Loading ....</Text>}
      {error && <Text>{error}</Text>}
      {data && <>
        <Text>{data.commit.message}</Text>
          </>}
      </>
  );
```

**Comment by fxbois** [comment]
I do not deal with this kind of syntax : ```code && tag```

**Comment by jcubic** [comment]
I need to check again the code from GitHub, I've updated from Melpa, but I don't see the fix working even with my base code.

Let's hope that {expression && JSX} this works out of the box, since this standard JavaScript code. This is pretty common code in React.

**Comment by jcubic** [comment]
I just checked again, with latest from git (I was using `load-path` not Melpa), and this works fine:

```
{data && <>
  <Commit ref={ref} {...data} />
  <Button onClick={screenshot}>Download Image</Button>
</>}
```

JSX tag is a first class value, so it can be put everywhere other values and this seems to work fine.

Thanks, for your work.
