### ISSUE TITLE
Blade: `@if` with following space: condition not highlighted 

### ISSUE THREAD

**Issue by cweiske** [fxbois/web-mode#1311]
In a laravel .blade.php template, the condition in an `@if` statement is only highlighted when there is no space between `@if` and `(`:
![2024-05-30 blade web-mode if](https://github.com/fxbois/web-mode/assets/59036/9d324fef-3c49-4a84-9351-120adb10c332)

Highlighted:
```
@if($feedbackform && false)
    {{$feedbackform}}
@endif
```
Not highlighted:
```
@if ($feedbackform && false)
    {{$feedbackform}}
@endif
```

The laravel blade documentation itself uses a single space between `@if` and the opening parenthesis: https://laravel.com/docs/11.x/blade#if-statements

----
This is with emacs 28.2 on Debian 12 using web-mode 20240413.1455. There is no update installable.

**Comment by fxbois** [comment]
@cweiske seems to work with the last web-mode.el version

**Comment by cweiske** [comment]
Thank you!
