### ISSUE TITLE
Add use-package documentation/example to main website/documentation

### ISSUE THREAD

**Issue by ArenT1981** [fxbois/web-mode#1312]
Hello

Thanks for the great work on this package. Like a lot of Emacs users, I make use of "use-package". I was initially having a few issues with it not automatically enabling the web-mode major mode when opening a relevant file (e.g. `*.php`), until I adjusted my configuration as per the snippet below.

Anyway, it would be nice if you would consider adding this snippet into the "Install" section/documentation of your website (web-mode.org)/README to allow new users whose Emacs configuration employs `use-package` get immediately up to speed via a simple "copy-paste and evaluate":

```
(use-package web-mode
  :ensure t
  :mode
  (("\\.phtml\\'" . web-mode)
   ("\\.php\\'" . web-mode)
   ("\\.tpl\\'" . web-mode)
   ("\\.[agj]sp\\'" . web-mode)
   ("\\.as[cp]x\\'" . web-mode)
   ("\\.erb\\'" . web-mode)
   ("\\.mustache\\'" . web-mode)
   ("\\.djhtml\\'" . web-mode)))
```

Thanks!

**Comment by fxbois** [comment]
done, thx
