### ISSUE TITLE
Web Mode Syntax Highlighting not working

### ISSUE THREAD

**Issue by gja** [fxbois/web-mode#153]
I wish I had a more descriptive issue title. I'm (usually) using prelude, and it's been broken for ~ 2weeks now.

I've tried to reproduce with a set of minimum .emacs as follows:

``` bash
$ emacs -q
```

``` elisp
(require 'package)
(package-initialize)
(require 'web-mode)
```

I've pasted my emacs window that has four screens:
1) The HTML that is not highlighting
2) Some ruby code, to prove that colors are enabled 
3) The output of web-mode-debug
4) The elisp i wrote

![screen shot 2013-12-05 at 7 55 50 am](https://f.cloud.github.com/assets/34746/1679572/959fe440-5d54-11e3-8734-ce2cd3914183.png)

**Comment by rinconjc** [comment]
Was this really fixed?... I'm experiencing a similar issue, where the syntax are not highlighted (at least in pure HTML), it's a shame this mode promises a lot, but unfortunately the syntax highlight is a big let down. By the way I'm using the most recent from MELPA: 20150612.1118.

**Comment by rinconjc** [comment]
The web-mode-debug just in case:

--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("11.2.8")
vars: engine("none") minor("none") content-type("html") file("index.html")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (ido-everywhere show-paren-mode yas-minor-mode yas-global-mode global-auto-revert-mode diff-auto-refine-mode shell-dirtrack-mode magit-auto-revert-mode company-mode global-company-mode electric-pair-mode projectile-mode projectile-global-mode emmet-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@rinconjc it is really a shame, I agree you. Please post your question on emacs stackoverflow

**Comment by srj-github** [comment]
Hope this helps somebody. I have encountered the same issue because of the "lsp-ui" package, and the setting that I had to turn off in order to make it work properly, was "lsp-ui-sideline-show-hover".
