### ISSUE TITLE
period in comment breaks indentation for next line in javascript

### ISSUE THREAD

**Issue by jaequery** [fxbois/web-mode#161]
with a given code:

```
// some comment.
     alert('hi');
```

if you perform C-M-\ on it, it doesn't auto-indent the alert('hi'); 
but once i remove the period in "some comment.", it indents correctly.

**Comment by dustinpaluch** [comment]
I can reproduce this.
https://asciinema.org/a/JycrbWTDtBT7L945o288M9Bp0

1. `emacs -q -nw`, load web-mode manually, open a new file, enable web-mode and whitespace-mode.
2. I typed in the following code manually. You should be able to paste it in.
3. C-x h and the indentation looks correct.
4. **Change `tab-width` to 4, then C-x h to produce the bug.**
5. Change `tab-width` back to default 8, then C-x h and the indentation looks correct.
6. Change `tab-width` to 16, then C-x h and the indentation looks correct.
7. Change `tab-width` back to default 8, then C-x h and the indentation looks correct.
8.  **Change `tab-width` to 4, then C-x h and the indentation looks correct. (!)**
9. **Remove the whitepsace before L11-12 with M-\ and indent these lines again to reproduce the bug.**

```
// Comment.
test();

if (true) {
// Comment.
test();
}

if (true) {
if (true) {
// Comment.
test();
}
}
```
```
--- WEB-MODE DEBUG BEG ---
versions: emacs(25.3) web-mode("16.0.0")
vars: engine("none") minor("none") content-type("javascript") file("/Users/imacintel/newfile.js")
system: window(nil) config("x86_64-apple-darwin16.7.0")
colors: fg(nil) bg(nil)
minor modes: (global-eldoc-mode whitespace-mode)
vars:
web-mode-enable-current-column-highlight=nil
web-mode-enable-current-element-highlight=nil
indent-tabs-mode=t
--- WEB-MODE DEBUG END ---
```
