### ISSUE TITLE
auto pair problem in erb

### ISSUE THREAD

**Issue by johand** [fxbois/web-mode#164]
when i try this

``` erb
<%= %>
```

i get a extra > like this using emacs gui

``` erb
<%= %>>
```

another thing is the auto pair stops working in the shell even if i put this in the conf

``` lisp
(setq web-mode-extra-auto-pairs
      '(("erb" . (("open" "close"))) ))
```

the same happens in GNU screen

**Comment by jojojames** [comment]
That snippet didn't work too well for me. I lost the auto formatting of the %> when I used that snippet.
I don't think smartparens handles < and <% together.

**Comment by johand** [comment]
@jojojames look [here](https://github.com/bbatsov/prelude/blob/master/modules/prelude-web.el#L50)

**Comment by jojojames** [comment]
@johand 

I made another issue thread. https://github.com/fxbois/web-mode/issues/847

Setting the autopairing to off isn't that great of a solution.
