### ISSUE TITLE
HTML+JS continuation lines poorly indented for trinary operator containing ==

### ISSUE THREAD

**Issue by fischman** [fxbois/web-mode#197]
Continuation lines following the trinary's question mark seemingly indent to the RHS of the ==, which seems strange.  E.g. compare this, which indents poorly IMO:

```
<html>
  <head>
    <script>
     var bar = 1;
     var foo = (bar == 1) ?
                       "ONE" : "OTHER";  // THIS IS THE PROBLEM
    </script>
  </head>
</html>
```

to this, which indents reasonably IMO:
```
<html>
  <head>
    <script>
     var foo = (1 < 2) ?
                "LT" : "NOPE";  // THIS IS OK
    </script>
  </head>
</html>
```

(although the second case is better than the first, I'm not sure why the "OK" case should be +1 indented from the (, either)

**Comment by axyz** [comment]
This is the default indent I have with multiple lines ternary operators: 
```
const x = 10 > 5 ?
          10
        : 5;
```

is it possible to set some option to have it like:
```
const x = 10 > 5 ?
  10
  : 5;
```

or also
```
const x = 10 > 5
  ? 10
  : 5;
```

and also
```
const x = 10 > 5 ? 10
  : 5;
```

I like to have everything indented by 2 lines when possible so that with long function or constants names I have no problem to stay below 80 characters per line

thanks

**Comment by fxbois** [comment]
@axyz I'll work on this

**Comment by fxbois** [comment]
@axyz with the last version on github, try
```(add-to-list 'web-mode-indentation-params '("lineup-ternary" . nil))```

**Comment by axyz** [comment]
thanks! going to give it a try soon
