### ISSUE TITLE
Issues with fill-column-indicator

### ISSUE THREAD

**Issue by LeartS** [fxbois/web-mode#242]
**Disclaimer:** not sure if a web-mode bug or a fill-column-indicator one

I have a problem when editing files in web-mode with fci-mode active: there are operations that trigger a strange bug where the cursor goes to the fci-column.
For example:
- C-j at the end of a line creates a newline and positions the cursor to column 80 (or I guess whatever the set column is)
- auto tag closing (e.g. typing `<` when there is an open tag) closes the tag at column 80
- ...probably others.

```
Emacs 24.3.1
fill-column-indicator 20140302.1809
web-mode 20140413.1309
```

relevant configuration in init.el:

``` lisp
(require 'fill-column-indicator)
(setq fci-rule-column 80)
(add-hook 'after-change-major-mode-hook 'fci-mode)

(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.html$" . web-mode))
(defun my-web-mode-hook ()
  "Hooks for Web mode."
  (setq electric-indent-mode nil)
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 4)
  (setq web-mode-code-indent-offset 4)
  (setq web-mode-script-padding 2)
)
(add-hook 'web-mode-hook 'my-web-mode-hook)
```

![fci-bug](https://cloud.githubusercontent.com/assets/5588738/2713408/487c26c0-c4e6-11e3-9b60-aac629d09e56.png)

**Comment by dlight** [comment]
Just to note, this bug is still present.

**Comment by fxbois** [comment]
@LeartS I can provide help if needed

**Comment by dlight** [comment]
I'm not LeartS (looks like he moved onto something else)

Anyway I'm interested in this approach, cited in a comment of alpaker/Fill-Column-Indicator#46

> I see the problem now. fci-mode redraws the fill-column rule after each buffer change, which also involves placing invisible padding at the end of line. web-mode also performs operations after each buffer change, such as auto-closing tag. What's happening is that web-mode is performing its update after fci-mode; as a result, the fci-related display state of the line becomes corrupted.

> I can think of a hacky fix. I'm going to try to come up with something cleaner before installing it, though.

and

> So, a simple change that would bring fci-mode and web-mode into harmony would be if web-mode installed its handler in after-change-functions with a nil value for the APPEND argument. Is that feasible? I.e., is it important that web-mode's addition to after-change-functions run last? I played around with web-mode for a bit after making that change and didn't notice any problems, but I'm not familiar with the package's internals or all its capabilities, so I'm not well-placed to tell if that's a viable solution.

Apparently you made the proposed change and @alpaker reported that it worked (but other people said it didn't). But it seems the bug about closing tags is fixed (I think?).

The issue I'm having is identical to the one shown in that screenshot [here](https://cloud.githubusercontent.com/assets/750314/2931803/bc5df8e2-d7a7-11e3-9c0a-7e137be52377.png), it happens when writing new lines into the file. It goes away if I switch out the buffer (with `C-x b`) and then switch it back. It seems *that* is what isn't fixed.

**Comment by fxbois** [comment]
@dlight when you come back, the buffer is redrawed so it is normal that every thing is ok. Perhaps you should try the nil parameter advice and tell me if everything is ok after playing with it for a long time

**Comment by dlight** [comment]
I don't know how to do the nil parameter thing, could you post an example code? I don't have `after-change-functions` in my code.

For reference, here is what I have right now (the `(when (not (memq major-mode
                              (list 'web-mode))) ...)` stuff is to disable fci on web-mode):

```elisp
(require 'fill-column-indicator)
(define-globalized-minor-mode global-fci-mode
  fci-mode (lambda ()
             (when (not (memq major-mode
                              (list 'web-mode)))
               (fci-mode 1))))


(global-fci-mode 1)

(require 'web-mode)

(add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))

(defun my-web-mode-hook ()
  "Hooks for Web mode."
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 4)
  (setq-default indent-tabs-mode nil)
  (define-key web-mode-map (kbd "C-n") 'web-mode-tag-match)
  ;(setq web-mode-enable-current-element-highlight t)
  (setq web-mode-enable-current-column-highlight t)
  (setq web-mode-ac-sources-alist
	'(("css" . (ac-source-css-property))
	  ("html" . (ac-source-words-in-buffer ac-source-abbrev))))
)

(add-hook 'web-mode-hook  'my-web-mode-hook)
```

**Comment by fxbois** [comment]
@dlight I ve just read the discussion and my previous advice is useless.
In fact I do have any idea about this. I do not work on  minor mode issue. I can provide help if needed
