### ISSUE TITLE
Electric-Pair mode and web-mode

### ISSUE THREAD

**Issue by eN-Joy** [fxbois/web-mode#275]
Not strictly an issue with web-mode, but i use electric-pair mode so `{` becomes `{}`, web-mode also provides auto-closing for me, so `{%` becomes `{% ... %}`, when            both are active, i got `{% ... %}}`, note the extra closing brace, is there a workaround from the web-mode side? Thanks,

**Comment by azizmb** [comment]
@eN-Joy I'm facing the same problem. How did you finaly work around this?

**Comment by PhilippBaschke** [comment]
@azizmb 

I fixed it like this:
```elisp
(add-hook
   'web-mode-hook
   '(lambda ()
      (setq web-mode-enable-auto-pairing nil)
      (setq-local
       electric-pair-pairs
       (append electric-pair-pairs '((?% . ?%))))))
```
The idea is from this StackExchange answer:
http://emacs.stackexchange.com/a/2559

**Comment by xuhdev** [comment]
An alternative solution: (adjusted from my answer here http://emacs.stackexchange.com/a/27426/2755 )

```elisp
  ;; remove {} auto pairing in electric-pair-pairs for web-mode
  (add-hook
   'web-mode-hook
   '(lambda ()
      (setq-local electric-pair-inhibit-predicate
                  (lambda (c)
                    (if (char-equal c ?{) t (electric-pair-default-inhibit c))))))
```

**Comment by dasboeh** [comment]
I followed xuhdev's advice but it doesn't work.

I want to enable auto-pairing in web-mode, but disable electric pairing for just "{".
I'm using Emacs 25 and up-to-date web-mode.

Thanks for any help.

**Comment by ayothealoko** [comment]
A little late but i found a solution that like @dasboeh asked

`	(setq web-mode-enable-auto-pairing nil)
	(setq-local
	 electric-pair-pairs
	 (cdr electric-pair-pairs))

;; and
(setq electric-pair-pairs '(
;; {} must be first for web-mode
                           (?\{ . ?\})
                           (?\( . ?\))
                           (?\[ . ?\])
                           (?\" . ?\")
                           ))

`
So make {} the first pair in electric-pair-pairs and then remove it for the local version for web-mode with cdr
