### ISSUE TITLE
Saving files takes long and in some cases seems to freeze emacs

### ISSUE THREAD

**Issue by mbutz** [fxbois/web-mode#283]
Hi,

this is probably not a bug within web-mode but rather a side-effect caused by some other package/mode and web-mode. I first thought it had something todo with me applying web-beautify, but I have this issue quite regularly while saving a medium sized xhtml-file after some changes:
- save xhtml-file from browser
- load file in emacs using web-mode
- apply web-beautify-html
- trying to save the file lets emacs freeze (only solution: kill emacs process)
- doing some other changes (such as removing all script-tags) and saving does not 
- freeze emacs but takes quite some time (up to a few seconds)

I tried the same with emacs started with -q, only loading web-mode.el and web-beautify.el. This works flawlessly.

Before I start dissecting my .emacs-configuration (which will probably take ages) I wanted to ask, if anyone has encountered this behaviour before or if anyone can give a hint, what could trigger that annoying side-effect? Any ideas, which extension could cause such a behaviour?

Example of file in question: https://gist.github.com/mbutz/fcc102828dd7e0028aef

GNU Emacs 24.3.1 (i686-pc-linux-gnu, GTK+ Version 2.24.10)
web-beautify: 20131118.226
web-mode: Version: 8.0.63

**Comment by 7Saturn** [comment]
@mbutz Did this actually work for you? I experience the same problem with using `(add-hook 'before-save-hook 'delete-trailing-whitespace)` on Emacs 29.4. It works just fine in terms of removed white spaces. But after a few times of saving a file, at some point Emacs just freezes. The file is saved, nevertheless. But I still have to kill the process and start anew. But the solution described by @fxbois does exactly nothing to my file. Any tailing white spaces just remain.

**Comment by mbutz** [comment]
@7Saturn I am not anymore working with Emacs. So sorry, can't answer this.
