### ISSUE TITLE
typing through quotation marks

### ISSUE THREAD

**Issue by david135** [fxbois/web-mode#370]
Thanks for this excellent mode! I'd like to suggest a feature.

I would find it helpful to be able to "type through” quotation marks.

For example, if I type
`<a href=`
the mode automatically inserts (cursor location marked with |)
`<a href="|"`
leaving me ready to type the contents of the string.

Possibly, if the first thing I type is a quotation mark, I would assume that I simply did not rely on the insertion, and the cursor should stay in place (`<a href="|"`) rather than producing `<a href=""|"`.

Regardless, after I have typed something (with the state as follows),
`<a href="<a URL>|"`

if I then type a quotation mark, it would be nice if the result were:
`<a href="<URL>"|`
rather than
`<a href="<URL>"|"`
as it currently functions.

I would prefer to be able to “type through” both opening and closing quotation marks, but I have found the closing quotation mark to be particularly troublesome.

I’ve made a particularly ugly hack for my own use (which I’m happy to share with you), but I’m sure that you would be able to produce something better.

**Comment by kyle-johnson** [comment]
I just pulled the latest version (I was running quite an old one) and still can't get out of auto quotes without anything other than movement commands.

Is this to be expected?

**Comment by fxbois** [comment]
please take a video so that I can understand what's happening

**Comment by kyle-johnson** [comment]
Here's an example:
https://www.youtube.com/watch?v=nmn6d72oCuI

Keydump is at the end of the video, but basically if I type out an "attr=" in an HTML tag, I get dumped into quote (great), but then the only way to get out of the quotes is with a movement command (ctrl+f, or an arrow key).

**Comment by fxbois** [comment]
I still do not understand anything. 
You use arrow key to go out of the attr value .. so what ? I use those keys all the time ... what do you need, please be way more descriptive in your issue.
And what is the purpose of using keydump ???
