### ISSUE TITLE
I really miss these features of sgml-mode when using web-mode

### ISSUE THREAD

**Issue by shackra** [fxbois/web-mode#394]
Those features are:

* Insert tag
* Insert attributes
* Backward tag
* Forward tag
* Delete tag
* Validate

**Comment by fxbois** [comment]
@shackra could you describe the behaviour of those methods please ?
For foraward and delete, I really wonder why you can't use the web-mode builtins methods

**Comment by fxbois** [comment]
@shackra the last version pushed on github provides ```web-mode-attribute-insert``` and ```web-mode-element-insert```

**Comment by shackra** [comment]
Nice, thanks and sorry for not being verbose enough!
