### ISSUE TITLE
no html syntax highlighted with javascript

### ISSUE THREAD

**Issue by zhjohn** [fxbois/web-mode#399]
I ran emacs in cygwin under windows.   
.emacs
(load "/home/vpcca/.emacs.d/web-mode/web-mode.el")
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))

M-x web-mode-debug
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("10.2.00")
vars: engine("none") content-type("html") file("/cygdrive/d/StudyRoom/web/demo5\
.html")
system: window(nil) config("x86_64-unknown-cygwin")
colors: fg(nil) bg(nil)
minor modes: (transient-mark-mode line-number-mode buffer-read-only auto-compre\
ssion-mode auto-encryption-mode auto-composition-mode font-lock-mode global-fon\
t-lock-mode file-name-shadow-mode menu-bar-mode tool-bar-mode mouse-wheel-mode \
electric-indent-mode tooltip-mode)
--- WEB-MODE DEBUG END ---

Could you please help to take a look.  Thanks

**Comment by fxbois** [comment]
@zhjohn if it is related to colors, please look at http://web-mode.org

**Comment by zhjohn** [comment]
Thanks for your quick reply.   did you mean I  manually set up these below for syntax highlighting 
            (set-face-attribute 'web-mode-css-rule-face nil :foreground "Pink3")
html web-mode-doctype-face, web-mode-html-tag-face, web-mode-html-tag-bracket-face, .............

Is there a switch to use built-in emacs html-mode ?

**Comment by fxbois** [comment]
@zhjohn please post a screenshot of your emacs editing an html file with web-mode

**Comment by zhjohn** [comment]
How come I can not paste the screenshot in comment field ?  How other people did this ?  thanks.

**Comment by zhjohn** [comment]
since I can not paste screenshot,  describe what I see, no highlighting for any html tag, but only javascript inside <script></script> are highlighted. 
 
<!doctype html>
<html>
      <head>
           <script>
                var name = "Javascript";
                function hello() {
                      alert("hello "+name);
                }
           </script>
        </head>
        <body>
        </body>
</html>  
-UUU:%*--F1  demo5.html        ALL L10    (Web) ---------------------------------------------------------------

**Comment by fxbois** [comment]
@zhjohn do drag and drop into it

**Comment by zhjohn** [comment]
![emacs](https://cloud.githubusercontent.com/assets/10488006/5696768/a584e760-9990-11e4-8774-b96bc9831e10.jpg)

**Comment by zhjohn** [comment]
Thanks. now the screenshot is posted. please help to take a look.

**Comment by fxbois** [comment]
the syntax of the javascript part is highlighted, I do not understand your issue

**Comment by zhjohn** [comment]
my problem is that html syntax is highlighted.   Can you see why ?

**Comment by fxbois** [comment]
I really do not understand anything to your problem. You should ask on stackoverflow

**Comment by zhjohn** [comment]
ok. thanks
