### ISSUE TITLE
web-mode is crashing when creating elements in jQuery.

### ISSUE THREAD

**Issue by jezenielzapanta** [fxbois/web-mode#400]
Whenever I create elements using jQuery it seems like `web-mode` crashes. For example, I wrote this piece of code in my html's script tag, `$('<input></input>')` syntax highlighting will turn off and it seems like I switched back to `html-mode`.

The only workaround I found is to call the `web-mode` function again.

**Comment by fxbois** [comment]
@jezenielzapanta could you
- post your example on gist + complete scenario to trigger the bug
- post a screenshot
- post the output of web-mode-debug
- try with an empty .emacs to see if it is not related to a minor mode

**Comment by jezenielzapanta** [comment]
This is the [gist](https://gist.github.com/jezenielzapanta/88ca5e100f8e103a1cc6) it  contains the sample code and the web-mode-debug output.

On line `7` above, while typing `var x = $('<input></` it would cause the web-mode to auto-complete `</script>` and web-mode looks like it stopped working there.

I tried the above example with almost vanilla emacs with only melpa repo inside my `.emacs` file.

The screenshot, look at line `8` it doesn't highlight the js script anymore and the indentation is back to html-mode'ish indentation style.
![2015-01-13-174836_1600x900_scrot](https://cloud.githubusercontent.com/assets/722817/5718892/8495d082-9b4d-11e4-8522-ad6a06d32037.png)

**Comment by fxbois** [comment]
@jezenielzapanta thx, I'll look at this

**Comment by fxbois** [comment]
@jezenielzapanta I've pushed a fix

**Comment by jezenielzapanta** [comment]
:+1: will look at it thanks. Can you reference the commit?

**Comment by fxbois** [comment]
https://github.com/fxbois/web-mode/commit/94bc3e42774c3320085b51fbc7b4fc28331385f9
