### ISSUE TITLE
Errors while editing erb files

### ISSUE THREAD

**Issue by seagle0128** [fxbois/web-mode#402]
I found lots of errors while editing my erb files.

tokenize: reg-beg(757) reg-end(798) regexp("\"\\|'\\|#\\|<<[-]?['\"]?\\([[:alnum:]_]+\\)['\"]?")

Please fix this ASAP. Thanks!

**Comment by fxbois** [comment]
@seagle0128 those are debug ... they are removed with the last commit

**Comment by seagle0128** [comment]
thanks

Best Regards,
Vincent

On Jan 14, 2015, at 7:38 PM, fxbois <notifications@github.com> wrote:

@seagle0128 those are debug ... they are removed with the last commit
