### ISSUE TITLE
web-mode not indenting React.js code correctly without semicolons

### ISSUE THREAD

**Issue by eagleflo** [fxbois/web-mode#403]
var Foo = React.createClass({
      render() {}
    })

After pressing enter at the last parenthesis, web-mode offers a continuation indent as if the block wasn't complete.

**Comment by fxbois** [comment]
@eagleflo I do not deal with syntax without ```;```

**Comment by gustavjf** [comment]
@fxbois Could you explain why not? Genuine curiosity here.

**Comment by fxbois** [comment]
@gustavjf I would need a proper js parser and I do not have that. js2-mode has that. I have to deal with many languages and this is the tradeoff ... most bracket based languages use the same methods

**Comment by gustavjf** [comment]
I see, thanks for clarifying.
