### ISSUE TITLE
Current Column Highlight leads to extra trailing whitespace.

### ISSUE THREAD

**Issue by jyasskin** [fxbois/web-mode#405]
Given the following document:

```html
<!DOCTYPE html>
<html>
  <body>
    <p></p>

    <ul>
    </ul>

    <ol>
      <li></li>
    </ul>
  </body>
</html>
```

If you turn on `web-mode-enable-current-column-highlight` and move the cursor over `<body>`, it'll add 2 spaces to the 2 blank lines. If you move the cursor over the mismatched `</ul>`, it'll add 4 spaces to the blank line between `</ul>` and `<ol>`.

I'd rather the column-highlight simply skip lines that aren't long enough to show it, rather than modifying the document.

**Comment by fxbois** [comment]
@jyasskin I ve discovered ```'after-string``` (http://emacs.stackexchange.com/questions/7398/overlay-and-buffer-content)
I'll use this to avoid the buffer alteration

**Comment by fxbois** [comment]
@jyasskin the last commit should solve the issue

**Comment by jyasskin** [comment]
Yep, that seems to have fixed the problem.
