### ISSUE TITLE
While editing html, expand css selector to tag with attributes

### ISSUE THREAD

**Issue by shackra** [fxbois/web-mode#406]
While you are editing an HTML/template document, it would be cool to write `tag.classname` or `tag#idname` and then pressing <kbd>TAB</kbd> to expand it to `<tag class="classname"></tag>` or `<tag id="idname"></tag>` respectively.

Hopefully without conflicting with yasnippet if turned on...

**Comment by fxbois** [comment]
@shackra if you use yasnippet, why do you wan't it directly in web-mode ?
Moreover TAB wouldn't be the key to trigger this because I don't wan't to mess with indentation

**Comment by NateEag** [comment]
@shackra I use [emmet-mode](https://github.com/smihica/emmet-mode) to get that and a lot more.

I don't have it bound to <kbd>TAB</kbd>, so I can't give you advice on getting that set up.

Given emmet-mode's existence, I'm not sure it would be worth the effort to add this to web-mode. Of course, that's @fxbois's call.

**Comment by fxbois** [comment]
@NateEag thx for the input

**Comment by shackra** [comment]
Thanks, @NateEag, I'll check emmet-mode!

**Comment by NateEag** [comment]
You're very welcome. Always glad to be of assistance.
