### ISSUE TITLE
Indentation for multiline attribute value

### ISSUE THREAD

**Issue by amardeep** [fxbois/web-mode#407]
Currently, if an attribute value is spread over multiple lines, web-mode indents it like this:
```html
<div style="color:blue; padding:20px 10px 20px 30px;
     margin: 100px 0px 0px 0px;">
  Test
</div>
```
Could i get it to align like this instead:
```html
<div style="color:blue; padding:20px 10px 20px 30px;
            margin: 100px 0px 0px 0px;">
  Test
</div>
```

**Comment by fxbois** [comment]
@amardeep I'll work on this

**Comment by fxbois** [comment]
@amardeep the last commit provides this behavior

**Comment by amardeep** [comment]
Thanks for fixing this. I verified that with latest melpa release, it works fine.
