### ISSUE TITLE
matching self-closing tags

### ISSUE THREAD

**Issue by MichaelXavier** [fxbois/web-mode#408]
Hi,

I've been working in an xml-like templating language called heist using web mode. Interpolations are often done like `<foo />`. The problem is that web-mode doesn't parse this tag as self-closing and elsewhere in the tree I'll type `</` and it will attempt to close that `foo` tag. Can you think of any way I could configure web-mode either for this type of template or globally to avoid doubly closing self-closing tags?

Thanks!

**Comment by fxbois** [comment]
@MichaelXavier are you sure you write ```<foo />``` and not ```<foo>``` ?
web-mode should recognize self closing tags when there is a slash before ```>```

**Comment by MichaelXavier** [comment]
@fxbois well this is embarassing. I'm not sure what I was doing to experience this but I can't reproduce it. I'll close this since I can't seem to get it to repro. Sorry about that.

**Comment by MichaelXavier** [comment]
I think I found the case. I'm still not sure if this is a smartparens issue or web-mode but I saw this in action: it seems like web-mode doesn't support tags that are optionally self closing:

1. Open a buffer and set it to web mode.
2. Type:
```xml
<foo>
  <foo />
```
3. As soon as you type `</`, it inserts a closing `</foo>` tag but it matches it with the self-closing one and puts it on the same indent level. It also highlights it in my editor and confirms that its matching with the self-closing one and not the outer one.

**Comment by fxbois** [comment]
@MichaelXavier 
https://github.com/fxbois/web-mode/commit/bfd72851a28b46de4f58087b9830180be8fbe894
should solve the issue
I am really surprised a ```<foo>``` tag can be start, end and self-closing in the same template

**Comment by MichaelXavier** [comment]
@fxbois Thank you! So in my case I'm using the `apply` tag in heist. In heist, apply includes a partial, which sometimes has content and sometimes just straightforwardly loads the template. If it's got content, you bind it inside the `<apply>` and if you don't have content, you can leave it blank or have it be self-closing. In my eyes we can close this ticket but I'll leave it to you since I don't know your release process.

**Comment by fxbois** [comment]
@MichaelXavier you're right, it makes sense !
