### ISSUE TITLE
Only indent on certain templating engine tags.

### ISSUE THREAD

**Issue by rye** [fxbois/web-mode#409]
In a test app, I have the following code in a `.erb` file:

```erb
<% $array.each do |element| %>
<%= element.inspect %>
<% end %>
```

When I use `web-mode` to indent this file, it sees the `map` code block as being something that should increase the indentation, but it shouldn't, or at least I'm asking that I have the ability to make it not increase the indentation.

When I indent this code block, I get the following resulting ERB, per `web-mode`'s indentation rules:

```erb
<% $array.each do |element| %>
    <%= element.inspect %>
<% end %>
```

Which results in the following HTML:

```html
    banana
    apple
    tangerine
```

Instead, I'd like `web-mode` to indent like this:

```erb
<% $array.each do |element| %>
<%= element.inspect %>
<% end %>
```

Which results in this:

```html
banana
apple
tangerine
```

* * *

To show how wonky this can make things, here's an extended example.

This is with `web-mode` indentation.

```erb
<div class="foo">
    <ul>
        <% $array.each do |element| %>
            <li>
                <%= element.inspect %>
            </li>
        <% end %>
    <ul>
</div>
```

The above ERB renders to this:

```html
<div class="foo">
    <ul>
            <li>
                banana
            </li>
            <li>
                apple
            </li>
            <li>
                tangerine
            </li>
    </ul>
</div>
```

This is wrong, as an additional indentation level is unnecessarily inserted. A better indentation would be:

```erb
<div class="foo">
    <ul>
        <% $array.each do |element| %>
        <li>
            <%= element.inspect %>
        </li>
        <% end %>
    <ul>
</div>
```

This would render to:

```html
<div class="foo">
    <ul>
        <li>
            banana
        </li>
        <li>
            apple
        </li>
        <li>
            tangerine
        </li>
    </ul>
</div>
```

The last two code blocks are the desired behavior.  The indentation engine would check if a ~~code block~~ (edit: enumerator, loop, etc.) had been opened on the previous line and would not increase the indentation line if so.  This would result in prettier code.

While I'd be happy to help resolve this, my knowledge of both the internals of `web-mode` and writing Emacs packages are extremely limited. I'd be glad to clarify desired behavior and provide further examples, but beyond that I'm afraid I can't be of too much help.

Thanks in advance for any solutions that are found.

**Comment by fxbois** [comment]
@rye get the last version on github and add in your ```.emacs```
```(setq web-mode-enable-control-block-indentation nil)```

**Comment by rye** [comment]
Just did that and tested it, it works wonderfully.
