### ISSUE TITLE
web-mode-dom-rsf: Invalid search bound (wrong side of point)

### ISSUE THREAD

**Issue by pedroteixeira** [fxbois/web-mode#411]
Not sure what happened, but recently this messaged started appearning when trying to indent (react's jsx files) - (I'm using latest released). Any clues?

thanks!

**Comment by fxbois** [comment]
@pedroteixeira please put on gist a file that triggers the issue and describe a complete scenario to trigger the message

**Comment by fxbois** [comment]
@pedroteixeira I ve fixed an issue that triggered this message.
Please reopen the issue if needed

**Comment by pedroteixeira** [comment]
thanks, it did stop the error I was seeing!

But for some reason, the indentation is not correct anymore:

![image](https://cloud.githubusercontent.com/assets/14740/5937174/79f97606-a6d3-11e4-87e8-56c72943c7cd.png)
(for ex: "schema" and everything below gets indented incorrectly, where it should be indented just like the key "value")

I use the following:
 '(web-mode-attr-indent-offset nil)
 '(web-mode-code-indent-offset 2)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-indentation-params '("lineup-calls" . nil))

Can you see anything that could cause this behavior?

thanks again.

**Comment by fxbois** [comment]
@pedroteixeira please test the last version

**Comment by pedroteixeira** [comment]
tested with the latest:
![image](https://cloud.githubusercontent.com/assets/14740/5938306/cc48deb2-a6e0-11e4-9b05-a2454729929f.png)

**Comment by fxbois** [comment]
please post your example on gist

**Comment by pedroteixeira** [comment]
https://gist.github.com/pedroteixeira/3312c94dca6d2ae44f81

**Comment by fxbois** [comment]
@pedroteixeira you should not replace ```web-mode-indentation-params``` but ``àdd-to-list``` ... look at web-mode.org

**Comment by pedroteixeira** [comment]
hm.. I tested with add-to-list but got the same output:

```js
var obj = {
  a:1,
    b:2,
    c:3
};
```

Removing these 2 modifications of "web-mode-indentation-params", indentation goes back to normal for this case:

```js
var obj = {
  a:1,
  b:2,
  c:3
};
```
