### ISSUE TITLE
Incorrect indentation after template constructs within attributes over multiple lines

### ISSUE THREAD

**Issue by spookylukey** [fxbois/web-mode#414]
Using the django template engine, I get this:

    <p class="someclass
              {% if foo %}fooclass{% endif %}">
              <

The indentation after the `<p>` tag is too far in. It seems to be combination of using the `{% if %}` and having the `class` attribute span over multiple lines.

Thanks!

**Comment by fxbois** [comment]
@spookylukey https://github.com/fxbois/web-mode/commit/2b83484b43ffe50c4b42b84b6fd5ea604144fced should solve the issue

**Comment by spookylukey** [comment]
3 hours from report to fix. And a total of 3 open bugs on your issues list (including this one). You are totally awesome. Make sure you don't burn out.

Thanks!

**Comment by fxbois** [comment]
Working on web-mode.el makes me not burning out ;)
