### ISSUE TITLE
cannnot indent correctly in js.erb

### ISSUE THREAD

**Issue by Ryohe** [fxbois/web-mode#415]
Hi. At first, I hope my poor english let you understand...

I'm using web-mode 10.3.05 and emacs 24.3.1.
my emacs on web-mode, following source code (example in your page) cannnot do correctly indentaion.

`<ul>`
`<% for @item in @items -%>`
`<li><%= @item %></li>`
`<% end %>`
`</ul>`

in this source code, `web-mode-engine` is erb. and I indent with `indent-for-tab-command` command.
my emacs init.el is here.

```lisp
...
;;web-mode
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.js.erb\\'" . web-mode))
(setq web-mode-engines-alist 
      '(("erb" . "\\.js.erb\\'"))
)
(defun my-web-mode-hook () 
  "Hooks for Web mode." 
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-block-padding 2)
  (setq web-mode-markup-indentation t)
)
(add-hook 'web-mode-hook 'my-web-mode-hook)
...
```

thanks!

**Comment by fxbois** [comment]
@Ryohe everything works fine with your example
perhaps add ```(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))``` in your .emacs
Moreover ```(setq web-mode-markup-indentation t)``` seems very bad
I don't where you have found such line

**Comment by Ryohe** [comment]
thanks for your advice. but problem remains unchanged...

I found above example shows correct indent in html.erb.
i wanna do like this in js.erb, for example
```javascript
<% array.each do |e| %>
var x = e;
<% end %>
```
to
```javascript
<% array.each do |e| %>
  var x = e;
<% end %>
```

isnt this supported?

**Comment by fxbois** [comment]
@Ryohe block controls are not considered when calculating js indentation.
Sorry

**Comment by Ryohe** [comment]
@fxbois ok, thank for sparing your time!
