### ISSUE TITLE
Another django indentation bug ...

### ISSUE THREAD

**Issue by spookylukey** [fxbois/web-mode#416]
<div id="foo"
         {% if hidden %}style="display: none;"{% endif %}>
         <div>

The inner div is aligned with the id attribute. This is similar to https://github.com/fxbois/web-mode/issues/414 except the `{% if %}` is outside an attribute, rather than inside.

I think this may have been a regression from your last fix.

**Comment by fxbois** [comment]
@spookylukey https://github.com/fxbois/web-mode/commit/e8030283fee427aced451b6a7bf3a0f524999c98 should solve the issue

**Comment by spookylukey** [comment]
OK, now you're just showing off...

Thanks again!
