### ISSUE TITLE
Way to enable JSX highlighting manually

### ISSUE THREAD

**Issue by jezenielzapanta** [fxbois/web-mode#419]
Is there a way to enable jsx manually? I tried creating external jsx files but I struggle in enabling syntax highlighting for this. But it works when inside the `<script type='text/jsx'>` tag.

**Comment by fxbois** [comment]
Just associate the jsx extension

**Comment by log0ymxm** [comment]
How can the jsx features be enabled in a file with just a js extension?

**Comment by fxbois** [comment]
@log0ymxm you can use the var ```web-mode-content-types-alist``` in your .emacs

```lisp
(setq web-mode-content-types-alist
      '(("jsx" . "/some/path/*\\.js\\'")))
```

**Comment by log0ymxm** [comment]
@fxbois Nice, thank you.
