### ISSUE TITLE
Can I add language tag otherthan css/script tag to html engine?

### ISSUE THREAD

**Issue by victorfence** [fxbois/web-mode#421]
My template file is in html format. And I have <php></php> tags in that to include some serverside thing. Codes inside it are not highlight of course. But, I wonder if it's possible to extend  this easily?

**Comment by fxbois** [comment]
@victorfence please post your example on gist + post the output of web-mode-debug
Moreover it would be so useful to tell me what template engine you use.
Last thing have you read http://web-mode.org ? when you have a template with a html extension, you have to force the engine

**Comment by victorfence** [comment]
@fxbois Sorry for disturbing you, this is not a bug, I just want to extend html engine to add my custmo tag <php></php>. Seems not easy to do, I am right?

**Comment by fxbois** [comment]
@victorfence do you have any, a doc, some examples ? It can be simple

**Comment by victorfence** [comment]
@fxbois Ok, I posted one to gist  https://gist.github.com/victorfence/8745f1f812f442c1b606

**Comment by fxbois** [comment]
but is it your engine ? does this engine has a website ? Is ```<php></php>``` the only possible block?

**Comment by victorfence** [comment]
@fxbois  yeah, <php></php>, is the only block I want to highlighting otherthan  css/script, the html looking template is for my self-created php template engine.

**Comment by victorfence** [comment]
@fxbois I add something like:
         ((string= tname "php")
          (setq element-content-type "javascript" ;; "php" not working
                part-close-tag "</php>"))
under line 3672
this will indent and highlight php code as javascript, imprecise, just not bad for me.

**Comment by NdYAG** [comment]
Sorry to bring this up @fxbois 
This is exactly what I metioned in https://github.com/fxbois/web-mode/issues/191

In my company, we did some slight modification on Mako: 
we defined two customized blocks
```html
<%block filter="collect_js">
// js content
<%/block>
``` 

and

```html
<%block filter="collect_css">
// css content
</%block>
```

In this way, we combine css/js snippets in different templates into a single css/js file.

That's why I could not provide any documentation for you.

---

I tried to add some code under line 3930,

```lisp
((string= tname "%block")
          (let (blk)
            (setq blk (buffer-substring-no-properties tbeg tend)
                  part-close-tag "</%block>")
            (cond
             ((string-match-p " filter=\"collect_js\"" blk)
              (setq element-content-type "javascript"))
             ((string-match-p " filter=\"collect_css\"" blk)
              (setq element-content-type "css"))
             (t
              (setq element-content-type "html"))
             ) ; cond
            ) ;let
          )
```
But it seems that `tname` will not be `%block` in any case(?).

**Comment by fxbois** [comment]
@NdYAG open a new issue for this new feature request please
