### ISSUE TITLE
use web-mode as inner-mode of polymode

### ISSUE THREAD

**Issue by falood** [fxbois/web-mode#422]
How could I use web-mode as inner-mode of [polymode](https://github.com/vspinu/polymode)?
I have added below code to my .emacs:
```
(setq web-mode-engines-alist ("json" . "\\.api\\'")))
(setq web-mode-content-types-alist '(("json" . "\\.api\\'")))
```
But, web-mode-debug says this:
```
vars: engine("none") content-type("html") file("/tmp/a.api")
```

So, How could I custom `engine` and `content-type` in my major-mode-changed-callback function?

**Comment by fxbois** [comment]
@falood please upgrade to the last version on github and just associate *.api file with web-mode (```auto-mode-alist```)

**Comment by falood** [comment]
Thank you for the extra modification for my `.api` file.
But I'm sorry, it works well with `.api` file and does **NOT** works as inner-mode.

**Comment by fxbois** [comment]
I know nothing about inner-mode ... perhaps you should ask to the maintainer of this mode

**Comment by falood** [comment]
I'm using js-mode temporarily.

There's function named [web-mode-guess-engine-and-content-type](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L10505), so I think there's a way to set `engine` and `content-type` manually instead of 'guess'.

I think it's the same scene like this:
> 
I open a file without `auto-mode-alist` to `web-mode`.
I change major-mode manually by `M-x web-mode`. 

Is there a way to set `engine` and `content-type` for this file?

**Comment by fxbois** [comment]
Yes there are web-mode-engine-set and web-mode-content-type-set

**Comment by falood** [comment]
Thanks! 
It works when I set `web-mode-engine` to `"none"`!

PS. Those are `web-mode-set-engine` and `web-mode-set-content-type`.

**Comment by fxbois** [comment]
@falood could you post a screenshot of web-mode runnning in polymode ?

**Comment by falood** [comment]
![poly-restclient-web](https://cloud.githubusercontent.com/assets/184053/6100912/4c51694a-b054-11e4-8b16-5a1b4e61b129.png)
![poly-restclient](https://cloud.githubusercontent.com/assets/184053/6100911/4afbf81c-b054-11e4-9a7f-4de41c2fef58.png)

**Comment by mwolson** [comment]
Here's what I currently have in my `~/.emacs/init.el` file to implement this, in case it's helpful. The core idea is:
* define new engine-specific major mode functions which when called:
* makes `(buffer-file-name)` return a fake name with a file extension in it which matches the code block.

```el
(defun my-define-web-polymode (file-ext)
  (let* ((sym-name (symbol-name file-ext))
         (filename (concat "." sym-name))
         (mode-sym (intern (concat "my-" sym-name "-mode")))
         (mode-name-alias (intern (concat "my-" sym-name))))
    (eval `(defun ,mode-sym (&rest mode-args)
             (cl-letf (((symbol-function 'buffer-file-name)
                        (lambda () ,filename)))
               (apply #'web-mode mode-args))))
    (add-to-list 'polymode-mode-name-aliases (cons file-ext mode-name-alias))))

(eval-after-load "polymode-core"
  '(progn
     (add-to-list 'polymode-mode-name-aliases '(bash . sh))
     (dolist (file-ext '(hbs html js json jsx))
       (my-define-web-polymode file-ext))))
```
