### ISSUE TITLE
Incorrect indentation in jsx files

### ISSUE THREAD

**Issue by curthoyt** [fxbois/web-mode#424]
Typing something like this:

    componentDidUpdate: function() {
                                    ^

...and pressing "enter" leaves the cursor on the next line, lined up directly beneath the closing brace on the previous line, as shown.

**Comment by fxbois** [comment]
@curthoyt in a jsx file or in a code inside a ```<script>``` tag ?

**Comment by fxbois** [comment]
I do not understand what you need. Please reopen if you can provide a complete testcase
