### ISSUE TITLE
Prevent use of spaces for indentation? (setq-default indent-tabs-mode t)

### ISSUE THREAD

**Issue by koodawg** [fxbois/web-mode#425]
I'm required by my employer to use tabs only for indentation. That's no spaces for indentation allowed. (setq-default indent-tabs-mode t) should do the trick according to what I've read but in web-mode it sometimes inserts tabs and spaces for indentation.

How can I prevent this? 
Thanks
Mike

**Comment by fxbois** [comment]
@koodawg I have no real answer to this question. Perhaps ask to Emacs Stackoverflow

**Comment by NateEag** [comment]
@koodawg: Not sure why `indent-tabs-mode` isn't working, but a workaround might be to add the `tabify` command to `before-save-hook`.

**Comment by koodawg** [comment]
indent-tabs-mode does work, except that emacs still wants to do smart indenting and sometimes adds a space. I found these setting sin web-mode.gl that appear to have been the problem for me:

(defcustom web-mode-script-padding 1
(defcustom web-mode-style-padding 1
(defcustom web-mode-block-padding 0
  '(("lineup-args"    . t)
    ("lineup-calls"   . t)
   ("lineup-concats" . t)

I set the bools to nil and the pads to the same as my indent length, 4, and the unwanted space alignment doesn't occur.

Thanks

**Comment by fxbois** [comment]
@koodawg in fact, of course, you must have settings that will enable emacs to insert tabs. So every settings must be compatible with a multiple of TAB width. @koodawg is right. I would add all the *indent-offset (even web-mode-attr-indent-offset). Once you have done that, I would be happy to get your config settings

**Comment by fxbois** [comment]
@koodawg @NateEag you can now ```(setq web-mode-enable-tab-indentation t)``` in your ```.emacs```

**Comment by koodawg** [comment]
Great I'll try that. 1 more question: sometimes web-mode will sort of "get lost" - it seems to lose track of syntax and font goes black. I kill buffer and reopen and it's fine again. Short cut for that?

**Comment by fxbois** [comment]
@koodawg i use web-mode-reload
If you have a way to trigger this kind of bug, do not hesitate to post an issue

**Comment by koodawg** [comment]
Thanks. Will do.

**Comment by koodawg** [comment]
Well I DLd your latest rev of web-mode.el and now I get no colorization at all. Any ideas? 
Here's my .emacs http://pastebin.com/Wnmk70x1

**Comment by fxbois** [comment]
@koodawg strange, I can not trigger the issue

**Comment by koodawg** [comment]
I'm using this Emacs http://emacsformacosx.com/ rev 24.2.1.

**Comment by koodawg** [comment]
With the new web-mode.el I get this error when opening a php file;
File mode specification error: (void-function setq-local)

**Comment by fxbois** [comment]
@koodawg I've pushed a new version that detects the value of indent-tabs-mode.
```web-mode-enable-tab-indentation``` is not used any more. Could you confirm that everything is ok ?

**Comment by koodawg** [comment]
I grabbed your latest and have been running with it today. I frequently have to do web-mode-reload. It's hard to know what causes it other than it's while adding code to a buffer. I'll use it a couple days before I report anything else. Thanks.

**Comment by pstray** [comment]
indent-tabs-mode t does't mean that you want only tabs, it means you want tabs instead of 8 spaces (or whatever a tabstop should use). Please fix so having indent-tabs-mode t doesn't break all other indentation settings.

**Comment by fxbois** [comment]
please propose a fix. I do not use TABS

**Comment by pstray** [comment]
The check in web-mode that calls web-mode-use-tabs should not check for indent-tabs-mode, but something else (since it not an indication that you want _only_ tabs). But web-mode-use-tabs could possibly set indent-tabs-mode to t, to make indentation actually use tabs.

**Comment by fxbois** [comment]
It is a problem that I wan't to work on at the moment. Do not hesitate to submit a patch.

**Comment by pstray** [comment]
Ok, you have a pull request available :)

**Comment by mkleehammer** [comment]
For others looking into this later, I found that the whole-line-or-region package in Emacs 25.1 also causes the original issue.
