### ISSUE TITLE
Web mode will not work with another plugins, causes a crash. 

### ISSUE THREAD

**Issue by ReneFroger** [fxbois/web-mode#426]
Hello there! 

Thanks for sharing this nice plugin!

However, when I turn on web-mode with `M-x web-mode` after opening a file, I get always this error: 

![schermafdruk 2015-02-12 11 44 34](https://cloud.githubusercontent.com/assets/5211845/6166002/f26ef784-b2ac-11e4-9101-0fa8385b3b7f.png)

It seems it conflicts with the plugin [Highlight indentation](https://github.com/antonj/Highlight-Indentation-for-Emacs)

My Lisp background is not very strong. Any suggestion how I could fix this? I didn't receive any response from the authors of Highlight Indentation.

**Comment by fxbois** [comment]
@ReneFroger you should ask to the developer of Highlight Indentation.
I can provide help

**Comment by fxbois** [comment]
@ReneFroger please reopen when you need help
