### ISSUE TITLE
context aware completion using company mode?

### ISSUE THREAD

**Issue by ChillarAnand** [fxbois/web-mode#427]
in the documentation there is a snippet to make it work with auto-complete mode. 

can someone tell me how to configure it using for company-mode?

**Comment by fxbois** [comment]
I let some web-mode users answer this question. I am not a company-mode user.
Perhaps you could try to crosspost this question on emacs stackoverflow

**Comment by NateEag** [comment]
@ChillarAnand I wrote the extension to support auto-complete mode.

I've never used company-mode, but if it has a similar concept to auto-complete's [ac-sources](https://github.com/auto-complete/auto-complete/blob/8d95cc17b05885bc04c7acee1a50ca27366c3f4b/auto-complete.el#L501) variable, then something similar could be implemented.

`ac-sources` is a list of auto-complete sources that are active for the current buffer. [web-mode advises the ac-start function](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L10393) to set `ac-sources` for the current language based on `web-mode-ac-sources-alist`.

You may find this closed issue where the auto-complete feature evolved helpful: https://github.com/fxbois/web-mode/issues/116

**Comment by fxbois** [comment]
@ChillarAnand Do not hesitate to reopen the issue if I can provide help.

**Comment by ChillarAnand** [comment]
just found a package https://github.com/osv/company-web for this.
might help any one searching for this.

**Comment by fxbois** [comment]
@ChillarAnand thx for sharing

**Comment by xaiki** [comment]
I thought I'd share this here, I'm using web-mode for jsx editing and tern to complete with company-mode, in order to get company-tern to work in my web-mode buffer I'm using this sniplet, maybe @fxbois will find it usefull to add to the documentation ? 
```lisp
(defadvice company-tern (before web-mode-set-up-ac-sources activate)
  "Set `ac-sources' based on current language before running auto-complete."
  (if (equal major-mode 'web-mode)
      (let ((web-mode-cur-language
             (web-mode-language-at-pos)))
        (if (or (string= web-mode-cur-language "jsx")
                (string= web-mode-cur-language "javascript"))
            (unless tern-mode (tern-mode))
          (if tern-mode (tern-mode))))))
```

**Comment by osv** [comment]
@xaiki you maybe mean

```lisp
          (if tern-mode (tern-mode -1))))))
```
