### ISSUE TITLE
settings effecting indentation of closing "?>"

### ISSUE THREAD

**Issue by koodawg** [fxbois/web-mode#428]
What settings effect the indent (or lack of) the closing "?>"  I'd like it to line up with the opening <?php

Thanks

![screen shot 2015-02-17 at 9 41 14 am](https://cloud.githubusercontent.com/assets/5799133/6230971/3eaeab8c-b689-11e4-8c17-bb086b3312e0.png)

**Comment by koodawg** [comment]
Nevermind, I see there are various configuration settings involved. Thanks.

**Comment by fxbois** [comment]
I can not trigger this bug
