### ISSUE TITLE
C-c / is undefined

### ISSUE THREAD

**Issue by rahiel** [fxbois/web-mode#429]
The shortcuts at http://web-mode.org/ say `C-c /` should close the html element but this keybinding is undefined. Currently `web-mode-element-close` is not bound to a key. And thanks for web-mode!

**Comment by fxbois** [comment]
@rahiel you're right, I'll have to correct this. I ve pushed a new version with the shortcut ```C-c C-e /```

**Comment by rahiel** [comment]
Thanks. Don't forget to update the website with the new shortuct.
