### ISSUE TITLE
JSX broken indentation on literal js objects

### ISSUE THREAD

**Issue by gnufied** [fxbois/web-mode#430]
The indentation seems to be broken when writing literal objects:

```
var data = [
  {author: "Frodo baggins", text: "Eat apples"},
    {author: "Sam wise", text: "Please don't eat apples"}
];
```

It seems to be indenting the next item after `,` to another level, rather than lining them up. This is how my `web-mode` configuration looks like:

```
(add-to-list 'auto-mode-alist '("\\.jsx$" . web-mode))
(defadvice web-mode-highlight-part (around tweak-jsx activate)
  (if (equal web-mode-content-type "jsx")
      (let ((web-mode-enable-part-face nil))
        ad-do-it)
    ad-do-it))

(defun my-web-mode-hook ()
  "Hooks for Web mode."
  (setq web-mode-markup-indent-offset 2)
  (setq indent-tabs-mode nil)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-enable-auto-pairing t)
  )

(add-hook 'web-mode-hook  'my-web-mode-hook)
```

**Comment by fxbois** [comment]
@gnufied I can not reproduce the issue. Do you have the last version available on github ?
Could you post the output of web-mode-debug.

**Comment by gnufied** [comment]
I am running latest version from github yes. Here is output of `web-mode-debug`:

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("10.4.07")
vars: engine(nil) content-type("") file("/home/gnufied/new_emacs/emacs_init.el")
system: window(x) config("x86_64-unknown-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (blink-cursor-mode tool-bar-mode tooltip-mode)
customs:
web-mode-enable-current-column-highlight(nil) 
web-mode-enable-current-element-highlight(nil) 
```

I also tried running with `emacs -Q` and manually requiring web-mode and then editing `jsx` file and I still could reproduce the problem.

**Comment by gnufied** [comment]
Here is a screenshot btw. 

![emacs](https://cloud.githubusercontent.com/assets/278/6289623/6e38d82e-b8ef-11e4-9a95-e05bcd9c106d.png)

I started emacs with `emacs -Q` for this and then manually loaded `web-mode` and my web-mode configuration via scratch buffer.

**Comment by fxbois** [comment]
@gnufied could you test the version just pushed please

**Comment by gnufied** [comment]
It appears to be fixed in master. thanks. :+1:
