### ISSUE TITLE
C-q SPC still triggers auto-pairing feature in Jinja templates

### ISSUE THREAD

**Issue by wasamasa** [fxbois/web-mode#431]
There is this feature that when you enter a space after an opening `{{`, it gets expanded to `{{ | }}`.  I figured I could temporarily disable it by entering the space with `C-q SPC` which uses the `quoted-insert` function. The difference between `self-insert-command` and `quoted-insert` is that the former runs `post-self-insert-hook`, the official place where commands triggered by insertion are kept, that way this trick can temporarily disable such special behaviour for one inserted char.

However `web-mode` is unimpressed by this. What's going wrong?

**Comment by fxbois** [comment]
@wasamasa why don't you disable auto-pairing ? ```(setq web-mode-enable-auto-pairing nil)```

**Comment by wasamasa** [comment]
I planned to do this as soon as I have set up `smartparens` properly, however that is a bit far away.

What I wanted to point out with this issue is that `web-mode` seems to be performing this trick in a non-standard manner and that it would be good to know whether this is intended or a bug.

**Comment by wasamasa** [comment]
Great, this means that something like hitting `M-SPC` to add one space will trigger this. Is this really intended?

**Comment by fxbois** [comment]
@wasamasa I ve tried your example and when I have ```{{|``` and I hit ```C-q SPC``` there is no auto-pairing

**Comment by wasamasa** [comment]
Ah, didn't restart after updating.
