### ISSUE TITLE
variable web-mode-auto-pairing-enable not set with clients launched via emacs --daemon

### ISSUE THREAD

**Issue by navdeepio** [fxbois/web-mode#432]
I've added (setq web-mode-auto-pairing-enable t) to my .emacs but when I try to spawn client by running emacs server with emacs --daemon command, it does not load/set. But if I start emacs server via M-x server-start, it works!

**Comment by fxbois** [comment]
@navdeepio I do not use emacs server ... you should ask some help on emacs stackoverflow

**Comment by navdeepio** [comment]
@fxbois so should I close this issue?
