### ISSUE TITLE
Strange comment behavior with Template Toolkit (.tt) files

### ISSUE THREAD

**Issue by sabof** [fxbois/web-mode#433]
To reproduce, with a buffer like:
```
<html>
|
</html>
```

Running `web-mode-comment-or-uncomment` results in
```
<html>|<!--  -->
</html>
```

instead of
```
<html>
<!-- | -->
</html>
```

**Comment by fxbois** [comment]
@sabof should be solved on trunk

**Comment by sabof** [comment]
Seems working. Another thing that happens is blank lines being removed. `#` is an active region mark.

```
<div>
|
	<img src="" />
#
</div>
```

```
<div>
	<!-- <img src="" /> -->|
</div>
```

**Comment by fxbois** [comment]
@sabof should be better with last commit

**Comment by sabof** [comment]
Thanks, haven't encountered anything unusual so far.
