### ISSUE TITLE
handlebars multi-line comments don't indent correctly when other handlebars commands are present

### ISSUE THREAD

**Issue by ericlowry** [fxbois/web-mode#434]
This indents correctly:

    {{!--
    quick test
    --}}
    <div class="checkbox">
        <label>
            <input type="checkbox">
        </label>
    </div>

This doesn't:

    {{!--
                                       quick test
                                       --}}
    <div class="checkbox">
        <label>
            <input type="checkbox">  {{label}}
        </label>
    </div>

In this example the contents of the comment are lining up with the first character of the "l" in {{label}}, if I increase the spaces between `<input>` and {{label}}, the indentation follows.

**Comment by fxbois** [comment]
@ericlowry it should be better with last commit

**Comment by fxbois** [comment]
@ericlowry please reopen if needed
