### ISSUE TITLE
web-mode-mark-and-expand inconsistency

### ISSUE THREAD

**Issue by mkleehammer** [fxbois/web-mode#435]
This last release has been great.  I've started using web-mode-mark-and-expand and noticed that:

```html
<div (2)> in body (1) </div>
```
* If I'm in the body of an element, such as (1) it selects the full tag including brackets.
* If I'm in the tag itself, such as (2), it selects everything except the opening '<' of "<div".

Thanks.

**Comment by fxbois** [comment]
@mkleehammer strange, I can not reproduce this isue

**Comment by mkleehammer** [comment]
It turns out that it only happens if I'm on the *first* character of the opening element, such as the "d" in "<div".  That sounds like an off-by-one error when determining whether point needs to be backed up.  Sorry for the confusion -- I hadn't noticed the pattern before.

**Comment by fxbois** [comment]
@mkleehammer 
```<div>body</div>```
when you are on the ```d``` of ```<div>``` and hit ```C-c C-m``` the issue happens for you ?
I can not trigger this bug

**Comment by mkleehammer** [comment]
I am quite sure this is related to me having an older *.elc file around.  I am not able to reproduce this with the latest (which I assume you guessed since you closed this).
