### ISSUE TITLE
wrong PHP syntax highlight in strings  

### ISSUE THREAD

**Issue by Infrid** [fxbois/web-mode#436]
there is an error in this code, after $img_path I don't close the string. In this case web-mode doesn't treat the rest of the lines like a string but it show the normal code highlight.

```php
<?php
if(empty($img_path)) return '';
else return "/images/cms/catalog/".$img_path.'; 
?>
</head>
<body>
	<?php
	$mix = array(1,2);

	//a comment
	$query = "SELECT column FROM table";
?>
```

of course github shows the highlight properly, here an image
![bug](https://cloud.githubusercontent.com/assets/3205312/6391616/7552b800-bdb8-11e4-9449-16c3b54353f4.png)

**Comment by fxbois** [comment]
@Infrid Thx but it is not a use case I really want to deal with

**Comment by Infrid** [comment]
don't get me wrong, is not just a cosmetic issue. I've spent a bunch of time to figure out this problem. PHP complains only to syntax errors in some lines that aren't ones that contains the error. In the end, when you are in crunch time, you don't think that your editor is hiding the error.

**Comment by fxbois** [comment]
@Infrid not an easy issue, it would need to rewrite all the parsing engine
At this time, when I encounter a <?php ... I try to find the next ?>, perhaps the proper would be to treat ?> as a delimiter token at the same level that comment and string tokens ...
Anyway that would
1- need a lot of work
2- have many nasty effects on fontification

**Comment by Infrid** [comment]
I understand, when I'll master ELIPS I'll help you in this project :)
