### ISSUE TITLE
emacs goes to fundamental mode, should be in web-mode

### ISSUE THREAD

**Issue by koodawg** [fxbois/web-mode#437]
I mentioned this in an earlier post, this still happens way too often. 
<pre>
 MR Name                    Size Mode             Filename/Process
 -- ----                    ---- ----             ----------------
[ Default ]
    Stat.php               45053 Web              ~/src/kixer/ads/backend/app/Model/Stat.php
    IosController.php       4673 Fundamental      ~/src/kixer/ads/backend/app/Controller/IosController.php
    Io.php                  4740 Fundamental      ~/src/kixer/ads/backend/app/Model/Io.php
    Campaign.php           19295 Fundamental      ~/src/kixer/ads/backend/app/Model/Campaign.php
  % *GNU Emacs*              709 Fundamental      
    *scratch*                  0 Lisp Interaction 
 *% *Messages*              4313 Messages         
  % *Completions*            156 Completion List  

    8 buffers              78939                  4 files, no processes
</pre>

I have no idea what triggers it. Maybe some other emacs pkg I'm using, maybe some key sequence I erroneously type (I don't think so). It's very annoying. When I open a php file it's opened in web-mode (Web) as expected. But at some point I'm editing along or something and pow, 1 or more of my php buffers are in Fundamental.If any one has a clue or suggestion I'm all ears. Thx, Mike

**Comment by koodawg** [comment]
Ok now I can reproduce it. When I enter one of the Fundamental buffers as shown above, then I do a m-x web-mode-reload to change it to Web, it changes the current buffer to Web, but it changes any other buffers in Web-mode to Fundamental!

**Comment by koodawg** [comment]
Ok now I cut everything else of my .emacs except for the web mode stuff and it's still happening:
$ cat .emacs
(add-to-list 'load-path "~/.emacs.d/lisp/")

;; http://web-mode.org/ for php/html/js all in one file
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))

(add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.ctp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.js\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.css\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.scss\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.xml\\'" . web-mode))
;;(setq web-mode-engines-alist
;;  '(("php"    . "\\.phtml\\'")
;;  ("blade"  . "\\.blade\\."))
;;)

**Comment by koodawg** [comment]
Now I see why. web-mode-reload does an unload-feature 'web-mode, and it obviously doesn't go and set the mode to all appropriate buffers, only the current one.

**Comment by fxbois** [comment]
@koodawg if you do not want to reload (which is there for debug purpose), just M-x web-mode
