### ISSUE TITLE
setq-local doesn't work with Emacs 23.3.1

### ISSUE THREAD

**Issue by ksmadsen** [fxbois/web-mode#438]
setq-local only appears to be available in newer versions of Emacs, causing web-mode 11.0.5 to fail in Emacs 23.3.1.

This can be solved by adding:

```
(unless (fboundp 'setq-local)
  (defmacro setq-local (var val)
    `(set (make-local-variable ',var) ,val)))
```

(found at https://github.com/flycheck/flycheck/issues/150)

**Comment by fxbois** [comment]
@ksmadsen thx
