### ISSUE TITLE
Indent block between begin/end for Mojolicous templates

### ISSUE THREAD

**Issue by ksmadsen** [fxbois/web-mode#439]
In Mojolicious template files, the keywords begin and end can be used like this:
```
% my $block = begin
  % my $name = shift;
  Hello <%= $name %>.
% end
```
It would be nice if web-mode treats begin/end like it does { and }

**Comment by fxbois** [comment]
@ksmadsen please the last version pushed on github

**Comment by ksmadsen** [comment]
Appears to work perfectly!

Thanks for the quick response.
