### ISSUE TITLE
HTML in type text/template not working again

### ISSUE THREAD

**Issue by mkleehammer** [fxbois/web-mode#440]
This is either a regression of #274 or something environmental.  I've tried disabling all options.  I was going to use git bisect to find the commit but I  tried all of the tagged versions 10.2, 10.3, 10.4, and 11 and couldn't find a starting point that worked.  I even tried a commit from 12 months ago.

I'm using emacs 24.4.1.  Any ideas on how to troubleshoot this?

I copied the following from #274 into test.html:

```html
<script type="text/template" id="giveScoreBoxTpl">
 <div id="give-score-box">
    <div class="score-operation">
    </div>
</div>
</script>
```

When I open the file everything inside the script is not highlighted and it does not indent.  I confirmed that the font-lock face is actually `nil`.  No change when I use font-lock-fontify-buffer.  Sometimes editing a line will color that line, but I assume that is due to code trying to determine the type of the surrounding text is stopping before it hits the script again.  Using font-lock-fontify-buffer or reindenting the entire script removes the syntax highlighting.

I normally use "ctemplate" (Underscore and Handlebars templates in script tags) but I've tried with no settings and it does not change it.

**Comment by fxbois** [comment]
@mkleehammer I ve just tried the example above and everything is ok. Could you post the output of ```web-mode-debug```. Moreover could you post a video of the issue please.

**Comment by mkleehammer** [comment]
Crap.  web-mode-debug was not defined even though I could see it in the source.  A rouge old .elc in a weird directory.  On both machines I tested.  Sorry about that.  I've removed it and I am now loading the most recent version.  web-mode-debug is a great edition.  (You may consider adding web-mode-version too -- that was my first guess.)

I tried find-library to make sure that wasn't happening but it always loaded the *new* source instead of indicating it could not find source for the given *.elc.  Do you know to find the elc a function was loaded from?  I would imagine every package maintainer would like to make this more apparent.  describe-function did report it was "web-mode is an interactive compiled Lisp function" and didn't mention a file name.  Perhaps that was my clue?
