### ISSUE TITLE
else block indentation for mojolicious templates

### ISSUE THREAD

**Issue by ksmadsen** [fxbois/web-mode#444]
Hi again,

The following mojolicious template-example isn't indented correctly:

```
% if ($a) {
  <p>If</p>
% } else {
  <p>Else</p>
% }
```
Instead of indenting the contents of the else branch, the following indentation is used:

```
% if ($a) {
  <p>If</p>
% } else {
<p>Else</p>
% }
```

**Comment by fxbois** [comment]
@ksmadsen the master branch should be ok

**Comment by ksmadsen** [comment]
Thanks, works perfectly.
