### ISSUE TITLE
Inline comments sometimes break C-m-f and C-m-b in JSX files

### ISSUE THREAD

**Issue by kryft** [fxbois/web-mode#445]
I'm using the latest web-mode.el from github (aeaf51).

https://gist.github.com/kryft/2b7de5a95bb5a3d2d41e

If you edit this file in web-mode, C-m-f and C-m-b don't work properly. For example, if you place the cursor on '{' in `function foo() {` and press C-m-f, you get an error: `Scan error: "Unbalanced parentheses ..."`. If you place the cursor on the last '}' in the file and press C-m-b, you end up at the '{' just before `/*Name*/`.

I accidentally discovered that if I surround the inline comments with whitespace, like so
https://gist.github.com/kryft/8be170ad8b525a169e8c ,
C-m-f and C-m-b work as they should.

**Comment by fxbois** [comment]
@kryft please try the last version on github

**Comment by kryft** [comment]
@fxbois Thanks for the quick response! I pulled the latest commit (8f59a6), but it seems like I still get the same problems as before.

**Comment by fxbois** [comment]
@kryft hope the last commit will be the good one

**Comment by kryft** [comment]
@fxbois Yes, everything seems to work now - thanks a lot once again! :)
