### ISSUE TITLE
Adding newlines changes whitespace-mode space color

### ISSUE THREAD

**Issue by trevorsenior** [fxbois/web-mode#450]
# The problem

Entering newlines in `web-mode` changes the color of the `whitespace-mode` spaces. This may be an issue with `whitespace-mode` but I thought I'd ask here first.

# Reproducing the problem

Reproducing the problem is not too hard.

## Javascript file used for testing

```javascript
function foo() {
    var a = 2 + 2;
    return 'bar';
}
```

## Expected behavior (using `javascript-mode` as a reference)

**A minimal `.emacs`**

```lisp
;; .emacs
(global-whitespace-mode t)
(setq-default indent-tabs-mode nil)
```

**The Results**

In `javascript-mode` *before newline*:

![javascript-mode before new line](http://i.imgur.com/qrbUURq.png)

In `javascript-mode` *after newline* (**Enter**):

![javascirpt-mode after new line](http://i.imgur.com/TESsFXc.png)

## Behavior using `web-mode`

**A modified version of the above `.emacs`**

```lisp
(global-whitespace-mode t)
(setq-default indent-tabs-mode nil)

(add-to-list 'load-path "/Users/baz/.emacs.d/el-get/web-mode")
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.js\\'" . web-mode))

(setq web-mode-code-indent-offset 4)
(setq web-mode-markup-indent-offset 4)
(setq web-mode-css-indent-offset 4)
```

**The Results**

In `web-mode` *after newline* (**Enter**):

![web-mode after new line](http://i.imgur.com/KZT3GHx.png)

# Side by side

These two images show the results of adding in a new line in `javascript-mode` and `web-mode` (in that order)

![javascirpt-mode after new line](http://i.imgur.com/TESsFXc.png)
![web-mode after new line](http://i.imgur.com/KZT3GHx.png)

# `web-mode-debug` information

This output was generated while using the second `.emacs` configuration file above.

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("11.0.19")
vars: engine("none") content-type("javascript") file("/Users/baz/tmp/foo.js")
system: window(ns) config("x86_64-apple-darwin13.4.0")
colors: fg(nil) bg(nil) 
minor modes: (global-whitespace-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
@trevorsenior should be better with last commit

**Comment by trevorsenior** [comment]
@fxbois much better, thanks for the update.
