### ISSUE TITLE
(set-web-mode-content-type "jsx") in web-mode hook doesn't do anything

### ISSUE THREAD

**Issue by neverov** [fxbois/web-mode#452]
I'm trying to enable jsx support by default for all js files.
I took [this](https://github.com/gaearon/react-hot-boilerplate) example with jsx embedded into .js files and wrote the following hook:
```elisp
(add-hook 'web-mode-hook
          (lambda ()
            (web-mode-set-content-type "jsx")
            (message "now set to: %s" web-mode-content-type)))
``` 
When I open a file, web mode is enabled, but jsx is not highlighted.

**Comment by neverov** [comment]
My bad. Restarted emacs and now everything is working as it supposed to.

**Comment by fxbois** [comment]
@neverov have just restarted or "updated and restarted" ?

**Comment by neverov** [comment]
Well, the first time I wrote this piece, executed it in place (in init.el) and reopened buffers (no effect), then just restarted emacs and it worked; I don't know emacs internals well enough to determine if there is an actual problem or it's just my setup or something else.

**Comment by mrcoles** [comment]
FWIW, if anyone else is not seeing the change, I had to remove an old .elc file before the change would be read.
