### ISSUE TITLE
Web mode with laravel 5

### ISSUE THREAD

**Issue by p1mps** [fxbois/web-mode#453]
Hello,
with Laravel 5 I can't indent correctly the blade files. I think it's because the new escaping data method: 

Hello, {!! $name !!}. 

Anothter example:

@section('box-content')

    <h4>Item </h4>
{!!Form::open( ['route' => ['menu.store'] , 'id' => 'form'])!!}
    
The Form::open tag starts at the beginning of the file.

I lost also the syntax highlighting :\

**Comment by fxbois** [comment]
@p1mps please test the last version on github

**Comment by p1mps** [comment]
I've installed it with melpa, is it the last version? If it's not I will try with the last version and I will tell you if it works :).

**Comment by fxbois** [comment]
@p1mps the last version is 11.0.23

**Comment by p1mps** [comment]
Ok, it works also with the melpa package :)
