### ISSUE TITLE
auto-commenting in jsx mode broken

### ISSUE THREAD

**Issue by faassen** [fxbois/web-mode#456]
In the version 20150221 auto-commenting using M-; works as expected. In the version 20150315 this appears broken. Instead I get the error "Symbol's function definition is void: nil", or, in some cases, the HTML comment (`<!--`) instead of the expected JavaScript comment.

**Comment by fxbois** [comment]
@faassen could you post a complete scenario to trigger the bug please

**Comment by faassen** [comment]
Okay, create a file: foo.jsx. Add a line ```var a = 1;```. Then M-; that line. I get:

```
<!-- var a = 1; -->
```

I expect:

```
/* var a = 1 */
```

I just noticed that this bug exists in the older 20150221 version too.

But if you create a file with

```
function a() {
    var a = 1;
}
```

and now try to comment out `var a = 1` I get the expected behavior in the older version, but the error message (and nothing happening) in the newer version.

**Comment by faassen** [comment]
Also possibly relevant: I'm trying this on different computers with different versions of Fedora, and different Emacs versions: the older version of web-mode is on Emacs 24.4 (thus a newer emacs), while the newer version with the problem is on the older Emacs 24.3.

**Comment by fxbois** [comment]
@faassen thx I'll look to it tonight

**Comment by fxbois** [comment]
@faassen I've pushed a fix

**Comment by fxbois** [comment]
@faassen please reopen if needed

**Comment by faassen** [comment]
Sorry, I hadn't had time yet to try this out - without a release it's a bit cumbersome to test. Thanks for looking into it!

**Comment by faassen** [comment]
I noticed there was a new release on elpa: it appears to work now. Thank you very much!
