### ISSUE TITLE
"Col" not recognized in JSX mode

### ISSUE THREAD

**Issue by faassen** [fxbois/web-mode#457]
I get weird behavior for both autoclosing and indentation when I try to use the `<Col>` tag in JSX mode. When auto-closing it instead closes the outer tag for me, so:

```
<Row>
    <Col>
    </Row> // expected Col
</Row>
```

and `</Col>` does not get indented with auto-indenting either.

It does work for 'Co' and 'Colu', so there is something special going on with 'Col'.

**Comment by fxbois** [comment]
@faassen in the specs, http://www.w3.org/TR/html5/syntax.html#void-elements, ```<col>``` is a self closing tag. I would prefer to keep it this way

**Comment by faassen** [comment]
Ah, I hadn't realized it was also in the HTML spec. The confusion arises as I was using Col as something else entirely in JSX, where it can have content. I can work around it by just naming it something else.
