### ISSUE TITLE
Indent after multiline dust element broken

### ISSUE THREAD

**Issue by garthgoodson** [fxbois/web-mode#458]
If I have a dust element like: {@helper param="hello" /} split across multiple lines, the subsequent line is indented as if the element was not closed properly.  If there are no line breaks the indentation is fine.

E.g. I get:
{@helper param="hello"
  /}  
  
<!-- end tag should start here>

**Comment by fxbois** [comment]
@garthgoodson I've pushed a fix

**Comment by garthgoodson** [comment]
Thanks for the fast response!

Found one other issue.  The following does not indent appropriately:

{?.isInput}
<input ... />
{/.isInput}

I believe the '.' after the ? is causing an issue.  If I omit the '.' it works.

**Comment by fxbois** [comment]
@garthgoodson I've committed a new fix
