### ISSUE TITLE
SGML-tags broken in web mode. 

### ISSUE THREAD

**Issue by ReneFroger** [fxbois/web-mode#460]
Hi there! Thanks for mainataining this nice mode. 

I have an issue, but I don't know where I could debug it. Even without Emacs configuration, this issue persists in web-mode. For example, In HTML mode somewhere between the `<form>/<div>/<table>/you name it` tags, you could do a `M-x sgml-close-tag`, and the tags will be closed. But when you switch to web-mode, and do again `M-x sgml-close-tag`, then there is an error: 

    Wrong type argument: pstring, nil

When I google around, I found no any related problem to this. The error is unknown yet. So I was wondering in which way I could enable the SGML-tags that works in HTML mode, for web-mode? 

Thanks in advance for your reply!

**Comment by fxbois** [comment]
@ReneFroger Sorry but I do not understand your question. In web-mode, you can't call ```sgml-close-tag``` which is not a function of web-mode
Perhaps it would be better to ask emacs stackoverflow

**Comment by ReneFroger** [comment]
@fxbois 

Thanks for your reply. On the video, starting on 1:22 you see why sgml-tags could be useful: 

https://www.youtube.com/watch?v=sBhQ2NIcrLQ&t=82

Didn't knew they're included in the HTML-package, instead a default function of Emacs itself. Then maybe I could trying to find a way to include sgml-features in web-mode, like HTML-features are included in web-mode too.

**Comment by fxbois** [comment]
Many features are implemented in web-mode ... please http://web-mode.org

If you wan't to close an element : ```C-c C-e /```

**Comment by ReneFroger** [comment]
Sorry for my reporting then! When I tried `sgml-close-tag`, I initially thought it was another package. So I was wondering why it didn't worked in Web mode, because I could see it in the list of commands. 

My bad. If I might ask another question. You see in the linked clip, that `sgml-close-tag` will automatically indent. In web-mode you get only that when pressing enter, then it will indent automatically. 
 
I tried to emulate the same behaviour to bind the command my-close-tag-indent to `C-c C-e /'

    (defun my-webmode-sluit-tag-en-enter ()
       ;; Sluiten van tags en daarna enter naar volgende
      (interactive)
      (web-mode-element-close)
      (newline)
     )

But it will not indent, but starts on the first position of the new line, instead indent. Any suggestion?

**Comment by fxbois** [comment]
@ReneFroger perhaps you do not have the last version. Indentation should be done as soon as the autoclosing is done

**Comment by ReneFroger** [comment]
I have the last version. I assume the version from 2 days ago, when I updated all my packages in MELPA. When I do `C-x C-e /`, I see no indentation:


![not indentation](https://cloud.githubusercontent.com/assets/5211845/6739697/b2a49110-ce7a-11e4-8edc-6919bc228a63.gif)

But when I do `sgml-close-tag` in HTML mode, he will automatically Enter and indent it. How could I debug this?

**Comment by fxbois** [comment]
have you enabled ```web-mode-enable-auto-closing``` ? auto-closing and indentation should be done as soon as you hit ```</```

**Comment by ReneFroger** [comment]
There is no existing command of `web-mode-enable-auto-closing` in the `M-x`. But I will find out the culprit, and let you know.

**Comment by ReneFroger** [comment]
Just tested it in Emacs 25, with empty configuration. Only webmode. 

After opening the HTML file, I activate web-mode and then I do `C-x C-e /`. 

I get the tags, but I see no indentation at all. It's the same as in the gif that I posted earlier above. 

How could I get any indentation on this?

**Comment by fxbois** [comment]
Indentation is done on </

**Comment by ReneFroger** [comment]
`</` gives me the same behaviour as  `C-x C-e /`, without any indentation. 

You want a video of it?

**Comment by fxbois** [comment]
Yes post a video of it. 
Moreover could you post the output of web-mode-debug please

**Comment by ReneFroger** [comment]
The video is the same as the video above, but without my colors customization (empty Emacs configuration). 

`</` gives me the same behaviour as  `C-x C-e /`, without any indentation. This is the output of web-mode-debug:

```
File mode specification error: (void-variable web-mode-html-offset)
highlight-indentation-mode: Symbol's value as variable is void: web-mode-html-offset
 [2 times]
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("11.0.27")
vars: engine("none") content-type("html") file("c:/Dropbox/Dev/texaco2/templates/html/#artikeldb.detail.html")
system: window(w32) config("x86_64-w64-mingw32")
colors: fg(nil) bg(nil) 
minor modes: (yas-minor-mode yas-global-mode electric-pair-mode savehist-mode helm-match-plugin-mode shell-dirtrack-mode helm-mode company-mode global-company-mode evil-local-mode undo-tree-mode global-undo-tree-mode evil-mode evil-matchit-mode global-evil-matchit-mode show-paren-mode btc-ticker-mode smooth-scroll-mode highlight-indentation-mode golden-ratio-mode evil-leader-mode display-time-mode flycheck-mode global-flycheck-mode rainbow-delimiters-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```
