### ISSUE TITLE
File mode specification error: (void-variable web-mode-html-offset) issue with Highlight Indentation in ERB templates

### ISSUE THREAD

**Issue by localredhead** [fxbois/web-mode#463]
Hello,

I have Highlight indentation mode hooked up and enabled for Web mode, and when I open an ERB template I can see that the mode is turned on and the following error is displayed ```File mode specification error: (void-variable web-mode-html-offset)```

When this is the case there is no indentation guides on the screen - so I then tried to toggle highlight indentation mode.  I was then notified that I had just turned the mode ```off```.

After this I re-issued the command to toggle highlight indentation mode - and this time it worked and the indentation guides are showing.

Web mode is the only mode that displays this behavior that I have noticed but it is very annoying.  I jump in and out of many file types (JS, ERB, HAML, JSX, SLIM) - only when Web mode is the governing mode for the file do I see this behavior.

**Comment by localredhead** [comment]
I have no idea if this is an issue within Web mode but I would like to resolve the ```File mode specification error: (void-variable web-mode-html-offset)``` issue - any insight you can give me would be most appreciated.

**Comment by localredhead** [comment]
Interestingly my lines are being truncated in an ERB template with Web mode as the major mode.  I everything configured to not wrap - so Web mode isn't respecting this.  

I'm not sure if they are related issues or not but I arrived here trying to figure out why I could not get highlight indents to work.  It just so happens that I have a hook on highlight-indentation-mode to toggle-truncate-lines so that the line should never wrap if I am using highlight-indendtation-mode

**Comment by fxbois** [comment]
@localredhead I do not have any idea about this. You should ask on emacs stackoverflow.

**Comment by localredhead** [comment]
Can you give me some context around ```web-mode-html-offset```   ??  From what I can tell this used to be part of web-mode and it is no longer.  

Can you comment?  It would at least give me some context for where to look.

**Comment by localredhead** [comment]
Hey found the issue inside Highlight-indentation - it was referencing an old function ```web-mode-html-offset```

Some insight into when this got removed would have *at least* been helpful at a minimum.  Thanks though.

**Comment by localredhead** [comment]
https://github.com/antonj/Highlight-Indentation-for-Emacs/pull/27

**Comment by fxbois** [comment]
@localredhead Glad you found the issue
