### ISSUE TITLE
disable hs-minor-mode in web-mode

### ISSUE THREAD

**Issue by zwb-ict** [fxbois/web-mode#464]
I use Prelude, in my personal.el, I wrote 
(add-hook 'prog-mode-hook #'hs-minor-mode)
(add-hook 'web-mode-hook (lambda () (hs-minor-mode -1))) 
but when I open a *.html file, in mini buffer, show an error information: "File mode specification error: (error "Web Mode doesn't support Hideshow Minor Mode")". I don't know why! Need your help, thank you.

**Comment by fxbois** [comment]
@zwb-ict you should ask to the prelude moderator. I can provide help if needed

**Comment by zwb-ict** [comment]
@fxbois Thank you, I send this iuuse to prelude moderator just now, When I get reliable information，I'll 
 feedback.

**Comment by zwb-ict** [comment]
@fxbois I got the solution, I tried (add-hook 'prog-mode-hook (lambda () (unless (eq major-mode 'web-mode) (hs-minor-mode)))), and it works. So I will close this issue. Sorry to bother you！

**Comment by fxbois** [comment]
@zwb-ict if web-mode is not compatible with hs-minor-mode, can your patch be added to prelude ?

**Comment by zwb-ict** [comment]
It may be not, prelude, in default, isn't enable hs-minor-mode for any prog-mode, I add this in my own personal.el.
