### ISSUE TITLE
Closing a block with point immediately after

### ISSUE THREAD

**Issue by simenheg** [fxbois/web-mode#465]
Hi. Calling `web-mode-block-close` with point immediately after a block doesn't insert a closing block. For instance, consider the following example, using the `django` engine:

```python
{% if foo %}
```

Calling `web-mode-block-close` with point right after the closing `}` does nothing. When there is at least one character between point and the opening block, it works as expected.

**Comment by fxbois** [comment]
@simenheg should be better with last commit

**Comment by simenheg** [comment]
Wow, that was quick!

Seems to work now, thanks. :)
