### ISSUE TITLE
Wrong syntax highlighting in blocks

### ISSUE THREAD

**Issue by simenheg** [fxbois/web-mode#466]
Consider the following block, here using the `django` engine:

```
{% if foo.block.bar %}
  Content
{% endif %}
```

`if` and `endif` is correctly highlighted with `web-mode-keyword-face`. `foo` and `bar` is correctly highlighted with `web-mode-variable-name-face`, but `block` is highlighted with `web-mode-keyword-face`, even though it's part of the variable name.

This happens for other keywords as well, when they are used as part of the variable name.

**Comment by fxbois** [comment]
@simenheg I hope the last commit won't trigger nasty side effects

**Comment by simenheg** [comment]
Thanks! The commit fixes the case if the variable name consists of several parts tied together with `.`.

The issue still remains if the variable is called the exact same as a keyword, as in:

```python
{% if block %}
  Content
{% endif %}
```

Now `block` gets highlighted by `web-mode-keyword-face`.

**Comment by fxbois** [comment]
@simenheg please provide me two lists : 
1/ tags 
2/ keywords

**Comment by simenheg** [comment]
What do you mean? Web-mode already has `web-mode-django-control-blocks` and `web-mode-django-keywords`, which seem to be fairly complete.

What I mean is that `block` is highlighted as a keyword in the above example, even though it is used in a variable position.

**Comment by fxbois** [comment]
@simenheg I've cleaned a lot of things to better respect keywords and control blocks

**Comment by simenheg** [comment]
Thank you, @fxbois! That seems to work. :)
