### ISSUE TITLE
Visiting an php file goes to html-mode or to fundamental-mode

### ISSUE THREAD

**Issue by downwater** [fxbois/web-mode#467]
Hi,

Not sure if it's a duplicate (looks a bit like #437)...

It seems like if a php file is empty or doesn't begin with `<html` string (`>` not required), it goes with fundamental mode. Otherwise it launches html-mode.

Here's my .emacs:

```lisp
(add-to-list 'load-path "~/.emacs.d/lisp/")

(require 'web-mode)
(require 'json-mode)

(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.css\\'" . web-mode))


(column-number-mode)
(put 'downcase-region 'disabled nil)
```
Sounds like I missed something to set up in order to get web-mode running when visiting a php file... By the way, calling explicitly `M-x web-mode` works.

Anyway, thanks for your work, really handy.

Regards,

D

**Comment by fxbois** [comment]
@downwater please post the output of ```web-mode-debug```
what version of emacs are you using ?

**Comment by fxbois** [comment]
moreover does adding ```(add-to-list 'auto-mode-alist '("\\.php\\'" . web-mode))``` change anything ?

**Comment by downwater** [comment]
@fxbois This is GNU Emacs 24.3.1 (x86_64-slackware-linux-gnu, GTK+ Version 2.24.17)

Here is the debug output for : running Emacs + open a php file which goes to fundamental mode or html-mode:
```
For information about GNU Emacs and the GNU system, type C-h C-a.
 [2 times]
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.3) web-mode("11.0.27")
vars: engine(nil) content-type("") file("*GNU Emacs*")
system: window(x) config("x86_64-slackware-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (buffer-read-only)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---
```

**Comment by downwater** [comment]
Thanks ! `(add-to-list 'auto-mode-alist '("\\.php\\'" . web-mode))` works !

**Comment by fxbois** [comment]
@downwater it does not seem obvious to you ??

**Comment by downwater** [comment]
Nope.

I believed that `(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))` was fine... As you tell it on your website...
