### ISSUE TITLE
settings question

### ISSUE THREAD

**Issue by koodawg** [fxbois/web-mode#468]
I'm modifying these 8 settings inside web-mode.el, I have to make the mods everytime I get the latest version. Is there anyway I can make these changes in my .emacs and not have to modify web-mode.el everything? Thanks

<pre>
$ diff web-mode.el web-mode.el.latest
48c48
< (defcustom web-mode-script-padding 4
---
> (defcustom web-mode-script-padding 1
53c53
< (defcustom web-mode-style-padding 4
---
> (defcustom web-mode-style-padding 1
58c58
< (defcustom web-mode-block-padding 4
---
> (defcustom web-mode-block-padding 0
69c69
<   (if (and (boundp 'standard-indent) standard-indent) standard-indent 4)
---
>   (if (and (boundp 'standard-indent) standard-indent) standard-indent 2)
75c75
<   (if (and (boundp 'standard-indent) standard-indent) standard-indent 4)
---
>   (if (and (boundp 'standard-indent) standard-indent) standard-indent 2)
81c81
<   (if (and (boundp 'standard-indent) standard-indent) standard-indent 4)
---
>   (if (and (boundp 'standard-indent) standard-indent) standard-indent 2)

</pre>

**Comment by fxbois** [comment]
@koodawg  ???? why don't you set those vars in your .emacs ?

**Comment by koodawg** [comment]
I tried and it didn't work. How should I set them in .emacs?

**Comment by fxbois** [comment]
have you tried inside a hook ?

**Comment by koodawg** [comment]
I dont know elisp. Can you show me?

**Comment by fxbois** [comment]
please read web-mode.org

**Comment by koodawg** [comment]
Ok I think I got it. Thanks!
