### ISSUE TITLE
emacs crashes on clone-indirect-buffer-other-window command 

### ISSUE THREAD

**Issue by omidnoorani** [fxbois/web-mode#470]
After upgrading web-mode from Version: 8.0.9 to Version: 11.0.19, *clone-indirect-buffer-other-window* command causes the emacs to crash. I am running emacs-23.1 on CentOS 6.6. web-mode is the only emacs plug-in. No fancy emacs configuration. I have been able to reproduce this with different files types. Downgrading back to the 8.0.9 version solves this problem. Please let me know how I can help with troubleshooting this.

**Comment by fxbois** [comment]
@omidnoorani could you describe the scenario where you use clone-indirect-buffer-other-window

**Comment by omidnoorani** [comment]
@fxbois 

By cloning the buffer, I can narrow to two different regions in the same buffer. I use the default key binding <kbd>C-x 4 c</kbd> to invoke clone-indirect-buffer-other-window. Pressing this key combo in the web-mode crashes Emacs. If I switch to a different mode, then pressing the same key combination works as expected. This is regardless file type/content that's open in the buffer. As noted above this started happening only after I upgraded from 8.0.9 to 11.0.19. I am now back to the older version which works fine. 

Narrowing: https://www.gnu.org/software/emacs/manual/html_node/emacs/Narrowing.html

**Comment by fxbois** [comment]
@omidnoorani I've just tried on a php template and haven't triggered a crash ... please try with an empty .emacs

**Comment by fxbois** [comment]
@omidnoorani please reopen when needed
