### ISSUE TITLE
JSTL tags ignored when auto-closing tag

### ISSUE THREAD

**Issue by Archenoth** [fxbois/web-mode#471]
When you have a JSTL tag like `<c:if>`, `<c:choose>`, or friends in a buffer... When you attempt to close the tag, web-mode automatically closes the parent tag to it and ignores the JSTL tag.

So, consider the following:
![screenshot from 2015-03-26 11 17 41](https://cloud.githubusercontent.com/assets/1385527/6852352/d52e7d52-d3a9-11e4-858c-91c23c33fa61.png)

When I start typing "`</`", web-mode automatically closes the `<div>` tag...
![screenshot from 2015-03-26 11 17 45](https://cloud.githubusercontent.com/assets/1385527/6852353/d53227b8-d3a9-11e4-8bcc-c9883a467b67.png)

But if I try it again, instead of closing the `<c:if>` tag with `</c:if>`, it skips it and goes right to closing the tag above it:
![screenshot from 2015-03-26 11 17 50](https://cloud.githubusercontent.com/assets/1385527/6852354/d539b7c6-d3a9-11e4-9984-e5a40ffd0f38.png)

**Comment by fxbois** [comment]
@Archenoth you should use ```web-mode-block-close``` 
I've rebinded it to ```^ /```

**Comment by Archenoth** [comment]
Oh hey! `web-mode-block-close` has the correct behavior. Thanks..!
(I wonder what the difference is between that and typing `</`)

I guess that makes this bug invalid then..? No sense having this open if its desired behavior.
