### ISSUE TITLE
Question on React and React jsx tags

### ISSUE THREAD

**Issue by danielbush** [fxbois/web-mode#472]
First off, I'm glad web-mode is around as it does a good job of handling React jsx tags within js - so thanks for maintaining this.

1) If I open a .jsx file and do `M-x web-mode` it works really well.  Is web-mode actually in some sort of "react jsx" mode or is it doing something else that just happens to work?
2) If I open a .js file that has jsx tags in it (which because of the way I'm doing things would be handy) can I get web-mode to handle this file like a react jsx file just like in 1) ?  At the moment, it looks to handle it like js only when I switch to web-mode `M-x web-mode`. 

[Not to confuse React jsx with "jsx" the statically typed language which is another thing altogether - which I think is what `jsx-mode` is doing - though it's not clear from the jsx-mode github page]

Regards,
Daniel

**Comment by asok** [comment]
> 2) If I open a .js file that has jsx tags in it (which because of the way I'm doing things would be handy) can I get web-mode to handle this file like a react jsx file just like in in 1) ?

You can set `web-mode-content-types-alist` variable to jave js files treated as jsx. I have created `.dir-locals.el` file in the dir where I have React's files with such content:
```elisp
((nil . ((eval . (setq web-mode-content-types-alist `(("jsx" . ,(concat default-directory ".*\\.js"))))))))
```

**Comment by fxbois** [comment]
@danielbush is this issue resolved ?

**Comment by danielbush** [comment]
Hi, thanks Asok, I think I can work with that.
Wasn't familiar with dir-locals and struggling a bit with the eval in a cons cell in that example.  So what this is doing is treating my js files as "jsx" in web-mode for that directory I think right? -- which is great.

Cheers guys.  I'll close.
Regards,
Daniel

**Comment by fxbois** [comment]
@danielbush I'll invest a lot of time in the next few weeks/months to bring better jsx compatibility into web-mode. I'll perhaps takle the above issue an other way. But thanks you @asok to bring a solution in the meantime

**Comment by asok** [comment]
@danielbush answering your question - yes it does.
