### ISSUE TITLE
How do I disable the commenting feature

### ISSUE THREAD

**Issue by angrybakon** [fxbois/web-mode#474]
Not really an issue : )

In web-mode, `M-;` replaces the default commenting, but I prefer having opening and closing tags for each line. How do I reassign `M-;` to the default commenting function ?

**Comment by fxbois** [comment]
Please post an example on gist

**Comment by angrybakon** [comment]
html-mode:

```html
<!-- <li>foo</li> -->
<!-- <li>foo</li> -->
```

web-mode:

```html
<!-- <li>foo</li>
<li>foo</li> -->
```

**Comment by fxbois** [comment]
@angrybakon in this case what behavior do you wan't 
```html
<div>
  aaa
  bbb <span>ccc</span></div>
```

**Comment by angrybakon** [comment]
Let's say I have tthe following code:

```html
<li>foo</li>
<li>foo</li>
```

If I select the two lines and comment with `M-;`, in html-mode, I'll get:

```html
<!-- <li>foo</li> -->
<!-- <li>foo</li> -->
```

However, in web-mode:

```html
<!-- <li>foo</li>
<li>foo</li> -->
```

So what I would like is the html-mode's behavior.

**Comment by fxbois** [comment]
?????

**Comment by angrybakon** [comment]
I read too fast, am not really awake :p. I've edited the message but left some lines, sorry.

**Comment by angrybakon** [comment]
Other issues regarding comments that I just noticed (`|` is cursor):

### Using newcomment.el

#### First case:

```html
<div>
|
    <p>Some HTML</p>
</div>
```
```html
<div>
    <!-- | -->
    <p>Some HTML</p>
</div>
```

#### Second case:

```html
<p>So|me HTML</p>
```
```html
<p>Some HTML</p>  <!-- | -->
```

Whereas web-mode.el as a different behavior.

### Using web-mode.el

#### First case A:

```html
<div>
|
    <p>Some HTML</p>
</div>
```
```none
web-mode-comment: Search failed: " -->"
```

#### First case B:
```html
<div>
    |
    <p>Some HTML</p>
</div>
```
```html
<div>
    |<!--      -->
    <p>Some HTML</p>
</div>
```


#### Second case A:

```html
<p>So|me HTML</p>
```
```html
<!-- |<p>Some HTML</p> -->
```

#### Second case B:

```html
<p>Some HTML</p>|
```
```html
<!-- |<p>Some HTM|L</p> -->
```

With newcomment.el and webmode.el being 2 different packages, I get that one shouldn't necessarily copy the other's behavior. The way newcomment.el works is that when you want to comment things, you should have an active region or it will simply create an inline comment.

- I can't always add an inline comment at the end of the line
  - With cursor at the beginning of an empty line, I'll get first case A
  - With cursor anywhere on the line (even right before new line character), the first parent element will be commented
- After adding an inline comment, cursor should be placed whithin comment brackets
- Each line should be individually commented, this makes partially uncommenting easier

Thanks : )

**Comment by skyer9** [comment]
<code>
(defun web-mode-comment-dwim ()
  "`comment-dwim' for `web-mode'."
  (interactive)
  (let (ctx language)
    (setq ctx (web-mode-point-context (if mark-active (region-beginning) (line-beginning-position))))
    (setq language (plist-get ctx :language))
    (cond
     ((member language '("html" "xml"))
      (web-mode-comment-dwim-with-newcomment "" "" nil))
     ((member language '("php" "javascript" "java" "jsx"))
      (web-mode-comment-dwim-with-newcomment "// " "" "//+[ \t]*" "[ \t]*\\(\\s>\\|\n\\)" t))
      ;; (web-mode-comment-dwim-with-newcomment "/* " " */" "/\\*+[ \t]*" "[ \t]*\\(\\s>\\|\\*+/\\)" nil))
     ((member language '("erb"))
      (web-mode-comment-dwim-with-newcomment "# " "" "#+[ \t]*" "[ \t]*\\(\\s>\\|\n\\)" nil))
     ((member language '("asp"))
      (web-mode-comment-dwim-with-newcomment "'' " "" "'+[ \t]*" "[ \t]*\\(\\s>\\|\n\\)" nil))
     (t
      (web-mode-comment-dwim-with-newcomment "/* " " */" "/\\*+[ \t]*" "[ \t]*\\*+/" nil)))))

(defun web-mode-comment-dwim-with-newcomment (wm-comment-start wm-comment-end wm-comment-start-skip wm-comment-end-skip wm-comment-use-syntax)
  (set (make-local-variable 'comment-start) wm-comment-start)
  (set (make-local-variable 'comment-end) wm-comment-end)
  (set (make-local-variable 'comment-start-skip) wm-comment-start-skip)
  (set (make-local-variable 'comment-end-skip) wm-comment-end-skip)
  (set (make-local-variable 'comment-use-syntax) wm-comment-use-syntax)

  (unless mark-active
    (end-of-line)
    (set-mark (line-beginning-position)))

  (comment-dwim nil)

  (setq comment-start nil)
  (setq comment-end nil)
  (setq comment-start-skip nil)
  (setq comment-end-skip nil)
  (setq comment-use-syntax nil))

(add-hook 'web-mode-hook
  '(lambda ()
     (define-key web-mode-map (kbd "C-;") 'web-mode-comment-dwim)))
</code>

**Comment by fxbois** [comment]
@angrybakon with the last pushed version, comment is inserted when you are at the end of a line

**Comment by angrybakon** [comment]
> with the last pushed version, comment is inserted when you are at the end of a line

@fxbois I'm sorry, this wasn't why I opened this issue :(. Although I'm not very familiar with elisp, I tried:

```elisp
(with-eval-after-load 'web-mode
  (setq
   web-mode-markup-indent-offset 2
   web-mode-css-indent-offset 2
   web-mode-code-indent-offset 2)
  (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
  (global-set-key (kbd "M-;") 'comment-dwim))
```

What I want is to use the default commenting function, even in web-mode.

**Comment by fxbois** [comment]
@angrybakon have you tried ```local-set-key``` ? it is a general emacs question ... you should post it on emacs stackoverflow
