### ISSUE TITLE
web-mode-element-close gives no indentation. 

### ISSUE THREAD

**Issue by ReneFroger** [fxbois/web-mode#475]
It was emerging from another issue, but for clarifity it could be better considered as a stand-alone issue.

I use *Emacs 24.4* with Windows 7 x64 bit, with very recent Web-Mode version from MELPA. This is a empty Emacs configuration, without any plugins installed except Web-mode. 

When I'm in HTML-mode, and I use SGML as minor mode, I do ` M-x sgml-close-tag`, then I see that it indents automatically after inserting a closing tag, [as showed in this video, starting on 1:22](https://www.youtube.com/watch?v=sBhQ2NIcrLQ&t=82)

But with Web-mode, this is not working with `C-`c`C-e /`, `</` gives me the same behaviour as  `C-x C-e /`, without any indentation. Both are referring to the command (web-mode-element-close). 

I made a gif about this: 
![web-mode-debug](https://cloud.githubusercontent.com/assets/5211845/6919808/733063ee-d7ba-11e4-8304-525eae98b1df.gif)

This is the output of the Web-mode debug: 

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("11.0.27")
vars: engine("none") content-type("html") file("z:/websites/intranet-development/applicaties/#cas.sav/templates/html/##artikelprofiel.detail.html")
system: window(w32) config("x86_64-w64-mingw32")
colors: fg(nil) bg(nil) 
minor modes: (helm-match-plugin-mode shell-dirtrack-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---
```

The question is: why haven't I any indentation after closing the tag in Web-mode? Any suggestion? 

Thanks in advance.

**Comment by fxbois** [comment]
@ReneFroger do you still have error related to ```web-mode-html-offset``` in your ```*Messages*``` buffer ?

**Comment by ReneFroger** [comment]
>@ReneFroger do you still have error related to web-mode-html-offset in your *Messages* buffer ?
I checked the `*Messages*` buffer again, after trying Web mode with the closing command again (`C-c C-e b`). But there is no any error related with it. 

>Moreover, does it change anything when you add (setq-default indent-tabs-mode nil) in your .emacs ?

I added it to my Dot-Emacs. I evaluated it, no difference. And still no difference in behaviour of indentation when I restart Emacs. When I run web-mode-debug, I see the `indent-tabs-mode=nil` on the last line, as expected.

**Comment by fxbois** [comment]
@ReneFroger have you tried with an empty .emacs ?

**Comment by ReneFroger** [comment]
I said in my opening post the example in the gif is with the empty Emacs configuration (which is the same as empty .emacs)...

**Comment by fxbois** [comment]
Perhaps you said it, but when your web-mode-debug shows many minor modes installed ... so what ?

**Comment by ReneFroger** [comment]
Yes, I had to give a path where the plugins would be loaded. Web-mode was already in that folder, same with other plugins. 
To be sure, I uninstalled Emacs 24.4, downloaded Emacs 24.3 and everything is empty. 
Then I added the Elpa, Orgmode and Melpa package lists. Then I downloaded Web-mode from MELPA, and then the same operation in HTML-file, with `C-x C-e /`, but I get same result too. No indentation at all.

Web-mode debug shows this: 
```
(("gnu" . "http://elpa.gnu.org/packages/") ("org" . "http://orgmode.org/elpa/") ("MELPA" . "http://melpa.milkbox.net/packages/"))
completing-read-default: Command attempted to use minibuffer while in minibuffer
Contacting host: elpa.gnu.org:80
Saving file c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/gnu/archive-contents...
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/gnu/archive-contents
Contacting host: orgmode.org:80
Saving file c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/org/archive-contents...
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/org/archive-contents
Saving file c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/MELPA/archive-contents...
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/MELPA/archive-contents
2 packages can be upgraded; type `U' to mark them for upgrading.
Mark saved where search started [2 times]
Contacting host: melpa.milkbox.net:80
Type C-x 1 to delete the help window.
Install package `web-mode'?  y
Contacting host: melpa.milkbox.net:80
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155/web-mode.el
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155/web-mode-pkg.el
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155/web-mode-autoloads.el
Making version-control local to web-mode-autoloads.el while let-bound!
Generating autoloads for web-mode-pkg.el...done
Generating autoloads for web-mode.el...done
Saving file c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155/web-mode-autoloads.el...
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155/web-mode-autoloads.el
(No changes need to be saved)
(No files need saving)
Checking c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155... [2 times]
Compiling c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155/web-mode-pkg.el...done
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155/web-mode-pkg.elc
Checking c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155...
Compiling c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155/web-mode.el...done
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155/web-mode.elc
Checking c:/Users/junza/AppData/Roaming/.emacs.d/elpa/web-mode-20150402.1155...
Done (Total of 2 files compiled, 1 skipped)
Contacting host: melpa.milkbox.net:80

Contacting host: elpa.gnu.org:80
Saving file c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/gnu/archive-contents...
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/gnu/archive-contents
Contacting host: orgmode.org:80
Saving file c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/org/archive-contents...
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/org/archive-contents
Saving file c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/MELPA/archive-contents...
Wrote c:/Users/junza/AppData/Roaming/.emacs.d/elpa/archives/MELPA/archive-contents
2 packages can be upgraded; type `U' to mark them for upgrading.
Quit
Mark saved where search started
byte-code: End of buffer
 [2 times]
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.3) web-mode("11.0.31")
vars: engine("none") content-type("html") file("c:/Users/junza/Desktop/artikelen.html")
system: window(w32) config("i386-mingw-nt6.1.7601")
colors: fg(nil) bg(nil) 
minor modes: nil
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---
```

Any suggestion?

**Comment by fxbois** [comment]
@ReneFroger as we are trying to debug your issue why do you install other stuff like org-mode ? Could you have a .emacs with only web-mode ?
If it does not change anything, add before ```(indent-according-to-mode)``` (line 8703) a debug command like ```(message "indentation triggered")``` and tell me if something appears in Messages

**Comment by ReneFroger** [comment]
I evaluated the package-list, in order to get Web-mode. The relevant line: 
```
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("org" . "http://orgmode.org/elpa/")
                         ("MELPA" . "http://melpa.milkbox.net/packages/")
                         ))
```

So Org-mode was accidentally included in the package-archives, but I thought it couldn't have any effect on the web-mode, when I download it from MELPA. 

I opened elpa/web-mode-20150317.1506/web-mode.el

However, `(indent-according-to-mode)` was not on the line 8703. But on line 8693. 
After adding it, saved and restarting Emacs, I did `C-x C-e /` in Web-mode on HTML file. I got the closed tag, but no indentation. 

After this, I checked the `*Messages*` buffer, I see no "Indentation triggered"  mentioned.

**Comment by fxbois** [comment]
@ReneFroger could you add ```(setq web-mode-enable-auto-indentation t)``` in your .emacs

**Comment by ReneFroger** [comment]
It is not working. However, when watching the `*Messages*` buffer, I noticed a warning: 

`File mode specification error: (void-variable web-mode-html-offset)`.

Is this any useful for you?

**Comment by fxbois** [comment]
I asked you if you still saw this and you told me no.
If you grep web-mode.el, you will see that there is no web-mode-html-offset anywhere.
So you have an issue on your side ... a minor mode triggers this.
I can't help you any further

**Comment by ReneFroger** [comment]
Not the helpful reply that I was hoping for, but thanks anyway.

**Comment by fxbois** [comment]
Are you just joking ?? I have never spent so such time on an issue and the fact that you write about web-mode-html-offset means that you are not able to give me the information that could make me help you.

The last time I heard about this var was there
https://github.com/fxbois/web-mode/issues/463#issuecomment-84215568
