### ISSUE TITLE
Problem with closing-string for Django block tag

### ISSUE THREAD

**Issue by shizhz** [fxbois/web-mode#478]
Hi,

When I insert a "{", a "}" will added automatically, but when I'm typing a "{%", there'll be a closing-string "%}" added, which makes "}" inserted twice.  Could anybody tell me how to resolve this problem?

Big thanks.

**Comment by fxbois** [comment]
@shizhz it is because you use an other autopairing minor mode. You'll have to choose between web-mode autopairing and the other
