### ISSUE TITLE
code folding for php and js

### ISSUE THREAD

**Issue by xikky** [fxbois/web-mode#479]
I would like to have a command for code folding for PHP and JS. C-c C-f does work fine in HTML blocks but not in other languages. Previously I used to use hs-toggle-hiding, but unfortunately Web Mode does not support HideShow Minor Mode. Any way to achieve this?

Thank you!

**Comment by fxbois** [comment]
@xikky could ask the hs-toggle-hiding why his minor mode does not work with web-mode
I do not intend to add other folding features in web-mode

**Comment by xikky** [comment]
If I'm not mistaken this is a built-in command. I think people who have a habit of hiding code would love to have Hide Show minor mode supported with Web Mode. But well I don't know anything about how these modes are created and have little idea of how much work needed for this. In any case Thank you for making such a great mode!!

**Comment by fxbois** [comment]
I'll try to look at Hide Show when I have a little time

**Comment by fxbois** [comment]
@xikky the last commit on master tries to bring some compatibility

**Comment by fxbois** [comment]
@xikky reopen if needed
