### ISSUE TITLE
font-lock error. "out-of-range"

### ISSUE THREAD

**Issue by sunilw** [fxbois/web-mode#480]
I updated web-mode (among other libraries) and restarted emacs.

I opened this php template: https://gist.github.com/anonymous/00ba0d9eacfbb26379ce

The template was in a single colour (unexpected) and I saw this message in the minibuffer:  Args out of range: 4028, 4029

I closed emacs and then restarted with 'emacs -q'. Then I opened the file again. I got the same error.

**Comment by fxbois** [comment]
@sunilw should be fixed with last commit

**Comment by fxbois** [comment]
reopen if needed
