### ISSUE TITLE
Wrong cursor move when it is located after multibyte characters (e.g. East Asian characters)

### ISSUE THREAD

**Issue by kissge** [fxbois/web-mode#481]
![web-mode-bug-report](https://cloud.githubusercontent.com/assets/4177010/7017534/bb2b8f06-dd33-11e4-9fa9-e00c450fe281.gif)
See this video.
Every time the Tab key is hit, the position of the cursor changes.
This is due to a wrong calculation of the current column in `web-mode-indent-line`.

**Comment by fxbois** [comment]
@kissge please post your example on gist please

**Comment by kissge** [comment]
@fxbois
Check this: https://gist.github.com/kissge/1b3778abb29bc407e1bb .
I also tried `emacs -Q` (and loaded only web-mode.el), but the same problem occurred.

**Comment by fxbois** [comment]
@kissge thx for your patch. Do not hesitate to report other issues with multibyte chars

**Comment by kissge** [comment]
@fxbois Thanks for merging!
