### ISSUE TITLE
Syntax highlighting breaks with named Mason blocks

### ISSUE THREAD

**Issue by dustinpaluch** [fxbois/web-mode#484]
Syntax highlighting for Mason augment blocks works correctly if the blocks are empty, but break once they contain HTML; destroying a named block tag that contains HTML correctly disables the syntax highlighting, but **restoring the tag does not reactivate the syntax highlighting,** until web-mode is reloaded. 

Here's a demo of the bug:
http://cl.ly/af4Z

Here's the documentation for Mason augment blocks:
[http://search.cpan.org/%7Ejswartz/Mason-2.22/lib/Mason/Manual/Syntax.pod#<%augment_name>](http://search.cpan.org/%7Ejswartz/Mason-2.22/lib/Mason/Manual/Syntax.pod#\<%augment_name\>)
(click on augment name in the table of contents. I guess you can't link urls with angle brackets with github markdown.)

**Comment by fxbois** [comment]
@dustinpaluch could you post the output of web-mode-debug please.
Moreover, please post your example on gist.

**Comment by dustinpaluch** [comment]
Here's a gist of the example code:
https://gist.github.com/dustinpaluch/0c5a72690a4b21dcc5d0

And here's my web-mode-debug.
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("11.0.31")
vars: engine("mason") content-type("html") file("/Users/Dustin/Desktop/testing.mc")
system: window(ns) config("x86_64-apple-darwin13.4.0")
colors: fg(nil) bg(nil) 
minor modes: (visual-line-mode global-visual-line-mode ido-everywhere auto-complete-mode global-auto-complete-mode helm-autoresize-mode shell-dirtrack-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@dustinpaluch many fixes have been pushed on master

**Comment by dustinpaluch** [comment]
@fxbois Can I just update via package/elpa to test the changes?

**Comment by fxbois** [comment]
it should be available on melpa

**Comment by dustinpaluch** [comment]
Getting closer. Here are a few things that still cause fontification to malfunction, tested on this chunk of the gist:

    1 <%augment wrap>
    2    <html>
    3        <body>
    4            <% inner() %>
    5        </body>
    6    </html>
    7 </%augment>

* Deleting/replacing the opening `<` or the closing `>` in line 1
* Deleting/replacing any letter in the word `augment` in line 1
* Deleting/replacing the opening `<%` in line 4 
* Deleting/replacing the `u`, `g`, `m`, or `e` in line 7*

\* I tested this one on the other closing tags from the gist, and the behavior is consistent. I'll use these closing tags to explain:
    
    </%augment>
    </%around>
    </%overrride>

#### Works:
* Delete/replace the first, last, or second-to-last alphabetical character. Fontification switches on/off correctly. 

#### Doesn't Work:
* Delete/replace any other alphabetical character. (The `r` in `around`, for example)

**Comment by fxbois** [comment]
@dustinpaluch I've pushed a new fix

**Comment by dustinpaluch** [comment]
@fxbois Nice! Looks like this one:

> Deleting/replacing the opening <% in line 4

is now fixed. Here's an updated list of outstanding bugs: 
(Note that line/character numbers here refer to the original gist I posted)

#### Killing/yanking the opening `<` of the 2nd, 3rd, ... , or nth named *opening* tag breaks fontification
* **To Reproduce**: kill/yank character 1 of line 6, 14, or 20

#### Killing/yanking the opening `<` of any named *closing* tag breaks fontification
* **To Reproduce**:  kill/yank character 1 of line 4, 12, 18, or 23. 

#### Killing/yanking the closing `>` of any named *opening* tag breaks fontification, unless the block only contains whitespace
* **To Reproduce**: kill/yank the last character of line 1, 6, 14, or 20
* also breaks if the block is completely empty i.e. `<%after render></%after>`

#### Killing/yanking the 2nd, 3rd, ... , or nth alphabetical character of a named *opening* tag *type* (that is, not the user defined name)

* **To Reproduce**: kill/yank **any character but the 1st** in the words `after`, `augment`, `around`, or `override` on lines 1, 6, 14, or 20 respectively. 

#### Killing/yanking the 2nd, 3rd, ... , or n-2th alphabetical character of the 1st, 2nd, ... , or n-1th named *closing* tags breaks fontification (1st, n-1th, and nth characters restore fontification correctly when killed/yanked)

* **To Reproduce**: kill/yank the `u` in `around` on line 18, but note that fontification toggles correctly when killing/yanking any of the characters in `override` on the last line (23).

**Comment by dustinpaluch** [comment]
All listed bugs appear to be solved as of MELPA version 20150417.1351. Thanks for the quick turnaround!

**Comment by fxbois** [comment]
I was a little affraid this morning reading your first report. Thx for the report and to let me know that there is at last one people using web-mode for mason

**Comment by dustinpaluch** [comment]
If you build it, they will come.
