### ISSUE TITLE
odd message on js chained method call

### ISSUE THREAD

**Issue by iantor** [fxbois/web-mode#486]
When doing indent entire buffer on html file including following:      
```
   angular.module("sportsStore", ["customFilters", "cart", "ngRoute"])
          .config(function ($routeProvider){
```
I get the following error on the second line (the formatting seems ok though).
config is shown in purple, whereas module is green.

javascript-calls-beginning-position ** failure **

latest version of web-mode (20150416.530), emacs 24.3.1

--- WEB-MODE DEBUG BEG ---
versions: emacs(24.3) web-mode("11.0.31")
vars: engine("ctemplate") content-type("html") file("/home/ian/angularjs/app.html")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (desktop-save-mode shell-dirtrack-mode icomplete-mode display-time-mode erc-readonly-mode erc-move-to-prompt-mode erc-noncommands-mode erc-irccontrols-mode erc-autojoin-mode erc-stamp-mode erc-fill-mode erc-button-mode erc-pcomplete-mode erc-list-mode erc-match-mode erc-menu-mode erc-netsplit-mode erc-networks-mode erc-ring-mode erc-services-mode erc-track-minor-mode erc-track-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@iantor the master branch is now fixed

**Comment by iantor** [comment]
thanks, when I get it from Melpa (tomorrow I guess?) I will verify fix.
