### ISSUE TITLE
Give javascript section another syntax coloring than the rest

### ISSUE THREAD

**Issue by ReneFroger** [fxbois/web-mode#487]
When you see this picture: 

![687474703a2f2f7765622d6d6f64652e6f72672f7765622d6d6f64652e706e673f763d35](https://cloud.githubusercontent.com/assets/5211845/7221126/2a3bc694-e6e0-11e4-9a16-303e63dcdb97.png)

You notice the CSS section does have his own syntax colors (sort of purple/pink). But the  syntax highlighting colors of the javascript section are the same as the rest in HTML/PHP. 

If I might ask, I would like to have optional keywords for javascript section. So I can colorize them with various green syntax highlighting, in order to distinguish them from the rest. :+1:

**Comment by fxbois** [comment]
@ReneFroger I don't understand. The <style> and <script> tags have the same colors

**Comment by ReneFroger** [comment]
To illustrate my question, an example in Vim.

![schermafdruk 2015-04-19 22 36 29](https://cloud.githubusercontent.com/assets/5211845/7221275/90d5fcc2-e6e4-11e4-8c3a-e691c99c0fa6.png)

From my own created syntax highlighting. You see, the javascript section (everything inside <script>) have their own syntax colors, which is different than the rest. 

In web-mode, only CSS-section knows to have own syntax highlighting. But PHP and Javascript shares the same keywords for syntax highlighting.

**Comment by fxbois** [comment]
@ReneFroger with the last version of web-mode.el on github you can customize ```web-mode-script-face``` and ```web-mode-style-face``` if ```web-mode-enable-part-face``` is ```t```

**Comment by ReneFroger** [comment]
Thanks for your reply, fxbois. It's really appreciated. Web-mode is such awesome tool. 

I tried it. And it worked, thanks for the effort! 

![schermafdruk 2015-04-21 22 34 24](https://cloud.githubusercontent.com/assets/5211845/7262026/986eb8b4-e876-11e4-8f75-b43ba026129c.png)

However, it's not my intention to be sounded as spoiled, even when you put awesome work with webmode. But for me it's not clear as in the example with the Vim. 
In the example of Vim, you will notice the variables, keywords and strings inside the script have different green colors. 

With `web-mode-enable-part-face` I'm able to set, for example, green face for Javscript, and darkyellow face for styles. But it's not clear enough as in the example of Vim. 

When I check the documentation of web-mode, I see the syntax is builded as, for example:

   `(web-mode-string-face ((t (here your own colors))))`
   `(web-mode-type-face ((t (here your own colors))))`

Would it be an option to add next to that, for example:

   `(web-mode-script-string-face ((t (here your own colors))))`
   `(web-mode-script-type-face ((t (here your own colors))))`

these colors will be enabled then if `web-mode-enable-part-face` is `t`. If you don't mind. You helped me already a little bit with the solution above. :+1:

**Comment by fxbois** [comment]
@ReneFroger you can also customize ```web-mode-javascript-comment-face``` and ```web-mode-javascript-string-face```

**Comment by ReneFroger** [comment]
Great. You're awesome. 

Thanks. Really.

**Comment by ReneFroger** [comment]
If it might interest you... my syntax highlighting looks now as: 

![schermafdruk 2015-04-22 21 07 18](https://cloud.githubusercontent.com/assets/5211845/7282973/a3d25a18-e933-11e4-9c6f-9220bc6e841d.png)

**Comment by fxbois** [comment]
@ReneFroger nice
Have you solved your indentation problem ?

**Comment by ReneFroger** [comment]
No. It didn't solved my problem. 

I even uninstalled Emacs 24.4 and installed 25.5. And started with a clean config, then I added MELPA only (thus without the org-package list), web-mode was the first package that I installed, and even I didn't get any indentation. 

I gave it up. Seems unsolvable to me, and decided to focus on other things. But thanks for your interest, I like that. :+1:
