### ISSUE TITLE
web-mode-content-types-alist doesn't register when set in .dir-locals.el

### ISSUE THREAD

**Issue by jdivock** [fxbois/web-mode#488]
So I've been fighting this while setting my my environment for react native. I wanted to ensure that index.ios.js would get treated as a jsx file so I'd get the proper indent and syntax highlighting. So I set this guy in my dir-locals.el

```
((nil . ((web-mode-content-types-alist . '(("jsx" . "**/*\\.ios.js\\'"))))))
```

Unfortunately nothing happened.

Setting this in my main javascript config though does cause the files to be set properly

```
(setq web-mode-content-types-alist
      '(("jsx" . "**/*\\.ios.js\\'")))
```

Am I doing something wrong here or is this an issue with web-mode itself? Thanks.

**Comment by fxbois** [comment]
@jdivock what do you mean "my main javascript config" ? Moreover if it works with the second case why is there an issue ? (I've never used dir-locals)

**Comment by jdivock** [comment]
Oh sorry, let me be more specific. When I say my "main js config" i mean my
init.el file that gets loaded when emacs load, the .dir-locals solution
actually doesn't work which is why I logged the issue. Thanks.

**Comment by fxbois** [comment]
please post the related init.el lines in a comment

**Comment by jdivock** [comment]
init.el (works)
```
(setq web-mode-content-types-alist
      '(("jsx" . "**/*\\.ios.js\\'")))
```

.dir-locals.el (doesn't work)
```
((nil . ((web-mode-content-types-alist . '(("jsx" . "**/*\\.ios.js\\'"))))))
```

Thanks.

Just some background, I'm working with the React Native stuff, which for the time being doesn't like being named ".jsx" so I'm getting away with it by just following the naming convention ".ios.js"

**Comment by fxbois** [comment]
@jdivock have you looked at 
https://github.com/fxbois/web-mode/issues/472 ?

**Comment by jdivock** [comment]
Ah thanks, I'll give it a shot when I have a moment and close it out if it
works. Thanks!
