### ISSUE TITLE
buffer-indent doesn't work well if code is folded.

### ISSUE THREAD

**Issue by ChillarAnand** [fxbois/web-mode#489]
i have few pieces of code folded. now when i run buffer indent it is not working.

![web](https://cloud.githubusercontent.com/assets/4463796/7227527/fcf4f996-e76e-11e4-9f97-cb2642964461.png)

**Comment by fxbois** [comment]
@ChillarAnand post your example on gist and specify very accurately a complete scenario to trigger the bug

**Comment by ChillarAnand** [comment]
[this file](https://gist.github.com/ChillarAnand/dcf611057e561fe95dde) is not properly indented.
 
fold the div(id=sidebar) and try to indent the buffer.
 
it wont indent correct elements. instead it is mis indenting div(id=sidebar)

**Comment by fxbois** [comment]
@ChillarAnand perfect report. I'll work on this

**Comment by fxbois** [comment]
@ChillarAnand it is now solved on master

**Comment by ChillarAnand** [comment]
:+1: that's fantastic.

**Comment by ChillarAnand** [comment]
i thinks this is the fastest an issue got solved for me on github
