### ISSUE TITLE
issues with mark-and-expand

### ISSUE THREAD

**Issue by ChillarAnand** [fxbois/web-mode#490]
1.  if user cancels mark-and-expand, point should be returned to original position?

2. when trying to expand in js part, it is not expanding as expected.

[in this file](https://gist.github.com/ChillarAnand/dcf611057e561fe95dde#file-expand-html), if you place point on `#sidebar` & expand it works for the first time. but if you expand again, it should expand to that line? but it is expanding to entire buffer?

**Comment by fxbois** [comment]
@ChillarAnand 
1. what do you mean cancel ? ```C-g```
2. be way more verbose about describing the issue

**Comment by ChillarAnand** [comment]
1. yes `C-g`. In emacs, if i search for something, while cycling through the results, if i press `C-g` it returns to original position. so it is better to have that for expand too.

2.  in this [file](https://gist.github.com/ChillarAnand/dcf611057e561fe95dde#file-expand-html) if cursor is at `#sid|ebar`, for first expand, it should cover entire **word** 

```
"#sidebar"
```
& its working fine.

for the next expand it should cover **statement**

```
$( "#sidebar" ).toggle( "blind", {direction: 'left'} );
```

and for the next expand it should cover function

```
 $( '#filter-data' ).click(function() {
         $( "#sidebar" ).toggle( "blind", {direction: 'left'} );
         $( "#icon" ).toggle( "blind", {direction: 'left'} );
});
```

that's what i was expecting. but its not working like that

**Comment by fxbois** [comment]
1. I'll check this
2. you should use an other minor mode for this. web-mode mark-and-expand is primarily designed for the dom

**Comment by fxbois** [comment]
@ChillarAnand I've pushed a fix for 1.

**Comment by ChillarAnand** [comment]
@fxbois thank you

**Comment by ChillarAnand** [comment]
@fxbois  reported an issue with expand region, looks like web-mode also has same issue https://github.com/magnars/expand-region.el/issues/164 ?

**Comment by fxbois** [comment]
@ChillarAnand the last version on github should deal with this

**Comment by ChillarAnand** [comment]
@fxbois thank you :+1:
