### ISSUE TITLE
JSX indentation for self-closing tag />

### ISSUE THREAD

**Issue by blandinw** [fxbois/web-mode#491]
Hi, thanks for your great work on web-mode :-)
I've been using it with JSX successfully so far, but still have one issue with it.
Self-closing JSX tags with `/>` on a new line should be indented at the same-level as the opening line.
e.g. http://facebook.github.io/react/docs/jsx-in-depth.html#comments

Would it be possible to have this as the default and maybe an option to be backwards-compatible?

**Comment by fxbois** [comment]
@blandinw not sure to understand what you mean. Please post on gist two files : actual and desired

**Comment by blandinw** [comment]
Certainly, here is the gist: https://gist.github.com/blandinw/c9aeb13efe9052e3e810

**Comment by fxbois** [comment]
@blandinw I've pushed a fix

**Comment by blandinw** [comment]
It works, thanks!

**Comment by chenca** [comment]
This is currently broken in master, the fix is simple: http://pastebin.com/1FA8iydU
