### ISSUE TITLE
Weird indentation when "form" is used as a variable in erb

### ISSUE THREAD

**Issue by rochgs** [fxbois/web-mode#492]
Hi:

It looks like there is a problem using "form" as variable name in erb files. For example, if you have this code snippet:

```erb
<% form_for Foo do |f| %>
<%= f.text_field :bar_1 %>
<%= f.text_field :bar_2 %>
<% end %>

<% form_for Foo do |form| %>
<%= form.text_field :bar_1 %>
<%= form.text_field :bar_2 %>
<% end %>
```

When you indent it, you get this:

```erb
<% form_for Foo do |f| %>
  <%= f.text_field :bar_1 %>
  <%= f.text_field :bar_2 %>
<% end %>

<% form_for Foo do |form| %>
  <%= form.text_field :bar_1 %>
    <%= form.text_field :bar_2 %>
    <% end %>
```

I don't use the second way at all but it's troublesome when working with other people's code who uses it.

Thanks for your time.

**Comment by fxbois** [comment]
@rochgs I've pushed a fix

**Comment by fxbois** [comment]
@rochgs reopen if needed

**Comment by rochgs** [comment]
Works great. Thanks for your work.
