### ISSUE TITLE
indentation doesn't work properly

### ISSUE THREAD

**Issue by sol1dus** [fxbois/web-mode#495]
Hey. First of all, thanks for a great project! Now down to business: i'm having this in my config file:
```elisp
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.hbs\\'" . web-mode))
(setq-default indent-tabs-mode nil)

(defun my-web-mode-hook ()
  "Hooks for Web mode."
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (local-set-key (kbd "RET") 'newline-and-indent)
)
(add-hook 'web-mode-hook  'my-web-mode-hook)
```
`web-mode` always auto indents with a tab for me. How can I force it to indent with 2 spaces ? I'm using the latest version from master. Thanks.

**Comment by fxbois** [comment]
@sol1dus ```(setq-default indent-tabs-mode nil)``` should do the trick .. I have no other idea

**Comment by sol1dus** [comment]
@fxbois sorry man, it's was my set up. closing.

**Comment by fxbois** [comment]
@sol1dus what was the bug

**Comment by sol1dus** [comment]
@fxbois I haven't updated my [Prelude](https://github.com/bbatsov/prelude/blob/master/modules/prelude-web.el) mode for a while, and in old version it had it's own setup for `web-mode` in a hook with variables etc - looks like that's was the reason. After I updated *Prelude*, variables can be overridden and everything works.
