### ISSUE TITLE
Commenting region function

### ISSUE THREAD

**Issue by linktohack** [fxbois/web-mode#499]
Currently `web-mode-comment-or-uncomment` works directly with mark and point instead of a region (as it support lines and blocks, too). It would be nice that it support the same signature as `comment-or-uncomment-region`

```emacs-lisp
(comment-or-uncomment-region BEG END &optional ARG)
```

I'm currently having [this][1] to integrate with [evil-commentary][], but it should be great if it's implemented by web-mode.

[1]: https://github.com/linktohack/evil-commentary/blob/531a57378b54e9e2a60e0aecdca91461352cf9df/ec-mode-comment-functions.el#L3
[evil-commentary]: https://github.com/linktohack/evil-commentary

**Comment by fxbois** [comment]
@linktohack I've added your func to master

**Comment by linktohack** [comment]
Great! @fxbois :+1:
