### ISSUE TITLE
web-mode overrides emacs colorscheme

### ISSUE THREAD

**Issue by s-p-k** [fxbois/web-mode#500]
Hi, 

first of all I would like to thank you, I recently discovered web-mode and I really like it.

One think that I don't like it's that it overrides my emacs colorscheme. 
I'm really happy with the colorscheme I'm using and I would like at least to have the option to disable the web-mode hl and use the hl my colorscheme uses.

Thank you for your work so far.

**Comment by fxbois** [comment]
@s-p-k i dont understand, everyone is able to override the web-mode colors... See themes for example

**Comment by s-p-k** [comment]
Since you didn't understand what I say, how come you came to the conclusion to close the issue?

Just to let you know, I would prefer not to open an issue. I would prefer sending you an email, since this might not be an issue in your eyes, but your LICENSE file is just a 'SAMPLE'. ({description} Copyright (C) {year}  {fullname}.

I have a specific colorscheme that I use for coding. After loading web-mode, web-mode hijacks that colorscheme. Wouldn't it be wise to let the user choose if he wants the colors that web-mode offers or not? I'm not talking about the colors that web-mode "offers". I'm talking about not hijacking the colorscheme a user has by default.

If there's already an option to do that please guide me since I couldn't find anything on your documentation page.

**Comment by fxbois** [comment]
@s-p-k Please Provide all you .emacs stuff related to this issue. You need to be way more verbose and accurate when you post an issue

**Comment by s-p-k** [comment]
@fxbois This is the theme I'm using:

https://github.com/oblique/configs/blob/master/.emacs.d/themes/behelit-theme.el

And these are the lines I use for loading behelit:

``` emacs-lisp
;; theme

(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
(load-theme 'behelit t)
```
These is how my emacs looks without web-mode enabled:

http://postimg.org/image/g30evnvl7/

After loading web-mode the colors are like this:

http://postimg.org/image/41r4ir4dx/

I would like to have the web-mode functionality without the colors changed. I hope now it's clear.


These are the settings I have in my init.el regarding web-mode:

``` emacs-lisp
;;web-mode
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))

;; use web-mode for plain html too
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
```

And this is the output of web-mode-debug:

```
--- WEB-MODE DEBUG BEG ---                                                                                   
versions: emacs(24.4) web-mode("11.1.00")                                                                    
vars: engine("none") content-type("html") file("/home/spk/repos/jsexamples/index.html")                      
system: window(nil) config("i686-pc-linux-gnu")                                                              
colors: fg(nil) bg(nil)                                                                                      
minor modes: (show-paren-mode linum-mode global-linum-mode global-auto-complete-mode yas-minor-mode yas-glob\
  al-mode)                                                                                                      
vars:                                                                                                        
web-mode-enable-current-column-highlight=nil                                                                 
web-mode-enable-current-element-highlight=nil                                                                
indent-tabs-mode=t 
```

If you want me to provide any other info please tell me.

**Comment by fxbois** [comment]
@s-p-k as you can see, behelit-theme.el does not define the faces needed by web-mode. You should ask the maintainer to create them.

**Comment by s-p-k** [comment]
Hmmm, okay, thank you for your time.
