### ISSUE TITLE
Expansion logic with expand-region no longer works?

### ISSUE THREAD

**Issue by vmalloc** [fxbois/web-mode#501]
Hi,

A while back (in #9) an expansion logic was added to incrementally select elements surrounding the cursor.

It seems at some point this stopped working. Am I correct?

Thanks in advance

**Comment by fxbois** [comment]
Please post thé output of web-mode-debug

**Comment by vmalloc** [comment]
```
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("11.1.00")
vars: engine("none") content-type("html") file("/Users/rotemy/workspace/src/opensource/vmalloc/slash-site/index.html")
system: window(ns) config("x86_64-apple-darwin13.4.0")
colors: fg(nil) bg(nil) 
minor modes: (projectile-mode projectile-global-mode global-auto-revert-mode cua-mode display-time-mode display-battery-mode show-paren-mode winner-mode popwin-mode guide-key-mode sublimity-mode yas-minor-mode yas-global-mode ido-ubiquitous-mode ido-vertical-mode shell-dirtrack-mode helm-mode diff-auto-refine-mode undo-tree-mode global-undo-tree-mode auto-complete-mode global-auto-complete-mode wrap-region-mode drag-stuff-mode drag-stuff-global-mode semantic-mode global-semantic-idle-scheduler-mode global-semanticdb-minor-mode emmet-mode nyan-mode diff-hl-mode subword-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
@vmalloc hitting ```C-c C-m``` repeatedly triggers ```web-mode-mark-and-expand``` as expected
Perhaps I haven't understood your question

**Comment by vmalloc** [comment]
It works on its own, however, in conjunction with expand-region (I don't know if you remember but we introduced it after consulting with you) it sopped working.

See https://github.com/magnars/expand-region.el/blob/master/web-mode-expansions.el#L24

**Comment by fxbois** [comment]
@vmalloc in ```web-mode-on-post-command```, uncomment ```(message "this-command=%S ... ``` and tell me the command that is used when you expand with ```expand-region.el``` ... perhaps we will have to add it to the list ```'(web-mode-mark-and-expand er/expand-region)``` (line 8684)

**Comment by vmalloc** [comment]
Ok, I tried restarting emacs and started with a clean slate. It seems to work, but `er/contract-region` doesn't properly go back to the previous mark. Is that an `expand-region` issue or `web-mode`s?

**Comment by fxbois** [comment]
@vmalloc what is ```contract-region``` ? I do not have a notion of "contraction"

**Comment by vmalloc** [comment]
Sorry - I was referring to `expand-region`s behavior. It allows 'undoing' the last expansion if you expanded too far. It's very comfortable.

**Comment by fxbois** [comment]
@vmalloc do you talk of the standard ```'undo``` command ? or a special ```expand-region``` command ?

**Comment by vmalloc** [comment]
AFAIK it's expand-region behavior, but it achieves it by 'remembering' the previous mark positions in a stack.

**Comment by fxbois** [comment]
@vmalloc it seems like a good idea. Could you tell me if you use ```undo``` or an other command ?

**Comment by vmalloc** [comment]
I don't use `undo` in this case. I use `C--` which is bound to `er/contract-region` (https://github.com/magnars/expand-region.el/blob/0e51e1092903e8889eb711684247d126c381c40b/expand-region-core.el#L127)
