### ISSUE TITLE
Ractive support

### ISSUE THREAD

**Issue by Sortskjegg** [fxbois/web-mode#502]
Any chance of getting Ractive support in the excellent web-mode?
The mustaches seem to mess up indentation.

http://docs.ractivejs.org/latest/mustaches

**Comment by fxbois** [comment]
@Sortskjegg is it different from http://mustache.github.io/ ? Because web-mode is already compatible with mustache

**Comment by Sortskjegg** [comment]
Perhaps it's Ractive's templates? Or does it not indent inside mustache-blocks?

With a bare-bone Emacs-setup none of the lines between the script tags are indented:

<html>
	<head>
		<script id="ractiveTemplate" type="text/ractive">
		{{#if list.remember}}
		<div>
		<select>
		{{#each list.remember:i}}
		<option value="{{i}}">{{remname}}</option>
		{{/each}}
		</select>
		</div>
		{{/if}}
		</script>
	</head>
</html>

I would expect at least the <select> to be indented.
Is this intended or are there any variables that can change this?

**Comment by fxbois** [comment]
@Sortskjegg what is the extension of ractive templates ?

**Comment by Sortskjegg** [comment]
They're just .js & .html files, I believe.

**Comment by fxbois** [comment]
so look at web-mode.org and force an engine according to the path of your templates
(web-mode can not guess your engine when you use the .html extension)

**Comment by Sortskjegg** [comment]
I have set the engine to "ctemplate" (using both "-*- engine:ctemplate -*-" and web-mode-set-engine) and it only works some of the time.

Indentation works just fine for a while, then something happens in the background, the colours of the tags change and indentation is broken again. If I remove the closing script-tag, the colours change and indentation works again. The mode has not changed and neither the engine, as far as I can tell. Any suggestions to what I may try?

I'm using web-mode v11.1.02 and emacs 24.5.1 on OSX.

**Comment by fxbois** [comment]
@Sortskjegg only solution to solve this, report a very acurate scenario to trigger the issue. Moreover post your template on gist please

**Comment by fxbois** [comment]
@Sortskjegg please reopen when you can provide more info
