### ISSUE TITLE
javascript break line without semicolon

### ISSUE THREAD

**Issue by bolasblack** [fxbois/web-mode#503]
Hi fxbios, so much thanks for your awesome mode at first.

I found javascript content-type will indent the line if previous line not end with semicolon, but the semicolon in line end is unnecessary in most case.

I'm a newbee of elisp, I tried to fix it but failed, if the issue can be fix, it will help me a lot.

Thanks.

**Comment by fxbois** [comment]
Web-mode does embed a full js parser (js2-mode does) so i can not deal with lines without semilicons... Sorry

**Comment by bolasblack** [comment]
@fxbois sadly :(

But I found [jsx-mode](https://github.com/jsx/jsx-mode.el) works well, dose it helpful?

**Comment by fxbois** [comment]
Perhaps

**Comment by transtone** [comment]
emacs's js-jsx-mode works well.
