### ISSUE TITLE
Indentation of endtrans and else clauses on for loops in jinja templates do not work properly

### ISSUE THREAD

**Issue by niwinz** [fxbois/web-mode#504]
Here a screen capture of the indentation:
![web-mode 1](https://cloud.githubusercontent.com/assets/843689/7549648/da5cfd00-f63e-11e4-900d-e24ca5053d27.png)

I'm using the last version deployed in melpa for today (20150507.455)

**Comment by niwibe** [comment]
Something similar happens with `{% set foo = 'bar' %}`. The following html is over indented like using the `{% with foo = 'bar' %}`.

**Comment by fxbois** [comment]
@niwibe please see : https://github.com/fxbois/web-mode/issues/124
Does Jinja has ```blocktrans``` ? I would like to continue to treat jinja like django
I'll see for other issues

**Comment by niwibe** [comment]
Jinja has several differences with django templates and trans is one of them. As example, django does not have `set`, ...

**Comment by fxbois** [comment]
@niwibe could you try the last version on github please

**Comment by niwibe** [comment]
I'll try it tomorrow and notice you with any info.  Thanks

**Comment by niwinz** [comment]
Sorry for my late response.

I have updated to the last version (11.1.06) and when I setup jinja2 engine, it just ignores me. 

I have tried to execute the `web-mode-set-engine` manually and it just ignores me if I set `jinja` or `jinja2`. In contrast, the `django` engine works as expected (indentation, code highlight, ...)

I'm not cleary understand that is happens.

**Comment by niwinz** [comment]
I have tested just previous version to this commit: https://github.com/fxbois/web-mode/commit/e919d03bcbc3d022fb16108e3ad0b757685a3955  and jinja2 engine starts as expected (but with obviously existing bugs reported previously)

Something introduced in that commit breaks the jinja2 engine web-mode flavor.

**Comment by fxbois** [comment]
@niwinz two things
- the last commit should solve the issue ```web-mode-set-engine```
- I've removed jinja2, web-mode now only "knows" ```jinja```

**Comment by niwinz** [comment]
Thanks @fxbois 
Now, everything works as expected!
