### ISSUE TITLE
Element insert: Wrap new element around selection

### ISSUE THREAD

**Issue by lindleyw** [fxbois/web-mode#505]
(feature request)

It would be most convenient if `C-c C-e i` wrapped the new element around the selected region. Examples:

* When working with many paragraphs of plain text, select one paragraph and insert a `p` element; this would add both the `<p>` at start and `</p>` at end of paragraph.
* Select some text in the document and insert an `a` element which would wrap around it

**Comment by fxbois** [comment]
@lindleyw should be ok with last commit

**Comment by lindleyw** [comment]
Seems to work perfectly, thank you!
