### ISSUE TITLE
Use Emacs argument for next/prev, kill, vanish

### ISSUE THREAD

**Issue by lindleyw** [fxbois/web-mode#506]
(feature request)

Would be convenient if the Emacs universal-argument (via `C-u` for example) would be regarded by at least 'block/element/attribute kill', 'next/previous block/element/tag/attribute', 'element vanish'.

Example:

* To "vanish" a series of eight useless `<span…>` elements, you could use: `C-u 8 C-c C-e v`
* To move forward by four attributes, you could use: `C-u C-c C-a n`

**Comment by fxbois** [comment]
@lindleyw do you have an example in an other major mode ? (to see the signature of the function)

**Comment by lindleyw** [comment]
The built-in HTML (and SGML) mode [has the argument enabled](http://www.gnu.org/software/emacs/manual/html_node/emacs/HTML-Mode.html).  Looking at the [source code](http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/textmodes/sgml-mode.el?h=emacs-24) in the SGML/HTML mode, the forward-tag function there (circa line 866) begins as:

    (defun sgml-skip-tag-forward (arg)
      "Skip to end of tag or matching closing tag if present.
    With prefix argument ARG, repeat this ARG times.
    Return t if after a closing tag."
      (interactive "p")
    …

This article: [Writing Command to Accept universal-argument](http://ergoemacs.org/emacs/elisp_universal_argument.html) and the section in the [official GNU Emacs Lisp Reference](http://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Command-Arguments.html) might be useful.

**Comment by fxbois** [comment]
@lindleyw thx I'll try to work on this this weekend

**Comment by fxbois** [comment]
@lindleyw the version just pushed is compatible with universal-arg for ```web-mode-element-next|previous``` ... could you confirm that this is ok for you ?

**Comment by lindleyw** [comment]
Confirm that "C-u <number> C-c C-e n" (next) and likewise previous, both respect the numeric argument, including proper handing of the default argument value of 4. Also confirm that negative values work for both next and previous (-1 nexts equals 1 previous, and v.v.)  

However, "C-c C-e d" for delete element, with or without argument, results in an error: "Wrong number of arguments" presumably because it calls the next/previous functions incorrectly now.

**Comment by fxbois** [comment]
only web-mode-element-next|previous have been adapted at the moment ... I'll keep web-mode updated as the process advances

**Comment by lindleyw** [comment]
OK.  Until then, perhaps put this latest on a different branch, so 'master' still works? The others are broken right now. Much obliged.

**Comment by fxbois** [comment]
I don't understand ... master still work as expected but you can only use unviersal-arg on 4 functions at the moment (I've added two this morning, the list is in the devel changelog on web-mode.org)

**Comment by lindleyw** [comment]
I have just downloaded the latest version, and several functions, such as C-c C-e d, C-c C-e f -- all give an error (Wrong number of arguments) and fail to operate; can you verify?

**Comment by fxbois** [comment]
??? have you read my comment ? The only functions that are compatible with universal argument (at the moment) are : web-mode-element-kill | next | previous | yank and you are talking to me of web-mode-element-child and web-mode-element-children-fold-or-unfold ...

**Comment by lindleyw** [comment]
Please remain calm. The newly updated functions do work fine.  However the other ones are broken and unusable; would best practice be to have such a version in a 'development' branch? Many thanks for your continued improvements.

**Comment by fxbois** [comment]
ok thx. Those args are now &optional

**Comment by lindleyw** [comment]
Hmm... color highlighting isn't working, and C-c C-e f (or b) forward/back aren't either.

− as of commit f91102a81d54d5048be3aabe38516883fbe6e107

**Comment by fxbois** [comment]
@lindleyw do you have anything in *Messages* ?
I've just pushed a patch to add universal-arg for web-mode-attribute-kill

**Comment by lindleyw** [comment]
Confirmed working, latest version.  This is a very fine addition, thank you.

**Comment by fxbois** [comment]
attr-next and attr-prev have been added.
