### ISSUE TITLE
`web-mode-html-tag-bracket-face` invalid until opening `web-mode`

### ISSUE THREAD

**Issue by ayrtonmassey** [fxbois/web-mode#507]
I'm trying to change the colour of the HTML tag brackets. With a file open in web-mode, the following works:

```emacs-lisp
    M-x (set-face-attribute 'web-mode-html-tag-bracket-face nil :foreground "White")
```

But if I put the command in my `.emacs` I get an error telling me that `web-mode-html-tag-bracket-face` is an invalid face. If I open emacs without opening a file in `web-mode`, attempting the above command using `eval` gives me the same "Invalid face" error. After opening a file in `web-mode` the attribute can be set.

**Comment by fxbois** [comment]
@ayrtonmassey please look at http://web-mode.org

**Comment by ayrtonmassey** [comment]
My apologies, missed the part about adding the command as a hook. Cheers!
