### ISSUE TITLE
Bad JSX indentation

### ISSUE THREAD

**Issue by vslinko** [fxbois/web-mode#509]
actual:
```
<div>
  {someBoolean &&
   <div>3 spaces on this line
   <div>3 spaces on this line</div>
   </div>
   }
   <div>3 spaces on this line</div>
</div>
```

expected:
```
<div>
  {someBoolean &&
    <div>4 spaces on this line
      <div>6 spaces on this line</div>
    </div>
  }
  <div>2 spaces on this line</div>
</div>
```

**Comment by fxbois** [comment]
@vslinko At the moment I do not recursively parse JSX elements. Being able to do so (for example to be able to indent elements that are inside tags like ```<List element={<ul />} />```) will need a lot of work. I hope to be able to work on this this summer.

**Comment by eguneys** [comment]
```
·····<Row>
··········<Col>
············
··········</Col>
······</Row>
```

The `Col` elements are not intented. The rest is intended fine.

**Comment by fxbois** [comment]
@vslinko ```<col>``` is a void element according to the html spec. Use ```<column>``` if you wan't to avoid the issue (or adapt the ```web-mode-void-elements``` according to your needs)

**Comment by eguneys** [comment]
@fxbois I am using this https://github.com/nkt/react-flexgrid

**Comment by fxbois** [comment]
@vslinko great ... so play with ```web-mode-void-elements```
