### ISSUE TITLE
Problem in JSX highlighting

### ISSUE THREAD

**Issue by vslinko** [fxbois/web-mode#511]
initial state (`|` is cursor):
```
<div>
  {123}
  |
</div>
```

When I'm inserting `{` character all lines above highlighted to white

expected (highlighted all):
```js
<div>
  {123}
  {}
</div>
```

actual (highlighted only last line):
```
<div>
  {123}
  {}
</div>
```

**Comment by fxbois** [comment]
@vslinko the last commit should solve this

**Comment by vslinko** [comment]
Working, thank you.
