### ISSUE TITLE
Problem with alignment of arguments in Blade templates

### ISSUE THREAD

**Issue by 501st-alpha1** [fxbois/web-mode#512]
I'd like to report a problem with the alignment of arguments in Blade templates. If I enter the following in a file such as `test.blade.php`:

    This is a test. {{ URL::action('someaction',
    [$arg]) }}

... then enable `web-mode`, and hit `TAB` from the bottom line, I get this:

    This is a test. {{ URL::action('someaction',
	                  [$arg]) }}

However, I would prefer it to look like this:

    This is a test. {{ URL::action('someaction',
                                   [$arg]) }}

Tested with `emacs -Q`. I'm using the latest version of `web-mode` from GitHub. My `web-mode-debug` is:

    --- WEB-MODE DEBUG BEG ---
    versions: emacs(24.3) web-mode("11.1.05")
    vars: engine("blade") minor("blade") content-type("html") file("[snip]/test.blade.php")
    system: window(x) config("x86_64-pc-linux-gnu")
    colors: fg(nil) bg(nil) 
    minor modes: nil
    vars:
    web-mode-enable-current-column-highlight=nil 
    web-mode-enable-current-element-highlight=nil 
    indent-tabs-mode=nil 
    --- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@501st-alpha1 I've pushed a fix

**Comment by 501st-alpha1** [comment]
Works great, thanks!
