### ISSUE TITLE
Function atttribute-select includes the carets. 

### ISSUE THREAD

**Issue by ReneFroger** [fxbois/web-mode#513]
Hi there, me again!

For example, you have this line: 
`<div id="foo" action="bar">`

Your cursor is on the letter `a` of the attribute `action`. In web-mode, the function `web-mode-attribute-select` will select the attribute `action` and his contents, but will select the closing caret too (`>`). When you yank the selected region, it will include the closing caret in the yank. I guess it has something to do with how Emacs handles with the pointer. :frowning:.

It seems to me that this is not the intention. And when you do the same with web-mode-attribute-kill, it will kill the region accordingly, without kill the closing caret. So I wonder if the behaviour of `web-mode-attribute-select` could be configured to behave consistent as with `web-mode-attribute-kill` without including the caret?

**Comment by fxbois** [comment]
@ReneFroger for me ```>``` is not selected when I ```web-mode-attribute-select```, please take a video

**Comment by ReneFroger** [comment]
Sorry for my belated response. The video, as asked: 

![web-mode-caret](https://cloud.githubusercontent.com/assets/5211845/7788951/c878770a-024f-11e5-98ff-f1b361bdd7d0.gif)

**Comment by fxbois** [comment]
@ReneFroger what command do you type after the attribute selection ?

**Comment by ReneFroger** [comment]
I give the command `kill-region` with pressing C-w.

**Comment by fxbois** [comment]
I can not trigger your issue. Perhaps start with a very light .emacs to see if a minor-mode is responsible of something

**Comment by ReneFroger** [comment]
You're right, my fault. I tested it with empty Emacs config, with web-mode only turned on. And I cannot trigger this issue anymore. 

I suspect it's related to Evil, so I will try to debug this issue further with the authors of Evil. Thanks for your support.
