### ISSUE TITLE
issues with nested comments

### ISSUE THREAD

**Issue by ChillarAnand** [fxbois/web-mode#514]
this div has an element commented out. now if i try to comment entire `div#results-filter`, it is not working

```
<div class="filter-values" id="results-filter">
  <div id="id_pagination_value">
    <!-- <p>{{form.per_page}}</p>  -->
    <p>{{form.sort_by}}</p>
    <p>{{form.sort_type}}</p>
  </div>
</div>
```

**Comment by fxbois** [comment]
@ChillarAnand you can not have comments inside comments

**Comment by ChillarAnand** [comment]
@fxbois  then web-mode shouldn't insert comments like this

```
<!-- <div class="filter-values" id="results-filter">
<div id="id_pagination_value">
<!-- <p>{{form.per_page}}</p>  -->
<p>{{form.sort_by}}</p>
<p>{{form.sort_type}}</p>
    </div>
</div> -->
```
may be throw a message instead?

**Comment by fxbois** [comment]
@ChillarAnand I do not agree with you, users should not put nested markup .. it not allowed by the specs.
I won't increase the already large code base for all the cases users should not do
