### ISSUE TITLE
Tag goto the wrong place

### ISSUE THREAD

**Issue by maxc01** [fxbois/web-mode#515]
When I write a `tag`, it will go to the right side of the current frame, but when I switch to other buffer and switch back, or when I change the window size of my Emacs, the `tag` will come back, strange.
Maybe there are some conflicts in Emacs packages, I think.
![screenshot_2015-05-20_18-53-04](https://cloud.githubusercontent.com/assets/2748078/7724223/391829f0-ff22-11e4-8317-63976ec4e635.png)

the web-mod debug output is
----
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("11.1.10")
vars: engine("none") minor("none") content-type("html") file("xxx")
system: window(x) config("amd64-portbld-freebsd10.1")
colors: fg(nil) bg(nil) 
minor modes: (show-paren-mode yas-minor-mode yas-global-mode flycheck-mode global-flycheck-mode smartparens-mode smartparens-global-mode show-smartparens-mode show-smartparens-global-mode projectile-mode projectile-global-mode async-bytecomp-package-mode shell-dirtrack-mode helm-descbinds-mode helm-mode pyvenv-mode company-mode global-company-mode semantic-mode global-semantic-idle-scheduler-mode global-semanticdb-minor-mode ede-minor-mode global-ede-mode undo-tree-mode global-undo-tree-mode nyan-mode global-whitespace-mode winner-mode ace-isearch-mode global-ace-isearch-mode popwin-mode clean-aindent-mode fci-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=t 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@maxc01 what minor-mode do you use for the vertical line ? I know there is a bug with one of them ...

**Comment by maxc01** [comment]
@fxbois I use `Fill Column Indicator`, maybe this is the problem, I notice there is a small vertical line on the right of the wild `div tag`

**Comment by fxbois** [comment]
@maxc01 I think there is a bug report ... I can provide help to the maintainer if needed

**Comment by maxc01** [comment]
@fxbois Yes, `Fill Column Indicator` is the problem, when I turn it off, everything goes right.
