### ISSUE TITLE
JSX doesn't maintain surrounding indentation level

### ISSUE THREAD

**Issue by mkscrg** [fxbois/web-mode#519]
I have this `web-mode-hook`:

```elisp
(add-hook 'web-mode-hook
          (lambda ()
            (setq web-mode-code-indent-offset 2)
            (setq web-mode-markup-indent-offset 2)
            (setq web-mode-attr-indent-offset 4)))
```

and I'm trying to format some JSX. I expect it to look like this:

```js
export default class MyComponent extends React.Component {
  // ...
  render() {
    return <div>
      <div
          style={{background: "red"}}>
        <p>
          <span>This is MyComponent.</span>
        </p>
      </div>
    </div>;
  }
}
```

But the indenter loses the 4-space indent at `return <div>`:

```js
export default class MyComponent extends React.Component {
  // ...
  render() {
    return <div>
  <div
      style={{background: "red"}}>
    <p>
      <span>This is MyComponent.</span>
    </p>
  </div>
    </div>;
  }
}
```

The 2nd `<div>` is indented 2 spaces regardless of the surrounding depth. Wrapping the JSX in parens and newlines avoids the issue:

```js
export default class MyComponent extends React.Component {
  // ...
  render() {
    return (
      <div>
        <div
            style={{background: "red"}}>
          <p>
            <span>This is MyComponent.</span>
          </p>
        </div>
      </div>
    );
  }
}
```

Some debugging info:

```text
web-mode-version is a variable defined in `web-mode.el'.
Its value is "11.1.00"

web-mode-content-type is a variable defined in `web-mode.el'.
Its value is "jsx"
Local in buffer MyComponent.js; global value is ""
```

PS `web-mode` is awesome! :smile:

**Comment by fxbois** [comment]
@mkscrg please post the output of ```web-mode-debug``` please

**Comment by mkscrg** [comment]
```text
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("11.1.00")
vars: engine("ejs") content-type("jsx") file("/Users/mike/Development/sandbox/webmodejsx/MyComponent.jsx")
system: window(nil) config("x86_64-apple-darwin14.3.0")
colors: fg(nil) bg(nil) 
minor modes: (linum-mode global-linum-mode global-whitespace-mode evil-local-mode undo-tree-mode global-undo-tree-mode evil-mode async-bytecomp-package-mode shell-dirtrack-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
could you try the version available on github please

**Comment by mkscrg** [comment]
Tried from `master`, same behavior. `web-mode-debug` says:

```text
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("11.1.12")
vars: engine("ejs") minor("ejs") content-type("jsx") file("/Users/mike/Development/sandbox/webmodejsx/MyComponent.jsx")
system: window(nil) config("x86_64-apple-darwin14.3.0")
colors: fg(nil) bg(nil) 
minor modes: (linum-mode global-linum-mode global-whitespace-mode evil-local-mode undo-tree-mode global-undo-tree-mode evil-mode async-bytecomp-package-mode shell-dirtrack-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
have you associated your template with the ejs template engine ?

**Comment by mkscrg** [comment]
No, not intentionally. I tried explicitly associating an engine:

```elisp
(setq web-mode-engines-alist
      '(("reactjs" . "\\.jsx$")))
```

But found the same indentation behavior. `web-mode-debug`:

```text
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("11.1.12")
vars: engine("none") minor("reactjs") content-type("jsx") file("/Users/mike/Development/sandbox/webmodejsx/MyComponent.jsx")
system: window(nil) config("x86_64-apple-darwin14.3.0")
colors: fg(nil) bg(nil) 
minor modes: (linum-mode global-linum-mode global-whitespace-mode evil-local-mode undo-tree-mode global-undo-tree-mode evil-mode async-bytecomp-package-mode shell-dirtrack-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
you do not need ```(setq web-mode-engines-alist '(("reactjs" . "\\.jsx$")))``` jsx will be recognized because your file has the .jsx extension

**Comment by mkscrg** [comment]
Right, that's what I was doing before (see original config at top of this issue)

**Comment by fxbois** [comment]
could you post the web-mode-debug ?
I am expecting "none" for both ```engine``` and ```minor```

**Comment by mkscrg** [comment]
Here's the whole (minimal) setup:

- OS X 10.10.3 running Emacs 24.5.1 (installed via Homebrew) in Terminal.app.
- `web-mode` downloaded from GH master: <https://raw.githubusercontent.com/fxbois/web-mode/master/web-mode.el>
- Remove `~/.emacs.d/` and run Emacs with a minimal init file:

    ```elisp
    (add-to-list 'auto-mode-alist '("\\.jsx$" . web-mode))
    
    (add-hook 'web-mode-hook
              (lambda ()
                (setq web-mode-code-indent-offset 2)
                (setq web-mode-markup-indent-offset 2)
                (setq web-mode-attr-indent-offset 4)))
    ```

    ```sh
    $ emacs -q -l web-mode.el -l init.el MyComponent.jsx
    ```

- Bad indentation behavior with JSX (described above). `web-mode-debug` says this:

    ```text
        --- WEB-MODE DEBUG BEG ---
    versions: emacs(24.5) web-mode("11.2.0")
    vars: engine("ejs") minor("ejs") content-type("jsx") file("/Users/mike/Development/sandbox/webmodejsx/MyComponent.jsx")
    system: window(nil) config("x86_64-apple-darwin14.3.0")
    colors: fg(nil) bg(nil)
    minor modes: nil
    vars:
    web-mode-enable-current-column-highlight=nil
    web-mode-enable-current-element-highlight=nil
    indent-tabs-mode=t
    --- WEB-MODE DEBUG END ---
    ```

    I'm not sure where `ejs` is coming from!

**Comment by fxbois** [comment]
@mkscrg I see, I think it is because there is 'ejs' in 'webmodejsx' ... I've disabled this extra detection with the last patch.

**Comment by mkscrg** [comment]
Ok, now `web-mode-debug` says `none`/`none` as intended:

```text
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("11.2.2")
vars: engine(none) minor(none) content-type("jsx") file("/Users/mike/Development/sandbox/webmodejsx/MyComponent.jsx")
system: window(nil) config("x86_64-apple-darwin14.3.0")
colors: fg(nil) bg(nil)
minor modes: nil
vars:
web-mode-enable-current-column-highlight=nil
web-mode-enable-current-element-highlight=nil
indent-tabs-mode=t
--- WEB-MODE DEBUG END ---
```

The JSX indentation is still incorrect. Am I misusing `web-mode` or is this a bug?

**Comment by fxbois** [comment]
could you take a screenshot of the window just after emacs is opened please

On Thu, May 28, 2015 at 5:47 PM, Mike Craig <notifications@github.com>
wrote:

> Ok, now web-mode-debug says none/none as intended:
>
> --- WEB-MODE DEBUG BEG ---
> versions: emacs(24.5) web-mode("11.2.2")
> vars: engine(none) minor(none) content-type("jsx") file("/Users/mike/Development/sandbox/webmodejsx/MyComponent.jsx")
> system: window(nil) config("x86_64-apple-darwin14.3.0")
> colors: fg(nil) bg(nil)
> minor modes: nil
> vars:
> web-mode-enable-current-column-highlight=nil
> web-mode-enable-current-element-highlight=nil
> indent-tabs-mode=t
> --- WEB-MODE DEBUG END ---
>
> The JSX indentation is still incorrect. Am I misusing web-mode or is this
> a bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fxbois/web-mode/issues/519#issuecomment-106429954>.
>



-- 
François-Xavier Bois
Kernix - 15 rue Cels - 75014 PARIS
Tel. +33 1 53 98 73 43

**Comment by fxbois** [comment]
In fact the paren is not needed you just have to put the first ```<div>``` on a new line.
