### ISSUE TITLE
Comment detection in Javascript and HTML-fields with Yasnippet. 

### ISSUE THREAD

**Issue by ReneFroger** [fxbois/web-mode#520]
I use YASnippet, to insert comment fields. The structure of the YASnippet for Web-mode is as following: 

     
     
     $2

I have bound this to a keybinding. I noticed when I'm going into a `<script>` field in the same buffer with the HTML DOM structure, the `<!--` comment tag is invalid for Javascript fields. 

In order to solve this, I changed the comment snippet for Web mode as following: 
 
     `(concat comment-start " ")` ${1:Some description about the DOM structure} (`(insert-date)`) -->
     `(concat comment-start " ")` ---------------------------${1:$(make-string (string-width yas-text) ?\-)}-->
      $2

Well, the function `comment-start` works fine in HTML-regions. But In the Javascript regions, I notice he is still inserting the `<!--` comment tag, which is unfortunately not a valid comment tag for Javascript fields in the same buffer with HTML.

When I look around, I notice that [Evil Nerdcommenter](https://github.com/redguardtoo/evil-nerd-commenter) works fine with Webmode. If I call Nerd-commenter inside `<script>`-fields, the regions got correct commented out with `\\` or `\* [Commented text] *\`. 

And in HTML fields of the same buffer, he is correct commenting out the HTML text with `<!-- [Commented text] -->`. 

What would be a good suggestion to let YASnippet know if he is in a script field or in HTML field inside Web-mode, then insert the correct comment tag? 

By the way, your support is really appreciated.

**Comment by fxbois** [comment]
@ReneFroger you can start by looking at the part "Context-aware auto-completion" on web-mode.org

**Comment by ReneFroger** [comment]
Thanks for your answer, I got some inspiration from the content of "Context-aware auto-completion". So I defined the following function: 

(defun my\fix-comment-tag ()
      (if (string= web-mode-cur-language "html")
           (insert "
     `(my\fix-comment-tag)` ---------------------------${1:$(make-string (string-width yas-text) ?\-)}-->
      $2

Then I got an error: `[yas] elisp error: Symbol's value as variable is void: web-mode-cur-language`.

**Comment by fxbois** [comment]
you should use ```(web-mode-language-at-pos)```

**Comment by ReneFroger** [comment]
I replaced the `(if (string= web-mode-cur-language "html")` with `(string= web-mode-language-at-pos "html")`. 

Well, I got the same error ` [yas] elisp error: Symbol's value as variable is void: web-mode-language-at-pos` when inserting the Yasnippet in the `foobar.html` with web-mode enabled as major mode.

**Comment by fxbois** [comment]
(string= (web-mode-language-at-pos) "html")

**Comment by ReneFroger** [comment]
Oh, yes! It works like a charm. I always thought I knew sufficient Elisp syntax, to fiddle around with it. Your comments proves for me, that I'm lacking in knowing Elisp. I should learn it damn good, instead bothering you with my silly questions. :smiley:

Thanks for your help!
