### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by recri** [fxbois/web-mode#521]
With this local variables setting comment on the first line of an html file :

  

I expected indentation at 2 spaces per level, but I get indentation at 8 spaces per level.  

I've looked at your code but I can't figure out how this could happen except when indent-tabs-mode is t and tab-width or standard-indent are bound to 8, which is how I ended up with the values in the comment, by trying to change the result.

I'll probably hack together a hook-function now, but I'd rather document the format constants in the source files.

This was using the latest commit to github.com/fxbois/web-mode 2015.05.28

**Comment by fxbois** [comment]
@recri handling this kind of vars has never been implemented in web-mode

**Comment by recri** [comment]
Well, no wonder it didn't work.  It looks fairly painless to do, once you figure out which variables are safe to take.

  http://www.gnu.org/software/emacs/manual/html_node/elisp/File-Local-Variables.html

**Comment by fxbois** [comment]
@recri could you add a special hook for this ?

**Comment by recri** [comment]
I thought yes, but then I looked deeper.

According to
http://www.gnu.org/software/emacs/manual/html_node/elisp/Auto-Major-Mode.html
emacs is reading and parsing the comment line before web-mode gets to run.
The comment line is the highest precedence mode selection, and I can verify
that setting mode:web in the comment overrides the default mode:html that
html/sgml mode set.  So emacs has already implemented those variable
settings when web-mode runs.

On further testing using C-h v after web-mode loads, all the comment
variables are set in the web-mode buffer according to the values specified
in the comment.  If I set:



then I get 2 spaces per indentation in web-mode-markup.  (By the way,
web-mode-markup-indent-offset is identified as an "unsafe" variable by
default.)   But if I set:



then I get 8 spaces per indentation in web-mode-markup and all other
web-mode contexts.

So the puzzle is where you get that 8 from when everything is set to 4 or
less, since standard-indent is set to 4 by default, and all your defaults
are set to 4 or 2, too.

I'm going to look at how cc-mode gets its offsets and defaults its custom
variables to see if there's a clue.  That's where I learned how to control
my indentation.

-- rec --

**Comment by fxbois** [comment]
strange that emacs can identify a comment before parsing the file. The rule is on "first line" or "first line if comment" ?

**Comment by recri** [comment]
It is actually searching for the -*- tags containing a sequence of valid
name:value; bindings near the beginning of the file, that it has comment
status is solely the business of the file's syntax.  There's a different
syntax for embedding file local variables one to a line towards the end of
the file, too, which also involves emacs deducing the comment syntax from
an exemplar.

Looking at the cc-mode sources, the answer is that it uses c-basic-offset
as the basis of indentation, it ignores tab-width and indent-tabs-mode and
standard-indent entirely, but spaces get translated to tabs when
indent-tabs-mode is t and the spaces reach to the next tab-width tab stop.
If someone sets indent-tabs-mode t and tab-width is equal to
c-basic-offset, then each leading tab represents one level of indentation,
cc-mode makes no effort to force this to be true.

I still do not understand why web-mode ends up with 8 space indentation.
I'm going to move my file local variables settings to the end of my files
and specify all the web-mode-*-indent-offset's to be 2.

**Comment by fxbois** [comment]
@recri have you defined standard-indent in your .emacs ?
Moreover have you disabled indent-tabs-mode ?

**Comment by recri** [comment]
Neither are defined in my .emacs.  I've fiddled with various combinations
in the file local variable settings, but I cannot claim to have tried every
combination.

It turns out that both are defined anyway, as 4 and t.  They turn up as
defined in the buffer when I open a non-existent file that gets defaulted
to fundamental-mode.  Again using c-H v to check buffer local variables.

This is with emacs-24.4.1 on Ubuntu 15.04, that's changed since this
morning when my chromebook developed a stuck control key after less than 60
days of service.
