### ISSUE TITLE
Problem with commenting PHP code

### ISSUE THREAD

**Issue by 501st-alpha1** [fxbois/web-mode#524]
I'd like to report a problem with commenting out PHP code, using `M-;` (`web-mode-comment-or-uncomment`).

If I have a file such as:

    <?php

    class Foo {
        public function bar() {
        }
    }

    ?>

... and I set the mark just before `public`, then move the point to just after the closing brace of `bar`, and do `M-;`, this is the result:

    <?php

    class Foo {
        public function bar() {
        }/*  */
    }

    ?>

The point is placed in the middle of the comment. If I swap the point and mark first, the function is commented out as expected.

Tested with `emacs -Q`, using the latest version of `web-mode` from GitHub. My `web-mode-debug` is:

    --- WEB-MODE DEBUG BEG ---
    versions: emacs(24.5) web-mode("11.2.2")
    vars: engine("php") minor("php") content-type("html") file("[snip]/test.php")
    system: window(x) config("x86_64-unknown-linux-gnu")
    colors: fg(nil) bg(nil) 
    minor modes: nil
    vars:
    web-mode-enable-current-column-highlight=nil 
    web-mode-enable-current-element-highlight=nil 
    indent-tabs-mode=t 
    --- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@501st-alpha1 should be better with last commit

**Comment by 501st-alpha1** [comment]
Yep, works great now. Thanks!
