### ISSUE TITLE
Web-mode with header lets Emacs crash

### ISSUE THREAD

**Issue by ReneFroger** [fxbois/web-mode#525]
# Bug report

## Setup:
GNU Emacs GUI version 24.4.51.1 (x86_64-w64-mingw32) 
[Compiled from Harroogan Emacs.](https://bitbucket.org/Haroogan/emacs-for-windows/)
Web-mode, using the latest version of web-mode from GitHub
[Library header2.el](http://emacswiki.org/emacs/AutomaticFileHeaders)
Windows 7 x64 bit.

## Situation:
header2.el lets you define file headers for different types of file (C, shell, EmacsLisp, and so on). You can automatically insert a header when you open a new file buffer.

I ran into crashes, when I use web-mode in combination with header2.el. This is tested with an empty Emacs configuration (emacs -q).

When I use header2.el in combination with PHP-mode, JS-mode, and HTML-mode, I don't run into crashes and everything works fine. 

## Action:
First, you need to configure your emacs.d, in order to get the packages. 
```
(setq user-emacs-directory "C:/Dropbox/Emacs/.emacs.d/")
(add-to-list 'load-path "C:\\Dropbox\\Emacs\\.emacs.d\\")
```

Then do load the packages Web-mode and header2.

````
(require 'header2)
(require 'web-mode) 
```

Then you need to configure the header, and set it up to be automatic created when create a new file:

```
(setq php-tag "<?php \n \n")
(setq html-close-tag " --> \n") 

(defsubst my/header-title ()
  (insert
   (if (eq major-mode 'php-mode)
       php-tag
     " \n")
   (concat comment-start  " File " (buffer-name))
   (if (eq major-mode 'web-mode)
       html-close-tag
     " \n")
   "\n"))

(setq make-header-hook '(my/header-title))

(autoload 'auto-update-file-header "header2")
(add-hook 'write-file-hooks 'auto-update-file-header)

(autoload 'auto-make-header "header2")
(add-hook 'html-mode-hook 'auto-make-header) 
(add-hook 'web-mode-hook 'auto-make-header) 
(add-hook 'php-mode-hook 'auto-make-header) 
(add-hook 'js-mde-hook 'auto-make-header)  
```

## Errornous behavior:
I create in Emacs a new file, called `foobar.php`. I get the header automatically inserted for me. And I can type around and press `RET`. Everything works fine.
Same for `foobar.js` and `foobar.html`

Then I add `(add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))` to my setup.

I restart Emacs. Then I create a new file, called `foobar.html`. The `.html`-filetype is hooked on web-mode. When typing some characters and press `RET`, this causes Emacs to freeze. Nothing is appearing in the `*Messages*`-buffer. This will not happen, when I don't add the `.html` extension to the `Web-mode` on auto-mode-alist, and get `html-mode`instead.

**Comment by fxbois** [comment]
@ReneFroger I do not have much time to deal with issues with minor modes. I've read very quickly the code and this minor mode use the vars comment-start, comment-end that I do not provide (because I can't provide them).

**Comment by ReneFroger** [comment]
Fxbois, I understand that you not having a lot of time. But this is **not** a minor mode. It's a action hook, that insert the text when you enter a major mode.

`comment-start` and `comment-end` are independent of any mode. It's native built-in. PHP-mode, JS2-mode and any other major mode don't have such variables, and it works for the other major modes. So it's more related with web-mode.

**Comment by fxbois** [comment]
@ReneFroger I woulb be happy to accept some patch.

**Comment by ReneFroger** [comment]
It seems there is a bug, http://emacs.stackexchange.com/questions/13074/why-is-autoheader-crashing-with-web-mode/14602#14602

I have not enough insight in the internals of Emacs or Web-mode, to see what's going on here. But I'm awaiting anohter reply of the beloved user PythonNut.
