### ISSUE TITLE
web-mode-scan-elements: Wrong type argument: number-or-marker-p, "html"

### ISSUE THREAD

**Issue by andreaortuno** [fxbois/web-mode#526]
Emacs Version:  Emacs 24.5.1 (i686-pc-mingw32)

I'm on a windows 8 machine. Highlighting and tabbing doesn't work.

Let me know if there is any more info I can provide.

**Comment by fxbois** [comment]
@andreaortuno it is now solved on github master.
Thx for the report

**Comment by andreaortuno** [comment]
Great! Any idea when it's getting pushed to melpa?
