### ISSUE TITLE
With SCSS files emmet expand incorrectly

### ISSUE THREAD

**Issue by lmartins** [fxbois/web-mode#527]
Hi,

Im trying to use web-mode with Sass files (SCSS) so that I can have the smart indentation and brackets. Unfortunately, with web-mode enable I loose the emmet context expansions:

`mr` expands to `<mr></mr>` instead of `margin-right:;`

Is there anyway I can get the correct expansions?

**Comment by fxbois** [comment]
@lmartins could you post 1/ a screenshot, 2/ your example on gist please

**Comment by lmartins** [comment]
Hey @fxbois,

Perhaps it's easier to explain with a little video:
http://quick.as/gb5u98yz

The emacs dialog that appears cutoff is when im switching from Scss mode to web-mode.

Thanks for your help.

**Comment by fxbois** [comment]
@lmartins I do not use emmet ... difficult for me to help. Perhaps you'll have more success on stackoverflow

**Comment by lmartins** [comment]
Thanks for looking into this anyway. Cheers
