### ISSUE TITLE
Web-mode makes emacs unresponsive with big html file. 

### ISSUE THREAD

**Issue by hydrosIII** [fxbois/web-mode#528]
I have tried to modifiy a html compiled from a .Rmd file (from the R language), there is a lot of data in there, but in other editors the file just opens find. In emacs it takes a long time to load, and when it finally loads it is impossible to work because of slowness.

This is due to some operation made by the web-mode, plain emacs doesn't do that.

Here is the file that im trying to load.

Emacs 24
Using the Prelude distribution.

https://github.com/jared275/Certificacion-de-Calidad/blob/master/An%C3%A1lisis_inmuebles.html

**Comment by fxbois** [comment]
@hydrosIII I've removed the limit on attr length. Modification is not slow for me (update web-mode). I can't do anything for slowness ... I've not designed web-mode for this king of giant tag
