### ISSUE TITLE
React JSX Components named `Link` do not autocomplete

### ISSUE THREAD

**Issue by nhunzaker** [fxbois/web-mode#529]
Assuming the following code:

```javascript
<Layout>
  <Link to="dashboard">Dashboard
```

When I go to type `</`, it autocompletes to:

```javascript
<Layout>
  <Link to="dashboard">Dashboard</Layout>
```

**Comment by fxbois** [comment]
@nhunzaker it is because link is a void element in html

**Comment by nhunzaker** [comment]
Is there any resolution here? A way to add exceptions for JSX?

**Comment by fxbois** [comment]
@nhunzaker the only solution I can offer is modifying the var ```web-mode-void-elements```
