### ISSUE TITLE
[ERB] Unexpected token for first ERB tag

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [fxbois/web-mode#531]
![users prathamesh projects bigbinary myautobrain app views preferences family_safeties _form html erb 2015-06-12 21-01-54](https://cloud.githubusercontent.com/assets/621238/8133515/69ed96f6-1146-11e5-8c36-c947001c7480.jpg)

This happens for first ERB tag in every file? Is this an issue?

**Comment by fxbois** [comment]
@prathamesh-sonpatki unrelated to web-mode

**Comment by prathamesh-sonpatki** [comment]
ok. I will try to investigate more. Thanks!
