### ISSUE TITLE
Add "mustache" to match for <script> type

### ISSUE THREAD

**Issue by DarrenN** [fxbois/web-mode#534]
On a current project we define our templates thus:

```html
<script type="text/mustache" id="foo">
```

The regex on [Line 3859](https://github.com/fxbois/web-mode/blob/0e677b0ad4ba0d3ba8ae04569efc474d0d7724a1/web-mode.el#L3859) doesn't match that template type and so I lose indentation, etc.

Instead of having to add to the list of match patterns on that line, perhaps we could set additional matching patterns in a variable?

Example: 

```lisp
;; .dir-locals.el style
((web-mode . ((web-mode-template-type . "mustache"))))
```

**Comment by fxbois** [comment]
Could you post a full example on gist

**Comment by DarrenN** [comment]
Full example of the template? https://gist.github.com/DarrenN/7b9459857a9963418529

**Comment by fxbois** [comment]
why do you use a script tag for this ?

**Comment by DarrenN** [comment]
This is a pretty common pattern for dropping templates into an existing HTML page. When its set to:

```html
<script type="text/template" id="foo">
```

Everything works fine as the pattern matches, but I'm working with a team that has been using `text/mustache` for a while in the project.

**Comment by fxbois** [comment]
@DarrenN I've pushed a fix

**Comment by DarrenN** [comment]
Thanks for your help, and for you efforts on this very useful package.
