### ISSUE TITLE
web-mode-set-engine doesn't list jsx

### ISSUE THREAD

**Issue by eguneys** [fxbois/web-mode#535]
I have described my problem here: http://stackoverflow.com/questions/31020635/how-to-set-web-mode-content-type-for-react-js-files-using-minibuffer

It would be nice to auto detect jsx in js extension however If I want to do it manually I can't use
`web-mode-set-engine` because it doesn't list jsx.

**Comment by fxbois** [comment]
```(web-mode-set-content-type "jsx")```

**Comment by eguneys** [comment]
@fxbois that doesn't work on minibuffer, I want to execute a command after pressing `M-x`

**Comment by fxbois** [comment]
@eguneys I've pushed a fix

**Comment by eguneys** [comment]
Now I can't set it in my config file like so!

```
;; this works
(add-hook 'web-mode-hook (lambda()
                           (local-set-key (kbd "C-M-x RET") 'web-mode-set-content-type)
                           ))
```

```
;; this fails
(add-hook 'web-mode-hook (lambda()
                           (local-set-key (kbd "C-M-x RET") (web-mode-set-content-type "jsx"))
                           ))
```

maybe rollback this commit?

**Comment by fxbois** [comment]
@eguneys I won't roll back ... perhaps try a lambda that embeds web-mode-set-content-type
