### ISSUE TITLE
Indentation problem with multi-line PHP strings

### ISSUE THREAD

**Issue by 501st-alpha1** [fxbois/web-mode#536]
I'd like to report a problem with the indentation of multi-line PHP strings. Currently, this is how `web-mode` indents such strings:

    $someVar = myfunction("this is my really long string"
                         ."here it continues on the next line");

But I would prefer it to be indented like this:

    $someVar = myfunction("this is my really long string"
                          ."here it continues on the next line");

This makes more sense to me, because the `.` is not related to the function call. (Note however that I would like this behavior to apply even when the string is not part of a function call.) If some prefer the current behavior, perhaps a configuration option could be added to allow the user to choose which to use?

**Comment by fxbois** [comment]
@501st-alpha1 you can update to the last version on github and add ```(add-to-list 'web-mode-indentation-params '("lineup-quotes" . nil))``` in your .emacs

**Comment by 501st-alpha1** [comment]
Works great, thanks!
