### ISSUE TITLE
Heredoc HTML/JAVASCRIPT not highlighted

### ISSUE THREAD

**Issue by nerton** [fxbois/web-mode#537]
I use webmode for PHP and it works well, aside from one thing. Heredoc HTML/JS is not highlighted at all. It shows up as regular PHP string.

I have this code for example:

    $var = <<<EOTHTML

    <script type="text/javascript">

    var test;

    function initialize() 
    {
      alert(3);
    }

    </script>

    EOTHTML;

EOTHTML is used to indicate HTML content in string, web-mode-enable-heredoc-fontification is set to t , web mode is quite recent: 11.1.10, yet it does not highlight heredoc stuff at all.

What can be the problem?

**Comment by fxbois** [comment]
@nerton you should prefer HTML to EOTHTML ...
But I do not deal with html/js

**Comment by nerton** [comment]
As you can see there is HTML in it, but the <script type="text/javascript"> part is not highlighted either. Why? It's a HTML tag. It does not work even if it's HTML only. E.g.:

    $test = <<<EOTHTML
    <div id="test" style="width: 100%; height: 500px"></div>
    EOTHTML;

Nothing is highlighted, not the tags, not the attributes. Why is that?

**Comment by nerton** [comment]
Now, I see it works with <<<HTML, instead of EOTHTML. That was the problem. But then why the official page mentions EOTHTML?  

http://web-mode.org/

>  Heredoc (cf. PHP strings) fontification (when the identifier is <<<EOTHTML or <<<EOTJAVASCRIPT)

Looks like EOTHTML stopped working for some reason.

**Comment by fxbois** [comment]
@nerton you're right, I've solved this with last commit

**Comment by nerton** [comment]
Great, thanks.
