### ISSUE TITLE
Indenting PHP ternary operator in a concatenation is not definitive

### ISSUE THREAD

**Issue by nerton** [fxbois/web-mode#538]
Here's this simple example:

    $test = "test" .
                  ($test ? 

When pressing TAB repeatedly on the ($test line, web mode moves the line to the right, instead of keeping it indented below "test"

**Comment by nerton** [comment]
I mistakenly submitted this issue halfway when typing.  I added the missing details to the issue.

**Comment by nerton** [comment]
Looks like it's not the ternary operator, the starting paren is enough.

**Comment by fxbois** [comment]
@nerton I've pushed a fix

**Comment by nerton** [comment]
Thanks,  I did a quick test and it seemed to have fixed it.
