### ISSUE TITLE
SQL support to heredoc strings

### ISSUE THREAD

**Issue by nerton** [fxbois/web-mode#540]
I propose adding SQL support to heredoc which is a practical way of writing SQL to avoid quoting issues in the query string.:

    $query = <<<SQL

    select * from a
    where description like '%"some quoted stuff"%'

    SQL

Also, since the heredoc tag makes it unambgious that the code is SQL, this can also support lower case keywords, because upper case keywords are remnants of an era when editors didn't do syntax highlight.

See, e.g.:

http://stackoverflow.com/questions/292026/is-there-a-good-reason-to-use-upper-case-for-sql-keywords

**Comment by fxbois** [comment]
@nerton thx, I'll work on this

**Comment by fxbois** [comment]
@nerton have you try the last version on github ?

**Comment by nerton** [comment]
I've just tried it, it seems to work well. It highlighted even the lower case keywords in SQL heredoc. Thanks!
