### ISSUE TITLE
How to use color name in css ?

### ISSUE THREAD

**Issue by hello-code** [fxbois/web-mode#541]
Some colors, like HTML colors name (yellow, red, …) and rgb() ones are automatically activated in some mode like html-mode or css-mode. But I found only `#xxx` in web-mode.
How to use color name automatically colorization in css ?
Thanks!

**Comment by fxbois** [comment]
@hello-code perhaps you should disable web-mode internal mechanism and use rainbow-mode

**Comment by hello-code** [comment]
Thank you for your reply!Thanks `web-mode`!
If `web-mode` have this feature would be great!
