### ISSUE TITLE
[ERB] Multiline array indentation broken

### ISSUE THREAD

**Issue by darkpssngr** [fxbois/web-mode#542]
When I try to define a multiline array, the indentation does not reset once the block is complete.
This is how it looks .
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/4415079/8590709/ac7aaffe-2640-11e5-857e-0492c9af24c0.png)
It should be like this
![screen shot 2015-07-09 at 1 48 48 pm](https://cloud.githubusercontent.com/assets/4415079/8590786/471803cc-2641-11e5-85f4-b32217d3c67e.png)

--- WEB-MODE DEBUG BEG ---
versions: emacs(25.0) web-mode("11.2.15")
vars: engine("erb") minor("erb") content-type("html") file("/Users/user/test.html.erb")
system: window(nil) config("x86_64-apple-darwin14.3.0")
colors: fg(nil) bg(nil)
minor modes: (global-eldoc-mode ido-everywhere flx-ido-mode projectile-mode projectile-global-mode)
vars:
web-mode-enable-current-column-highlight=nil
web-mode-enable-current-element-highlight=nil
indent-tabs-mode=t
--- WEB-MODE DEBUG END --

**Comment by fxbois** [comment]
@darkpssngr for the closing bracket, I'll work on this.
For the ```b=10``` line, it won't be possible. Can you add a ```;``` after ```]``` ?

**Comment by darkpssngr** [comment]
Tried adding ; too still the next line is locked at that place.

**Comment by fxbois** [comment]
@darkpssngr I've updated ruby indentation on master

**Comment by darkpssngr** [comment]
Thanks, it fixes the issue.
