### ISSUE TITLE
Indentation for chained methods in javascript

### ISSUE THREAD

**Issue by kryft** [fxbois/web-mode#544]
Is it possible to get indentation like this in web-mode?

<pre>
var result = someObject
                 .method1()
                 .method2()
                 .method3();
</pre>

Currently this would get indented as

<pre>
var result = someObject
             .method1()
             .method2()
             .method3();
</pre>

**Comment by fxbois** [comment]
@kryft no it is not possible

**Comment by bleadof** [comment]
Seriously? That's the worst reply for a request I've seen in a while. :grin:

**Comment by fxbois** [comment]
Sorry I should have written : I ll be happy to accept your patch.

**Comment by fxbois** [comment]
@kryft I just scanned your issue and was wondering if your needed an alignement on the first uppercase letter or just an additional indent offset

**Comment by kryft** [comment]
@fxbois Um, now that I read the issue again, I realize that the following is what I *actually* wanted, assuming a basic indentation of four spaces:
<pre>
someCall();
var result = someObject
    .method1()
    .method2()
    .method3();
return result;
</pre>

So basically indenting the chained method calls as if there were an opening bracket after someObject and a closing bracket after the final chained call.

Apologies for the confusing initial question! I should sleep more.

**Comment by fxbois** [comment]
@kryft you should read about ```(add-to-list 'web-mode-indentation-params '("lineup-calls" . nil))``` on web-mode.org
No problem for the initial post ... I would think that people like @bleadof should sleep more

**Comment by bleadof** [comment]
@fxbois Well, I'm actually in the camp of people being nice on the Internet and one-line replies saying it's not possible aren't nicest ways of replying. Or do you disagree?-)

**Comment by kryft** [comment]
@fxbois Ah, indeed; I should have read the docs more carefully. Thank you!
