### ISSUE TITLE
Optional HTML tags not taken into account for indentation

### ISSUE THREAD

**Issue by aumo** [fxbois/web-mode#546]
The [HTML specification](https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission) defines tags that may be omited in certain circumstances.  
**web-mode** does not seem to take that into account when indenting, example:

```html
<tr>
  <td>Cell 1
    <td>Cell 2
```
when it should be:
```html
<tr>
  <td>Cell 1
  <td>Cell 2
```

Using Emacs 24.3.1
with web-mode version 20150709.1434
on Ubuntu 12.04

**Comment by fxbois** [comment]
Hi this feature would be very difficult to implement if i wan't to maintain a good performance. 
Clearly not a priority at the moment
