### ISSUE TITLE
Inconsistent indentation for anonymous PHP functions

### ISSUE THREAD

**Issue by 501st-alpha1** [fxbois/web-mode#547]
I found a problem with the way anonymous PHP functions are indented in `web-mode`. Here is an example PHP file, with `web-mode` indenting applied:

    <?php
    
    class Foo {
      public function bar() {
        SomeClass::someFunction(function () {
          $a = "foo";
          return true;
        }):
    
        SomeOtherClass::someOtherFunction($someArg, $anotherArg,
                                          function () {
                                            $a = "foo";
                                            return true;
                                          }):
      }
    }
    
    ?>

I prefer the first method, where the contents of the anonymous function are indented one level past the enclosing function call. This lines up the `});` to where I would expect it. The latter indentation appears to happen only when the anonymous function has been moved to a new line. As mentioned, I prefer the first option, but I think both cases should at least be treated consistently.

I'm using the latest version of `web-mode` from GitHub.

**Comment by fxbois** [comment]
@501st-alpha1 could you post this example the way you would like it to be please

**Comment by 501st-alpha1** [comment]
Reformatting the second example to match the first, it would look like this:

    SomeOtherClass::someOtherFunction($someArg, $anotherArg,
                                      function () {
        $a = "foo";
        return true;
    }):

**Comment by fxbois** [comment]
@501st-alpha1 sorry but I have no solution for this (a real parser would be necessary to handle this case)

**Comment by 501st-alpha1** [comment]
Bummer. Thanks for the update.
