### ISSUE TITLE
Javascript Regular expressions with quotes break highlighting

### ISSUE THREAD

**Issue by trevorsenior** [fxbois/web-mode#548]
I'm using `Version: 11.2.16` of webmode, and run into the following issue: 

```javascript
// ...
else if (/'|"/.test(placeholders.join(''))) {
    result[name].type = 'string';
}
```

Where the `/'|"/` regular expression will highlight the remaining code as a string.

![](http://i.imgur.com/0gkut8Y.png)

**Comment by fxbois** [comment]
@trevorsenior I've pushed a fix

**Comment by trevorsenior** [comment]
:+1: Thanks for the quick patches as always. Works great.
