### ISSUE TITLE
Web-mode comment-or-uncomment works only at the beginning of line. 

### ISSUE THREAD

**Issue by ReneFroger** [fxbois/web-mode#549]
For example, a Javascript snippet in `web-mode`:

      <script>
     var foobar; []
     </script>

`[]` = the cursor.

When calling `evilnc-comment-or-uncomment-lines` from [the package Evil Nerdcommenter](https://github.com/redguardtoo/evil-nerd-commenter), then `var foobar` will be commented out. 

      <script>
     /* var foobar; */ []
     </script>

When calling `webmode-comment-or-uncomment`, the `var foobar` will not be commented out.

      <script>
     var foobar; /* */ []
     </script>

So I'm wondering if there is any way to get the same behaviour as from `evilnc-comment-or-uncomment-lines` within Web-mode featureset? Nevertheless, Web-mode is awesome, and it's deeply appreciated! :smile:

**Comment by fxbois** [comment]
@ReneFroger that's a feature ... many developers put comment at the end of the line ..
but i should perhaps put the cursor between ```/*``` and ```*/``` in the cas

**Comment by ReneFroger** [comment]
Clear enough. Would it then possible to create a `webmode-comment-or-uncomment-line` out of this?

**Comment by ReneFroger** [comment]
Any update on this?

**Comment by fxbois** [comment]
@ReneFroger you should write a little function for your need.
