### ISSUE TITLE
Could wrapping text be aligned with the indentation? 

### ISSUE THREAD

**Issue by ReneFroger** [fxbois/web-mode#550]
I have the following wrapped text, especially when you use a lot of windows: 

![dmg shop keukendump](https://cloud.githubusercontent.com/assets/5211845/8895292/0586156a-33d5-11e5-9ef8-1c678556e6a0.png)

I'm wondering if the indentation of wrapped text could be changed like in Vim: 

![](http://i.imgur.com/ze2uZQG.png)
)

**Comment by fxbois** [comment]
it is the role of http://emacswiki.org/emacs/AutoFillMode

**Comment by ReneFroger** [comment]
Sorry for the delay, I just noticed it. Thanks for the link.

**Comment by ReneFroger** [comment]
If it might interest you, http://emacs.stackexchange.com/questions/14589/correct-indentation-for-wrapped-lines

**Comment by fxbois** [comment]
@ReneFroger thx for sharing
