### ISSUE TITLE
Wrong auto-closed tag in jsx file

### ISSUE THREAD

**Issue by felix-d** [fxbois/web-mode#551]
Thanks a lot for your work!

I'm using web-mode to edit my *.jsx files.  I noticed that when I use `react-bootstrap` `Col` element (or sometimes it happens with other tags too), it doesn't get closed properly, instead web-mode closes the parent element. 

```jsx
<Row>
  <Col xs={12}>
  // Caret is here
```

```jsx
<Row>
  <Col xs={12}>
</Row> // Pressing '</'
```

**Comment by fxbois** [comment]
Hi, this issue has already been submitted. Check the history with the jsx label.
