### ISSUE TITLE
Syntax highlighting for arrow functions.

### ISSUE THREAD

**Issue by g-ortuno** [fxbois/web-mode#553]
Could it be possible to include syntax highlighting for arrow functions?

For example `function` and `example` in the following code get highlighted
```javascript
Promise.resolve(function(example) {
  // code
});
```
But on this one neither `=>` nor `example` is highlighted:
```javascript
Promise.resolve(example => {
  // code
});

**Comment by fxbois** [comment]
Are there any other synthax for arrow functions ?

**Comment by g-ortuno** [comment]
What do you mean?

**Comment by fxbois** [comment]
@g-ortuno it is ok ... it will be available with the next release

**Comment by g-ortuno** [comment]
Great! Thanks! Out of curiosity when is the next release?

**Comment by fxbois** [comment]
@g-ortuno I've pushed a new version

**Comment by g-ortuno** [comment]
I see it :smile: thanks!
