### ISSUE TITLE
Javascript block comments do not work with `indent-new-comment-line`

### ISSUE THREAD

**Issue by jenanwise** [fxbois/web-mode#554]
`M-j` or `indent-new-comment-line` should extend a block comment like it does in `js2-mode` or `java-mode`.

## Expected

```javascript
/*
 *|
 */
```

`indent-new-comment-line` =>

```javascript
/*
 *
 *|
 */
```

## Actual

```javascript
/*
 *|
 */
```

`indent-new-comment-line` =>

```javascript
/*
 *
   /|
 */
```

**Comment by fxbois** [comment]
could you provide a patch ?

**Comment by jenanwise** [comment]
I'll take a look. My elisp-fu is nonexistent though :grin:

**Comment by fxbois** [comment]
@jenanwise please reopen if needed

**Comment by SamHasler** [comment]
Why was this closed? It's still an issues in 13.0.7

**Comment by fxbois** [comment]
@SamHasler do you plan to work on this ?
