### ISSUE TITLE
PHP: ?> inside a string breaks the mode

### ISSUE THREAD

**Issue by paulcdejean** [fxbois/web-mode#555]
Try pasting the following in for an example:

```
<?php
echo '/[\'^?$%&*()}{@#~?><>,|=_+?-]/';
echo "BROKEN MODE";
?>
```

**Comment by paulcdejean** [comment]
Example of the code working and properly syntax highlighted: http://codepad.org/77eLD691

**Comment by fxbois** [comment]
Hi this has already been discussed and i won t be able to solve this issue

**Comment by fxbois** [comment]
dup of https://github.com/fxbois/web-mode/issues/436
