### ISSUE TITLE
sgml-parse-tag-backward is wrong in web-mode but not in html-mode

### ISSUE THREAD

**Issue by siriustnt** [fxbois/web-mode#556]
While trying out skewer mode, I kept getting some weird errors. After searching for a while the problems seems to lie in sgml-parse-tag-backwards when used in web-mode. For some reason it gives a different result than html-mode.

	<html>
	  <head>
		<title></title>
	  </head>

	  <body>
		<h1>test</h1>
	  </body>

	</html>

When I place the point on the '<' from the closing body tag and call sgml-parse-tag-backwards I get these results:
web-mode: \<h1>
html-mode: \</h1>
I am using web-mode-20150722.12 from MELPA.

**Comment by fxbois** [comment]
I do not understand what you mean. I do not provide sgml-* functions.

**Comment by siriustnt** [comment]
I know, they are in sgml-mode. But for some reason web-mode changes the behaviour sfml-parse-tag-backwards. Since I only have this problem in web-mode I thought maybe you would know why that is.

**Comment by fxbois** [comment]
But sgml-mode is a major mode isn t it ? I have absolutly no idea how web-mode could influence an other major mode. Could you ask on emacs stackoverflow please

**Comment by siriustnt** [comment]
Ok, sorry. IThought it was something in web-mode that would interfere with it.
