### ISSUE TITLE
JSP comments not correctly paired? <%-- %> instead of <%-- --%>

### ISSUE THREAD

**Issue by rorsach** [fxbois/web-mode#558]
JSP comments aren't correctly paired.

Typing `<%-` produces: `<%-- %>`. 
I'm expecting: `<%-- --%>`

I don't really have the elisp skills to fix it, it seems. I poked around _web-mode.el_ but nothing I tried fixed it, so I'm filing an issue for it now, hoping to get it fixed or for some tips on how to fix it.

Repro steps:

1. Start emacs clean:

        > emacs -q

1. Load only web-mode 12 (from melpa-stable)

        (load "c:/Users/myusername/AppData/Roaming/.emacs.d/elpa/web-mode-12/web-mode.el")

1. Open JSP, load web-mode and enter start comment characters, note the auto inserted output is incorrect.

        M-x web-mode
        C-x C-f someJspFile.jsp
        M-x web-mode-set-engine RET jsp RET

**Comment by fxbois** [comment]
@rorsach please test the latest commit

**Comment by rorsach** [comment]
Tested, validated working

Looking at the diff, I realize the fix was something i had tried. I think the reason i wasn't seeing my fix is because of the .elc file. Note to self: when editing packaged modes, byte compile them. :)

Thanks for the fix and for web-mode.
