### ISSUE TITLE
Indentation breaks when buffer begins with whitespace

### ISSUE THREAD

**Issue by PythonNut** [fxbois/web-mode#559]
**Background:** [This question on Emacs.SE](http://emacs.stackexchange.com/questions/13074/why-is-autoheader-crashing-with-web-mode/14602#14602).

In the definition of [`web-mode-markup-indentation-origin`](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L7082), there is, essentially, the following loop:

```emacs
(while continue
  (forward-line -1)
  (back-to-indentation)
  (setq continue (not (bobp))))
```

When the buffer starts with whitespace, `back-to-indentation` does not take the point to `bolp` and therefore, we never reach `bobp`. This causes an infinite loop:

1. Try to backup another line (no-op)
2. Go back-to-indentation (i.e. _after_ the leading whitespace)
3. Check if it's at the beginning of the buffer. (it's not)

The loop will hang Emacs, and in some instances (i.e. with auto-indentation), the problem will be unrecoverable. (Requiring a `kill -9` to terminate Emacs)

Admittedly, we don't often see buffers that begin with whitespace, but still...

**Comment by fxbois** [comment]
@PythonNut should be solved with last commit

**Comment by ReneFroger** [comment]
I updated it to the latest version of web-mode, and removed my patch. And I can confirm, everything is working again without any freezing. So my issue that haunted me for months, is solved now. Thanks @PythonNut for tracking it down and @fxbois me out. 

I really appreciate all your help, and I'm working on a package to give something back to the community.

**Comment by PythonNut** [comment]
Indeed the problem seems to be fixed. Thanks @fxbois!
