### ISSUE TITLE
JSX comment

### ISSUE THREAD

**Issue by stevemolitor** [fxbois/web-mode#560]
It'd be great if `web-mode-comment-or-uncomment` supported JSX comments.  For example:

```
    <div>
      {/* 
      <div>
        This is commented out
      </div>
      */}
      {// <div>This is commented out via single line comment</div> }
    </div>
```

HTML comments don't work in JSX. You have to use the curly braces ('{', '}') to make it code, and then use Javascript comments (`//` or `/* ... */`, whatever would be easiest).

**Comment by fxbois** [comment]
@stevemolitor could you explain what you want an other way, I am not sure to understand

**Comment by stevemolitor** [comment]
Sure.  This is not valid JSX:

```
// <div>HI</div>
```

Neither is this:

```
/* <div>Hi</div> */
```

The React JSX compiler will blow up complaining of syntax errors with either of those examples. The reason is that JSX is not Javascript, and JSX does not have a comment syntax. HTML comments like `<!-- comment -->` won't work either. Instead you have wrap the JSX code you want to comment with curly braces, which escapes to JS, where you can use normal Javascript comments:

```
  {/* <div>This will work!</div> */}
```

For more information see https://facebook.github.io/react/docs/jsx-in-depth.html, the section under 'Comments': 

"It's easy to add comments within your JSX; they're just JS expressions. You just need to be careful to put {} around the comments when you are within the children section of a tag."

**Comment by fxbois** [comment]
ok, understood

**Comment by fxbois** [comment]
@stevemolitor I've started implementing this in the with the last commit

**Comment by fxbois** [comment]
reopen if needed

**Comment by stevemolitor** [comment]
Awesome thanks I will try it it out!

**Comment by stevemolitor** [comment]
Working great so far. Thanks!
