### ISSUE TITLE
switch/case indentation

### ISSUE THREAD

**Issue by kgwinnup** [fxbois/web-mode#561]
In c/c++ mode I have (c-set-style "k&r") set to properly indent switch/case keywords. Meaning the case keywords are indented 1 "tab" in from the switch keyword block. However, I don't know how to apply that same setting to web mode,

```
switch(var){
case:
    break;
}
```
to
```
switch(var){
    case:
        break;
}
```

**Comment by fxbois** [comment]
what language ?
post an example on gist please

**Comment by kgwinnup** [comment]
I am using javascript. However, when using something like the code below the indentation seems to get messed up in two different ways as seen below. It appears to work fine with functions defined in ES6 style classes.

```
var test = function(){
    var n = 10;

    switch (n){
        case:
        console.log("test");
        break;
        case:
        break;
    }
});

```

```
AppDispatcher.register(function(action){
    var n = 10;

    switch (n){
    case 9:
        console.log(n);
        break;
    case 10:
        break;
    }
});
```

**Comment by kgwinnup** [comment]
these files have extensions of both .js and .jsx

**Comment by fxbois** [comment]
Thx, I ll look at this

**Comment by fxbois** [comment]
@kgwinnup strange, I can not trigger this. Can you post the output of web-mode-debug for those two examples please

**Comment by kgwinnup** [comment]
hmm, I am using spacemacs and oddly do not have a M-x web-mode-debug function. nothing related to web mode in the *messages* buffer either. Any other ideas for how to get debug info to you?

Also, if I create a js file with only the following in it I get the indentation case.

```
function(){
    var a = 10;

    switch(a){
        case:
        break;
    }
}
```

**Comment by fxbois** [comment]
@kgwinnup perhaps the web-mode version is too old

**Comment by kgwinnup** [comment]
looking through my .emacs.d configs, and web-mode.el is 12.0.2

**Comment by fxbois** [comment]
@kgwinnup remove everything but web-mode.el related stuff for your .emacs and see if it changes anything

moreover there is no reason not to be able to call web-mode-debug

**Comment by someonewithpc** [comment]
Have the same problem

Here's the output of `web-mode-debug`

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(28.2) web-mode("17.1.4")
vars: engine("vue") minor("vue") content-type("html") file("/home/hugo/projects/space-builder/src/components/tools/Create/OptionsField.vue")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (size-indication-mode window-divider-mode show-paren-mode global-eldoc-mode general-override-mode override-global-mode +popup-mode +lsp-optimization-mode +javascript-npm-mode projectile-mode anzu-mode global-anzu-mode solaire-global-mode dtrt-indent-mode doom-modeline-mode persp-mode editorconfig-mode ws-butler-mode ws-butler-global-mode flycheck-mode global-flycheck-mode undo-tree-mode global-undo-tree-mode smartparens-mode smartparens-global-mode winner-mode hl-line-mode gcmh-mode volatile-highlights-mode marginalia-mode vertico-mode company-mode global-company-mode better-jumper-local-mode better-jumper-mode savehist-mode which-key-mode shell-dirtrack-mode global-git-commit-mode global-so-long-mode save-place-mode highlight-indent-guides-mode hl-todo-mode display-line-numbers-mode highlight-numbers-mode vi-tilde-fringe-mode npm-mode yas-minor-mode yas-global-mode flycheck-popup-tip-mode emmet-mode whitespace-mode +emacs-lisp-non-package-mode projectile-rails-mode eros-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by someonewithpc** [comment]
For anyone coming here, you're looking for `"case-extra-offset"` in the `web-mode-indentation-params` `assoc`
