### ISSUE TITLE
ac-source-css-property not working

### ISSUE THREAD

**Issue by luongtrongdai** [fxbois/web-mode#562]
First, sorry for my bad english :)

I want to use web-mode and auto-complete to edit css file. My config:

(setq web-mode-ac-sources-alist
        '(("css" . (ac-source-words-in-buffer ac-source-css-property))
          ("html" . (ac-source-words-in-buffer ac-source-abbrev))))

I see ac-source-words-in-buffer working normaly. But ac-source-css-property not working. I don't know why

**Comment by fxbois** [comment]
Hi, this is a question for emacs stackoverflow

**Comment by luongtrongdai** [comment]
@fxbois I'm not sure to understand your question. I'm a newbie of emacs. I try to find issue list and found some same question. But I can't find solution. Someone talk it a auto-complete bug

**Comment by fxbois** [comment]
@luongtrongdai please post you question on 
https://emacs.stackexchange.com/
I do not know anything about ac-source

**Comment by luongtrongdai** [comment]
@fxbois Thank you for support. I found solution is:

(defvar ac-source-css-property-names
  '((candidates . (loop for property in ac-css-property-alist
                        collect (car property)))))
then, change ac-source:
(setq web-mode-ac-sources-alist
      '(("css" . (ac-source-css-property-names ac-source-css-property))
        ("html" . (ac-source-words-in-buffer ac-source-abbrev))))

I don't know why but it working :D

**Comment by fxbois** [comment]
@luongtrongdai great, thank you for the post
