### ISSUE TITLE
web-mode not worked well with subword-mode.

### ISSUE THREAD

**Issue by zw963** [fxbois/web-mode#563]
I switch from rhtml-mode to web-mode recently.

I found some function work well previously it not worked well now.

```html
<h1> Please input Order Info </h1>

<%= render "form", role_path: 'orders/buyer' %>

<%= link_to 'Back', buyer_orders_path %>
```
When cursor at ``|buyer_order_path``, M-x `subword-kill`, I expect
1. remove buyer
2. remove _order
3. remove _path
But, it will:
1. remove buyer
2. remove _orders_path

When cursor at ``buyer_order_path|``, M-x `subword-backward-kill`,
will delete full ``buyer_order_path`` directly. What I expect is:
1. remove path
2. remove _orders
3. remove buyer

subword-mode is work well with my others major-mode, so I think it maybe
some bug here.

**Comment by zw963** [comment]
Hi, I have fixed this.
```cl
(defvar web-mode-syntax-table
  (let ((table (make-syntax-table)))
   ;; comment this can worked for me.
    ;; (modify-syntax-entry ?_ "w" table)
    (modify-syntax-entry ?< "." table)
    (modify-syntax-entry ?> "." table)
    (modify-syntax-entry ?& "." table)
    (modify-syntax-entry ?/ "." table)
    (modify-syntax-entry ?= "." table)
    (modify-syntax-entry ?% "." table)
    table)
  "Syntax table used to reveal whitespaces.")
```
but I don't know change this weather effect others.
Could you resolve this?

**Comment by fxbois** [comment]
I can not apply this patch because having _ has a word component is often useful. You should rewrite the synthax table in your .emacs

**Comment by zw963** [comment]
I don't understood `having _ has ' what means.

Anyway, thanks. I do this myself already.

**Comment by fxbois** [comment]
@zw963 I meant "having _ as a word component"

**Comment by zw963** [comment]
Oh, I see now.

Seem like can have other method to resolve this?
seem like ``_`` is as a word component in many emacs mode, 
But those mode can use subword-mode correctly? 

I have look up ruby-mode, I found this mode add syntax like this:
```cl
(modify-syntax-entry ?_ "_" table)
```

It worked for me too. this can worked for yours case?

**Comment by fxbois** [comment]
@zw963 the last commit has your change. We'll see if there is any report about this

**Comment by fxbois** [comment]
@zw963 I've canceled the patch .. to many errors with the file demo.djhtml
