### ISSUE TITLE
Highlighting via font-lock-add-keywords

### ISSUE THREAD

**Issue by 8cylinder** [fxbois/web-mode#566]
I have been using this snippet of code in my init.el to arbitrarily highlight code in other html modes, but when I use it with web-mode it doesn't work.  What I was wondering is if there is another method I could use to achieve the same thing?
```elisp
(mapc (lambda (mode)
        (font-lock-add-keywords
         mode
         '(
           ("{{.*?}}" 0 'sm/django-variable-face prepend)
           ("{%.*?%}" 0 'sm/django-tag-face prepend)
           ("{%.*?block.*?%}" 0 'sm/django-block-face prepend)
           ;<more lines here...>
           )))
      '(html-mode nxml-mode web-mode))
```

**Comment by fxbois** [comment]
I think there is an other param to use for font-lock-add-keywords

**Comment by 8cylinder** [comment]
You are correct, I had to make sure the keywords were added to the end of font-lock-add-keywords instead of the beginning by adding a non-nil argument to the third param.  

Thank you, and thanks for the awesome web-mode!
```elisp
(mapc (lambda (mode)
        (font-lock-add-keywords
         mode
         '(
           ("{{.*?}}" 0 'sm/django-variable-face prepend)
           ("{%.*?%}" 0 'sm/django-tag-face prepend)
           ("{%.*?block.*?%}" 0 'sm/django-block-face prepend)
           ;<more lines here...>
           )'end))
      '(html-mode nxml-mode web-mode))
```

**Comment by fxbois** [comment]
@8cylinder my pleasure, but I don't know why you need this. web-mode has font you can customize to get exactly the same effect

**Comment by 8cylinder** [comment]
The main reason is that I wanted the django `block` and `blockend` tags to stand out, and I have various things  like `fixme` in comments stand out also.  Plus this works across multiple modes as well.
