### ISSUE TITLE
[Un]Commenting/uncommenting of region is not worked correctly in case of spaces at beginning

### ISSUE THREAD

**Issue by AlexYegupov** [fxbois/web-mode#567]
Here are examples of two cases of incorrect commenting/uncommenting of region (;; Version: 11.1.09)

definitions:
 | - cursor position
 M - mark start and end

1) ...if spaces before text in marked region:
M|
  getAll() {
    return tracks;
  }M

2) ...if cursor is located at the end of the marked block:
MgetAll() {
    return tracks;|M

Hope that will be fixed. Thanks.

**Comment by fxbois** [comment]
Hi, I do not support old versions... can you update ?

**Comment by AlexYegupov** [comment]
tested on ;; Package-Version: 20150815.1328
For this version that all seems much better. The only found problem is the wrong uncommenting  in case of empty line presense in marked region before the comment start:

M|
  /* 
     getAll() {
     return tracks;
     }
   */M

NB: I use standard emacs mark-paragraph function (M-h) that's why spaces are occurred at the beginnging of marked region.

**Comment by fxbois** [comment]
could explain more please, I think I do not understand what you mean

**Comment by AlexYegupov** [comment]
screenshot of selection when UNcommenting doesn't work
https://yadi.sk/i/dQtS_2MLiXaR8
