### ISSUE TITLE
Lacking 1 closing parenthesis in web-mode.org

### ISSUE THREAD

**Issue by nekonenene** [fxbois/web-mode#568]
The "Context-aware auto-completion" part in "Customisation" section

You wrote : 
(setq web-mode-ac-sources-alist
  '(("css" . (ac-source-css-property))
    ("html" . (ac-source-words-in-buffer ac-source-abbrev)))

This code lacks a closing parenthesis, so an error causes.
Fix it please. Thank you.

**Comment by fxbois** [comment]
ok
