### ISSUE TITLE
please gpg sign tags (and commits?)

### ISSUE THREAD

**Issue by thkoch2001** [fxbois/web-mode#569]
I'd like to package web-mode for Debian, but I can not verify that the file downloaded from git is the one you authored. Please be so kind and use signed git tags and maybe also signed git commits for those who want to follow the master branch.

**Comment by fxbois** [comment]
do you have an howto for this?

**Comment by thkoch2001** [comment]
thx for your interest!
https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
man git-tag
why: http://mikegerwitz.com/papers/git-horror-story

git commit signing:
https://lists.debian.org/debian-devel/2015/05/msg00515.html
