### ISSUE TITLE
no info documentation

### ISSUE THREAD

**Issue by thkoch2001** [fxbois/web-mode#570]
web-mode doesn't have documentation in info format. I've never authored info docs. What would be a good workflow?
One could start with the information from http://web-mode.org

**Comment by fxbois** [comment]
@thkoch2001 yes it would be great that someone take care of it.
On my side, if I find some time, I will split web-mode.org in many pages

**Comment by thomas-koch-comsolit** [comment]
Good morning - just to understand your workflow: why did you close this issue? It could be a reminder for me and other people to work on this issue, but if it's closed the chances are smaller that it'll be resolved eventually. Or did I miss something?

**Comment by fxbois** [comment]
Ok understood. Indeed it would be great if someone work on this. On my side, i won t have the time.

**Comment by thomas-koch-comsolit** [comment]
Do you have a source file for the web-mode.org site or do you edit the html directly?

**Comment by fxbois** [comment]
I edit the html directly. I found some time ago a good mode for emacs ...

**Comment by fxbois** [comment]
Please reopen when you start to work on it.
