### ISSUE TITLE
Inentation auto insert extra single space in embedded <script> and <style>

### ISSUE THREAD

**Issue by deflexor** [fxbois/web-mode#571]
This is from web-mode FAQ:

> If you want to indent only with tabs, use: (setq indent-tabs-mode t).

But when this option is set then indentation of html markup is fine, but embedded blocks indented like this:
```
<style type="text/css">
•body, td { font: 8pt Verdana, Arial, Helvetica, sans-serif; }
•table.orders {
	•width: 740px;
	•border-collapse: collapse;
	•page-break-after: always;
 }
```
This bullet symbol  `•` i use here to show a space character, so you can see where auto indentation puts those unwanted spaces, is there way to get rid of these spaces ?

**Comment by fxbois** [comment]
@deflexor could you try  ```(setq web-mode-style-padding 0)```

**Comment by deflexor** [comment]
Thank you for quick reply, @fxbois. I did it and it seems worked for css embeds, but not for javascript embeds.

**Comment by fxbois** [comment]
```(setq web-mode-script-padding 0)```

**Comment by deflexor** [comment]
Yes, this looks like a real fix, thank you!
