### ISSUE TITLE
HTML Tag navigations shortcuts 

### ISSUE THREAD

**Issue by AlexYegupov** [fxbois/web-mode#572]
Hello.

tested on  ;; Package-Version: 20150819.1412

tested on file
https://github.com/facebook/flux/blob/master/examples/flux-chat/js/components/ChatApp.react.js

The following shortcuts seems not work:

navigation C-c C-n 

C-c C-b b block beginning
...
C-c C-b s block select

Thanks.

**Comment by fxbois** [comment]
@AlexYegupov post the output of ```web-mode-debug```

for definition of ```block```, read web-mode.org

**Comment by AlexYegupov** [comment]
after pressing C-c C-n (while cursor inside "div" of ChatApp.react.js):

Unexpected token <

**Comment by fxbois** [comment]
content-type should be jsx ... you really need to read http://web-mode.org
