### ISSUE TITLE
Unexpected indentation/dedentation with JSX in ONLY in truthy part of ternary operators

### ISSUE THREAD

**Issue by winny-** [fxbois/web-mode#573]
I am working on a lot of code with functions that builds JSX elements within ternary operators and have noticed a few issues:

```
function f() {
  var x = true ? <div></div> : '';
return x;  // pressing tab doesn't indent.
}

function f2() {
               // pressing tab here indents to the opening brace. :(
}
```

I also noticed the syntax coloring seems to be messed up with the comments. See the screenshot below

![2015-08-21-192222_818x563_scrot](https://cloud.githubusercontent.com/assets/3893828/9421503/2a8bb756-483a-11e5-9e62-65db4b4aa747.png)

According to `M-x package-list-packages` I have version `20150809.1314` installed.

**Comment by fxbois** [comment]
@winny- it is now fixed on master

**Comment by winny-** [comment]
:+1: It's in MELPA too, now. Major kudos! :cake:
