### ISSUE TITLE
Highlighting HTML entities

### ISSUE THREAD

**Issue by mmcclimon** [fxbois/web-mode#574]
(Copied from http://emacs.stackexchange.com/questions/14938/highlight-html-entities-in-web-mode.)

I often edit articles in web-mode (using PHP). It would be nice if there were some way of fontifying HTML entities (like `&#8211;`, `&eacute;`, and so on)? I'd like them to be a lighter color so that they're easier to see. Since the font-lock code in `web-mode.el` deals with lots of different flavors, I couldn't figure out exactly what to patch or where to do it myself.

Thanks!

**Comment by fxbois** [comment]
@mmcclimon with the last version on github, you can add ```(setq web-mode-enable-html-entities-fontification t)``` in your conf and customize ```web-mode-html-entity-face```

**Comment by mmcclimon** [comment]
:+1:

Perfect! Thanks so much!

**Comment by fxbois** [comment]
@mmcclimon please update the stackoverflow post
