### ISSUE TITLE
ruby keyword will highlight as a part of varible in ERB.

### ISSUE THREAD

**Issue by zw963** [fxbois/web-mode#577]
```html
  <%= link_to 'Back', not_return_path %>
```

here, `not `and `return` as ruby keyword, will highlight as a part of  a variable `not_return_path`.

**Comment by fxbois** [comment]
@zw963 not here, perhaps related to your subword setting

**Comment by zw963** [comment]
I'm affirm just now in newest version web-mode.
This is not a big problem although, thanks.
