### ISSUE TITLE
Indent after expression-type arrow function

### ISSUE THREAD

**Issue by sander** [fxbois/web-mode#579]
[Arrow functions (MDN)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) can be either of ‘statement type’ or ‘expression type’. The first indents properly in web-mode:

```javascript
const f = (x) => {
  return x + 1;
};
```

The second, without brackets, doesn’t:

```javascript
const f = (x) =>
x + 1;
```

I would expect the indentation to be:

```javascript
const f = (x) =>
  x + 1;
```

I’m using `web-mode-20150912.16` from Melpa.

**Comment by fxbois** [comment]
@sander you can try the last version on github

**Comment by sander** [comment]
Great, works well, thank you!
