### ISSUE TITLE
.jsx question: highlighting and indents also for .js files?

### ISSUE THREAD

**Issue by torgeir** [fxbois/web-mode#581]
Hi and thanks for a great emacs mode! This is merely a question, not an issue;

I see jsx highlighting and indenting kicking in when my files end in `.jsx` (on the left)

<img width="893" alt="screen shot 2015-09-14 at 21 16 33" src="https://cloud.githubusercontent.com/assets/118202/9859278/fbee0d82-5b25-11e5-849d-c2f8da5ef947.png">

What is needed to make this behavior the same for `.js` files as well?

Also, the ending paren seems to be kind of off? I haven't done too much configuration of `web-mode`, these are the interresting parts

```
(add-hook 'web-mode-hook ; http://web-mode.org/
            (lambda ()
              (dolist (mode '(js-mode html-mode css-mode))
                (yas-activate-extra-mode mode))
              (setq web-mode-markup-indent-offset indent)
              (setq web-mode-css-indent-offset indent)
              (setq web-mode-code-indent-offset indent)))
```

**Comment by jeffbski** [comment]
+1 I am interested in answer as well.

**Comment by fxbois** [comment]
@torgeir please read http://web-mode.org

**Comment by torgeir** [comment]
I have, skimmed it atleast - any part in particular?

**Comment by fxbois** [comment]
look at ```web-mode-content-types-alist```

**Comment by torgeir** [comment]
Alright, thanks.

**Comment by torgeir** [comment]
`(setq web-mode-content-types-alist '(("jsx"  . "\\.js\\'")))` did the trick.

The trailing paren is still kinda off, though
