### ISSUE TITLE
handlebars comments

### ISSUE THREAD

**Issue by pavloo** [fxbois/web-mode#582]
First of all, thanks for your work. Now down to business: commenting in `handlebars` doesn't work for me properly: html comments syntax is used instead. Valid handlebars comments syntax is `{{!-- --}} or {{! }}.` 

![untitled](https://cloud.githubusercontent.com/assets/2216562/9874860/67f1c956-5bb2-11e5-99b5-60d4923c88b4.gif)

My web-mode version is `;; Version: 12.1.2`. Can you confirm that this issue is present?

**Comment by fxbois** [comment]
@pavloo see ```web-mode-comment-style```
