### ISSUE TITLE
Html snippeet inside script tag doesn't get indented.

### ISSUE THREAD

**Issue by madhavan020985** [fxbois/web-mode#583]
Html content inside ````<script>```` tags are not properly  indented.
I started emacs --no-init, then loaded web-mode.el manually, and opened a html file, selected all text and pressed tab.

The jquery template html content written between script tag is no longer properly indented.
It looks like,
````
<script id="suiteSummaryTemplate" type="text/x-jquery-tmpl">
<tr>
<td>${suite}</td>
<td>${status}</td>
</tr>
</script>
````
It was working earlier. I was switching between 24.4 to 24.3, back and forth and updating system software. Now, it is all broken.
I am reiterating, that emacs' default html mode is indenting the same stuff properly, only when i turn on web mode, it stops working.
misc info-----------------------------
````
;; Version: 20150304.1240
;; X-Original-Version: 11.0.16
````

**Comment by fxbois** [comment]
post a screenshot please

**Comment by madhavan020985** [comment]
![emacs-tab-broken](https://cloud.githubusercontent.com/assets/4812767/9901094/d52bf228-5c82-11e5-9317-d098b8c6bc01.png)

**Comment by fxbois** [comment]
@madhavan020985 please test the last version on github

**Comment by madhavan020985** [comment]
i will do it and tell you in some time

**Comment by madhavan020985** [comment]
it works... so closing this issue

**Comment by madhavan020985** [comment]
really sorry for the above repeated actions... please ignore...
