### ISSUE TITLE
JavaScript/Jsx: Paren inside single-quoted strings breaks fontification of rainbow-delimiters mode

### ISSUE THREAD

**Issue by mbme** [fxbois/web-mode#584]
[Rainbow delimiters](https://github.com/Fanael/rainbow-delimiters) mode allows to highlight unmatched parens.
This code uses double quotes and its highlighting is ok:
```javascript
console.log(")");
```
This code uses single quotes and last brace is highlighted as unmatched:
```javascript
console.log(')');
```
Everything is ok when I use js-mode.
So probably rainbow-delimiters mode use some information provided by current major mode to detect if brace is inside string or not.

**Comment by fxbois** [comment]
@mbme could you ask the rainbow delim maintainer ?
I can provide help

**Comment by mbme** [comment]
@fxbois So, as follows from the [answer of rainbow-delimiters maintainer](https://github.com/Fanael/rainbow-delimiters/issues/19#issuecomment-141619504), web mode should properly mark single-quoted strings as strings in the syntax table

**Comment by fxbois** [comment]
impossible ... I can have strings (eg. php strings) in strings (eg. js strings)

**Comment by mbme** [comment]
but it somehow works for double-quoted strings?

**Comment by mbme** [comment]
@fxbois thanks, now everything works correctly!
