### ISSUE TITLE
Recognize typescript ".ts"/".tsx" extensions

### ISSUE THREAD

**Issue by martine** [fxbois/web-mode#585]
It would be nice if web-mode understood typescript.  There's a typescript mode already (based on javascript-mode) but web-mode understands JSX (which is HTML-like) mixed with code and typescript-mode doesn't support that.

https://github.com/aki2o/emacs-tss/blob/master/typescript.el appears to be the current recommended mode for typescript.  The comments indicate it had a replace-string of "javascript" for "typescript" and presumably some other changes.

**Comment by fxbois** [comment]
@martine please post examples of templates that embed typescript parts

**Comment by martine** [comment]
Actually, I think it already works fine, I just needed to get web-mode to treat the file as JavaScript.  (TypeScript syntax is basically ES6 syntax as far as I understand it.)

```
  (setq web-mode-content-types-alist
        '(("jsx" . ".*\\.tsx?\\'")))
```

Perhaps the fix is just building the equivalent of that into web-mode by default.

Here's a fake snippet of some TypeScript+JSX code, which web-mode seems to render just fine:

```
interface Value {
  x: Date;
  y: number;
  y0?: number;
}

function leastSquares(data: Value[]) {
   return <div>foo</div>;
}
```

**Comment by fxbois** [comment]
is *.tsx a standard extension for this kind of scripts ?

**Comment by martine** [comment]
Yes, new as of TypeScript 1.6:
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript
(see "new .tsx file extension").

**Comment by fxbois** [comment]
@martine I've pushed a fix. Modifying ```web-mode-content-types-alist``` is not needed any more.

**Comment by martine** [comment]
Great, thanks!

**Comment by martine** [comment]
I noticed that web-mode doesn't trigger for plain ".ts" files, which are typescript without jsx and analagous to .js files.  There is an existing typescript-mode emacs library that might be more appropriate for those files, but it's a little weird to use web-mode for most file types but then typescript-mode just for one specific javascript variant.

See also https://github.com/ananthakumaran/tide/issues/3 , where a derived mode triggers on the buffer using typescript-mode, which means it doesn't trigger on web-mode buffers.

**Comment by fxbois** [comment]
@martine I've pushed a fix

**Comment by martine** [comment]
Thanks!
