### ISSUE TITLE
Homepage example of web-mode-content-types-alist has bad syntax

### ISSUE THREAD

**Issue by martine** [fxbois/web-mode#586]
On web-mode.org there's this example snippet:
```
(setq web-mode-content-types-alist
  '(("json" . "/some/path/*\\.api\\'")
    ("xml"  . "/other/path/*\\.api\\'")
    ("jsx"  . "/some/react/path/*\\.js[x]?\\'")))
```

From a skim of the code it appears these are matched using string-match-p.  I don't understand emacs regexes well, but I think `/*` should match any number of slashes, which doesn't make sense for a path (?).

Perhaps this is a typo?  If not, sorry for wasting your time with useless bug reports!

**Comment by fxbois** [comment]
@martine you are right. It is now corrected. Thanks for the report.
