### ISSUE TITLE
web-mode highlight is not be applied when copy code in.

### ISSUE THREAD

**Issue by zw963** [fxbois/web-mode#587]
I found web-mode is not rendered inner tag when copy html code in current buffer.
it seem like just render the first line and the last line in some case.
e.g. following only first and last line is highlight.
```html
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"> <= 
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
```
though when editing buffer,  will correct highlight the editing tags.

is this a bug?

if this not bug, is exist a lisp function to force render right now ?

Thanks.

**Comment by fxbois** [comment]
could you try to take a video of this ?

**Comment by zw963** [comment]
I spent fifteen minutes to found a video capture program in my linux, finally, I just found a 
snapshot program.

following screenshot, after ``<body>``, and before ``</body>``,  is copied from another
buffer, it just like this, it render part of content, but not all.

In my emacs, if used with rhtml-mode, never happen this case.

http://zw963.github.io/snap1.png

Thanks.

**Comment by zw963** [comment]
just for clarify, when paste from browser, has this problem too. : )

**Comment by zw963** [comment]
If i edit some line, e.g. delete a char, it will rendered correctly at once.

**Comment by zw963** [comment]
if can not reproduce, maybe locally `auto-indent-mode` cause this?

**Comment by fxbois** [comment]
please describe a complete testcase so that I can reproduce (don't forget to post the examples)

**Comment by zw963** [comment]
## Create a new html file (1.html) with somebasic html scaffold, it default open with web-mode, 
with some base html scaffold.

## Copy some html code from browser with C-c

##  C-y (yank command) to paste code to this buffer

following ...
http://zw963.github.io/snap1.png

**Comment by zw963** [comment]
It not happen when I skip all my emacs personal script. 

thanks.

**Comment by zw963** [comment]
all right, I debug all my emacs personal script, I found this bug happen when
https://github.com/mattfidler/auto-indent-mode.el is enable ...

I guess this yesterday, I just not to try this directly...

It seem like , when I paste buffer content into web-mode,  auto-indent-mode
will be trigger at once, it will make my web-mode indent correctly, but it prevent
web-mode highlight correct render too.

I don't know this problem still is a bug ? although, I enable all my development
mode auto-indent feature, this case just happen in web-mode.

So, I enable this issue again, If you think those not a bug, please close it.

**Comment by fxbois** [comment]
I auto indent on paste ... so I won't dig this issue

**Comment by zw963** [comment]
>> I auto indent on paste 

I remove all my personal emacs config, only with following:

```el
(require 'web-mode)
(setq web-mode-script-padding 2)
(setq web-mode-enable-auto-pairing t)
(setq web-mode-markup-indent-offset 2)
(setq web-mode-css-indent-offset 2)
(setq web-mode-code-indent-offset 2)
(setq web-mode-enable-current-element-highlight t)
(setq web-mode-enable-current-column-highlight t)
(setq web-mode-enable-comment-keywords t)
;; use server comment, not html comment.
;; (setq web-mode-comment-style 2)
(setq web-mode-enable-css-colorization t)
(setq web-mode-ac-sources-alist
      '(("css" . (ac-source-css-property))
        ("html" . (ac-source-words-in-buffer ac-source-abbrev))))


(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
(setq web-mode-engines-alist '(
                               ("erb" . "\\.erb\\|\\.r?html?\\'"))
      )
```

But , it not auto-indent when I paste, where I have mistaken?
How can I `auto indent on paste ` ?

Thanks.

**Comment by fxbois** [comment]
could you try the last version on github please

**Comment by zw963** [comment]
Thank very much for quick reply.

But still not worked for me : ( 

(clean emacs with only basic web-mode settings)

**Comment by fxbois** [comment]
how do you yank your text ?
Could you post the output of ```web-mode-debug```

**Comment by zw963** [comment]
before paste:
```el
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.3) web-mode("12.2.6")
vars: engine("erb") minor("erb") content-type("html") file("/home/zw963/Dropbox/common/code/bootstrap/1.html")
system: window(x) config("x86_64-slackware-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: nil
vars:
web-mode-enable-current-column-highlight=t 
web-mode-enable-current-element-highlight=t 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---
```

after paste:
```el
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.3) web-mode("12.2.6")
vars: engine("erb") minor("erb") content-type("html") file("/home/zw963/Dropbox/common/code/bootstrap/1.html")
system: window(x) config("x86_64-slackware-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: nil
vars:
web-mode-enable-current-column-highlight=t 
web-mode-enable-current-element-highlight=t 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---
```
here is the snapshot before I paste and after i paste.

http://zw963.github.io/111.png
http://zw963.github.io/222.png

**Comment by zw963** [comment]
After update, cause indent error.

following `<% end %>` is not indent correctly

```html
<div id="buyer_rating_form">
  <%= form_tag "#", method: :post, style: 'display:none' do %>
<% end %>
</div>
```

**Comment by zw963** [comment]
another example, label not indent correctly.

```html
        <label class="btn btn-primary active">
          <input type="radio" name="rating" value="good" autocomplete="off" checked><%= Rating.human_attribute_name("rating.good") %>
          </label>
```

**Comment by fxbois** [comment]
I don't know it works on my machine

**Comment by zw963** [comment]
I pull code just now.

previous two problem is fixed in fbef5c3...252ba1d. Thanks.

**Comment by fxbois** [comment]
cool

**Comment by zw963** [comment]
Hi, this bug not fixed.

fbef5c3...252ba1d only fix the new bug introduced for fix this issue.

That is:

before paste:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  <body>
    <!-- Modal -->
         | <== my cursor at here.
  </body>
</html>
```

And at this position, I paste this:
```html
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>
```

Result:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  <body>
    <!-- Modal -->
	<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>  
  </body>
</html>

```

The problem is  ``<button type="button" ....>`` and ``</button>`` not auto-indent according to context. (<body> tag)

**Comment by fxbois** [comment]
@zw963 does not appear on my machine. 
Do not forget to ```(setq web-mode-enable-auto-indentation t)```
Perhaps related to a minor mode.
This bug is closed for me

**Comment by zw963** [comment]
```(setq web-mode-enable-auto-indentation t)``` is worked, Thank you very much!
