### ISSUE TITLE
Javascript/JSX: bad detection of the end of regex literal

### ISSUE THREAD

**Issue by mbme** [fxbois/web-mode#588]
Currently web mode doesn't highlight correctly js regex literals when they contain escaped slash:
```javascript
'test/1'.match(/[a-z]+\/[0-9]+/g)
```
In this case regex highlighting works only to the escaped slash (`\/`)

**Comment by fxbois** [comment]
@mbme could you provide a patch ?

**Comment by fxbois** [comment]
@mbme I've pushed a fix to solve this

**Comment by mbme** [comment]
@fxbois Thanks, fixed

Next time I'll try to provide a patch, but its hard to start working on such a large major mode for elisp newbie like me :)
