### ISSUE TITLE
M - ; comments not closing 

### ISSUE THREAD

**Issue by seanareed** [fxbois/web-mode#589]
I recently upgraded web-mode.

I use it with PHP, and love it.

Since then, the M - ; shortcut for comments doesn't close those comments in a PHP block within web-mode.

Is it possible that this is due to a change in web-mode?

I'm attaching images of what it used to do and what it does now.

Thanks,
Sean

![old](https://cloud.githubusercontent.com/assets/14617978/10001624/af1b198c-6070-11e5-8f11-4f8177b936a1.jpg)

![now](https://cloud.githubusercontent.com/assets/14617978/10001629/b70ec4ea-6070-11e5-81a2-7efa2d9f6220.jpg)

**Comment by fxbois** [comment]
@seanareed I do not plan to provide this kind of comments ... perhaps someone could provide a function (ask on stackoverflow)

**Comment by seanareed** [comment]
Ok. Thanks. I may take a stab at it myself. Cheers, S

**Comment by itkach** [comment]
It also does this now when editing javascript too. If I set web-mode-set-content-type to jsx in js buffer then it closes the comment properly.

**Comment by seanareed** [comment]
Thanks! 
That works for me too!

Is there a way to add something to the init file that automatically sets this on opening php files?

**Comment by itkach** [comment]
Setting wrong content type on a buffer is a useful workaround, but this is still broken, inserts /*. Should this issue really be closed?
Ideally, for javascript it should be // (these can be nested while multi-line comments can't be).

**Comment by fxbois** [comment]
as I wrote in my first comment, I do not plan to work on this. Perhaps someone could write a minor mode to handle this

**Comment by jasondf** [comment]
Well, I got the same issue, and try to do a stab myself, lucky me it works. Here is the screenshot:
<img width="651" alt="screen shot 2015-10-08 at 01 17 48" src="https://cloud.githubusercontent.com/assets/9963736/10345253/e93474b4-6d5a-11e5-9698-f612b61f19a2.png">
Now M-; works in PHP file and php block in HTML file. Although I don't know if there is any side effects.

**Comment by seanareed** [comment]
I looked at the diffs from the commit to web-mode.el on 15-Sep-2015 ('jsx commenting'), which is when I noticed the change in behavior.

The original code had a (not ) that is missing in the new code.

I don't know if this was intentional or an oversight.

However, adding that (not ) back in returns the proper closing behavior that was present before.

![not](https://cloud.githubusercontent.com/assets/14617978/10354049/24413eec-6d2a-11e5-81fa-c969901819a1.jpg)

Changing line 8302 in the added code (green) to (not (string= alt "/*"))) remedies the issue for me.

-S

**Comment by seanareed** [comment]
(...however, I have to evaluate the web-mode.el buffer for it to take effect.)

**Comment by seanareed** [comment]
(...ah, yes... the .el library must be byte-compiled first... there is an .elc version.)

**Comment by jasondf** [comment]
@seanareed it works for me, thanks a lot.
