### ISSUE TITLE
un-balanced parenthese in source code

### ISSUE THREAD

**Issue by stardiviner** [fxbois/web-mode#590]
Because the `web-mode.el` is really huge, I can't open it with Emacs, it stucked, also can't edit on GitHub website. So I write down this issue.
The un-balanced parenthese is at the end of `(when offset`.

**Comment by fxbois** [comment]
I've just byte-compiled it and no error raises.

**Comment by stardiviner** [comment]
When I source code jump with `[M-.]` into the file `web-mode.el`, then paredit reported un-balanced parentheses. Because big file stucked my Emacs, so I can't verify it. You can check it in function `web-mode-indent-line`.

**Comment by fxbois** [comment]
If there was an issue with unbalanced parenthese, I guess I would receive many alerts from the numerous users of web-mode. Moreover byte-compile would trigger an error. I am sorry but can not help you. Perhaps try on emacs stackoverflow

**Comment by stardiviner** [comment]
This is the last time I check on this issue, sorry I have to update one time.
Here is the screenshot I open `web-mode.el` with `emacs -q`

![out](https://cloud.githubusercontent.com/assets/378699/10017400/890fa866-6160-11e5-872f-8e7c205ceb8c.gif)

**Comment by stardiviner** [comment]
Sorry, I think could be other reason like paredit configure error.

**Comment by stardiviner** [comment]
close it
