### ISSUE TITLE
web-mode-engines-alternate-delimiters no longer working

### ISSUE THREAD

**Issue by ericnorris** [fxbois/web-mode#592]
A while back I filed #175, regarding using customizable delimiters with smarty (i.e. `{%` instead of `{`).

Although this was helpfully pushed out into [this beta](http://web-mode.org/beta/web-mode.el), it seems that the latest version does not respect the `web-mode-engines-alternate-delimiters` option.

Is it possible to get this into the latest version?

**Comment by fxbois** [comment]
this brought a lot of complexities ... you should stick to the version that responds to your needs

**Comment by ericnorris** [comment]
@fxbois, okay, is there no other way to handle `{%` in web-mode? Perhaps an addition to [this](https://github.com/fxbois/web-mode/blob/252ba1d4c7ddc8bcf022954cc22130520636a4b2/web-mode.el#L1067)? It's disheartening to not be able to use the latest version, but I appreciate your quick response.

**Comment by fxbois** [comment]
I'll try to look at this when I have some time.

**Comment by fxbois** [comment]
I won't have time to work on this. Perhaps you could directly modify web-mode
