### ISSUE TITLE
web-mode and wrap-region

### ISSUE THREAD

**Issue by djangoliv** [fxbois/web-mode#593]
I use emacs-25 with last web-mode.el 
When wrap-region (https://github.com/rejeep/wrap-region.el) is enable the HTML tag auto closing doesn't work.
So I must do (add-to-list 'wrap-region-except-modes 'web-mode)... not very serious, but annoying

**Comment by fxbois** [comment]
I won't dig it but I can provide help

**Comment by fxbois** [comment]
If you need help, please reopen.
