### ISSUE TITLE
Doesn't align by html attribute

### ISSUE THREAD

**Issue by ElectricCoffee** [fxbois/web-mode#594]
According to the website attributes should align automatically by each other. But I've found that this isn't the case at all. 

So instead of getting this:

    <div data-foo=""
         data-bar=""
         data-baz=""></div>

    <select data-foo=""
            data-bar=""
            data-baz=""></select>

    <blockquote data-foo=""
                data-bar=""
                data-baz=""></blockquote>

I get this:

    <div data-foo=""
            data-bar=""
            data-baz=""> </div>

    <select data-foo=""
            data-bar=""
            data-baz=""></select>

    <blockquote data-foo=""
            data-bar=""
            data-baz=""></blockquote>

I'ts no major issue, but it's annoying to look at.

**Comment by fxbois** [comment]
you should look at web-mode.org (TAB indentation)

**Comment by ElectricCoffee** [comment]
I did, there's no useful information regarding alignment. In fact it says alignment by attribute is enabled by default

**Comment by fxbois** [comment]
have you disabled indent-tabs-mode ?
```(setq indent-tabs-mode nil)```
