### ISSUE TITLE
Indentation inside an underscore escape

### ISSUE THREAD

**Issue by lbstoller** [fxbois/web-mode#596]
Hi, given an html file with the underscore engine, is auto indentation of
this fragment supported? Everything is left justified ... 

<%
var title_text  = "";
var expand_text = "";
if (1) {
title_text = "foo";
expand_text = "Add Key";
}
%>

**Comment by fxbois** [comment]
is it standard javascript ?

**Comment by lbstoller** [comment]
> is it standard javascript ? 

Seems like standard JS code to me. 

Leigh

**Comment by fxbois** [comment]
@lbstoller you can test the last version on github

**Comment by lbstoller** [comment]
> @lbstoller you can test the last version on github 

Okay, I just downloaded that and tried it out; no change … 

Leigh

**Comment by fxbois** [comment]
could you post the output of ```web-mode-debug```

**Comment by lbstoller** [comment]
> could you post the output of web-mode-debug 

Ah, I am glad you had me do that … I was indeed running the older
version cause of a file naming mistake I made. Thanks! Works much
better now.

Leigh
