### ISSUE TITLE
[Feature Request] Flow Support

### ISSUE THREAD

**Issue by bieber** [fxbois/web-mode#599]
I don't think web-mode is explicitly intended to support Flow (flowtype.org), but it actually handles most Flow syntax in pretty well in JSX mode.  The only major issue I run into is that if I have any kind of type parameter in angle braces, it totally breaks the indentation for the rest of the file.  For instance:

    function getInstructions(): Array<HTMLElement> {
    												indentationGoesOutToHere();

Feel free to close of course if you're not interested in Flow support. If you don't have time or interest to do it yourself though, would you be open to a pull request for it?

**Comment by fxbois** [comment]
@bieber can flow handle jsx elements ? If not, prefer the ```javascript``` to the ```jsx``` content type

**Comment by bieber** [comment]
Yep, it can work in both JSX and non-JSX files.  The way to differentiate them would be to look for them only in the places where type expressions are allowed.  For instance:

    var x: Array<number> = [5];
    function f<T>(xs: Array<T>): Array<T> {
      return xs.map(x => x + 1);
    }
    type X = {
      arr: Array<SomeType>;
    };
    class Container<T> {
      ...
    }

Basically, type expressions should only appear after a colon in a variable or function declaration, in a type = declaration, or immediately after the name of a class or function (in that latter case, I'm pretty sure it's restricted to just a list of type parameters).  They shouldn't be able to appear anywhere that a JSX expression would be legal

**Comment by fxbois** [comment]
@bieber it seems to me very dangerous. I do not have a valid js parser and can not be sure to detect a type or an element. The only way for me would be to decide that this is a type when the character directly before ```<``` is a letter. 
Is there a discussion somewhere about this ?

**Comment by aaronjensen** [comment]
@fxbois This would be super helpful for me as well. `web-mode` doesn't work very well when using generic types in flow.

The idea of checking for a preceding character probably would not work unfortunately:

```js
// This is valid with flow
type t = <T>(t: T) => T

// This is valid jsx
const x = <div>h<span>i</span></div>
```

**Comment by fxbois** [comment]
@bieber @aaronjensen @vjeux do you have any advice how I could differentiate the two syntaxes ?

**Comment by aaronjensen** [comment]
@fxbois I'm not familiar with how web-mode is is currently parsing js files so I doubt I could provide much help.

My guess is that you'd need to add support for type expressions if you don't have it already and then follow the examples in [the above comment](https://github.com/fxbois/web-mode/issues/599#issuecomment-145368712).

Also add in arrow functions:

```js
const x = <T>(x: T): T => x
```

There's also this potential edge case:

```js
const x = <T, Y: Foo<T>>(x: T): T => x
```

**Comment by vjeux** [comment]
cc @jeffmo

**Comment by jeffmo** [comment]
As @aaronjensen says, it really depends on how `web-mode` is parsing things...

For the stated edge case, the most generic approach might be to parse into a "cover grammar" -- some structure that can accomodate all of the commonalities between JSX and a type param instantiation list. Then once you hit the first character that discriminates between the two (in the example, it would be the `,` after the first `T`), simply convert the generic structure into the correct one.
