### ISSUE TITLE
Preserve code folding

### ISSUE THREAD

**Issue by ChillarAnand** [fxbois/web-mode#600]
Hi when  i do some code folding, kill buffer and re open it, code was gone. Is there a way to preserve code folding?

**Comment by fxbois** [comment]
code was gone ? what do you mean ? you lost code or the folding ?
If it is the folding, I do not plan to work on bringing the folding back after a kill/open

**Comment by ChillarAnand** [comment]
I lost the folding. 

> I do not plan to work on bringing the folding back after a kill/open

Why?

**Comment by fxbois** [comment]
It would need to maintain a state in a separate file, I do not wan't to enter this kind of stuff ... this is the role of an other minor mode

**Comment by ChillarAnand** [comment]
Thanks!

**Comment by ChillarAnand** [comment]
[vimish-fold](https://github.com/mrkkrp/vimish-fold) preserves code folding.

**Comment by fxbois** [comment]
great .. is there any compatibility with web-mode ? I could provide help (or helpers)

**Comment by ChillarAnand** [comment]
web mode fold automatically figures out begining/ending of element and folds accordingly.

vimish fold takes begining/ending of a region(or current active region) and folds it.

if you can provide a wrapperr around vimish fold which figures out beg/end of element and folds it, it would be great.
