### ISSUE TITLE
Error auto-indenting PHP

### ISSUE THREAD

**Issue by cosarara97** [fxbois/web-mode#601]
Auto-indenting the following code (using indent-region), I'm getting an "Invalid search bound (wrong side of point)":

    <?
    while (1) {
    ?>
    <?
    }
    ?>

Checking for (< limit (point)) in web-mode-block-opening-paren-position before the regex seems to solve it, but I'm not sure if that's the proper fix.

**Comment by fxbois** [comment]
@cosarara97 could you describe a complete scenario to trigger this please

**Comment by cosarara97** [comment]
Let's see...

First save the code I pasted above as /tmp/test.php

    $ cd /tmp
    $ wget https://raw.githubusercontent.com/fxbois/web-mode/master/web-mode.el
    $ emacs -Q

M-x load-file (ret) /tmp/web-mode.el

C-x C-f /tmp/test.php

M-x web-mode

(select everything)

M-x indent-region

(error appears in the messages buffer and at the bottom of the screen)

**Comment by cosarara97** [comment]
What I did is http://hastebin.com/ronimololi

**Comment by fxbois** [comment]
@cosarara97 thx, I've pushed a fix
