### ISSUE TITLE
Web-mode syntax highlighting gets deleted when applying an overlay

### ISSUE THREAD

**Issue by ReneFroger** [fxbois/web-mode#606]
## Setup:
GUI version GNU Emacs 25.0.50.1 (x86_64-w64-mingw32)
of 2015-07-25 on KAEL

[Compiled from EmacsW64.](http://emacsbinw64.sourceforge.net/)

Web-mode, using the latest version of web-mode from MELPA
vimish fold, using the latest version of vimish fold from MELPA

## Situation:
Currently I use the package [vimish-fold](https://github.com/mrkkrp/vimish-fold/). For various modes, the syntax highlighting is contained inside the fold. But this is not the case for `web-mode`.
As stated in the issue https://github.com/mrkkrp/vimish-fold/issues/28 with a screencast to illustrate this issue:

![webmode](https://cloud.githubusercontent.com/assets/5211845/10338866/a58cf256-6d08-11e5-8bf5-b88c82f89ba3.gif)

 I would like to debug, but I have no idea why the syntax highlighting is not applied in the folds. Any suggestion?

The author of `vimish-fold` can also reproduce this issue. Vimish-fold just creates and deletes overlays — nothing more, there is almost no place where such a “bug” could creep in. Also note that all other modes don't suffer from this kind of flaw. So I wonder how coloration is done and why this bug takes place with web-mode and not with any other mode?

**Comment by fxbois** [comment]
@ReneFroger I've read the vim-mode issue. It seems to have issue with ruby-mode.
I can provide help but I do not dig minor mode issues

**Comment by fxbois** [comment]
reopen when needed
