### ISSUE TITLE
Support "outline" tags in template-toolkit

### ISSUE THREAD

**Issue by madsen** [fxbois/web-mode#608]
Template Toolkit 2.26 added support for ["outline" tags](https://metacpan.org/pod/distribution/Template-Toolkit/lib/Template/Manual/Syntax.pod#Outline-Tags).  This lets you write

```
%% IF condition
  <h1>Hello</h1>
%% END
```
instead of
```
[% IF condition -%]
  <h1>Hello</h1>
[% END -%]
```
They mean the same thing, and can be mixed in the same file.

But web-mode doesn't currently recognize the outline syntax.  It'd be nice if it did.  I'm particularly interested in outline-style comments (`%%#`) as that's what I generally use it for.

Thanks for writing web-mode.  I just came across it, and it looks like what I've been looking for.

**Comment by fxbois** [comment]
@madsen I've added ```%%#``` comments
