### ISSUE TITLE
Nested curly braces blocks are used to finish outer ones [Syntax highlighting

### ISSUE THREAD

**Issue by CestDiego** [fxbois/web-mode#611]
@fxbois This was an issue I fogot to point to at  #609. 

> If there are nested curly braces, syntax highlighting also screws up a little, for example in the code above, the nested `}` in the inner curly braces block is used by the outer block to finish it, and so the rest of the code is seen as `invalid` and so is bright red. While on the example as how it should look that part looks fine. I hope I'm not being too pushy, I'm very thankful that you responded to this issue fast.

**Comment by fxbois** [comment]
post your example on gist

**Comment by CestDiego** [comment]
https://gist.github.com/dd03a7102266cd2f4910

**Comment by CestDiego** [comment]
syntax hightlighting is the main issue here, the identation is **kinda** solved in #609

**Comment by fxbois** [comment]
@CestDiego please test the last version

**Comment by CestDiego** [comment]
issue is still persistent, is there a way i can be of more help to resolve the issue?

**Comment by fxbois** [comment]
With the last version I have this. What is the issue ?
![0611](https://cloud.githubusercontent.com/assets/959622/10570853/cdb83c16-7638-11e5-83d2-2f7a9b294114.png)

**Comment by CestDiego** [comment]
I got this

[![alt](https://i.imgur.com/rgsEF5T.png)](https://i.imgur.com/rgsEF5T.png)

**Comment by CestDiego** [comment]
oh....ok Sorry I think I got my modes messed up. It's something on my end. This is resolved. I was using react-mode which is based on web-mode, this is how spacemacs treats jsx files. It must be the js minor mode doing syntax highlighting as well.
