### ISSUE TITLE
CSS colorization does not display at all (inc Rainbow mode)

### ISSUE THREAD

**Issue by AnOctopus** [fxbois/web-mode#612]
When web-mode is enabled, it fails to fontify CSS colors (#abc and #aabbcc). The presence of web-mode also causes rainbow-mode to not fontify any colors, where switching to another mode (eg html-mode) will cause rainbow mode to work as expected.

Bug occurs in the latest versions of Emacs and web-mode, in a clean (emacs -q) emacs process.

Steps to reproduce:
* Open new buffer
* Enable web-mode
* Type #aabbcc 
* Nothing happens
* Enable rainbow-mode
* Nothing happens
* Enable html-mode and re-enable rainbow-mode
* #aabbcc has background color changed as expected

--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("12.3.5")
vars: engine("erb") minor("erb") content-type("html") file("test.html.erb")
system: window(x) config("x86_64-unknown-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: nil
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@AnOctopus please post your example on git

**Comment by AnOctopus** [comment]
@fxbois since the issue is about fontification, I'm not sure what to even put on gist. Instead, I've uploaded screenshits showing the issue as described.


![emacs anoct_011](https://cloud.githubusercontent.com/assets/7356217/10417487/6fac649a-6ff2-11e5-9c39-4da7d6a637cb.png)
![emacs anoct_012](https://cloud.githubusercontent.com/assets/7356217/10417488/6fad49c8-6ff2-11e5-9c29-17a52a81d515.png)
![emacs anoct_013](https://cloud.githubusercontent.com/assets/7356217/10417489/6fafceaa-6ff2-11e5-826d-8a587dd19833.png)

**Comment by fxbois** [comment]
Test with a valid css file

**Comment by AnOctopus** [comment]
In a css file:
Web-mode css colorization works
Rainbow-mode colorization (eg "red") does not work, even if web-mode colorization is disabled
Rainbow-mode colorization works if web-mode is changed to css-mode

**Comment by fxbois** [comment]
It should be related to the third param of font-lock-add-keywords
see https://github.com/fxbois/web-mode/issues/566

**Comment by AnOctopus** [comment]
I was able to get correct behavior from web-mode + rainbow-mode by setting the third param as suggested, so I will contact the rainbow-mode maintainer about changing this.
