### ISSUE TITLE
Auto expanding in jsx

### ISSUE THREAD

**Issue by rockneurotiko** [fxbois/web-mode#613]
I would really love to have auto expanding in jsx files.

I don't know if this is possible right now, I have it enabled and expands in html, but not in jsx.

**Comment by fxbois** [comment]
@rockneurotiko it is ok with last commit (only for elements inside the top level element)

**Comment by rockneurotiko** [comment]
Yeah, it works! Really thanks :smile:

**Comment by domtronn** [comment]
I'm still having trouble with this 😞 ...

I have `web-mode-enable-auto-expanding` set to `t` and have the following block of JSX _(where `|` is my cursor;

```js
var ExampleComponent = React.createClass({
  render: function () {
    return (
      d/s/|
    )
  }
})
```

As per the documentation, I'm expecting just typing `d/s/` to expand into `<div><span></span></div>`, but it's not... When I do the same thing in a HTML file, calling `web-mode-complete` _does_ expand it but not automatically...

Should this happen automatically? Or does it require a key binding? Is there any way I can debug `web-mode-complete` for why it isn't expanding in JSX?

Thanks!

**Comment by domtronn** [comment]
I've done a little bit of digging and it seems to be the line of the `web-mode-complete` defun which checks the character before does have a `part-side` text property?

In my case _(above)_ this is returning `jsx`

**Comment by fxbois** [comment]
@domtronn I've pushed a fix

**Comment by domtronn** [comment]
Awesome thanks! :+1:
