### ISSUE TITLE
Subexpressions in Handlebars templates

### ISSUE THREAD

**Issue by simenheg** [fxbois/web-mode#614]
Consider the following Handlebars snippet:

```
{{foo-block foo1=bar1 foo2="bar2" foo3=(inner-helper "bar3")}}
```

With the `ctemplate` engine, everything is highlighted nicely except the `foo3=(inner-helper "bar3")` part. It seems that the [subexpression](http://handlebarsjs.com/expressions.html#subexpressions) is causing the problem.

**Comment by fxbois** [comment]
@simenheg master should now be fixed

**Comment by simenheg** [comment]
Thank you very much @fxbois, it seems that did the job!
