### ISSUE TITLE
[jsx] can't fold jsx 

### ISSUE THREAD

**Issue by CestDiego** [fxbois/web-mode#615]
I have this  code https://gist.github.com/098dbfc96e017509c542 and i get `blocks-control-get ** invalid value (202) **`  It may have to do with multiple `{` stuff

**Comment by fxbois** [comment]
@CestDiego it seems to work with the last version on github

**Comment by CestDiego** [comment]
doesn't work. and now there is a regression with the ternary operators, like in older commit https://github.com/fxbois/web-mode/issues/609

**Comment by CestDiego** [comment]
This is the gist that shows how bad it looks: https://gist.github.com/fc0c3245f17c05d7aeb7 
[![alt](https://i.imgur.com/ev2etbB.png)](https://i.imgur.com/ev2etbB.png)

**Comment by fxbois** [comment]
put ( ) around the test

**Comment by CestDiego** [comment]
there are ( ) around the parent ...what do you mean?

**Comment by fxbois** [comment]
at the moment you should write ``` (this.props.scope.get('type') === "topic") ```

**Comment by CestDiego** [comment]
ok, it looks like this: https://i.imgur.com/sU6rhIl.png

**Comment by fxbois** [comment]
remember that web-mode.el can only fold html elements ...
for other foldings, you should use a dedicated minor mode

**Comment by CestDiego** [comment]
Well that fixed identation, but the code supplied (the one with `Col` Components) still doesn't fold and gives same error with different number. I think it has to do with position or something.

**Comment by fxbois** [comment]
@CestDiego please note that ```<col>``` is a void elements in the html specs. Perhaps you should modify   ```web-mode-void-elements``` if you really wan't to use this tag name

**Comment by CestDiego** [comment]
I didn't know about this, thank you :)

**Comment by fxbois** [comment]
@CestDiego Perhaps I'll remove ```<col>``` from the list in a few months because more and more people are using ```<col>``` in jsx (and less and less in raw html)

**Comment by fxbois** [comment]
@CestDiego should be ok with last commit
