### ISSUE TITLE
Screen update issues with indent

### ISSUE THREAD

**Issue by caioaao** [fxbois/web-mode#616]
I'm experiencing some issues on screen update after an electric indent. As soon as I press RET, the line I was at goes to far right. When I press c-l to force a redraw, the line goes back to its place.

Some pics to illustrate what's going on:

Before pressing ret (also note the current line is actually 1 position off to the right, pressing C-l fixes it as well):
![On the line](https://cloud.githubusercontent.com/assets/1395990/10555738/57fbfb74-744a-11e5-8470-95e68ac71fc7.png)

After pressing ret:
![After pressing ret](https://cloud.githubusercontent.com/assets/1395990/10555737/57fac844-744a-11e5-953e-1f7df98bd46a.png)

I tried stepping through web-mode-indent-line with Emacs' debugger, but my Emacs simply crashes during indent-line-to.

This is the output from web-mode-debug:

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("12.3.5")
vars: engine("none") minor("none") content-type("html") file("/home/bla/tmp/teste.html")
system: window(x) config("x86_64-unknown-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (linum-mode global-linum-mode global-colnum-mode fci-mode global-fci-mode golden-ratio-mode yas-minor-mode yas-global-mode flycheck-mode global-flycheck-mode shell-dirtrack-mode semantic-mode global-semantic-stickyfunc-mode global-semanticdb-minor-mode global-semantic-idle-summary-mode global-semantic-idle-scheduler-mode company-mode global-company-mode async-bytecomp-package-mode global-git-commit-mode diff-auto-refine-mode projectile-mode projectile-global-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

Tests were made on Arch Linux running I3 wm.

**Comment by fxbois** [comment]
This is a known issue with the minor mode that draws the vertical line. Reopen the issue if I can provide help ...
