### ISSUE TITLE
Web-mode always comments as HTML when at the beginning of a buffer.

### ISSUE THREAD

**Issue by crito** [fxbois/web-mode#618]
When calling the function `web-mode-comment-or-uncomment` at the beginning of a buffer, the line or region is always commented as if it was HTML. This is also true for other languages such as Javascript or JSX.

Removing the [first condition](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L6244-L6246) in `web-mode-point-context` fixes the issue for me. I don't understand why this condition is there, but as it is now, I can't comment/uncomment the first line of my Javascript/JSX files.

**Comment by fxbois** [comment]
@crito please post on gist the example you use

**Comment by crito** [comment]
I created a [minimal test case](https://gist.github.com/crito/f88d5d2a6582ffbe402e). If I comment line nr. 1 I get the following:

    
    var b = 42;

Commenting line nr. 2 yields the expected result:

    var a = 23;
    /* var b = 42; */

If I leave the first line empty, it works as expected.

**Comment by crito** [comment]
Some more info. Running `(text-properties-at (point))` on the first column of the first line yields the following result:

    (face web-mode-keyword-face part-side jsx)

**Comment by fxbois** [comment]
@crito ok understood
I'll look at this

**Comment by fxbois** [comment]
@crito a fix has been pushed

**Comment by crito** [comment]
118055b seems to work fine for me. Thanks for the quick response and thanks for web-mode.
