### ISSUE TITLE
Setting web-mode-comment-formats for JS/JSX to // is not recognized.

### ISSUE THREAD

**Issue by crito** [fxbois/web-mode#619]
I my emacs config I have the following to force line comment for JS/JSX files:

```
(add-to-list 'web-mode-comment-formats '("jsx" . "//" ))
(add-to-list 'web-mode-comment-formats '("javascript" . "//" ))
```

When I execute `web-mode-comment-or-uncomment` the comments are still created using block comments (`/* ... */`). Looking at the case condition in [`web-mode-comment`](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L8356-L8357) I see that the `alt` string is matched to `/*`. Changing it to `//` correctly comments my JS/JSX code using line comment.

**Comment by fxbois** [comment]
@crito please test the last version on github

**Comment by crito** [comment]
118055b seems to work fine for me. Thanks for the quick response and thanks for web-mode.

**Comment by pors** [comment]
This doesn't work for me, I have:

```
web-mode-comment-formats is a variable defined in ‘web-mode.el’.
Its value is (("jsx" . "//") ("javascript" . "//"))
```

but I still get `/* ... */` style comments.

Is this variable still used?

**Comment by pors** [comment]
@fxbois what should I include in the gist?

I have this in my .emacs:

```
(add-to-list 'web-mode-comment-formats '("jsx" . "//" ))
(add-to-list 'web-mode-comment-formats '("javascript" . "//" ))
```

**Comment by fxbois** [comment]
@pors the jsx file + where is the cursor + what is the region when you comment

**Comment by pors** [comment]
For any component, even as simple as:

```
class Square extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: null,
    };
  }

  render() {
    return (
      <button className="square" onClick={() => this.setState({value: 'X'})}>
        {this.state.value}
      </button>
    );
  }
}
```

I select:

```
    this.state = {
      value: null,
    };
```

And `m-;` results in the region being commented out with `/* ... */`.

**Comment by fxbois** [comment]
@pors thx I'll look at that

**Comment by fxbois** [comment]
@pors sorry but if I add ```(add-to-list 'web-mode-comment-formats '("jsx" . "//" ))``` in my web-mode-hook, it works as expected. If it does not work for you, please try with an empty .emacs

**Comment by pors** [comment]
Sorry, I had an ancient version of web-mode... All works fine now. Thanks.
