### ISSUE TITLE
Indentation: Some React components do not align properly

### ISSUE THREAD

**Issue by gustavjf** [fxbois/web-mode#621]
In #591, you had worked with alignment of elements according to Airbnb's React/JSX style-guide.

I noticed this particular case wasn't adhering to that change. 

Expected:
```
import { React, Component } from 'react'
import { Label, Input } from 'react-bootstrap'

export default class Test extends Component {
  render() {
    return (
      <Label 
          name="foo"
      >
        Foo
        <Input 
          type="select"
        >
        </Input>
      </Label>
    )
  }
}
```

Actual:
```
// Same results if Label and Input are not imported
import { React, Component } from 'react'
import { Label, Input } from 'react-bootstrap'

export default class Test extends Component {
  render() {
    return (
      <Label 
          name="foo"
      >
        Foo
        <Input 
          type="select"
        >
</Input>
      </Label>
    )
  }
}
```

Notice how `Label` indents correctly, however, `Input`'s closing tag does not. I'm unsure whether or not this is expected. Perhaps it's because normal `<input>` is a self-closing tag, but the `Input` component from `react-bootstrap` uses a closing tag when `type` is `select`. Could this be related?

[Here](https://react-bootstrap.github.io/components.html#input-types) is the relevant `react-bootstrap` doc for reference. Click `show-code` and take a look at `<Input type=select> ... </Input>`.

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("12.2.8")
vars: engine("none") minor("none") content-type("jsx") file("test.js")
system: window(nil) config("x86_64-apple-darwin14.0.0")
colors: fg(nil) bg(nil)
minor modes: (global-prettify-symbols-mode anzu-mode global-anzu-mode ido-everywhere ido-ubiquitous-mode auto-complete-mode global-auto-complete-mode winner-mode desktop-save-mode savehist-mode electric-pair-mode global-auto-revert-mode whitespace-cleanup-mode global-whitespace-cleanup-mode undo-tree-mode global-undo-tree-mode show-paren-mode cua-mode global-page-break-lines-mode hes-mode guide-key-mode shell-dirtrack-mode global-rinari-mode ipretty-mode auto-compile-on-save-mode auto-compile-on-load-mode flycheck-mode global-flycheck-mode xterm-mouse-mode goto-address-prog-mode paredit-everywhere-mode bug-reference-prog-mode diff-auto-refine-mode diff-hl-mode highlight-symbol-mode highlight-symbol-nav-mode)
vars:
web-mode-enable-current-column-highlight=nil
web-mode-enable-current-element-highlight=nil
indent-tabs-mode=nil
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
@gustavjf you can redefine ```web-mode-void-elements```

**Comment by gustavjf** [comment]
I'm not sure I follow, `<Input type="select"> ... </Input>` wouldn't be a void element in this case. There would be `<option>` elements within it.

**Comment by gustavjf** [comment]
I don't see a mention of `web-mode-void-element` in web-mode's source, docs or as an editable field in `M-x customize`. How could I take a look at that?

**Comment by fxbois** [comment]
@gustavjf I think I ll do something because I have received many reports about this .. I just hope it won't trigger side effects

**Comment by gustavjf** [comment]
Thank you for taking it into consideration :)

**Comment by fxbois** [comment]
@gustavjf I've pushed a fix

**Comment by gustavjf** [comment]
Works great, thanks again :+1:
