### ISSUE TITLE
Faulty fontification for SCSS variables

### ISSUE THREAD

**Issue by dustinpaluch** [fxbois/web-mode#622]
I found a case where fontification fails for [SCSS variables](http://sass-lang.com/guide#topic-2). Tested with emacs -q and a bare-bones init file. Here's a video demo: http://cl.ly/dZpO

**Steps to reproduce**:
1. Open a new/empty .scss file (enable web-mode)
2. Type `$black: #000;`

I get the following output in the \*Messages\* buffer:
`web-mode-scan-region: Args out of range: 1, 15`

**Comment by fxbois** [comment]
@dustinpaluch right. In fact I've never really worked on a compatibility layer with scss ... 
could you elaborate a test case which would contain all the syntaxes that are not in standard css ?

**Comment by dustinpaluch** [comment]
@fxbois I'll see what I can do. I'll reopen this when I have a comprehensive test case for you.
