### ISSUE TITLE
Jsx tag-as-field breaks auto-complete

### ISSUE THREAD

**Issue by xizhao** [fxbois/web-mode#623]
When you try to close an opening tag like:

```
<Bootstrap.Button>
```

it doesn't seem to complete correctly.  It may complete with just `</Bootstrap>` itself or something entirely different.

**Comment by fxbois** [comment]
prefer the separator ```-``` to ```.```

**Comment by fxbois** [comment]
even better, could you prefer ```<Bootstrap:Button>```?

**Comment by xizhao** [comment]
Awesome, what is the config for that?

**Comment by fxbois** [comment]
@xizhao I do not understand your question

**Comment by xizhao** [comment]
Sorry -- I meant what is the config for web-mode.el to change the separator from `-` to `.`?

This is for React/JSX files.

**Comment by fxbois** [comment]
@xizhao I've pushed a fix to deal with tag names with a ```.``` as a separator

**Comment by xizhao** [comment]
Awesome, is JSP the mode of editing HTML within JSX documents?

Also, does this support deeper references?  I.e. <Bootstrap.Modal.Header>

**Comment by fxbois** [comment]
@xizhao I do not understand what you mean
