### ISSUE TITLE
JSP comments don't detect correctly when turning existing tags into incomplete tags

### ISSUE THREAD

**Issue by Archenoth** [fxbois/web-mode#626]
Kind of a sub-issue of #620, which had the example where if you have two sets of JSP comment tags like the following:

```JSP
<%--  --%>
Words
<%--  --%>
```
...and then you add a space at the end of the first tag like this:
```JSP
<%--  -- %>
Words
<%--  --%>
```
The top is no longer recognized as a comment:
![screenshot from 2015-10-19 15 45 43](https://cloud.githubusercontent.com/assets/1385527/10592326/a646220c-7678-11e5-83a9-5c5005cc1669.png)

I found that this fixes itself if you edit the contents of the comment.

However, upon further investigation, it seems as though there are other ways to break this without nesting tags, and it seems to be rooted in multiline comments... For example if you start with the following:

```JSP
<%--
Test --%>
```
And you add a space to the top like so:

```JSP
< %--
Test --%>
```

Then remove it again:

```JSP
<%--
Test --%>
```
The entire block loses its color:
![screenshot from 2015-10-28 09 11 12](https://cloud.githubusercontent.com/assets/1385527/10792826/fea951da-7d53-11e5-8e7a-2afe825c71df.png)

However, if you do the above process with that all being on a single line, it updates correctly:
![screenshot from 2015-10-28 09 11 20](https://cloud.githubusercontent.com/assets/1385527/10792827/feacae34-7d53-11e5-801f-499fea25e9cc.png)

All the above are highlighted correctly if you load a file with the failing examples--they are created when editing.

This is with Emacs 24.5.1 with web-mode MEPLA 20151026.1437 (Commit 390fa14b4930714fa9f8112f398ca6591b7a5513).

**Comment by fxbois** [comment]
@Archenoth could you test the last version on github please

**Comment by Archenoth** [comment]
I guess the two examples were two different problems...

The thing with:
```jsp
<%--
Test --%>
```
...works perfectly as of the most recent commit (Sweet!), though the problem in the first example still stands.

Should I create another issue for that? Or would should we just keep this one open..?

**Comment by fxbois** [comment]
@Archenoth I've pushed a new patch

**Comment by Archenoth** [comment]
Awesome, both seem to work now.

Thanks fxbois..!
