### ISSUE TITLE
ES7/JSX splats cause indentation problems

### ISSUE THREAD

**Issue by jsdir** [fxbois/web-mode#627]
```jsx
class Test {
  constructor() {
    super(...arguments)
      let a = 1 // This should not indent.
  }
}
```

```jsx
const a = {};
const b = {
...a, // This should indent.
  ...b,
  ...c
};
```

**Comment by fxbois** [comment]
isn't it due to the lack of ```;``` at the end of lines ?
web-mode requires this

**Comment by jsdir** [comment]
The first example behaves that same way even without the splat. Does it indent because it expects chained method calls? The second example appears to have nothing to do with semicolons.

**Comment by fxbois** [comment]
do you pointers on the web where I can info about this syntax ?

**Comment by jsdir** [comment]
- https://github.com/sebmarkbage/ecmascript-rest-spread
- https://github.com/sebmarkbage/ecmascript-rest-spread/blob/master/Spec.md
- https://facebook.github.io/react/docs/jsx-spread.html

**Comment by fxbois** [comment]
@jsdir I've pushed a fix for the second issue. For the first one, write ```super(...arguments);```

**Comment by jsdir** [comment]
Thanks :+1:
