### ISSUE TITLE
Incorrect auto-closing of JSP/GSP tags

### ISSUE THREAD

**Issue by and-dmitry** [fxbois/web-mode#629]
When I try to close a JSP tag web-mode auto-closes previous HTML tag. Example:
```
<body>
  <g:link action="create">|
</body>
```
Typing `</` or calling `web-mode-element-close` does this:
```
<body>
  <g:link action="create"></body>
</body>
```
Here's what I've expected to get:
```
<body>
  <g:link action="create"></g:link>
</body>
```

I've tested it with the latest code from git.

**Comment by fxbois** [comment]
@and-dmitry to close ```<g:link>``` to have to invoke ```web-mode-block-close``` (which I bind in my ```.emacs``` to ```^-/```)

**Comment by and-dmitry** [comment]
Thanks!

Also now I see that there's probably no way to implement auto-closing for both HTML and JSP tags.
