### ISSUE TITLE
ES7 class property highlighting

### ISSUE THREAD

**Issue by jacktrades** [fxbois/web-mode#633]
I know it's not a finalized feature, but are there any plans to add highlighting for ES7 class properties?

![property highlighting](https://cloud.githubusercontent.com/assets/385989/11054340/a8e689e0-871f-11e5-9600-9d3f697af4e9.png)

**Comment by fxbois** [comment]
@jacktrades do you have a pointer to the specs ?

**Comment by jacktrades** [comment]
Looks like [this](https://github.com/jeffmo/es-class-static-properties-and-fields) is as close as we get to a spec for now.  [Babel supports class properties](https://babeljs.io/docs/plugins/syntax-class-properties/) as an optional feature.

**Comment by fxbois** [comment]
@jacktrades should be fixed with last commit

**Comment by jacktrades** [comment]
Looks great, thanks!
