### ISSUE TITLE
linum white background and line err

### ISSUE THREAD

**Issue by transtone** [fxbois/web-mode#635]
after press TAB, some line number(some indent lines, not all indent lines) diserpeared. and 9 jumps to 11.

![image 1](https://cloud.githubusercontent.com/assets/46688/11115741/9f89fd46-8968-11e5-89f1-460f4eb0c5ef.png)

**Comment by fxbois** [comment]
post your example on gist please

**Comment by transtone** [comment]
all lines is on screen.

**Comment by fxbois** [comment]
@transtone I've tested and nothing happens here. I think you should report an issue to emacs.
Moreover have you updated to the last version of emacs ?
