### ISSUE TITLE
Why web-mode does not support highlight in Org-mode code block Babel?

### ISSUE THREAD

**Issue by stardiviner** [fxbois/web-mode#636]
```lisp
(with-eval-after-load 'enh-ruby-mode
  (add-to-list 'org-src-lang-modes '("ruby" . enh-ruby)))

;; open those babels with `web-mode'.
(eval-after-load "web-mode"
  '(progn
     (add-to-list 'org-src-lang-modes '("html" . web))
     (add-to-list 'org-src-lang-modes '("browser" . web))
     (add-to-list 'org-src-lang-modes '("rhtml" . web))
     ))
```

I set org-mode babel with upper config.
Here is the question I asked on Stack Emacs. There are screenshots over there.
(PS, I lost my original screenshot images now)
I want to know, is there a way to make web-mode syntax highlighting support Org-babel?

**Comment by fxbois** [comment]
@stardiviner I am not aware of any way to do this. Moreover I do not use org-mode.
It is more a question for Stack Emacs
