### ISSUE TITLE
Indentation of switch/case statement in a js file.

### ISSUE THREAD

**Issue by AriaFallah** [fxbois/web-mode#637]
I like to have my case labels unindented:

```
  switch (q) {
  case 'a':
    return a;
  case 'b:
    return b;
  case 'c':
    return c;
  case 'd':
    return d;
  default:
    return [];
  }
```
however, web-mode forces me into indenting the case statements and I haven't found a configuration setting to change this.
```
  switch (q) {
    case 'a':
      return a;
    case 'b':
      return b;
    case 'c':
      return c;
    case 'd':
      return d;
    default:
      return [];
  }
```

How can I fix this?

**Comment by fxbois** [comment]
@AriaFallah what configuration do you use with other languages ? (I would like to know the name of the directive)

**Comment by AriaFallah** [comment]
Usually other modes that I used before had the case statements indented the way I wanted it by default

For example, js2-mode which I actually just switched over from because I like web mode better.

In general the only time I ever had to change my case statement to line up to my preferences was for C++ using the command specified [here] (https://www.gnu.org/software/emacs/manual/html_node/efaq/Indenting-switch-statements.html)

I had to change

    (c-set-offset 'case-label '+)

to

    (c-set-offset 'case-label '0)

Does that answer your question?

**Comment by fxbois** [comment]
That's exactly what I wanted. I'll work on this

**Comment by AriaFallah** [comment]
Thank you very much for being so responsive.

Everything else about web-mode has been perfect (other than having to call `font-lock-fontify-buffer` every now and then), and I like that it supports .jsx for react as well.

**Comment by fxbois** [comment]
If you have a testcase for triggering issues with font-locking, do not hesitate to post a specific issue

**Comment by AriaFallah** [comment]
I'll definitely look into it. It happens only 2-3 times for very small sections of code in a few hours of coding.

**Comment by fxbois** [comment]
with last version, you can try
```(add-to-list 'web-mode-indentation-params '("case-extra-offset" . nil))```

**Comment by AriaFallah** [comment]
Thank you very much!
