### ISSUE TITLE
JavaScript If statement indentation issues

### ISSUE THREAD

**Issue by amasad** [fxbois/web-mode#638]
First of all, thanks so much for your work on this mode.

I'm having trouble with the if statement indentation when it comes to large conditionals. For example if I want to split my conditional into multiple lines then the indentation for the body of the if statement is double indented. Furthermore the continuation of conditional doesn't align correctly.

Expected:
```javascript
if (x &&
    y) {
  return 1;
}
```

Actual:
```javascript
if (x &&
 y) {
    return 1;
}
```

**Comment by fxbois** [comment]
@amasad should be fixed with latest commit
