### ISSUE TITLE
Integration with multiple-cursors is broken

### ISSUE THREAD

**Issue by vmalloc** [fxbois/web-mode#639]
At some point recently web-mode broke compatibility with multiple-cursors (or perhaps it's the other way around, I just don't know how to approach investigating it).

Steps to reproduce:

1. Open a file in web-mode
2. Mark a word (say a tag name)
3. call `mc/mark-next-like-this`

The selection around the first word disappears, but around the next word it remains, which makes editing through multiple cursors either impossible or really hard.

Thanks in advance!

**Comment by fxbois** [comment]
@vmalloc could you ask to the maintainer ? I do not debug minor-mode issues but can provide help

**Comment by vmalloc** [comment]
I will try. Thanks!

**Comment by fxbois** [comment]
@vmalloc so 12.2.11 does not work and 12.2.10 works fine ... right ?

**Comment by vmalloc** [comment]
I don't know about the version numbers, but using `git bisect` narrowed it down to a single commit - https://github.com/fxbois/web-mode/commit/fa3b49f6b34616a8bd4f4b3628b2f6f75db3ce5e. One commit prior it worked, and after this commit it no longer works.

**Comment by fxbois** [comment]
@vmalloc could you try the last version on github ?

**Comment by vmalloc** [comment]
@fxbois seems to work great!
