### ISSUE TITLE
Support for Vue

### ISSUE THREAD

**Issue by geekplux** [fxbois/web-mode#641]
[Vue](http://vuejs.org) is a library for building interactive web interfaces. In the Vue.js project we can divide the page into many small components and we can create a component by using `.vue` file. It looks like:

![[Single File Component](http://vuejs.org/guide/application.html#Single_File_Components)](http://vuejs.org/images/vue-component.png)

so is there some tricks to highlight the syntax ? :D

**Comment by fxbois** [comment]
adding 
```(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))```
would do the job, no ?

**Comment by geekplux** [comment]
It works! Thank you.
