### ISSUE TITLE
web-mode-use-tabs not called after hook

### ISSUE THREAD

**Issue by jobevers** [fxbois/web-mode#642]
I set `indent-tabs-mode` to True in web-mode-hook:

```
(add-hook 'web-mode-hook
	  (lambda ()
	    (setq tab-width 2)
            (setq indent-tabs-mode t)))
```

but, that doesn't cause `web-mode-use-tabs` to be called.

Instead I had to modify my hook to do:

```
(add-hook 'web-mode-hook
	  (lambda ()
	    (setq tab-width 2)
            (setq indent-tabs-mode t)
            (web-mode-use-tabs)))
```

I think it would be worthwhile to add a call similar to https://github.com/fxbois/web-mode/blob/master/web-mode.el#L2252 to be run after the hook.

**Comment by fxbois** [comment]
@jobevers the second version is the good one. If ``ìndent-tabs-mode``` was set outside the hook you wouldn't need to call ```web-mode-use-tabs```
