### ISSUE TITLE
Attribute kill misses the first character

### ISSUE THREAD

**Issue by dustinpaluch** [fxbois/web-mode#643]
<div class="test"></div>
    <a href="#"></div>

**Steps to reproduce:**
1. emacs -q
2. load web-mode, open a new php file, paste above code, activate web mode
3. With the point ~~somewhere over~~ over an attribute (excluding the first character), do `C-c C-a k`

**Expected Results:**

    <div ></div>
    <a ></div>

**Actual Results:**

    <div c></div>
    <a h></a>

**Comment by dustinpaluch** [comment]
New observation: It does work correctly if your point is on the first character of the attribute.

**Comment by fxbois** [comment]
@dustinpaluch should be fixed with last commit

**Comment by dustinpaluch** [comment]
@fxbois working correctly in "13.0.4". Thank you.
