### ISSUE TITLE
Syntax highlighting of es6 arrow functions.

### ISSUE THREAD

**Issue by AriaFallah** [fxbois/web-mode#645]
<img width="351" alt="screen shot 2015-12-02 at 1 12 32 am" src="https://cloud.githubusercontent.com/assets/9424976/11523649/ffef22d2-9891-11e5-98b6-989ea6542644.png">

<img width="444" alt="screen shot 2015-12-02 at 1 13 29 am" src="https://cloud.githubusercontent.com/assets/9424976/11523653/06a0f704-9892-11e5-9d1f-5e9a0f884a47.png">

If written as an arrow function like this it doesn't get syntax highlighting.

```javascript
router.get('/alerts', (request, response) => {})
```

If written as a regular function like this it does get syntax highlighting.

```javascript
router.get('/alerts', function(request, response) {})
```

**Comment by fxbois** [comment]
@AriaFallah you can try the last version on github
