### ISSUE TITLE
[jsx] folding issue

### ISSUE THREAD

**Issue by chalmagean** [fxbois/web-mode#646]
I'm using web-mode to edit jsx and folding doesn't seem to work. I get the following error: `block-controls-get ** invalid value (752) **`

Here's the code I am trying to fold (cursor is before the `r` in `return`).
```javascript
window.Room = React.createClass({
  defaultState: function() {
    return {
      dynamicFields: []
    };
  }
});
```

**Comment by fxbois** [comment]
@chalmagean folding only work for html elements and active blocks. Many minor modes can do this ... ask on emacs stackoverflow
