### ISSUE TITLE
indent-tabs-mode behavior is broken

### ISSUE THREAD

**Issue by wavexx** [fxbois/web-mode#647]
I have indent-tabs-mode set to t globally, which forces a call to ``web-mode-use-tabs``.

None of the changes by web-mode-use-tabs make any sense to me: they simply set all padding to 0 and offsets to ``(or tab-width standard-indent)``.

I cannot customize any of these offsets anymore through the standard customize interface, but have to resort to the web-mode-hook. I also generally set indent-tabs-mode to nil, where needed, in the mode hook. But it's ran too late for your check.

Since you already default to standard-indent, you don't need to do any of that. Just advise to set standard-indent properly.

**Comment by fxbois** [comment]
@wavexx please provide a very clear description of what would be better.

**Comment by wavexx** [comment]
I'd like either lines 2260-2261 to be removed, which I think is preferable, or changed to something like:

````
(defvar web-mode-indent-with-tabs nil
  "When t, use only TABs for all indentation")

...

 (when web-mode-indent-with-tabs
   (setq indent-tabs-mode t)
   (web-mode-use-tabs))
````

**Comment by fxbois** [comment]
@wavexx I've removed the call to ```web-mode-use-tabs```

**Comment by wavexx** [comment]
Thanks. I was using defadvice to work around it.
