### ISSUE TITLE
ERB fontification on identifiers containing keywords

### ISSUE THREAD

**Issue by hut8** [fxbois/web-mode#649]
In ERB mode, if I'm highlighting:

```
        <% layout.columns.each do |col| %>
          <td class="<%= class_for_col col %>">
            <%= best_in_place(expense, col) %>
          </td>
        <% end %>
```

I would expect that `class_for_col` would be treated as a single token, and therefore would only be fontified one way. But it looks like this to me:

![fontification-issue](http://i.imgur.com/Z8mt6nMl.png)

I updated to 20151208.1412 before posting this.

**Comment by fxbois** [comment]
@dgutov with the change to the syntax-table, I now have issues with fontification rules like ```(cons (concat "\\<\\(" web-mode-erb-builtins "\\)\\>") '(0 'web-mode-builtin-face))``` (due to ```\\<```)

What advice could you give me ?

**Comment by dgutov** [comment]
@fxbois You should try replacing them with `\\_<`, which means "symbol boundary".

**Comment by fxbois** [comment]
@dgutov seems obvious now ! thx a lot

@hut8 should be fixed with last commit

**Comment by hut8** [comment]
Confirmed fixed. Thanks for such a quick fix.
