### ISSUE TITLE
Fold/Unfold does not work properly with namespaced xml files

### ISSUE THREAD

**Issue by johnbendi** [fxbois/web-mode#650]
I know probably the software was not designed to do this but could it be considered as a feature request. It will be nice to have folding work for long xml files so please consider. Also if it's possible to borrow validation code from nxml-mode that will be nice to have to. This issue may be rightly considered a feature request.

Some supporting screenshots:

Before fold:
![xsd_screenshot_before_fold](https://cloud.githubusercontent.com/assets/1025834/11820576/875a002e-a365-11e5-8d81-40a41e33b43a.png)

After fold:
![xsd_screenshot_after_fold](https://cloud.githubusercontent.com/assets/1025834/11820575/870489dc-a365-11e5-9f55-140841fdd299.png)

**Comment by fxbois** [comment]
@johnbendi please post your example on gist

**Comment by fxbois** [comment]
@johnbendi please try the last version on github
