### ISSUE TITLE
PHP commenting bug

### ISSUE THREAD

**Issue by vergiljk** [fxbois/web-mode#651]
When I edit a PHP file and comment multiple lines of code, only the first line is highlighted.

![image](https://cloud.githubusercontent.com/assets/5583965/11824940/13d6d4ec-a342-11e5-98d5-ee8416764e74.png)

But when I reopen the file, it highlights all the lines appropriately. I can only reproduce this issue while editing a file.

**Comment by fxbois** [comment]
@vergiljk please describe the complete test case .. 
how do comment ? with a shortcut ?

**Comment by vergiljk** [comment]
@fxbois Yep sure. I didn't use any shortcuts. I just typed code normally.

Here's the test case.

**Test Case:**

1. I have a test.php file with some code

 ```
 echo "hey";
 print 'hello';
 $hi  = 'hmmm';
 $hi2 = 'new var';
 $hi = 'something else';
 echo $hi;
 ```
2. I commented lines 1 to 4 manually without using any shortcuts

 ```
 /*echo "hey";
 print 'hello';
 $hi  = 'hmmm';
 $hi2 = 'new var';*/
 $hi = 'something else';
 echo $hi;
 ```

3. **Current Result:** Only 1 line is highlighted (screenshot below)
 
 ![image](https://cloud.githubusercontent.com/assets/5583965/11828095/ef5f2ce4-a356-11e5-9b24-e048bfeaf38e.png)
 **Expected Result:** All four lines should be highlighted.

4. But if I close the file and open the same file again, all the line from 1 to 4 are highlighted

 ![image](https://cloud.githubusercontent.com/assets/5583965/11828185/0cfd6b66-a358-11e5-9b5b-e502ac78a556.png)

**Comment by fxbois** [comment]
@vergiljk perfect. I'll work on this.
Could you post the output of ```web-mode-debug``` please

**Comment by fxbois** [comment]
@vergiljk please try the last version on github

**Comment by vergiljk** [comment]
@fxbois It works great with the latest version! Thanks for the quick response! :+1:  :)
