### ISSUE TITLE
javascript regular breaks indention 

### ISSUE THREAD

**Issue by pkvov** [fxbois/web-mode#654]
jQuery.validator.addMethod("lettersonly", function (value, element) {
            return this.optional(element) || /^[^:%,'\*\"\s\<\>\&]+$/i.test(value);
        }, "Letters only please");

thanks for the mode and happy new year.

**Comment by fxbois** [comment]
@pkvov could you poste the output of ```web-mode-debug``` please

**Comment by pkvov** [comment]
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("8.0.4")
vars: engine("php") content-type("html") file("/Users/kepeng/workfolder/wsbz/shop/templates/default/home/registerStep2.php")
system: window(ns) config("x86_64-apple-darwin13.4.0")
colors: fg(nil) bg(nil) 
modes: whitespace-mode(nil) global-whitespace-mode(nil) rainbow-mode(nil) idle-highlight-mode(t) fic-mode(nil)
(transient-mark-mode auto-fill-function line-number-mode column-number-mode auto-compression-mode auto-encryption-mode auto-composition-mode font-lock-mode global-font-lock-mode file-name-shadow-mode mouse-wheel-mode electric-indent-mode show-paren-mode ido-ubiquitous-mode yas-minor-mode yas-global-mode auto-complete-mode global-auto-complete-mode undo-tree-mode global-undo-tree-mode idle-highlight-mode recentf-mode shell-dirtrack-mode)
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@pkvov please use the last version on github

**Comment by pkvov** [comment]
@fxbois i am ok now, thanks
