### ISSUE TITLE
Indentation of conditional comments

### ISSUE THREAD

**Issue by ignativs-reilly** [fxbois/web-mode#655]
Can't control the indentation of conditional comments. All the lines of the comment (included the closing '-->') get indented to 4 space. 

Look lines 27-31:
Original ------------- https://gist.github.com/ignativs-reilly/9eacfb3d639b7f2c4cdf
After indent -------- https://gist.github.com/ignativs-reilly/bd5653289510af542003

Builtin HtmlMode and SgmlMode behaves the same way as web-mode.

**Comment by ignativs-reilly** [comment]
In fact my expression is wrong, this is not inherent to "conditional comments" (sorry), is the way all html comments behave. I think it would be nice to control the way comments are indented, both the tag delimiters and content. Thanks a lot.

**Comment by fxbois** [comment]
I do not understand. Use precise example (before / after)

**Comment by ignativs-reilly** [comment]
The first comment has the example, lines 27-31.

**Comment by fxbois** [comment]
@ignativs-reilly should be ok with last commit

**Comment by ignativs-reilly** [comment]
Yes, now conditional comments are indented in bootstrap style. Thanks!
