### ISSUE TITLE
auto-closing undesirable behavior when pasting code

### ISSUE THREAD

**Issue by paxperscientiam** [fxbois/web-mode#656]
Hi @fxbois ,

I wanted to raise a small problem I've been having with "auto-closing." While it works great when you're writing your own code, an issue crops up when code is pasted into emacs.

If the user attempts to paste a complete block of code, web-mode still attempts to auto close the block (and sub-blocks). So, the user winds up with unnecessary closing tags appended to the end of the block and each nested block.

The obvious work around is to copy `<tag>...</` and allow web-mode to complete the closing tag upon pasting.

I suppose this is more of a feature request than a bug.

Thanks.

**Comment by fxbois** [comment]
@paxperscientiam are you using emacs in a terminal. If it is the case, it is the normal behavior (see web-mode.org).
