### ISSUE TITLE
web-mode smarty indentation issues

### ISSUE THREAD

**Issue by geraldus** [fxbois/web-mode#657]
**Web-mode** indents closing `foreach` **smarty** tags too deep, here is an example:
```smarty
{foreach $items as $i}
    <span>{$i}</span>
    {/foreach}
```
Also, there is no extra indent level in smarty's `if` conditions:
```smarty
{if $condition}
<span>this aligned to {</span>
{else}
<span>so do this</span>
{/if}
```

Note, in my current setup I have:
```elisp
(custom-set-variables
 '(smarty-left-delimiter "<{")
 '(smarty-right-delimiter "}>"))
```
But I guess this does not matters

**Comment by fxbois** [comment]
@geraldus could you post the output of ```web-mode-debug``` please

**Comment by geraldus** [comment]
Surely, here it is
```
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("13.0.16")
vars: engine("smarty") minor("smarty") content-type("html") file("/ssh:<…>:<…>hockey/templates/statistics-fielder-iteration.tpl")
system: window(x) config("x86_64-unknown-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (ido-everywhere flx-ido-mode electric-pair-mode savehist-mode undo-tree-mode global-undo-tree-mode evil-local-mode evil-mode global-flycheck-mode company-mode global-company-mode diff-auto-refine-mode diff-hl-mode shell-dirtrack-mode async-bytecomp-package-mode global-git-commit-mode show-paren-mode whitespace-mode linum-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
@geraldus I can not trigger your issue. Perhaps with a very light .emacs to see if a config/minor-mode is not the culprit

**Comment by geraldus** [comment]
You can see full `.emacs` [here](https://github.com/geraldus/g-dots/blob/master/.emacs).

**Comment by geraldus** [comment]
Some times it behaves differently for `foreach` statements and aligns it as in above example for `if` blocks.
Indent occurs when I insert newlines pressing `<return>` (runs `evil-return` in my case) or pressing `<tab>` key (which runs `indent-for-tab-command`).

Thank you very much for your attendance.

**Comment by fxbois** [comment]
can I close ?

**Comment by geraldus** [comment]
Surely, but does this means "this is not web-mode issue"?

**Comment by fxbois** [comment]
@geraldus if you look at the sources, you will see that ```indent-line-function``` is bound to ```'web-mode-indent-line```
Perhaps you should ask on stackoverflow

**Comment by geraldus** [comment]
@fxbois indeed, `indent-line-function` is set to `web-mode-indent-line`, sorry for that but first time I got wrong result because executed `describe-variable` function in Help buffer.
