### ISSUE TITLE
Whitespace after last attribute in tag

### ISSUE THREAD

**Issue by TheBB** [fxbois/web-mode#658]
E.g. in HTML,

type: `<tag attr=value">`  
get: `<tag attr="value" >`

This is typically not the desired behavior. Is there any way to get rid of that space when closing a tag with `>` (but not, say, with `/>`)?

**Comment by fxbois** [comment]
I can not trigger this. Could you post a video ?

**Comment by TheBB** [comment]
Sure: https://vid.me/iLYp

Emacs 24.5.1, run with `emacs -q` and a fresh web-mode installation from MELPA.

**Comment by fxbois** [comment]
@TheBB thx
It may be due to a minor mode.
Please try with a very light .emacs.

**Comment by TheBB** [comment]
That was in `emacs -q`. I just reproduced it in `emacs -Q` as well.

`describe-mode` shows:

> Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Blink-Cursor Electric-Indent File-Name-Shadow Font-Lock
Global-Font-Lock Line-Number Menu-Bar Mouse-Wheel Tool-Bar Tooltip
Transient-Mark

I just disabled all of these in turn. I need font lock to be on to reproduce it, but I also need that to get any kind of auto-quoting behaviour from web-mode.

I'm surprised you can't reproduce it. I just ran `emacs -Q` in this repo, loaded web-mode and tried.

Maybe you can point me to the code that's supposed to keep this from happening, and I can try to debug myself?

**Comment by TheBB** [comment]
It's here I assume: https://github.com/fxbois/web-mode/blob/master/web-mode.el#L8945-L8985

**Comment by TheBB** [comment]
Well, I just had a brief look in that fnuction and I don't see any code on `?>` that checks whether there is a space in front and deletes it. I tried coding it myself but I must have run into some corner cases, or I don't understand entirely what I'm doing, because the result was not satisfactory.

**Comment by fxbois** [comment]
@TheBB in fact, that is a feature. Would you like that I remove the whitespace when I detect that the char ```>``` is entered ?

**Comment by TheBB** [comment]
Okay. Yes, if this is the intended behaviour, I think it would be nice to optionally delete the whitespace when the closing `>` is entered.

**Comment by fxbois** [comment]
@TheBB Maybe you should write a small minor mode to handle this. If ```" >``` is detected, replace by ```">```
