### ISSUE TITLE
JSX array formatting in properties

### ISSUE THREAD

**Issue by trevorsenior** [fxbois/web-mode#659]
This is something that I noticed I've been adjusting a lot without thinking to ask about it here.

Currently the formatting of JSX components with array properties is as follows:

```js
function foo() {
    return <label>
        First Name:
        <Input name="name"
               type="text"
               validators={[
                       required('You must supply a first name!'),
                       (value) => value > 15 ? 'too long!': null
                   ]} />
    </label>;
}
```

vs.

```js
function foo() {
    return <label>
        First Name:
        <Input name="name"
               type="text"
               validators={[
                   required('You must supply a first name!'),
                   (value) => value > 15 ? 'too long!': null
               ]} />
    </label>;
}
```

(Removed 4 spaces from the array items, and the closing of the array)

This may be a non-issue, or done on purpose. If so please close this & thanks for all the work you've put into this mode.

**Comment by fxbois** [comment]
@trevorsenior should be fixed with last commit
