### ISSUE TITLE
getting html comment tag in php code, .php file

### ISSUE THREAD

**Issue by mikemakuch** [fxbois/web-mode#660]
I've been using web-mode for a while, updated to latest. I'm getting html comment tags instead of php comments;

<?php

<!--    if (...) { xxxxx; }  ->

file: xxx.php

What would cause this?
Thanks

**Comment by fxbois** [comment]
@mikemakuch I do not understand your report

**Comment by mikemakuch** [comment]
When I use comment-region, it used to correctly comment lines of php code like

//  if (.....

but now it's using html comments 



why?

**Comment by fxbois** [comment]
@mikemakuch do you use ```^-,```

**Comment by mikemakuch** [comment]
I don't know what that means.

**Comment by fxbois** [comment]
@mikemakuch you can try the last version on github

**Comment by mikemakuch** [comment]
Ok that's better, that works. But can I use

// ...

instead of

/* ... */

how can I set that?

**Comment by fxbois** [comment]
There is some doc on web-mode.org

**Comment by mikemakuch** [comment]
Great that works. Is there any way to get the "//" to appear in the leftmost column instead of aligned with the line of code above?

**Comment by fxbois** [comment]
could you post an example ?

**Comment by mikemakuch** [comment]
The comment slashes "//" are inserted here:

```
          // if (..) {
                  // dosomething();
          // }

```
but I'd like them to appear here in leftmost column;
```
//          if (..) {
//                  dosomething();
//          }
```
Thanks

**Comment by fxbois** [comment]
that's not possible at the moment
