### ISSUE TITLE
list comprehension jsx

### ISSUE THREAD

**Issue by koolkt** [fxbois/web-mode#661]
Indentation stops working correctly after declaring a list comprehension like this:
```
this.images = [for (i of props.images) <div style={this.getStyle(i['url'],i['position'])}></div>];
```
Any sugestions?

Thanks

**Comment by fxbois** [comment]
Can you post the output of web-mode-debug

**Comment by koolkt** [comment]
Loading 00debian-vars...done
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...done
Loading debian-ispell...done
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...done
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/shell-integration.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/navigation.el (source)...
Loading /home/adolfo/.emacs.d/.recentf...done
Cleaning up the recentf list...done (0 removed)
Loading /home/adolfo/.emacs.d/customizations/navigation.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/ui.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/editing.el (source)...
[yas] Discovered there was already *scratch* in fundamental-mode
[yas] Discovered there was already  *code-conversion-work* in fundamental-mode
[yas] Discovered there was already  *load* in fundamental-mode
[yas] Discovered there was already  *load*-572744 in fundamental-mode
[yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode) (quote fundamental-mode)))!
[yas] Loading compiled snippets from /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode
Loading /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode/.yas-setup...done
[yas] Prepared just-in-time loading for /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets
[yas] Prepared just-in-time loading for ~/.emacs.d/snippets
[yas] Reloaded everything (snippets will load just-in-time)....
[yas] Loading compiled snippets from /home/adolfo/.emacs.d/elpa/haskell-mode-20150202.632/snippets/haskell-mode [2 times]
[yas] Prepared just-in-time loading for /home/adolfo/.emacs.d/elpa/haskell-mode-20150202.632/snippets
[yas] Discovered there was already *scratch* in fundamental-mode
[yas] Discovered there was already  *code-conversion-work* in fundamental-mode
[yas] Discovered there was already  *load* in fundamental-mode
[yas] Discovered there was already  *load*-572744 in fundamental-mode
[yas] Discovered there was already  *code-converting-work* in fundamental-mode
[yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode) (quote fundamental-mode)))!
[yas] Loading compiled snippets from /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode
Loading /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode/.yas-setup...done
[yas] Prepared just-in-time loading for /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets
[yas] Prepared just-in-time loading for ~/.emacs.d/snippets
[yas] Reloaded everything (snippets will load just-in-time)....
Loading /home/adolfo/.emacs.d/customizations/editing.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/misc.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/elisp-editing.el (source)...done
Loading /home/adolfo/.emacs.d/vendor/doc-mode.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/setup-clojure.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/setup-web.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/setup-js.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/setup-css.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/setup-yaml.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/setup-org.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/setup-prolog.el (source)...done
Loading /home/adolfo/.emacs.d/customizations/setup-ruby.el (source)...done
[yas] Loading for `lisp-interaction-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/lisp-interaction-mode) (quote lisp-interaction-mode)))!
[yas] Loading compiled snippets from /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/lisp-interaction-mode
[yas] Loading for `emacs-lisp-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/emacs-lisp-mode) (quote emacs-lisp-mode)))!
[yas] Loading compiled snippets from /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/emacs-lisp-mode
[yas] Loading for `prog-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode) (quote prog-mode)))!
[yas] Loading compiled snippets from /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode
Loading /home/adolfo/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode/.yas-setup...done
Starting Emacs daemon.
Mark set
Indenting region...
javascript-args-beginning-position ** failure **
web-mode-block-opening-paren-position: Invalid search bound (wrong side of point)
Indenting region...
javascript-args-beginning-position ** failure **
web-mode-block-opening-paren-position: Invalid search bound (wrong side of point)
Indenting region...
javascript-args-beginning-position ** failure **
web-mode-block-opening-paren-position: Invalid search bound (wrong side of point)
Indenting region...
javascript-args-beginning-position ** failure **
web-mode-block-opening-paren-position: Invalid search bound (wrong side of point)
Mark set
Mark deactivated
Beginning of buffer
javascript-args-beginning-position ** failure **
web-mode-block-opening-paren-position: Invalid search bound (wrong side of point)
Mark set [2 times]
reg-beg(233) reg-end(340) token-type(nil) point(960)
Undo!
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
Redo!
Undo! [8 times]
reg-beg(233) reg-end(340) token-type(nil) point(1043)
Undo! [5 times]
user-error: No further undo information [24 times]
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
(No changes need to be saved) [2 times]
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
Undo! [3 times]
javascript-args-beginning-position ** failure ** [2 times]
Undo!
web-mode-block-opening-paren-position: Invalid search bound (wrong side of point)
Undo!
Mark set [2 times]
Undo!
Mark set
End of buffer [2 times]
Mark set
Quit
Mark set [3 times]
Undo!
Mark set
Indenting region...
web-mode-block-opening-paren-position: Invalid search bound (wrong side of point)
Mark set
Mark deactivated
Mark set
Indenting region...done
End of buffer
Mark set
Indenting region...done
"cimage" is defined but never used [no-unused-vars]
"currentimage" is defined but never used [no-unused-vars]
Mark set [2 times]
Parsing error: Unexpected token [5 times]
Mark set [2 times]
Parsing error: Unexpected token
Mark set
Undo!
Mark set [2 times]
Undo!
reg-beg(1011) reg-end(1141) token-type(nil) point(1437)
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
Mark set
reg-beg(187) reg-end(324) token-type(nil) point(1303)
Indenting region...done
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
Mark set
Parsing error: Unexpected token
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
Undo! [2 times]
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
Beginning of buffer [16 times]
Mark set [2 times]
Beginning of buffer [14 times]
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
byte-code: Beginning of buffer
Mark set [2 times]
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
Parsing error: Unexpected token
Mark set [2 times]
Parsing error: Unexpected token
Saving file /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js...
Wrote /home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js
 [2 times]
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("11.2.4")
vars: engine("none") minor("none") content-type("jsx") file("/home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (global-prettify-symbols-mode ido-ubiquitous-mode projectile-mode projectile-global-mode git-gutter-mode global-git-gutter-mode show-paren-mode yas-minor-mode yas-global-mode nyan-mode shell-dirtrack-mode flycheck-mode global-flycheck-mode rainbow-delimiters-mode)
vars:
web-mode-enable-current-column-highlight=t 
web-mode-enable-current-element-highlight=t 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
 [2 times]
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("11.2.4")
vars: engine("none") minor("none") content-type("jsx") file("/home/adolfo/Projects/test/components/Carousel/jspm-react/public/components/Carousel.js")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (global-prettify-symbols-mode ido-ubiquitous-mode projectile-mode projectile-global-mode git-gutter-mode global-git-gutter-mode show-paren-mode yas-minor-mode yas-global-mode nyan-mode shell-dirtrack-mode flycheck-mode global-flycheck-mode rainbow-delimiters-mode)
vars:
web-mode-enable-current-column-highlight=t 
web-mode-enable-current-element-highlight=t 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
Could you update?

**Comment by koolkt** [comment]
How could i do that? I reinstalled web-mode with package-install but web-mode-debug still shows versions: emacs(24.4) web-mode("11.2.4"). I guess i could install it manualy but if there is something obious that i'm doing wrong while instaling from melpa i would like to know. I'm suposed to have version 13 aren't i?

Thanks a lot for helping me and thanks for this awesome package.

**Comment by koolkt** [comment]
I figured it out i did'nt realized i hqd an old version of web-mode. I hqd to delete the folder for it to update correctly. I'm going to try with this new version thanks. I love web-mode.
