### ISSUE TITLE
[feature request] add a new function to jump to a specific tag/element interactively

### ISSUE THREAD

**Issue by stardiviner** [fxbois/web-mode#664]
RT.
Provide a function to use completion system like `ido`, `ivy`, `helm` etc with a `defcustom` to jump to a specific tag/element interactively will speedup user navigation in code. (Even though user can `isearch`)
What do you think?

**Comment by fxbois** [comment]
Could you elaborate .... I do not really understand what you want

**Comment by stardiviner** [comment]
Usually, `[C-s]` (`isearch`) will search full buffer context.
I hope web-mode can provide a function to only search **tags** in current buffer.
But this function should use completion system for searching just like swiper.
Can you understand my question now?
I can't describe it more detailed.

**Comment by fxbois** [comment]
I won't have to work on this but will be happy to accept patch
