### ISSUE TITLE
Wrong indentation for playframework template

### ISSUE THREAD

**Issue by jilen** [fxbois/web-mode#665]
![screenshot from 2016-01-19 10-56-23](https://cloud.githubusercontent.com/assets/546573/12408433/521b9a02-be9b-11e5-86b8-dbbbfe1a1a5d.png)

**Comment by fxbois** [comment]
@jilen post your example on gist please

**Comment by jilen** [comment]
@fxbois  https://gist.github.com/jilen/640d272ada4bddb3cd7c

**Comment by fxbois** [comment]
@jilen could you post the output of ```web-mode-debug``` please

**Comment by jilen** [comment]
versions: emacs(24.5) web-mode("13.1.2")
vars: engine("razor") minor("razor") content-type("html") file("/tmp/foo.scala.html")
system: window(x) config("x86_64-unknown-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (rainbow-mode rainbow-delimiters-mode linum-mode global-linum-mode which-function-mode show-paren-mode nyan-mode global-auto-revert-mode helm-autoresize-mode async-bytecomp-package-mode shell-dirtrack-mode helm-mode electric-pair-mode volatile-highlights-mode subword-mode global-subword-mode anzu-mode global-anzu-mode company-mode global-company-mode company-quickhelp-mode yas-minor-mode yas-global-mode ethan-wspace-clean-tabs-mode ethan-wspace-clean-eol-mode ethan-wspace-clean-no-nl-eof-mode ethan-wspace-clean-many-nls-eof-mode ethan-wspace-mode global-ethan-wspace-mode projectile-mode projectile-global-mode flycheck-mode flycheck-color-mode-line-mode global-git-commit-mode magit-auto-revert-mode diff-auto-refine-mode global-git-gutter-mode which-key-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=t 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
is there anything in the ```*Messages*``` buffer ?

**Comment by jilen** [comment]
@fxbois  Nothing special. When I first open the file and select whole region, it ident well, but when I delete last `}`  then re-type '}', it cannot ident properly

**Comment by jilen** [comment]
@fxbois  I am pretty sure this issue still exist in the latest version

**Comment by fxbois** [comment]
@jilen I know, I must find time to work on this. I'll keep you posted

**Comment by fxbois** [comment]
@jilen I've pushed a fix

**Comment by jilen** [comment]
:+1: Works like a charm

**Comment by fxbois** [comment]
@jilen if you find time, it would be great to put on gist a very complete template with all the specific syntax and all the keywords ... I would be able to improve the compatibility

**Comment by teozkr** [comment]
This still seems to be broken using the latest version from MELPA.

More specifically, it seems to never want to dedent if the first thing inside the block is another `@`-thing. See https://gist.github.com/teozkr/d90eff707e4a94ca75cc29de35131ec1 for a few examples.

`web-mode-debug`:

```
versions: emacs(25.1) web-mode("14.1.1")
vars: engine("razor") minor("razor") content-type("html") file("/home/teo/Documents/nullauth/app/views/login.scala.html")
system: window(x) config("x86_64-unknown-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (hs-minor-mode global-eldoc-mode global-page-break-lines-mode global-auto-revert-mode xterm-mouse-mode global-spacemacs-leader-override-mode spacemacs-leader-override-mode evil-local-mode evil-mode undo-tree-mode global-undo-tree-mode override-global-mode which-key-mode clean-aindent-mode company-mode diff-auto-refine-mode eval-sexp-fu-flash-mode anzu-mode global-anzu-mode evil-escape-mode show-smartparens-mode show-smartparens-global-mode evil-search-highlight-persist global-evil-search-highlight-persist evil-surround-mode global-evil-surround-mode eyebrowse-mode flx-ido-mode flycheck-mode global-flycheck-mode shell-dirtrack-mode async-bytecomp-package-mode global-git-commit-mode global-git-gutter+-mode helm-flx-mode helm-mode helm-descbinds-mode ido-vertical-mode Info-breadcrumbs-in-mode-line-mode linum-mode persp-mode popwin-mode savehist-mode save-place-mode spaceline-helm-mode spaceline-info-mode vi-tilde-fringe-mode global-vi-tilde-fringe-mode volatile-highlights-mode window-numbering-mode winner-mode spacemacs-whitespace-cleanup-mode global-spacemacs-whitespace-cleanup-mode hl-todo-mode golden-ratio-mode projectile-mode yas-minor-mode yas-global-mode rainbow-delimiters-mode highlight-parentheses-mode highlight-numbers-mode auto-highlight-symbol-mode bug-reference-prog-mode goto-address-prog-mode evil-matchit-mode emmet-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
```

**Comment by fxbois** [comment]
@teozkr could you post a screenshot of an editor that colorises and indents the good way
TIA

**Comment by teozkr** [comment]
@fxbois Sorry, not quite sure what you mean. Do you want a screenshot from IDEA?

**Comment by fxbois** [comment]
@teozkr yes, it would be great

**Comment by teozkr** [comment]
![image](https://cloud.githubusercontent.com/assets/649832/23835195/5c64065e-0763-11e7-97ad-d639ea22fff6.png)

Should cover most of it.

However, it's sadly still wrong in a few places. Notably, the curly braces around the cases are required, and `@("x: " + x)` is not "useless" (although it's fairly pointless in this specific case).
