### ISSUE TITLE
Don't use mode for file type when narrowing

### ISSUE THREAD

**Issue by kevdunleavy** [fxbois/web-mode#666]
It would be nice if you could narrow the buffer of a `.js` file and force `web-mode` to treat the narrowed content as HTML, for example.

**Use Case:**
I am using ES 6 multi-line strings in `.js` files to define templates for Angular JS directives. If I narrow the buffer to the content of the template string I can then change to `html-mode` I get nice syntax highlighting. I would like to be able to do the same with `web-mode` since it is a much richer mode.

**Comment by fxbois** [comment]
@kevdunleavy could you post a example on gist please

**Comment by kevdunleavy** [comment]
Sure, [here's an example directive](https://gist.github.com/kevdunleavy/c945c0600ec2bc52ecce).

If I mark a region from the start of line 9 to the end of line 11 and run `narrow-to-region` I am presented with a buffer containing only template code (HTML with Angular expressions). If I then run `html-mode` the syntax highlighting updates correctly and I can work on the template comfortably and then run `widen` when I'm finished.

It would be great if I could run `web-mode` (or similar) instead and have an even better editing experience.

I can make it work by first cloning an indirect buffer from the full Javascript buffer, then renaming that indirect buffer to `example.js.html` and then narrowing to the template code like above and then entering `web-mode`. Since this is so cumbersome I wrote a function for it.

```lisp
(defun narrow-to-template (start end)
  "Narrow to region and then enter web-mode"
  (interactive "r")
  (deactivate-mark)
  (let ((buf (clone-indirect-buffer nil nil)))
    (with-current-buffer buf
      (narrow-to-region start end))
    (switch-to-buffer buf))
  (rename-buffer (concat (buffer-name) ".tpl.html"))
  (web-mode))
```

But that's a very specific function. It would be great if I could narrow and then run `web-mode-html` or something to force the mode without renaming the buffer. I could imagine this being useful for editing `<style>` or `<script>` blocks in HTML files too.

**Comment by fxbois** [comment]
@kevdunleavy have looked at ```(web-mode-set-content-type)``` ?

**Comment by fxbois** [comment]
@kevdunleavy PLease reopen if needed
