### ISSUE TITLE
Function call custom faces

### ISSUE THREAD

**Issue by TCMiranda** [fxbois/web-mode#668]
Hello,

Is it possible implement a similar behavior of js2-mode, in order to set a custom face for function calls like: something.`method()` ?

When using Javascript es6, I often get methods with barelly no custom faces, which makes it difficult to read pomises based functions. ex:

![captura de tela de 2016-01-26 10 12 20](https://cloud.githubusercontent.com/assets/10077439/12580336/da4d0292-c415-11e5-9066-1f11aa1eae09.png)

Other improvement, might be to recognize `(arg1, arg2) => {}` arguments as parameters.

The same code with js2-mode is displayed with globals and function calls faces, being much more readable:

![captura de tela de 2016-01-26 10 18 22](https://cloud.githubusercontent.com/assets/10077439/12580368/40460e4a-c416-11e5-98f1-9b582f0730b7.png)

Thanks!

**Comment by TCMiranda** [comment]
ps. I dont know much lisp, but I think that if I add the regexp here:
https://github.com/fxbois/web-mode/blob/master/web-mode.el#L1555

It will work, right?

Problem is I dont even know how to test it, modifying `~/emacs.d/elpa/web-mode.../web-mode.el` doesn't seems to work.

If one could help me get started, I can try to implement it.

Thanks!

**Comment by fxbois** [comment]
@TCMiranda please test the last version on github. You can customize ```web-mode-function-call-face```

**Comment by TCMiranda** [comment]
@fxbois thanks for your answer, but I cant make it work, in which circumstances the face would be activated?

**Comment by fxbois** [comment]
each time a function is called. Perhaps try to update the face

```(set-face-attribute 'web-mode-function-call-face nil :foreground "Pink3")```

**Comment by TCMiranda** [comment]
Setting it manually worked! I cant tell why, but thanks!

**Comment by pedroteixeira** [comment]
Hi there,

It seems currently the new "method definition" in es6 is interpreted as "Web Mode Function Call Face".
Is there currently way to distinguish between function call and method definition?

thank you,
Pedro
