### ISSUE TITLE
Can't get indent to work with Django engine

### ISSUE THREAD

**Issue by dlparker** [fxbois/web-mode#669]
I have been struggling with this. I have read the instructions, and I think I have followed them correctly. I have read all the closed issues involving indentation and django, and I didn't find any clues there. 

I hope you are going to tell me I misunderstood the instructions. 

Here is my config:

```
(load-file "~/.emacs.d/vendor/web-mode.el")
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
(defun my-web-mode-hook ()
  "Hooks for Web mode."
  (setq web-mode-markup-indent-offset 4)
  (setq web-mode-css-indent-offset 4)
  (setq web-mode-code-indent-offset 4)
  (setq web-mode-indent-style 4)
  (setq web-mode-style-padding 1)
  ;; For <script> parts
  (setq web-mode-script-padding 1)
  ;; For multi-line blocks
  (setq web-mode-block-padding 0)
  (setq web-mode-engines-alist
	'(("django"    . "\\.html\\'"))
	)
  (setq indent-tabs-mode nil)
)
(add-hook 'web-mode-hook  'my-web-mode-hook)
```

Here is what debug says about the buffer:
```

--- WEB-MODE DEBUG BEG ---
versions: emacs(24.3) web-mode("13.1.2")
vars: engine("django") minor("django") content-type("html") file("/home/dparker/dev/fplan/apps/fdata/templates/fdata/foo.html")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: nil
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

Here is the buffer after indenting:
```
<div id="content-main">
    <form id="form1" action="." method="post" class="well">
{% csrf_token %}
	<table>
{{ form.as_table }}
	</table>
    </form>
</div>

```

The above does not render quite right in github. The regular html tags are properly indented, the just don't look it here. The total lack of intending on the django tags is accurately shown.

**Comment by fxbois** [comment]
@dlparker where have you seen the value ```4``` for ```web-mode-indent-style``` ?
You should comment this line

**Comment by dlparker** [comment]
I can't remember where I got that line. You know how, when you are flailing about with something you really don't understand, and you are trying to apply change you read in issue reports and the like, you sometimes loose track of where you got it? No? Well, I do sometimes.

Thanks for your time and attention, you fixed me.

**Comment by fxbois** [comment]
Good News!
