### ISSUE TITLE
comment/uncomment multi-line snippet

### ISSUE THREAD

**Issue by redguardtoo** [fxbois/web-mode#670]
for hello.erb containing:
```erb
<%= render "form.html", changeset: @changeset,
                        action: trade_path(@conn, :update, @trade) %>
```
`M-x web-mode-comment-or-uncomment` won't comment out the snippet with right syntax, web-mode v13.1.2

Whe I select the whole region of above two lines, the region will be comment out with html syntax `<!-- -->` tags.

When no region is selected and the focus is at the first line, the first line will be comment out with html syntax.

**Comment by fxbois** [comment]
Where is the region-begging, where is the region-end ... please provide more info

**Comment by fxbois** [comment]
@redguardtoo when ```(point)``` is on the erb block, the commenting/decommenting should be ok
