### ISSUE TITLE
How to disable indentation when saving file in emacs?

### ISSUE THREAD

**Issue by Foxly1990** [fxbois/web-mode#671]
How to disable indentation when saving file in emacs?

**Comment by Foxly1990** [comment]
For web-mode, ofc

**Comment by fxbois** [comment]
What do you mean ?

**Comment by Foxly1990** [comment]
When I save the file then auto-indenture. How to disable?

**Comment by fxbois** [comment]
web-mode do not do this ... perhaps a minor mode in your .emacs

**Comment by Foxly1990** [comment]
Thx
