### ISSUE TITLE
Closing parents align to the left side

### ISSUE THREAD

**Issue by favetelinguis** [fxbois/web-mode#674]
Trying to use web mode with JavaScript but cant get it to understand how to align closing brackets.

Check `myTestFunc` in the followin gist:
[Faulty](https://gist.github.com/favetelinguis/b630f7ff26a15ca40b9a)

The gist also contains output from `web-mode-debug`

Instead of aligning the closing brackets to match the opening brackets. Is there some special setting that needs to be set to get this working or is this the intended behavior in web-mode

**Comment by fxbois** [comment]
@favetelinguis please post real example on gist.
Moreover, could you post the output of ```web-mode-debug```

**Comment by fxbois** [comment]
@favetelinguis it works here. Perhaps you should try to upgrade to the last version. After that, if it doesn't work, perhaps try to disable minor mode.
