### ISSUE TITLE
Some features dont work in emacsclient

### ISSUE THREAD

**Issue by connorjsmith** [fxbois/web-mode#675]
Several features (such as auto tag closing and quote pairing) don't work when using `emacsclient` to connect to a running daemon (`emacs --daemon`).  The features work fine when using emacs normally without `emacsclient`. 

Both of these were tested using the GUI version of emacs 24.5

**Comment by fxbois** [comment]
@connorjsmith does ```(display-graphic-p)``` returns true with emacsclient ?

**Comment by connorjsmith** [comment]
@fxbois yes it does

**Comment by fxbois** [comment]
could you try to debug a little bit in ```web-mode-on-post-command```

**Comment by DoMiNeLa10** [comment]
Auto tag closing should work if you add `(setq web-mode-enable-auto-closing t)` to your .emacs.

**Comment by fxbois** [comment]
Please reopen if anyone can provide some info
