### ISSUE TITLE
Disable auto quoting in jsx buffers only

### ISSUE THREAD

**Issue by zhengpd** [fxbois/web-mode#677]
I am trying to disable auto quoting in jsx buffers when there are multiple web-mode buffers. The following code works for me:

```lisp
  (make-local-variable 'web-mode-enable-auto-quoting)
  (setq web-mode-enable-auto-quoting
        (if (string= web-mode-content-type "jsx") nil t))
```

Just wonder if this is the right way to go since I haven't found any doc about this.

**Comment by fxbois** [comment]
do you put this code in a hook ?

**Comment by zhengpd** [comment]
Yes, I put it in `web-mode-hook`.

**Comment by fxbois** [comment]
so it seems like a perfect way to do so

**Comment by zhengpd** [comment]
Ok, thanks.
