### ISSUE TITLE
Auto close erroneously tries to close void elements

### ISSUE THREAD

**Issue by aiguofer** [fxbois/web-mode#679]
I have the following options set for web-mode:
```elisp
 '(web-mode-auto-close-style 2)
 '(web-mode-code-indent-offset 3)
 '(web-mode-css-indent-offset 3)
 '(web-mode-enable-auto-expanding t)
 '(web-mode-enable-auto-indentation t)
 '(web-mode-enable-sql-detection t)
 '(web-mode-markup-indent-offset 3)
 '(web-mode-script-padding 0)
 '(web-mode-sql-indent-offset 3)
 '(web-mode-style-padding 0)
```

I really like the `auto-close-style 2` to close when I type `>`, however when I'm typing a void tag like `<img>` or `<br>` it automatically tries to close it with the closing tag for the previous element.

For example, if I have
```html
<div>
   <img
</div>
```
when I close the `<img` I get:

```html
<div>
   <img></div>
</div>
```

**Comment by fxbois** [comment]
@aiguofer should be better with last commit

**Comment by aiguofer** [comment]
@fxbois thanks but this still doesn't seem to be working for me. I see this works outside of any other tags, but it still fails when i try closing

```
<div>
   <img
</div>
```

**Comment by fxbois** [comment]
@aiguofer I've pushed a new fix

**Comment by aiguofer** [comment]
Great this last commit seems to have fixed it, thanks!
