### ISSUE TITLE
Multiple variables and multiline arguments

### ISSUE THREAD

**Issue by prajwalit** [fxbois/web-mode#680]
Hello,

I'm trying to configure web-mode but couldn't find a config which fixes
colours of my multiple variables and multiline arguments.
For eg.

![pic 1](https://cloud.githubusercontent.com/assets/155951/13174829/4a3bffbc-d72c-11e5-859c-b4de186ec0e1.png)

Here, `bar` and `argument5` should be in brick-red just like `foo` and `argument1-4`.

I also wanted to fix the indentation when there are multiline arguments.
I wanted just the 2 spaces before `// Hello`.

![pic 2](https://cloud.githubusercontent.com/assets/155951/13174839/5bc81a5e-d72c-11e5-98d6-3ca89f15cf5a.png)
(Whether arguments are on single line or multiline shouldn't affect the indentation).

I went through web-mode.org, may be I missed some setting.
Sorry to bother you. And thanks for the awesome web-mode!

Here's the debug info:
```
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("13.1.4")
vars: engine("none") minor("none") content-type("jsx") file("/Users/prajwalit/repos/moby/resources/static/scripts/components/hsPage.jsx")
system: window(ns) config("x86_64-apple-darwin13.4.0")
colors: fg(nil) bg(nil) 
minor modes: (yas-minor-mode yas-global-mode git-gutter-mode global-git-gutter-mode smartparens-mode smartparens-strict-mode smartparens-global-strict-mode auto-complete-mode global-auto-complete-mode undo-tree-mode global-undo-tree-mode desktop-save-mode auto-revert-mode shell-dirtrack-mode async-bytecomp-package-mode global-git-commit-mode magit-auto-revert-mode diff-auto-refine-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
@prajwalit as I do "have" a proper js parser, I could not provide what you wan't.
