### ISSUE TITLE
indentation of html attribute string values

### ISSUE THREAD

**Issue by dd1dd1** [fxbois/web-mode#682]
Hi, I am figuring out how to use emacs to edit html files with embedded javascript code. As the stock html modes in emacs and xemacs do not indent javascript and most html in any useful way, I am trying your web-mode and I got everything working just right except for one little problem. As they say, instead of this I want this.

Currently I get my javascript code indented too much, everything shifts to the right:

          <input type=button value='Push me' onClick='var paths = [
                                                      "/Runinfo", ...
                                                      ];
                                                      mjsonrpc_db_get_values(paths).then(function(rpc) {
                                                      document.getElementById("db_get_values_json_data").innerHTML = JSON.stringify(rp...

See how everything is aligned to "onClick=" and most javascript code is shifted way to the right? I would rather have this: (allowing for github mangling everything, I put "x" instead of space)

<input type=button value='Push me' onClick='var paths = [
xxx "/Runinfo", ...
xxx ];
xxx mjsonrpc_db_get_values(paths).then(function(rpc) {
xxx document.getElementById("db_get_values_json_data").innerHTML = JSON.stringify(rp...

Also it would be nice if:

a) javascript were indented correctly inside string attributes like "onClick"
b) or web-mode had a way to preserve my indentation inside string attributes (like with "pre" tag?)
c) or had a mode for "align string attributes to previous line"

P.S. I know about web-mode-attr-indent-offset and it helps, but not good enough for me, I want
to indent be just a few spaces instead of by the length of "<input onClick=".

Thanks in advance, K.O.

**Comment by fxbois** [comment]
@dd1dd1 could you test the last version : it disables indentation in onclick attributes (see ```web-mode-indentless-attributes```). However, I won't work on automatic javascript indentation inside attribute values.

**Comment by dd1dd1** [comment]
yes, thank you. now is much better - stuff inside "onclick" is no longer indented all the way to the right and I can live with making my own indentation. maybe encourages people to move this stuff into standalone functions. K.O.
