### ISSUE TITLE
Feature request: Marko Template engine

### ISSUE THREAD

**Issue by CestDiego** [fxbois/web-mode#683]
According to the thread in
[reddit](https://www.reddit.com/r/emacs/comments/45bl91/anyone_using_marko_templates_what_webmode_engine/)
I hereby ask to support  in web-mode for the [marko](https://github.com/marko-js/marko
) templating language.

Thanks :)

**Comment by fxbois** [comment]
could you post a big example on gist (with many syntax features) please

**Comment by fxbois** [comment]
@CestDiego could you provide this example ?

**Comment by CestDiego** [comment]
What about this:

```
<lasso-page package-path="./Some_path" flags="data.someFlags"/>

<layout-use template="path/to/default-layout.marko"
    title="${data.pageTitle}"
    bodyClass="${data.bodyClass}">
    <layout-put into="body">
        <ul if(notEmpty(data.colors))>
          <li for(color in data.colors)>
            ${color}
          </li>
        </ul>
        <include template="path/${data.site}/template.marko"
            model="${data.model}" />
    </layout-put>
</layout-use>
```

**Comment by CestDiego** [comment]
this is the official repo https://github.com/marko-js/marko , and here are many features that explain what they do. http://markojs.com/try-online/#Expressions_Simple ... Given that marko can also be written in a jade-like syntax, I was wondering how hard is it to have `emmet` like expansion without the tags? I would work on this in the future if it's possible. And of course I'd need to create a mode based on web-mode because a template engine doesn't cut it for this I guess. A new mode kinda like how `react-mode` works in Spacemacs. What are your thoughts on this jade-like syntax support?

**Comment by fxbois** [comment]
@CestDiego I've pushed a fix to handle ```${ }``` expressions
web-mode is not compatible with jade like syntaxes

**Comment by CestDiego** [comment]
Thanks fxbois
