### ISSUE TITLE
riot.tag engine [question]

### ISSUE THREAD

**Issue by osv** [fxbois/web-mode#684]
Hi, I working on engine for [riot tag](http://riotjs.com/guide/#tag-syntax). It is very simple, so almost done in
https://github.com/osv/web-mode/tree/riot-engine branch

But I found bug that I can't solve myself. See below selected region:

![screenshot](http://rghost.net/8v4YvXZHV/image.png)

as you can see,  `<script>` (javascrip part) have engine blocks `{title: .. }` too. Can I disable it? currently I found next solution - check text property for parts:

```lisp
(defun web-mode-scan-blocks (reg-beg reg-end)
;; ....

         ((and (string= web-mode-engine "riot")
               (not (get-text-property reg-beg 'part-side))) ; <-- not in any parts (js, css, etc)
          (setq closing-string "}"
                delim-open "{"
                delim-close "}")
          ) ;riot
```
 But this work only if you go to part (`<script>`) and modify code for invalidate region and not work at start -when you open file. Can you help me?

**Comment by fxbois** [comment]
choosing ```{``` and ```}``` is such a strange idea. Anyhow, is it possible to have ```{ }``` riot blocks in a javascript part ?

**Comment by osv** [comment]
riot is minimalistic so not strange that they choose `{ }`. 

No, `<script>` is controller of view. In worse case riot tag can even have no `script` like below: 

```html
<todo>

  <!-- layout -->
  <h3>{ opts.title }</h3>

  // logic comes here, no script ;)
  this.items = [1, 2, 3]

</todo>
```

but that case is rare and I don't known any editor that can handle this situation.

How ever I tried find any similar templates that not allow engine blocks in some parts and fail.
