### ISSUE TITLE
vanish should retain position

### ISSUE THREAD

**Issue by ChillarAnand** [fxbois/web-mode#686]
```
|<p>
----
----
</p>
```

When cursor is at closing tag, if element is made to vanish, cursor is going to `|` position.

**Comment by fxbois** [comment]
@ChillarAnand I am not sure to understand what you mean. Please describe more precisely all the steps

**Comment by ChillarAnand** [comment]
```html
<h3>
<p>
-----
</p>
</h3|>
```
When `web-mode-element-vanish` is run, after removing `h3`, is moving cursor to beginning of position of `h3`, which results in

```html
|
<p>
-----
</p>
```

Instead it should retain cursor position like this

```html
<p>
-----
</p>
|
```

Does that help?

**Comment by fxbois** [comment]
This is not possible because this function takes an argument and enables to vanish more than one element. One thing i should do is forward the cursor to <p>

**Comment by ChillarAnand** [comment]
:+1:
