### ISSUE TITLE
Feature request: Command for linking files.

### ISSUE THREAD

**Issue by DoMiNeLa10** [fxbois/web-mode#689]
I think that adding a function that can link files (like pictures, scripts of stylesheets) would make this mode even better. I wrote some code that seems to work, but I'm not sure if it's good enough to be added to this extension. If it's good I could try to create a pull request. I wrote it so it can be extended to support more formats. I think C-c C-l would be a good shortcut for it.

Here's the code that I wrote:
https://gist.github.com/DoMiNeLa10/fa2113f4ad59748c071d

**Comment by DoMiNeLa10** [comment]
Is my code as of now good enough to be added to web-mode?

**Comment by fxbois** [comment]
@DoMiNeLa10 sorry to be late on this. I'll try to look at your patch this we

**Comment by fxbois** [comment]
@DoMiNeLa10 the last commit contains a version slightly different from your patch
https://github.com/fxbois/web-mode/commit/08078a39814f358a6e37898be2dd28f6ea5c6845

**Comment by DoMiNeLa10** [comment]
Thanks.
