### ISSUE TITLE
React JSX Formatting Breaks When Mixed With HTML  

### ISSUE THREAD

**Issue by sshaw** [fxbois/web-mode#691]
This is using version `13.1.9`. 

Initially everything is okay:
<img width="576" alt="1" src="https://cloud.githubusercontent.com/assets/17570/13899213/d10215e2-edbe-11e5-9225-2f4fd0cf3ea5.png">

Then I make the following modification:

![2](https://cloud.githubusercontent.com/assets/17570/13899237/7ee5a80e-edbf-11e5-9758-c1082b5f4f90.png)

Note the  assignment to `CommentList` no longer has syntax highlighting.

Then, calling `indent-region` on the `CommentList` assignment produces: 

<img width="537" alt="3" src="https://cloud.githubusercontent.com/assets/17570/13899242/9a74a9bc-edbf-11e5-89d1-0583193449c3.png">

**Comment by fxbois** [comment]
@sshaw have you tried in a plain jsx file ?
Moreover, could you post your example on gist please

**Comment by yzprofile** [comment]
First:

```html
<!DOCTYPE html>
<html>
    <body>
        <div id="example"></div>
        <script type="text/babel">
         ReactDOM.render(
             <div>
                    <h1>Hello, world!</h1>
             </div>,
             document.getElementById('example')
         );
        </script>
    </body>
</html>
```

Then:

```html
<!DOCTYPE html>
<html>
    <body>
        <div id="example"></div>
        <script type="text/babel">
         ReactDOM.render(
             <div>
                    <h1>test<h1>
                    <h1>Hello, world!</h1>
             </div>,
             document.getElementById('example')
         );
        </script>
    </body>
</html>
```

Now, We indent at first `<div>`, and `ReactDOM.render(`

You will see:

```html
<!DOCTYPE html>
<html>
    <body>
        <div id="example"></div>
        <script type="text/babel">
            ReactDOM.render(
            <div>
                 <h1>test</h1>
                 <h1>Hello, world!</h1>
             </div>,
             document.getElementById('example')
         );
        </script>
    </body>
</html>
```

**Comment by sshaw** [comment]
> @sshaw have you tried in a plain jsx file ?

Yes, it's not a problem there. 

> Moreover, could you post your example on gist please

https://gist.github.com/sshaw/1065c8608075ba82f42de6c03edf54d5

**Comment by fxbois** [comment]
@sshaw can you test the last version on github please

**Comment by sshaw** [comment]
@fxbois just cloned the repo and did a `load-file` and the problem still exists.

**Comment by fxbois** [comment]
@sshaw I've pushed another fix

**Comment by sshaw** [comment]
It's working 🎉

**Comment by NeilMenne** [comment]
I am having this problem. I am using web-mode version 20160702.718, so I was surprised to hit this. Was there something other than just updating that was required to fix the problem?
