### ISSUE TITLE
Destructuring (es6) is not supported

### ISSUE THREAD

**Issue by CestDiego** [fxbois/web-mode#694]
This is what is looks like, the destructuring part is very important for React and ES6 in templates so I think this should be supported.

![screen shot 2016-03-24 at 4 17 30 pm](https://cloud.githubusercontent.com/assets/3291619/14030062/060d60d6-f1dc-11e5-8c54-2f7d1e8c2dd5.png)

code:

```
import React from "react";
import { RouteHandler } from "react-router";

import { Row, Col, Input} from "react-bootstrap";

import CollectionContainer from "./CollectionContainer"

export default React.createClass({
  render: function() {
    let collections = this.props.collections;
    let CollectionContainers = Object.keys(collections).map( (index) => {
      let data = {
        index: index,
        collection: collections[index]
      }
      return <CollectionContainer {...data} />
    });
    let styles = {
      highlight: {
        backgroundColor: "#f6f6f6"
      }
    }

    return (
      <Col lg={12} md={12}>
        <form action="">
          <Input type="text" label="Promo Message" htmlFor="promoMessage"  />
          <Row>
            <Col lg={2}> </Col>
            <Col lg={4}>Collection id</Col>
            <Col lg={4}>Description</Col>
          </Row>
          {CollectionContainers}
        </form>
      </Col>
    );
  }
});
```

**Comment by fxbois** [comment]
@CestDiego could you be more precise on what do you need ?
```{...data}``` is already highlighted with last version of web-mode

**Comment by CestDiego** [comment]
I will update when I update :)

On Fri, Mar 25, 2016, 11:58 AM fxbois <notifications@github.com> wrote:

> @CestDiego <https://github.com/CestDiego> could you be more precise on
> what do you need ?
> {...data} is already highlighted with last version of web-mode
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/fxbois/web-mode/issues/694#issuecomment-201342653>
>
-- 
Diego Berrocal
http://cestdiego.github.io

**Comment by CestDiego** [comment]
UPDATE: indeed I hadn't updated web-mode and this wasn't showing. Just updated and the {...data}} is highlighted as one would expect.

**Comment by CestDiego** [comment]
Thank you @fxbois
