### ISSUE TITLE
Conflict with editorconfig-mode

### ISSUE THREAD

**Issue by choma** [fxbois/web-mode#695]
When I use web-mode with [editorconfig-mode](https://github.com/editorconfig/editorconfig-emacs) something strange happens with `web-mode-block-padding` variable. I'm not sure how nor where, it is set with the value 4, resulting in this code:
```php
<?php
class SomeClass {
    function some() {}
}
```
to be indented like this:
```php
<?php
    class SomeClass {
        function some() {}
    }
```
You can see what I mean with this very basic init.el file:
```elisp
;; Add package sources
(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
                         ))
(package-initialize)

(unless (package-installed-p 'use-package)
  (progn
    (package-refresh-contents)
    (package-install 'use-package)))
(setq use-package-verbose t)
(setq use-package-always-ensure t) ;; use :ensure t for all packages

(eval-when-compile
  (require 'use-package))

;; editorconfig (editorconfig.org)
(use-package editorconfig)
(editorconfig-mode 1)

;; web-mode (php,js,html,css)
(use-package web-mode)
```
I've already reported [this](https://github.com/editorconfig/editorconfig-emacs/issues/79) to editorconfig developers, but they say it may be a web-mode issue, and a suggested this workaround:
```elisp
(add-hook 'editorconfig-custom-hooks
          (lambda (hash) (setq web-mode-block-padding 0)))
```
My `web-mode-debug` output:
```
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("13.1.10")
vars: engine("php") minor("php") content-type("html") file("/home/my-user/tests/test.php")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (override-global-mode editorconfig-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
@choma ```web-mode-block-padding``` is set to 0 by default. You should check ```editorconfig-mode ``` (or other minor modes you are using).

**Comment by xuhdev** [comment]
@fxbois The problem is not about the conflict: it is not about editorconfig at all. The issue is that, whether `web-mode-block-padding` should indent the line after `<?php`. For me, I don't really see any point to affect the line below `<?php` with `web-mode-block-padding`. What do you think?

**Comment by fxbois** [comment]
@xuhdev it is a feature. If you don't like it, put it to zero
