### ISSUE TITLE
Wrong indentation for javascript without semicolon

### ISSUE THREAD

**Issue by arongp** [fxbois/web-mode#696]
```
foo() {
    bar()
        baz()
}
```

The line with bar() has no ending semicolon, and baz() is incorrectly indented.

**Comment by fxbois** [comment]
@arongp could you post the output of ```web-mode-debug``` please

**Comment by arongp** [comment]
Here it is:

--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("13.1.12")
vars: engine("none") minor("none") content-type("javascript") file("c:/abc.js")
system: window(w32) config("i686-pc-mingw32")
colors: fg(nil) bg(nil) 
minor modes: (size-indication-mode electric-pair-mode global-auto-revert-mode icomplete-mode show-paren-mode projectile-mode projectile-global-mode which-key-mode ido-vertical-mode undo-tree-mode global-undo-tree-mode override-global-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@arongp should be fixed with last commit

**Comment by arongp** [comment]
@fxbois thanks, I see it's fixed now.
