### ISSUE TITLE
Closing comment in freemarker template is wrong

### ISSUE THREAD

**Issue by jcubic** [fxbois/web-mode#699]
In FreeMarker template you can close comments with `-- anything >` it should be only `-->`. this also work as closing comment `-      - something else >`

**Comment by jcubic** [comment]
I think that right now closing comment is just `>`.

**Comment by fxbois** [comment]
@jcubic should be better with last commit
https://github.com/fxbois/web-mode/commit/e02ddb3444afb1d59a4b787bf274f90ba19079a6

**Comment by jcubic** [comment]
I've pull last changes and it's still the same, it's closing by single `>`.

**Comment by jcubic** [comment]
it seems that this change only added auto insert of `-->` when type `<#--`

**Comment by fxbois** [comment]
So i do not understand what you want

**Comment by jcubic** [comment]
I want syntax highlight for comment to not end by single `>` but by `-->`.

**Comment by fxbois** [comment]
@jcubic should be better now

**Comment by jcubic** [comment]
It works, thanks.
