### ISSUE TITLE
Typing parentheses in long Javascript files is very slow

### ISSUE THREAD

**Issue by zeptonaut** [fxbois/web-mode#700]
I've been working on some long Javascript files recently and have noticed that inserting braces is *extremely* slow with web-mode enabled.

For example, when I insert a left parenthesis on [this line of code](https://github.com/catapult-project/catapult/blob/3008811061493ca0888b899fb97840b0ff647d49/tracing/tracing/extras/importer/trace_event_importer_test.html#L5650), it takes 5-10 seconds to insert on a fast machine.

I hooked up the emacs profiler (`M-x profiler-start`, run command, `M-x profiler-report`) when doing this, which generated this report:

```
- command-execute                                                5445  99%
 - call-interactively                                            5445  99%
  - funcall-interactively                                        5412  98%
   - self-insert-command                                         5397  98%
    - sp--post-self-insert-hook-handler                          5393  98%
     - sp-insert-pair                                            5393  98%
      - font-lock-after-change-function                          5393  98%
       - font-lock-fontify-region                                5393  98%
        - font-lock-default-fontify-region                       5393  98%
         - web-mode-extend-region                                5049  92%
          - web-mode-propertize                                  5049  92%
           - web-mode-invalidate-region                          5049  92%
            - web-mode-scan-region                               5029  91%
             - web-mode-process-parts                            5009  91%
              - web-mode-part-scan                               5005  91%
                 looking-back                                    4985  91%
                 web-mode-dom-rsf                                   8   0%
               web-mode-scan-elements                               4   0%
            + web-mode-invalidate-region-beginning-position                 20   0%
         + font-lock-fontify-keywords-region                      344   6%
    + font-lock-after-change-function                               4   0%
   + execute-extended-command                                      15   0%
  + byte-code                                                      33   0%
+ ...                                                              20   0%
+ whitespace-post-command-hook                                      5   0%
```

Is there any way that we could get this fixed?

**Comment by zeptonaut** [comment]
Investigating this more, it seems like this problem only exists when smartparens mode is enabled. A minimal init file that reproduces the problem is:

```elisp
(require 'package)
(package-initialize)

(require 'smartparens-config)
(smartparens-global-mode 1)

(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))
```

**Comment by zeptonaut** [comment]
Also, for some reason, the parenthesis is only taking around 1 second to insert now. Still worth looking into what's making this slow.

**Comment by fxbois** [comment]
@zeptonaut Hi, thank you to have investigated. I do not work on minormode related issues ... however I'll be happy to provide help to anyone that wants to dig into it

**Comment by zeptonaut** [comment]
Alright - I think that I'll look into it. 

My initial hunch is that the beginning and end parameters aren't being passed properly somewhere along this call chain, causing web-mode to try to rescan the whole file every time that any paired character is called.

Ultimately, [this](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L4281-L4391) is the problematic code (specifically the `looking-back` part of it).

**Comment by zeptonaut** [comment]
Looks like that hunch is confirmed.

Inserting a left parenthesis anywhere in the script region ultimately causes `web-mode-part-scan` to be called with `reg-beg` of 1849 and `reg-end` of 111,042 - almost 110,000 characters. Now I'm going to see if I can track down why this is happening.

**Comment by fxbois** [comment]
try to debug in ```web-mode-on-post-command``` 
perhaps some smartparens function could be ignored

**Comment by zeptonaut** [comment]
What does `web-mode-on-post-command` do?

**Comment by fxbois** [comment]
called after each command

**Comment by zeptonaut** [comment]
I might be misunderstanding, but it seems like `web-mode-extend-region` might be doing the wrong thing here. When I insert `(` and `)` automatically gets inserted, `web-mode-extend-region` gets called. My understanding is that this function gets called in order to make sure that the region that needs to be refontified is correct. This is necessary because, by default, modes only rehighlight the changed line, but `web-mode` (like many other modes) allows for multiline syntactic elements.

It seems like the problem that we're having is that `web-mode-extend-region` is saying "just rehighlight everything between the script tags" instead of doing something smarter. I don't have any concrete suggestions to fix this, but it does seem like that might be the problem. 

Does that sound right, @fxbois?

**Comment by fxbois** [comment]
@zeptonaut in my case extend-region is also used to lexify to region (find tokens like strings, comments, jsx elements etc.). So it is normal that an insertion calls extend-region

**Comment by zeptonaut** [comment]
Is it normal, though, that the region re-lexified would be everything between the script tags?

**Comment by fxbois** [comment]
@zeptonaut when you uncomment the ```(message )``` line in ```web-mode-scan-region``` you see that ```web-mode``` does not always try to scan the entire ```<script>``` with an insertion of ```(```

**Comment by fxbois** [comment]
@zeptonaut reopen if needed
