### ISSUE TITLE
RFE: *-prefix for multi line comments in PHP

### ISSUE THREAD

**Issue by sphakka** [fxbois/web-mode#702]
When using '/* */' comment style in PHP, it would be nice to have (optional) *-prefixing (JavaDoc-ish...) in multi-line snippets. This would help preserving indented lines.
That is, given
```
<?php
foo
  bar
    baz
```
`web-mode-comment-or-uncomment` would give
```
<?php
/* 
 * foo
 *   bar
 *     baz 
 */
```
instead of (which might well be a bug, indeed...)
```
<?php
/* foo
   bar
   baz */
```

**Comment by miguel-guedes** [comment]
This behaviour can also be observed when editing Javascript source files (and possibly Js blocks).

**Comment by fxbois** [comment]
@sphakka should be better with last version on github
