### ISSUE TITLE
Yank indent line

### ISSUE THREAD

**Issue by jcubic** [fxbois/web-mode#703]
Now something weird happen when I paste (yank) text inside comment and when I have this comment:
```
<#---
 -- |
-->
```
and yank when I'm on the line that's indented 1 space, after yank the space is removed, like when I press <kbd>TAB</kbd>.

```
<#---
-- some text that was yanked
-->
```

There was no such behavior before #699 was fixed.

**Comment by fxbois** [comment]
perhaps because, it was not considered as a real comment. I ll try to do something about it.

**Comment by jcubic** [comment]
I think that yanking should not indent at all, like with other major modes.

**Comment by fxbois** [comment]
@jcubic I won't change the current behavior. But now lines are aligned

**Comment by jcubic** [comment]
Now it indent 2 spaces insidead of 1 I think that indentation should be disabled for comments if possible in javascript mode indentaion in multiline comments is the same amount of spaces as the previous line.

**Comment by fxbois** [comment]
Yes I align the prefix ```--```
