### ISSUE TITLE
Add support for css/js tag customization?

### ISSUE THREAD

**Issue by NdYAG** [fxbois/web-mode#705]
Usually styles and scripts are contained in `<style>` and `<script>` tags, but in some cases they could also be in other tags.

For example, we did some slight modification on Mako: 

we defined two customized blocks

```html
<%block filter="collect_js">
// js content
<%/block>
``` 

and

```html
<%block filter="collect_css">
// css content
</%block>
```

to combine css/js snippets in different templates into a single css/js file later.

The block name might change in different engines, so it would be great to support css/js tag name customization.

ref: https://github.com/fxbois/web-mode/issues/421

**Comment by NdYAG** [comment]
Styles or scripts inside `<style>` or `<script>` still have their `element-content-style` set as `css` or `javascript`.

So is it possible to let the user set `element-content-type` in any tags/blocks pair?

**Comment by fxbois** [comment]
@NdYAG I'll look at this

**Comment by fxbois** [comment]
@NdYAG should be ok with last commit

**Comment by NdYAG** [comment]
Amazing @fxbois !
It works for me now.
