### ISSUE TITLE
web-mode + whitespace-mode give broken mode

### ISSUE THREAD

**Issue by Holt59** [fxbois/web-mode#706]
I have trouble getting `web-mode` to work with `whitespace-mode`, if I open a file with both mode enabled, I get error like this one:

```
File mode specification error: (invalid-regexp "Invalid content of \\{\\}")
font-lock-fontify-keywords-region: Invalid regexp: "Invalid content of \\{\\}"
```

This seems to happen when I load `whitespace-mode` in a buffer with `web-mode`.

Then most of the modes are broken: white spaces are not displayed correctly, syntax highlighting does not work anymore, automatic closing tags neither, and so on.

`web-mode` works perfectly if I do not enable `whitespace-mode` and `whitespace-mode` also works if I do not enable `web-mode`.

**Comment by fxbois** [comment]
@Holt59 I do not work on issues related to minor modes. Perhaps you could try on emacs stackoverflow

**Comment by fxbois** [comment]
@Holt59 please reopen if you need that I provide help
