### ISSUE TITLE
forward-sexp (C-M-f) doesn't work in jsx files

### ISSUE THREAD

**Issue by kwillick** [fxbois/web-mode#707]
When editing a jsx file, pressing ```C-M-f``` for the ```forward-sexp```command has no effect.
Example: I want to skip over the braces after the style attribute, but it has no effect.
| is the cursor.
```jsx
return (
  <div style=|{ { width: '30%' } }>
  </div>
);
```
web-mode version: 13.1

**Comment by fxbois** [comment]
@kwillick should be better with last commit
