### ISSUE TITLE
Keywords colors when used as properties

### ISSUE THREAD

**Issue by arcanis** [fxbois/web-mode#708]
The following:

```
@connect((state, props) => ({

    error: state.errorRegistry.get(resourceRequest(props.eventLocator)).relevant,
    event: state.resourceRegistry.get(props.eventLocator)

}))
```

gives the following:

![image](https://cloud.githubusercontent.com/assets/1037931/14424261/68ddb032-ffe0-11e5-9523-112dc10300b5.png)

As you can see, the `get` property member is highlighted with the wrong color (the same is true for any other ES keyword, even those that are allowed per the spec to be used as property names, such as `delete`, `get`, `set`, etc - which make it worse since these names are heavily used by the new ES6 containers).

Less an issue, but it also happens inside JSX text tags (in this example, the `in` keyword):

![image](https://cloud.githubusercontent.com/assets/1037931/14424397/1f56daaa-ffe1-11e5-8d0d-f4d023c40f02.png)

**Comment by fxbois** [comment]
@arcanis can you try the last commit please

**Comment by arcanis** [comment]
It works fine, except for `for()` constructs, in which keywords (such as `var` / `let`) are not highlighten anymore.
