### ISSUE TITLE
Multi-line comment

### ISSUE THREAD

**Issue by miguel-guedes** [fxbois/web-mode#710]
If I start a new comment in a javascript source file with <kbd>M;</kbd>, the string `/* */` is appended and point is placed in the middle.  However, if I attempt to add a new line inside the comment block by hitting <kbd>M-j</kbd>, the following happens:

```javascript
/* Start of comment line (M-j pressed)
   /<point>*/
```

... whereas the expected behaviour should be:

```javascript
/* Start of comment line (M-j pressed)
 * <point> */
```
Is this a known bug or is there something I need to do to configure web-mode correctly?

Many thanks.

**Comment by fxbois** [comment]
@miguel-guedes I'll look if ```comment-indent-new-line``` can be bound

**Comment by miguel-guedes** [comment]
@fxbois Many thanks for looking into this!

**Comment by fxbois** [comment]
@miguel-guedes I've added this to the last version on github

**Comment by miguel-guedes** [comment]
@fxbois Much closer but I think it's not quite there yet.

Consider the following code block:

```c
function foo()
{
  deactivate.me();
  deactivate.alsoMe();
}
```

In `c-mode`, commenting out the two bogus statements in `foo` would look like:

```c
function foo()
{
/*   deactivate.me(); */
/*   deactivate.alsoMe(); */
}
```

*The same result is observed in `c++-mode` and `php-mode`.*

`web-mode` is currently producing the following:

```javascript
function foo()
{
  /*deactivate.me();
   *deactivate.alsoMe();*/
}
```

So it seems that,
* it is producing a comment block encompassing the selection and not comments on a per-line basis like `c-mode` and similar modes.
* it isn't adding a space between the commented content and the comment prefix.

However, <kbd>M-j</kbd> now works *and* adds a space after the prefix.

Also note that if I set the comment format in `web-mode-comment-formats` to `//`, the following is produced:

```javascript
function foo()
{
  //deactivate.me();
  //deactivate.alsoMe();
}
```

The only thing wrong when the `//` comment style is used is lack of a space between prefix and commented content.  <kbd>M-j</kbd> works but, again, without the space.

Another issue I spotted is that if I set the comment format to `//` (for javascript) and hit <kbd>M-j</kbd> to create a comment, it produces `/* */`. For instance:

```javascript
function foo()
{
  /* . */ 
}
```

(`.` symbolises point)
and not:
```javascript
function foo()
{
  // . 
}
```

**Comment by fxbois** [comment]
@miguel-guedes 

see ```web-mode-comment-formats``` to set an alternative comment format.

I've added a space at the beginning of the comment lines.

Concerning repeating ```/**/ /**/``` on each line, I prefer the alternative way and won't implement it.
