### ISSUE TITLE
For-of indentation

### ISSUE THREAD

**Issue by arcanis** [fxbois/web-mode#711]
ES6 adds a new iteration operator: `of`. This keyword doesn't seem to be recognized yet, and as such is not highlightened. On top of that, the identation is wrong when the statement doesn't use curly braces:

![image](https://cloud.githubusercontent.com/assets/1037931/14584003/49c70740-0434-11e6-99a8-872dc925a0c9.png)

[gist](https://gist.github.com/arcanis/1d1ddbef8a94046c9bef5393c1bfe246)

**Comment by fxbois** [comment]
@arcanis please also post your example on gist please

**Comment by arcanis** [comment]
Sure thing, I've updated my first post to add this information :)

**Comment by fxbois** [comment]
@arcanis should be ok with last commit

**Comment by arcanis** [comment]
Thanks ! :+1:
