### ISSUE TITLE
Nested no-curly constructs break indentation

### ISSUE THREAD

**Issue by arcanis** [fxbois/web-mode#712]
The [following code](https://gist.github.com/arcanis/c98ec8f421923c106406c3eb4691d95c) breaks the indentation if multiple indented constructs are used without curly braces.

```js
if (a)
  if (b)
  if (c) // wrong indent
  ; // wrong indent
```

should be

```js
if (a)
  if (b)
    if (c)
      ;
```

**Comment by fxbois** [comment]
@arcanis should be fixed
