### ISSUE TITLE
Font-locking of nested sub-expressions in Handlebars

### ISSUE THREAD

**Issue by simenheg** [fxbois/web-mode#720]
In the following Handlebars template, everything from the first `(` up until the first `)` is font-locked with `web-mode-block-attr-value-face` as expected, but the values after that haven't received a face:

``` hbs
{{foo prop=(or a (and b c) d e)}}
```

This always seems to happen in presence of nested sub-expressions.

**Comment by fxbois** [comment]
@simenheg does it work when you put it inside quotes?

**Comment by simenheg** [comment]
@fxbois: Hm, put what inside quotes?

**Comment by fxbois** [comment]
@simenheg ```prop="(or a (and b c) d e)"```

**Comment by simenheg** [comment]
Yes, then the font-lock gets right, but it has different semantics in the template.

`prop="(or a (and b c) d e)"` binds `prop` to a string, while `prop=(or a (and b c) d e)` binds prop to the value of evaluating `(or a (and b c) d e)` (where `or` and `and` works just like in Emacs Lisp).

**Comment by fxbois** [comment]
@simenheg this one is really more difficult ... perhaps you could provide a patch

**Comment by simenheg** [comment]
OK @fxbois, I can try to look into it.
