### ISSUE TITLE
Invalid indentation of chained methods when dot present before method invocation

### ISSUE THREAD

**Issue by miguel-guedes** [fxbois/web-mode#722]
The indentation of chained methods is invalid if there is a dot before the invocation to the dominating method:

```javascript
  $(document.body).append("<span>Field label</span>")
            .attr(...);
```

Expected:

```javascript
  $(document.body).append("<span>Field label</span>")
                  .attr(...);
```

Incidentally, if one attempts to place the invocation to an object's method in the following line, the indentation is also invalid:

```javascript
// The dominating statement is rather long at 45 chars making indentation of 
// chained methods at col 46 impractical.  We then place the first method
// invocation in the following line expecting `web-mode' to increase the 
// indentation level by 1.
$('<div style="background: #fff">Open</div>')
.attr("data-id", "foo");
```

Expected:

```javascript
$('<div style="background: #fff">Open</div>')
  .attr("data-id", "foo");
```

EDIT:
Third case would be when there is a dot in the parent statement but the actual method invocation is moved to the following line:

```javascript
$(document.body)
          .append("<span/>")
          .attr(...);
```

Expected:

```javascript
$(document.body)
  .append("<span/>") 
  .attr(...);
```

**Comment by fxbois** [comment]
@miguel-guedes please give a complete example for the second issue

**Comment by miguel-guedes** [comment]
@fxbois Not a problem!  What else would you like me to include?

**Comment by fxbois** [comment]
@miguel-guedes just a normal script ... not a statement that begins at the column X

**Comment by miguel-guedes** [comment]
@fxbois I've improved the second case above (edited original post).  Would that be enough, do you think?

**Comment by miguel-guedes** [comment]
@fxbois Added a third case to the original post.
