### ISSUE TITLE
Feature request: buffer local comment format variables

### ISSUE THREAD

**Issue by miguel-guedes** [fxbois/web-mode#723]
I often work on source files written by different (people and) organisations that employ different code styles.  And it's often the case that some organisations prefer 4 chars indentation, while others favour 2 chars, and `/* */` comments rather than `//`.  This is easy enough to specify in a source file in Emacs and one of the ways is via local variables. For instance, the following declaration sets up the comment style and indentation offset in a PHP source file:
 
```php
// --
// Local Variables:
// c-basic-offset: 4
// comment-start: "//"
// comment-end: ""
// End:
```

However, currently `web-mode` seems to expose comment formats on a per mode in a *global* variable, `web-mode-comment-formats`.  

Would it be possible for buffer local variables to be introduced in `web-mode` for the purpose of specifying comment start and end prefixes?

**Comment by fxbois** [comment]
@miguel-guedes I've added ```(make-local-variable 'web-mode-comment-formats)``` is it what you want ?
