### ISSUE TITLE
Broken regular expressions in web-mode-file-extensions

### ISSUE THREAD

**Issue by DoMiNeLa10** [fxbois/web-mode#724]
The regular expressions in web-mode-file-extensions are broken because I forgot to escape backslashes properly.

**Comment by DoMiNeLa10** [comment]
I fixed this in this commit in my fork:
https://github.com/DoMiNeLa10/web-mode/commit/a669a30422361726cb4acdbd5913175d00780ea6
(I have no idea how to attach commits to issues)

**Comment by ldeck** [comment]
@DoMiNeLa10 you'd create a pull request

**Comment by DoMiNeLa10** [comment]
https://github.com/fxbois/web-mode/pull/781
I made a pull request with improvements to the function.
