### ISSUE TITLE
JavaScript indentation in Razor

### ISSUE THREAD

**Issue by allencch** [fxbois/web-mode#725]
In a .html file with the following sample code,

    <!DOCTYPE html>
    <html>
      <head>
        <script>
        function foo() {
          alert('foo');
        }
        function bar() { //this line will be indented in cshtml
          alert('bar');
        }
        </script>
      </head>
    </html>

When the code saves as .cshtml (Razor), the indentation of the function does not work properly

    <!DOCTYPE html>
    <html>
      <head>
        <script>
        function foo() {
          alert('foo');
        }
          function bar() { //this line will be indented in cshtml
            alert('bar');
        }
        </script>
      </head>
    </html>

More functions written will produce more indents. Adding a semicolon after function will make the indentation properly, but usually we do not use semicolon after function.

**Comment by fxbois** [comment]
@allencch please test the last commit

**Comment by allencch** [comment]
@fxbois , works perfect! Thanks
