### ISSUE TITLE
HTML attributes do not benefit of syntax colorization

### ISSUE THREAD

**Issue by yamafaktory** [fxbois/web-mode#727]
Hi,

First of all,  many thanks for your awesome work!
I'm trying to get some syntax colorization in the HTML attributes, as mentioned in https://github.com/fxbois/web-mode/issues/263, without success.

Is anything special that I need to activate in order to get it eventually working?

N.B.: My .emacs settings are available [here](https://github.com/yamafaktory/.emacs.d).

**Comment by fxbois** [comment]
do you mean javascript colorisation in the attribute value ?
web-mode.el does not provide this

**Comment by yamafaktory** [comment]
Yup, exactly! Ok, so closing that issue then. Thanks!

**Comment by fxbois** [comment]
I'll try to look at it this week end.
Could you post a complete example on gist please

**Comment by yamafaktory** [comment]
Ok, here it is https://gist.github.com/yamafaktory/beec0bc47fa8cf26e986e58ceaf19780. That's some Angular template, but could be React too in a JSX component.

Thanks!

**Comment by fxbois** [comment]
@yamafaktory do you have a screenshot of an editor that handles this the way you want ?
