### ISSUE TITLE
disable auto indentation

### ISSUE THREAD

**Issue by mikemakuch** [fxbois/web-mode#729]
Is there any way to completely disable auto indentation in web-mode? I have electric-indent-mode 0, but that doesn't seem to affect auto indentation in web-mode. Thx.

**Comment by fxbois** [comment]
@mikemakuch have you tried ```(setq web-mode-enable-auto-indentation nil)``` ?

**Comment by mikemakuch** [comment]
That doesn't work. This does;

**Comment by Soreine** [comment]
`(setq web-mode-enable-auto-indentation nil)` worked for me (using JSX), whereas @mikemakuch did nothing

**Comment by featheredtoast** [comment]
`(setq web-mode-enable-auto-indentation nil)` fixed it for me, too.

Could `electric-indent-mode` also alter `web-mode-enable-auto-indentation` somehow? It would save users from digging, who have no idea where indentation features are coming from. Stumbled on this ticket from a few hours of going around in circles, googling "emacs disable auto indent".

**Comment by runekaagaard** [comment]
@featheredtoast Disabling `electric-indent-mode` fixed the problem for me. One can do it for all major modes like this:

    ; Disable electric indent.
    (electric-indent-mode -1)
    (add-hook 'after-change-major-mode-hook (lambda() (electric-indent-mode -1)))

**Comment by keisetsu** [comment]
I don't know if this is related, but it is auto-indenting whenever I close a tag. Have tried all the above, no luck. I have to use a different editor when making changes to html; probably have to stop using web-mode, unfortunately.

**Comment by 1MikeMakuch** [comment]
What I've evolved into doing is, for each language/syntax, I have a beautifier that I like and have it format the buffer every time I save. Works for me.

**Comment by keisetsu** [comment]
Actually, updated to latest version of web mode and it looks like it is responding to runekaagard's suggestion.
Unfortunately, we don't have a standard set up for html in my group, so I have to take a hands off policy. (no pre-save beautifier, maybe one day...) Was having to undo huge sections I hadn't noticed had been indented until it came time for code review.
