### ISSUE TITLE
Uncommenting a subset of a comment block (javascript)

### ISSUE THREAD

**Issue by miguel-guedes** [fxbois/web-mode#734]
Consider the following code block:

```javascript
/* fetch(this.url, this.options)
 *   .then((xhr) => {
 *     if(!xhr.ok) reject(xhr);
 *   });*/
```

Attempting to uncomment a subset of the block (say, the `if` line) results in the entire block being uncommented, whereas it should ideally only uncomment the current active region:

```javascript
fetch(this.url, this.options)
  .then((xhr) => {
    if(!xhr.ok) reject(xhr);
  });
```

Expected:

```javascript
/* fetch(this.url, this.options)
 *   .then((xhr) => { */
if(!xhr.ok) reject(xhr);
/*   }); */
```

**Comment by fxbois** [comment]
@miguel-guedes I wont work on this. No not hesitate to send a patch.

**Comment by miguel-guedes** [comment]
@fxbois Not a problem.  Unfortunately I lack the time and haven't looked at the code.  How complicated is implementing this feature likely to be, in your opinion?  I take it that's (at least part of) the reason you're not working on this?
