### ISSUE TITLE
`fill-column` ignored

### ISSUE THREAD

**Issue by miguel-guedes** [fxbois/web-mode#735]
It seems `auto-fill-mode` does not seem to work inside a comment block; e.g. when the char count exceeds `fill-column`, the current line isn't broken up and indented as one is typing.

For instance, assuming `fill-column` is `79` and given the following comment block:

```javascript
  /* In addition to any hooks its parent mode `web-mode-prog-mode' might have run, this mode runs the hook `web-mode-hook' */
```

The *expected behaviour* is that typing anything past `might have` should have caused the line to break up as given below:

```javascript
  /* In addition to any hooks its parent mode `web-mode-prog-mode' might have
   * run, this mode runs the hook `web-mode-hook' */
```

**Comment by fxbois** [comment]
@miguel-guedes I do not use auto-fill-mode. You can provide patch
