### ISSUE TITLE
Subsequently re-rendering of a comment block retains `*`

### ISSUE THREAD

**Issue by miguel-guedes** [fxbois/web-mode#736]
The comment prefixes (`*`) aren't removed when the comment block is rendered a second or more times.

Given the following comment block:

``` javascript
  /* In addition to any hooks its parent mode `web-mode-prog-mode' might have
   * run, this mode runs the hook `web-mode-hook' */
```

And editing the first line in the comment block by appending the string `POSSIBLY` after `might have`, and hitting <kbd>M-q</kbd> to cause the block to re-render, results in the following:

``` javascript
  /* In addition to any hooks its parent mode `web-mode-prog-mode' might have
  POSSIBLY * run, this mode runs the hook `web-mode-hook' */
```

Expected result:

``` javascript
  /* In addition to any hooks its parent mode `web-mode-prog-mode' might have
   * POSSIBLY run, this mode runs the hook `web-mode-hook' */
```

Also related to #733.

**Comment by fxbois** [comment]
@miguel-guedes would accept patch for this one also
