### ISSUE TITLE
Strange line jumps

### ISSUE THREAD

**Issue by gregnewman** [fxbois/web-mode#737]
When I am closing tags and return, the new line jumps to the right side of the buffer.
So far I'm not finding anything that would cause it.  I made a screencast so you can see what I'm seeing.

http://g.recordit.co/W3NobWv4Hz.gif

My web-mode specific configs are simple: https://github.com/gregnewman/emacs-config/blob/master/greg.org#html-and-js

**Comment by fxbois** [comment]
@gregnewman it is due to the vertical indicator. It seems to me that an issue is opened for this minor mode.

**Comment by gregnewman** [comment]
Confirmed.  fill-column removed and all is fine.  Thanks @fxbois, that was driving me insane.
