### ISSUE TITLE
Incorrect highlighting with destructured function parameters

### ISSUE THREAD

**Issue by jacobj** [fxbois/web-mode#738]
<img width="488" alt="screenshot 2016-05-22 14 50 44" src="https://cloud.githubusercontent.com/assets/1075421/15455795/d5cfb304-202c-11e6-9063-aaaa7ef3f9f2.png">

As you can see, destructured function parameters aren't properly highlighted (the last one does not match the other two). This style is fairly common when writing stateless components in React.

Here's a gist with a sample: https://gist.github.com/jacobj/e5526cf7b5fba2b9244efa2b0b352339

**Comment by fxbois** [comment]
@jacobj please put your example on gist

**Comment by jacobj** [comment]
@fxbois done!

**Comment by fxbois** [comment]
@jacobj please test the last version on github
