### ISSUE TITLE
Feature request: convert a number of lines with text into a list

### ISSUE THREAD

**Issue by TLINDEN** [fxbois/web-mode#741]
I'd like to convert a marked number of lines into a list like so:

```
line one
line two
```

Then I want to mark the lines and after executing a function it should be:

```
<ul>
  <li>line one</li>
  <li>line two</li>
</ul>
```

Also, it would be great if this is generic, i.e. like `web-mode-element-wrap` so that it asks for a tag or something.

**[update]:**
I'm thinking of something like this:

``` lisp
(defun html-listify (beg end)
  (interactive "r")
  (save-excursion
    (let* ((lines (split-string (buffer-substring beg end) "\n" t)))
      (delete-region beg end)
      (insert "<ul>\n")
      (while lines
        (insert "  <li>")
        (insert (pop lines))
        (insert "</li>\n"))
      (insert "</ul>\n")
      )))
```

**Comment by DoMiNeLa10** [comment]
I updated the function, and now it prompts for the tag that will enclose the list.

**Comment by fxbois** [comment]
@DoMiNeLa10 web-mode now has ```web-mode-lify-region```
