### ISSUE TITLE
Question: do you support SQL code embedded in <sql>..</sql> tags?

### ISSUE THREAD

**Issue by fniessen** [fxbois/web-mode#745]
That'd be interesting for .axvw files (ARCHIBUS views) which are, in fact, XML with both JavaScript code and SQL...

Thanks a lot for that wonderful mode, btw.

**Comment by fxbois** [comment]
@fniessen please provide a link to the spec and post a full example on gist

**Comment by fniessen** [comment]
Minimal working example: https://gist.github.com/fniessen/5538418214880e61e8edb1843472f5fa.

Regarding the spec, I don't have a real document, but this is from an official source:
http://www.archibus.com/ai/abizfiles/v20.2_help/system_management_help/Content/wc_views/Adv_Views_Techniques/using_js_to_extend_views/using_query_parameters.htm

Thanks!

**Comment by fxbois** [comment]
@fniessen what is the file extension of those files ?

**Comment by fniessen** [comment]
.axvw

**Comment by fxbois** [comment]
@fniessen I've added "some" compatibility with the last commit

**Comment by fniessen** [comment]
Wonderful!  That will greatly improve the edition of ARCHIBUS views files... Thanks a lot.
