### ISSUE TITLE
Feature request: Put a background behind code blocks

### ISSUE THREAD

**Issue by fniessen** [fxbois/web-mode#746]
IMHO, it'd be nice to be able to get a background behind the whole JS blocks (from left to right of the screen -- not from first to last character...).

Thanks!

**Comment by fniessen** [comment]
The idea would be to be able to get nicely demarcated code blocks, like on the first screenshot demo'ing my Leuven-theme (https://github.com/fniessen/emacs-leuven-theme)...

**Comment by fxbois** [comment]
@fniessen a font face already exists for this ```web-mode-part-face```
You must enable it with ```(setq web-mode-enable-part-face t)```

**Comment by fniessen** [comment]
I guess you meant `web-mode-script-face`, enabled by `web-mode-enable-part-face`.

Waouw. Thanks a lot, that's fantastic!

It would be nice if you could then add the contents between `sql` tags as well -- that'd make my week! ;-)
