### ISSUE TITLE
Razor: else block not highlighted as code.

### ISSUE THREAD

**Issue by strout** [fxbois/web-mode#749]
The Razor engine should treat "if-else" constructs as code, but currently only the "if" branch is highlighted. In the screenshot below, both "var shouldBeHighlighted = true;" lines should be treated as code, as should the 'else' itself.

I'm using web-mode version 20160529.1148

![web-mode-else-block](https://cloud.githubusercontent.com/assets/110026/15755646/5703761a-28c3-11e6-989e-da1530c384fd.png)

Thanks for web-mode (it's great!) and let me know if I can provide any more details.

**Comment by fxbois** [comment]
@strout please try the last version on github
