### ISSUE TITLE
PHP syntax highlighting breaks when using '?>' in string

### ISSUE THREAD

**Issue by ext** [fxbois/web-mode#750]
### Steps to reproduce

```php
<?php

$x = '?>';

function foo(){
    /* ... */
}
```

### Expected behavior

Syntax highlighting to work for the entire file (like here on github)

### Actual behavior

Syntax highlighting stops for PHP after `?>` despite it being in a string.

![asdf](http://i.imgur.com/eXxPTaQ.png)

I have run into this issue more than once when dealing with regular expressions.

**Comment by fxbois** [comment]
@ext Hi, it would require a complete rewrite of the parser. I won't be able to solve your pb.
You can write ```'?'.'>'```
