### ISSUE TITLE
cursor position and auto-close

### ISSUE THREAD

**Issue by paultopia** [fxbois/web-mode#755]
Hi there, 

I've been trying out web-mode, and I've noticed that auto-closing html tags leaves the cursor one character inside, rather than outside, the closing tag --- requiring at least one extra keystroke to get out before one can start typing anything else.  (Using web-mode via the html layer in the most current flavor of the build provided by spacemacs, if that matters.)

Is this intended behavior?  If not, can that be tweaked?  I'm happy to try to contrib a patch myself, though I'm *very, very, very* new to emacs (and my knowledge of elisp is limited to "this looks enough like clojure that I can sorta figure it out"), so I might need a pointer to things like where in the current code to look...

**Comment by fxbois** [comment]
@paultopia please give a complete step by step example ... I am not sure to understand what you mean (for mean, cursor is outside the closing tag)

**Comment by paultopia** [comment]
This is probably best expressed by screenshots.  So here's a demonstration: 

I'm merrily typing away at some html file, and I open an italics tag, type the italicized content, and then type `</` -- at which point autocomplete kicks in and supplies the `i>` for me, as shown in this screenshot: 

<img width="647" alt="h1" src="https://cloud.githubusercontent.com/assets/11756255/16567221/b5c89392-41e1-11e6-9ebb-a6873d5572c4.png">

However, the cursor position lands lands as follows: `</i~|~>` rather than where I'd expect, namely,  `</i>~|~`.   So if I just keep typing right after autocomplete, my new text appears just inside the close tag, rather than just outside of it.  Example: 

<img width="665" alt="h2" src="https://cloud.githubusercontent.com/assets/11756255/16567234/cf5ce2cc-41e1-11e6-90fc-d9c4b0575102.png">

**Comment by fxbois** [comment]
@paultopia perhaps it is due to some other configuration. For me, the cursor is located just after the ```>```.
Try with a very light .emacs
