### ISSUE TITLE
Use single quotes for auto-quoted HTML attributes

### ISSUE THREAD

**Issue by colepeters** [fxbois/web-mode#758]
In the version 14 release notes, I notice:

> html: single quote auto-quoting (for html attr values)

…however I haven’t been able to discover how to enable this (double quotes are used by default). Could anyone let me know how to enable this? Thanks!

**Comment by fxbois** [comment]
It was an error ... I should have written : single quote auto pairing

**Comment by colepeters** [comment]
@fxbois Thanks for clarifying. Would it be possible to enable single quotes for auto-quoting as an option?

**Comment by fxbois** [comment]
@colepeters I'll try to work on this

**Comment by colepeters** [comment]
@fxbois Thanks a lot! :)

**Comment by fxbois** [comment]
@colepeters you can use : 
```(setq web-mode-auto-quote-style 2)```

**Comment by colepeters** [comment]
@fxbois Works perfectly. Thanks so much!
