### ISSUE TITLE
variables not being respected

### ISSUE THREAD

**Issue by jrios** [fxbois/web-mode#760]
First, thanks for web-mode. It's been working great for me so far. 

I've run into a problem this morning that I didn't have yesterday, so I'm not sure what's going on. 

It doesn't appear to be picking up any of the vars I set. Here is a stripped down version of my ``.emacs`` configuration:

````lisp
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))

(package-initialize)

;; web-mode
(defun web-mode-hook-up ()
  (setq-default indent-tabs-mode nil)
  (setq web-mode-indent-style 2)
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-attr-indent-offset 2)
)
(add-hook 'web-mode-hook  'web-mode-hook-up)
````

When I run web-mode-debug, I get the following:

````
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("14.0.12")
vars: engine(nil) minor(nil) content-type("") file("*Messages*")
system: window(ns) config("x86_64-apple-darwin13.4.0")
colors: fg(nil) bg(nil) 
minor modes: (buffer-read-only)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
````

I usually switch between JavaScript mode and web-mode when writing JSX code, but the indentation vars don't appear to be getting set at all when I run ``web-mode-debug``.

**Comment by fxbois** [comment]
@jrios Sorry but I have no idea

**Comment by jrios** [comment]
I was able to get around this issue using this as a solution: https://github.com/fxbois/web-mode/issues/452

I can figure out another way to switch between modes as necessary.
