### ISSUE TITLE
auto-closing capitalized tags: cursor position

### ISSUE THREAD

**Issue by david135** [fxbois/web-mode#762]
I'm working with a minimal .emacs (just enough to load the web-mode package), with an updated web-mode (14.0.13).

I notice a difference in behavior between the following two cases:
````
<foo>*|*</foo> - after typing the first >, the tag is closed, with the cursor between the tags (at *|*)
<Foo></Foo>*|* - after typing the first >, the tag is closed, with the cursor after both tags (at *|*)
````
I'd like to be able to have both cases act similarly (with the cursor left between the tags).

web-mode-reveal indicates that both tags (lower-case and capitalized) seem to have a lower-case tag-names.

lower-case opening tag:
[point=3 engine="none" minor="none" content-type="html" language-at-pos="html"]
tag-beg(nil) tag-end(nil) tag-name("foo") tag-type(start) tag-attr(nil) tag-attr-beg(nil) tag-attr-end(nil) part-side(nil) part-token(nil) jsx-beg(nil) jsx-end(nil) jsx-depth(nil) block-side(nil) block-token(nil) block-controls(nil) block-beg(nil) block-end(nil) syntax-table(nil) font-lock-face(web-mode-html-tag-face) face(web-mode-html-tag-face) 

lower-case closing tag:
[point=9 engine="none" minor="none" content-type="html" language-at-pos="html"]
tag-beg(nil) tag-end(nil) tag-name("foo") tag-type(end) tag-attr(nil) tag-attr-beg(nil) tag-attr-end(nil) part-side(nil) part-token(nil) jsx-beg(nil) jsx-end(nil) jsx-depth(nil) block-side(nil) block-token(nil) block-controls(nil) block-beg(nil) block-end(nil) syntax-table(nil) font-lock-face(web-mode-html-tag-face) face(web-mode-html-tag-face) 

upper-case opening tag:
[point=15 engine="none" minor="none" content-type="html" language-at-pos="html"]
tag-beg(nil) tag-end(nil) tag-name("foo") tag-type(start) tag-attr(nil) tag-attr-beg(nil) tag-attr-end(nil) part-side(nil) part-token(nil) jsx-beg(nil) jsx-end(nil) jsx-depth(nil) block-side(nil) block-token(nil) block-controls(nil) block-beg(nil) block-end(nil) syntax-table(nil) font-lock-face(web-mode-html-tag-face) face(web-mode-html-tag-face) 

upper-case closing tag:
[point=21 engine="none" minor="none" content-type="html" language-at-pos="html"]
tag-beg(nil) tag-end(nil) tag-name("foo") tag-type(end) tag-attr(nil) tag-attr-beg(nil) tag-attr-end(nil) part-side(nil) part-token(nil) jsx-beg(nil) jsx-end(nil) jsx-depth(nil) block-side(nil) block-token(nil) block-controls(nil) block-beg(nil) block-end(nil) syntax-table(nil) font-lock-face(web-mode-html-tag-face) face(web-mode-html-tag-face) 

Many thanks for your consideration and any ideas!

**Comment by fxbois** [comment]
@david135 the last commit should solve this

**Comment by david135** [comment]
Thanks!
