### ISSUE TITLE
JSP: Incorrect syntax highlighting

### ISSUE THREAD

**Issue by kostafey** [fxbois/web-mode#764]
`web-mode-function-call-face` used for both declaration and call of functions.
It seems `web-mode-function-name-face` is expected for function declaration and `web-mode-function-call-face` for function calls.

**Comment by fxbois** [comment]
@kostafey should be better with last commit

**Comment by kostafey** [comment]
Looks the same with last commit.
Here is example.jsp:
```java
<%!
private void doNothing(HttpServletResponse response) {}
%>
<%
doNothing(response);
%>
```
In both cases `doNothing` has `web-mode-function-call-face` fontification but `web-mode-function-name-face` is expected.

**Comment by fxbois** [comment]
@kostafey I've pushed a new fix

**Comment by kostafey** [comment]
@fxbois Problem solved. Thank you!
