### ISSUE TITLE
Odd underscorejs indenting

### ISSUE THREAD

**Issue by lbstoller** [fxbois/web-mode#765]
Hi. When using emacs 24.5.1 and the most recent web-mode.el from the repository, I get odd indenting in the following fragment:

       <% if (1) { %>
          <td>foo</td>
        <% } else { %>
        <td><%= value.creator %></td>
    <% } %>

I have no customizations. Have you seen this before. I am attaching a screenshot to make sure it is clear. 
Thanks!
![foo](https://cloud.githubusercontent.com/assets/5486469/16693560/8a73cb38-44ea-11e6-9978-1ba77abf0db1.jpg)

**Comment by fxbois** [comment]
@lbstoller can you post the output of web-mode-debug

**Comment by lbstoller** [comment]
Here is the debug output. The problem with the example is that the indentation is messed up.

--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("14.0.13")
vars: engine("underscore") minor("underscore") content-type("html") file("/home/stoller/testbed/testbed/www/aptui/template/images.html")
system: window(x) config("amd64-portbld-freebsd10.2")
colors: fg(nil) bg(nil) 
minor modes: (shell-dirtrack-mode async-bytecomp-package-mode global-git-commit-mode diff-auto-refine-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---

**Comment by lbstoller** [comment]
Ah, try this example, I think my fragment was too small:

<div>
  <div>
    <% _.each(images, function(value, imageid) { %>
      <% if (isadmin) { %>
	<td>foo</td>
      <% } else { %>
      <td>bar</td>
    <% } %>
    <% } %>
  </div>
</div>

**Comment by lbstoller** [comment]
Here is a picture of the fragment above:

![fee](https://cloud.githubusercontent.com/assets/5486469/16708290/40a3ea7a-45a2-11e6-9cd6-afb8295edc89.jpg)

**Comment by fxbois** [comment]
@lbstoller could you try the last version please

**Comment by lbstoller** [comment]
Yep, that did the trick. Thanks very much!!
