### ISSUE TITLE
Wrong CSS syntax highlighting with :not() pseudo-class

### ISSUE THREAD

**Issue by DoMiNeLa10** [fxbois/web-mode#768]
Web-mode fails to highlight CSS selectors with `:not()` pseudo-class, like in this example:
![image](https://cloud.githubusercontent.com/assets/16294095/16901340/b7f98c52-4c40-11e6-9236-d736d2f914bb.png)
Example code with this problem:
https://gist.github.com/DoMiNeLa10/3c7babfaa7a53160f411b37de858abcd

**Comment by fxbois** [comment]
@DoMiNeLa10 I've pushed a fix

**Comment by DoMiNeLa10** [comment]
It works. Thanks a lot.
