### ISSUE TITLE
web-mode-mark-and-expand doesn't work well with expand-region

### ISSUE THREAD

**Issue by wh11e** [fxbois/web-mode#771]
https://github.com/magnars/expand-region.el/blob/master/expand-region-core.el#L98
expand-region's expanding logic is something like this:
1. Execute all expanders with save-excursion
2. Find the expander which makes smallest region (also bigger than current)
3. Place the point and the mark using that expander

(In this context, an expander means an item of er/try-expand-list. web-mode-mark-and-expand is an expander.)

Therefore, calling of web-mode-mark-and-expand and updating of [web-mode-expand-previous-state](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L8043) will happen even if expand-region doesn't select web-mode-mark-and-expand as the expander.

It causes this weird behavior while using er/expand-region:
<img width="314" alt="2016-07-18 5 56 10" src="https://cloud.githubusercontent.com/assets/12756700/16903012/669827a8-4cac-11e6-8cc3-2f8cb12561df.png">
web-mode-expand-previous-state is set to html-tag now but the actual region is created by er/mark-word.

<img width="322" alt="2016-07-18 6 04 49" src="https://cloud.githubusercontent.com/assets/12756700/16903051/94ca6806-4cad-11e6-8ef7-636f5f86d933.png">
web-mode-mark thinks the tag already marked, then calls web-mode-element-content-select.
but it should call web-mode-tag-select.

To avoid this problem, web-mode-mark should not use something like "previous state".
Just use expand-region's logic instead.
like:

``` el
(setq-local er/try-expand-list (append er/try-expand-list
                                       '(web-mode-attribute-select
                                         web-mode-tag-select
                                         web-mode-element-content-select
                                         web-mode-element-select
                                         web-mode-block-select)))
```

This is modification of https://github.com/magnars/expand-region.el/blob/master/web-mode-expansions.el .
If you agree with this, I'll send PR to expand-region repo.

**Comment by wh11e7rue** [comment]
And there's a need to fix web-mode-element-content-select a bit...

**Comment by fxbois** [comment]
@wh11e7rue as I do not use expand-region, so I'll trust you on this
