### ISSUE TITLE
Cannot enter newlines in HTML

### ISSUE THREAD

**Issue by NateEag** [fxbois/web-mode#772]
I had not done web programming in emacs for a while, but I recently started
again, and discovered this problem.

I currently bind [`"RET"` to `"M-j"` in my `prog-mode-hook`](https://github.com/NateEag/.emacs.d/blob/master/init.el#L229),
which I run as part of my `web-mode-hook`.

`"M-j"` is in turn bound by Emacs to `comment-indent-new-line`.

Since web-mode [overrides `comment-indent-new-line` with `web-mode-comment-indent-new-line`](https://github.com/fxbois/web-mode/blob/e170d2720be0758a7ebe001e234231be52c83554/web-mode.el#L2357),
I would expect them to be equivalent.

However, they are not. I cannot enter newlines in HTML, as the following
function shows:

``` elisp
(defun test-web-mode-newline ()
  "Test case showing `web-mode-comment-indent-new-line' behaving differently
from `comment-indent-new-line'."

  (switch-to-buffer "test-web-mode-comment-indent-new-line")

  (web-mode)
  (insert "<html>
    <body></body>
</html>")

  (goto-char 0)
  (search-forward "<body>")

  (web-mode-comment-indent-new-line)

  (switch-to-buffer "test-comment-indent-new-line")

  (web-mode)
  (insert "<html>
    <body></body>
</html>")

  (goto-char 0)
  (search-forward "<body>")

  (comment-indent-new-line)

  (split-window-right)
  (other-window 0)
  (switch-to-buffer "test-web-mode-comment-indent-new-line"))
```

I saved that to my .emacs.d in `web-mode-newline-report.el`, then started Emacs as follows:

```
emacs -Q -l ~/.emacs.d/web-mode-newline-report.el -l ~/.emacs.d/elpa/web-mode-20160717.1201/web-mode.el
```

then did `M-:` and evaled `(test-web-mode-newline)`.

The result is that `comment-indent-new-line` inserts a newline between the
<body> tags, but `web-mode-comment-indent-new-line` does not.

I'm running the [current version of web-mode from MELPA](http://melpa.org/#/web-mode).

`(emacs-version)` reports the following:

```
"GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of
2015-04-10 on builder10-9.porkrind.org"
```

**Comment by fxbois** [comment]
@NateEag perhaps you should override "my overriding"

**Comment by NateEag** [comment]
I could certainly do that, yeah.

I just thought I should file it as a bug, since it's not exactly intuitive behavior.

Is the difference in behavior between `web-mode-comment-indent-newline` and `comment-indent-newline` intentional?

**Comment by fxbois** [comment]
@NateEag as I deal with commenting, I need to set some specific behavior when a user insert a new line in a comment. But in your issue, you talk about newline and not, comment-newline

**Comment by c02y** [comment]
Is this problem fixed?

I open a html file using `emacs -q`, the `M-j` is bound to `indent-new-comment-line`, and `M-j` does exactly what it should do.

But if I load my configuration which using `web-mode` to open a html file, `M-j` is bound to `web-mode-comment-indent-new-line`, and `M-j` is not working at all.

**Comment by NateEag** [comment]
This problem still exists in web-mode, AFAIK - I just tested it and see the exact issue you described.

My `web-mode-version` is "15.0.3".

Per @fxbois's suggestion, I just bound <RET> to `newline-and-indent` in web-mode.

It would be nice to have a working `M-j` in web-mode, though.

**Comment by NateEag** [comment]
For clarity's sake - with web-mode `20180206.120` from MELPA, `M-j` is still broken relative to base emacs behavior.

In `emacs -q`, starting a new empty HTML document and pressing `M-j` adds newlines to the document.

When using web-mode, starting a new empty HTML document and pressing `M-j` does nothing.

**Comment by fxbois** [comment]
@NateEag should be fixed with last commit

**Comment by NateEag** [comment]
Awesome. Thanks so much, @fxbois !
