### ISSUE TITLE
Remove auto indentation

### ISSUE THREAD

**Issue by kostafey** [fxbois/web-mode#773]
How can I remove auto indentation at all? It's buggy, I'll describe the problem in details in the next issue.

**Comment by fxbois** [comment]
(setq indent-line-function nil) perhaps

Please keep your commentaries like "It's buggy" for you

**Comment by kostafey** [comment]
Thank you! Yes, it may be related to JSP pages only. Furthermore, it can be fixed via `whitespace-mode`, so I can't explain the problem correctly yet. But it looks terrible in my case. So, you should apologise me for that :).
