### ISSUE TITLE
Indentation after JavaScript Expressions is wrong

### ISSUE THREAD

**Issue by domtronn** [fxbois/web-mode#775]
Hi there, I'm using version `20160717.1201` of `web-mode`, and I'm getting the following strange behaviour with indentation, given the following example code:

```jsx
var React = require('react')

return React.render(
  <div className="fooBar">
    {
      conditional &&
      <myComponent className="myComponent" />
    }
      <label>{labelText}</label>
      <div>
        <span>Hello</span>
      </div>
  </div>
)
```

I would expect the indentation of the `<label>` and `<div>` & `<span>` to be two spaces back, like this:

```jsx
var React = require('react')

return React.render(
  <div className="fooBar">
    {
      conditional &&
      <myComponent className="myComponent" />
    }
    <label>{labelText}</label>
    <div>
      <span>Hello</span>
    </div>
  </div>
)
```

You can see that the inner `<span>Hello</span>` is indented correctly relative to the container `<div>`, but it seems like these are aligning with the _previous_ jsx tag rather than previous jsx tag, _not including_ ones in JavaScript expressions

**Comment by fxbois** [comment]
@domtronn I've pushed a fix
