### ISSUE TITLE
Error when trying to fold in React

### ISSUE THREAD

**Issue by grks** [fxbois/web-mode#778]
Hi,

I'm switching to web-mode for editing react jsx files, but got an issue with folding. 
When I try to fold I get the following error:

    block-controls-get ** invalid value (3567) **

I'm running vanilla prelude. I saw some posts on the net e.g. https://emacs.stackexchange.com/questions/18615/enable-jsx-folding-in-web-mode so just wondering if this is supposed to work?

Thanks for a fantastic mode!

**Comment by fxbois** [comment]
@grks could you try with the last version available on github please

**Comment by grks** [comment]
I tried, but doesn't seem to work. Maybe I'm doing something wrong. This is what I try:

````jsx
function f() {
    return "";
}

const Component = React.createClass({
    f() {
        return true;
    }
});
````

I then place the cursor between return and true and run the command "C-c C-f runs the command web-mode-fold-or-unfold"

Then I switch to js2-mode and try the same.

So what I'm expecting is that web-mode should work like in js2-mode, it should fold everything in the buffer. 

What happens is that I get the following error message when in web-mode

    Checker definition probably flawed.
    block-controls-get ** invalid value (97) **

Maybe I'm doing something wrong here or I expect something different than what should happen?

**Comment by fxbois** [comment]
@grks folding is only (at the moment) for html elements and control blocks.
You should use a specific minor mode for your need

**Comment by grks** [comment]
Ok, thanks. Sorry for not providing a testcase in the first place. Guess we can close this.

**Comment by fxbois** [comment]
@grks I'll try to improve folding in the next two months.

**Comment by grks** [comment]
Great :) Let me know if you need some testing!
