### ISSUE TITLE
JSX comment style

### ISSUE THREAD

**Issue by elton2048** [fxbois/web-mode#779]
It is great to have comment and uncomment using web-mode in jsx file. However it is even better if the style of the comment could be the same as the ordinary one.

![jsx_comment_issue1](https://cloud.githubusercontent.com/assets/11803493/17778470/b2f854b2-6596-11e6-81e8-dcc0bbf339bd.png)

The line {/* Here is the some kind of comment in React */} shows the same colour as the HTML element now. The green one shows the ordinary comment part existing now.

**Comment by fxbois** [comment]
@elton2048 please put your example on gist

**Comment by elton2048** [comment]
https://gist.github.com/elton2048/5a373b79399b23f723754a0ad8b03ade

**Comment by fxbois** [comment]
@elton2048 I've pushed a fix

**Comment by elton2048** [comment]
The fix works well. Thanks for the effort.
