### ISSUE TITLE
Wrong indention on jsx in es6 class export

### ISSUE THREAD

**Issue by utvk** [fxbois/web-mode#783]
Hi,

I'm using 20160821.1054 and got some trouble with indention while editing jsx in an es6 class export.

The following code:
````jsx
export default class Header extends Component {
  render() {
    return (
      <div {...attributes} 
        onClick={this.onClicked}
        onKeyDown={this.onKeyDowned}>
          {this.getChildren()}
      </div>);
  }
}
````

Ends up looking like this:
````jsx
export default class Header extends Component {
  render() {
    return (
      <div {...attributes}
      onClick={this.onClicked}
      onKeyDown={this.onKeyDowned}>
      {this.getChildren()}
      </div>);
  }
}
````
It seems like the indention is not done and everything is kept on the same level. In general I have a few issues like this while editing different forms of jsx and I can provide some more examples.

**Comment by fxbois** [comment]
@utvk I am interested by your other examples

**Comment by fxbois** [comment]
@utvk I've pushed a fix
