### ISSUE TITLE
Wrong JSX Indentation when inserting open curly brace

### ISSUE THREAD

**Issue by tmtxt** [fxbois/web-mode#787]
Web mode jsx indentation breaks after inserting an open curly brace on attribute value

For example, when insert `{` after `val=`, the indentation breaks

```
<div val= ></div>
```

![jsx](https://cloud.githubusercontent.com/assets/2741919/18251753/2e2e1a8c-73b5-11e6-8100-40e1ac23d15f.gif)

This happens with both command `autopair-insert-opening` and `paredit-open-curly` but it's okay if I press `C-q {`

**Comment by fxbois** [comment]
@tmtxt I've added auto closing to jsx attribute

**Comment by tmtxt** [comment]
Thanks, let me try

**Comment by tmtxt** [comment]
When will it be on melpa? I installed it using emacs package manager but the newest version I see is still 20160921.1327
