### ISSUE TITLE
Blade syntax highlighting off with apostrophes

### ISSUE THREAD

**Issue by joshmedeski** [fxbois/web-mode#788]
When an apostrophe is in my blade template, it breaks the syntax highlighting. Can you help?

<img width="1398" alt="screen shot 2016-09-06 at 5 44 22 pm" src="https://cloud.githubusercontent.com/assets/2036594/18293631/a688ff48-7459-11e6-9a8a-38246a1b8fdf.png">

**Comment by fxbois** [comment]
@joshmedeski are you sure the major mode associated with this buffer is web-mode ?
Can you send the output of ```web-mode-debug```

**Comment by joshmedeski** [comment]
You're right @fxbois. It's not using `web-mode` (by default). I'll reach out to the spacemacs community and see whats going on.
