### ISSUE TITLE
Support embedded markdown in reveal.js

### ISSUE THREAD

**Issue by xuhdev** [fxbois/web-mode#789]
Reveal.js presentations usually contain some markdown parts within `<section data-markdown></section>`. It would be nice to see them highlighted.

**Comment by fxbois** [comment]
@xuhdev please post on github a example (the bigger the better)

**Comment by xuhdev** [comment]
@fxbois A demo is available in [their official demo](https://github.com/hakimel/reveal.js/blob/master/demo.html#L107)

**Comment by fxbois** [comment]
@xuhdev some initial work have landed with the last commit

**Comment by xuhdev** [comment]
Thanks, please let me know if you need any help!
