### ISSUE TITLE
No HTML syntax highlighting

### ISSUE THREAD

**Issue by 97gupe30** [fxbois/web-mode#790]
So I've read this issue:
https://github.com/fxbois/web-mode/issues/153
But still havn't fixed this. Is it impossible to get html syntax highlighting with web-mode?

This is my .emacs file:
`(add-to-list 'load-path "~/.emacs.d/")
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
(setq web-mode-engines-alist
      '(("jinja"    . "\\.html\\'"))
)

`

**Comment by fxbois** [comment]
@97gupe30 you should ask some help on https://emacs.stackexchange.com/
