### ISSUE TITLE
web-mode-comment-or-uncomment removes necessary whitespace

### ISSUE THREAD

**Issue by dustinpaluch** [fxbois/web-mode#791]
Type 

`<?php echo "test"; ?>` 

into a new PHP file. Do M-; twice with point over any one of these characters. I expect:

`<?php echo "test"; ?>` 

but I get this instead:

`<?phpecho "test";?>`

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("14.0.23")
vars: engine("php") minor("php") content-type("html") file("/Users/imacintel/Desktop/test.php")
system: window(nil) config("x86_64-apple-darwin14.5.0")
colors: fg(nil) bg(nil)
minor modes: nil
vars:
web-mode-enable-current-column-highlight=nil
web-mode-enable-current-element-highlight=nil
indent-tabs-mode=t
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
@dustinpaluch I've pushed a fix

**Comment by dustinpaluch** [comment]
It mostly works, unless point is over `<?php`.  When my point is on one of those characters, and I do M-; twice, I get `<?php /*/*echo "test";*/*/ ?>`.

**Comment by fxbois** [comment]
@dustinpaluch I've pushed a new fix

**Comment by dustinpaluch** [comment]
Working for me in 38b9f10. Thanks! Feel free to close.
