### ISSUE TITLE
M-q does not work (but M-x fill-paragraph does)

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [fxbois/web-mode#792]
When I'm in `web-mode`, `M-q` doesn't seem to work as a binding for `fill-paragrah`. If I call `M-x fill-paragraph` directly, it works fine. `M-q` works for me outside of `web-mode`. Any idea what might be up?

**Comment by fxbois** [comment]
@uhoh-itsmaciek in fact, M-q is bound to web-mode-fill-paragraph which, at the comment, only deals with comments. I need to do some work for the other cases

**Comment by uhoh-itsmaciek** [comment]
Huh, pretty sure this was in a comment. I can't find where I initially encountered the issue now, and testing a new multiline JS comment does work. Testing a single-line JS comment does wrap but doesn't prefix the wrapped lines with comment markers and doesn't unwrap.

In any case, thanks for `web-mode`--it's awesome!
