### ISSUE TITLE
web-mode-toggle-comments mark buffer as modified

### ISSUE THREAD

**Issue by madhavan020985** [fxbois/web-mode#793]
When i run `web-mode-toggle-comments` to hide all comments in the region, it marks the buffer as a modified buffer. Since the comments are hidden only for viewing purpose, and there is no persistent change in the file content, the buffer's modified state must not be changed.

I had a quick look at the source code as well. And the buffer is made as modified due to this line,
`            (put-text-property pos end 'invisible visibility)`.

I am just curious, why do we need to set the invisible text property, when hide/show can be achieved using the already created overlay as,

`
            (when visibility
              (setq overlay (make-overlay pos end))
              (overlay-put overlay 'display "..."))
`

This is more cleaner as this doesn't misguide people about buffer edit status..

**Comment by fxbois** [comment]
@madhavan020985 I've pushed a fix
