### ISSUE TITLE
hideshow is inoperant

### ISSUE THREAD

**Issue by fniessen** [fxbois/web-mode#794]
First of all, many thanks for this wonderful package, really!

Now, the issue I wanna report: Hideshow does not have any effect when called within Web buffers (my test case: XML file).

Setting the mode to nxml does allow Hideshow to work; so, I have the impression the problem is somehow bound to Web mode.

Thanks!

**Comment by madhavan020985** [comment]
I too had the same problem.. Web-mode comes with web-mode-fold-or-unfold (binded to `C-c C-f`). Keep your `point` on the start tag name & do `C-c C-f`

**Comment by fxbois** [comment]
@fniessen is ```web-mode-fold-or-unfold``` was what you expected ?
