### ISSUE TITLE
Hide or show inside array brackets doesn't work

### ISSUE THREAD

**Issue by madhavan020985** [fxbois/web-mode#795]
I have an array of object as 
````
var a = [
  {
    "a" : 2,
   "b" : 3
  },
  {
   "c" : 3,
  "d" : 4
  }
]
````

My cursor is next to square bracket, [] and i try to hide the array using hs-hide-block, `C-c @ C-h`. It doesn't work. 
I fixed it by enhancing `hs-special-modes-alist` as,
````
(add-to-list 'hs-special-modes-alist '(web-mode "\\[\\|{" "}\\|]" "/[*/]" web-mode-forward-sexp nil))
````

**Comment by fxbois** [comment]
@madhavan020985 ok thanks
