### ISSUE TITLE
Indent on && in js

### ISSUE THREAD

**Issue by grks** [fxbois/web-mode#797]
Hi!

Just a small issue regarding && operator (and possible &, | and ||) with javascript.

In this example

````js
funtion foo() {
  1 === 0 &&
  foo();
}
````

Shouldn't web-mode indent like this?

````js
funtion foo() {
  1 === 0 &&
    foo();
}
````

**Comment by fxbois** [comment]
@grks could you provide a similar example with the condition in a ```if ()```

**Comment by grks** [comment]
YEa, here is an example. if seems to work fine.

````html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Document</title>
    <script>
     function foo1() {
       if (1 === 0) {
         foo();
       }
     }
     function foo2() {
       1 === 0 &&
       foo();
     }
    </script>
  </head>
  <body>
  </body>
</html>
````

**Comment by fxbois** [comment]
@grks aligning ```1 === 0``` and  ```foo()``` is desired behaviour according to me.

**Comment by grks** [comment]
I think it looks strange as it's really a new block and should be indented as a block. I also tested e.g. js2-mode and it seems to do it what I consider the correct way.

Also it seems a bit inconsistent. E.g. web-mode will indent the bellow like this.

Not sure why it indents with 4 spaces though, js2-mode and my expectations would be to indent with 2 spaces as this is how my mode is configured.

````js
function foo4() {
  return 1 === 0
      && foo();
}
````

**Comment by grks** [comment]
I guess it makes more sense to align them in the later example with an return. But when used as a block it's not what I expected. However, just close this bug if it works like you expect.

Here is an example I don't really understand. It seems inconsistent? The first one is onot indented but the second one is?

````js
     function foo5() {
       (1 === 0)
       && {1 === 1
        && foo()}
     }
````

**Comment by fxbois** [comment]
@grks Sorry but I won't be able to solve this one
