### ISSUE TITLE
support to close single tags like <input />

### ISSUE THREAD

**Issue by stardiviner** [fxbois/web-mode#798]
As the title.
Let function `web-mode-element-close` support to close `<input type="checkbox"` with `<input type="checkbox" />` and other similar tags.

**Comment by fxbois** [comment]
This function is not designed to do this. It is designed to add a close tag

**Comment by stardiviner** [comment]
Does `web-mode` has built-in function/keybinding for my purpose?

**Comment by fxbois** [comment]
no, I advice you to create a simple shortcut to insert ```/>```
