### ISSUE TITLE
JSX inside ternary if/else is indented too much

### ISSUE THREAD

**Issue by denisw** [fxbois/web-mode#801]
Expected indentation (note the two-space indentation of `<ContentIfTrue />` and `<ContentIfFalse />`):

``` javascript
import React from 'react'

class Example extends Component {
  render() {
    return (
      <div>
        {this.props.condition ? (
          <ContentIfTrue />
         ) : (
          <ContentIfFalse />
         )}
      </div>
    )
  }
}
```

Actual indentation (three spaces of indentation instead of two):

``` javascript
import React from 'react'

class Example extends Component {
  render() {
    return (
      <div>
        {this.props.condition ? (
           <ContentIfTrue />
         ) : (
           <ContentIfFalse />
         )}
      </div>
    )
  }
}
```

It seems as if the indentation would happen relative to the first character after the opening brace, rather than relative to the brace itself.

**Comment by fxbois** [comment]
@denisw Indeed the indentation is done according to the character after the opening brace.

Could you point to an example on the official websites that would help to decide what is better.

**Comment by denisw** [comment]
[This](https://facebook.github.io/react/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored) section of the official React docs has the following example:

```jsx
<div>
  {props.messages.length &&
    <MessageList messages={props.messages} />
  }
</div>
```

**Comment by fxbois** [comment]
@denisw in fact, if ```)``` must be aligned with the ```t``` of ```this``` the extra space is more logical according to me
