### ISSUE TITLE
Cannot set comment style to // for javascript 

### ISSUE THREAD

**Issue by dagda1** [fxbois/web-mode#802]
My init.el looks like this:
```
(require 'web-mode)

(defun my-web-mode-hook ()
  "web-mode settings"
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (add-to-list 'web-mode-comment-formats '("javascript" . "// ")))

(add-hook 'web-mode-hook  'my-web-mode-hook)

(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.js?$" . web-mode))
```

I've also adding the `web-mode-comment-formats` on its own expression:

```
(require 'web-mode)

(add-to-list 'web-mode-comment-formats '("javascript" . "// "))
```

But my comment style is still the block

```
/* import React from 'react';
 * import { mount, shallow } from 'enzyme';
 * import {expect} from 'chai';
 * */
```

**Comment by fxbois** [comment]
@dagda1 could you try to put ```(add-to-list 'web-mode-comment-formats '("javascript" . "// "))``` just before ```(defun my-web-mode-hook ()```

**Comment by AlexYegupov** [comment]
>try to put (add-to-list 'web-mode-comment-formats '("javascript" . "// ")) just before (defun my-web-mode-hook ()

I've tried. This doesn't work neither  before my-web-mode-hook nor inside :( 

How can I make //-style commenting?
