### ISSUE TITLE
Support for Haml and Slim Templates

### ISSUE THREAD

**Issue by breyno127** [fxbois/web-mode#804]
Just wondering if this is on the roadmap for this project at all.

**Comment by fxbois** [comment]
@breyno127 for Slim Templates are you only interested by the Haml support ?

**Comment by breyno127** [comment]
Slim mostly, But I _think_ there are likely many people who use Haml as well. I currently use [`slim-mode`](https://github.com/slim-template/emacs-slim) but the support for embedded Javascript the template isn't the best.

**Comment by fxbois** [comment]
@breyno127 web-mode is before everything else an html mode.
Compatibility with haml is not on the roadmap.

**Comment by breyno127** [comment]
Thanks @fxbois I appreciate the quick response. Since this isn't on the roadmap at all I will go ahead and close this in an effort to keep your issues list clean.

**Comment by fxbois** [comment]
I keep it open because I'll add slim support (but in the html way)

**Comment by breyno127** [comment]
What do you mean by "in the html way" out of curiosity.

**Comment by fxbois** [comment]
you're right ... I thought I add read something.
Let's close this issue
