### ISSUE TITLE
support flagging custom blocks as SQL, CSS, JS

### ISSUE THREAD

**Issue by slippycheeze** [fxbois/web-mode#805]
We have some custom Django tags that embed SQL or JS code inside them, and do some stuff around them – for example, background loading or attach reloading when controls are changed by the user in JavaScript.

It would be great to be able to flag these regions for `web-mode` to highlight those based on something easily configurable, such as "this tag" or so.  In this case the things would be:

```
{% graph %} ... {% endgraph %}
{% manifest %} ... {% endmanifest %}
```

...but there are multiple tags – one per backend store – for the various query languages.  Which are all SQL-like, so highlighting as SQL would be ideal. :)

My rough thought is something like:

```
(setq web-mode-block-type-rules
  '(("{%\\s-*graph.*?%}" "{%\\s-*endgraph.*?%}" sql)))
```

...where that would be the start and end regular expressions, but something like a "tag" based match where I just set `'("graph" . sql)` or something would also be fine.

I only care about highlighting the content between the full tags as SQL, though they also have attributes.  (eg: django style attributes and arguments to the tag, such as `{% manifest backend="production" %}`)

**Comment by fxbois** [comment]
@daniel-pittman could you post an extended example on git please

**Comment by konnorbeard** [comment]
This would be awesome to use with shopify site customization, I was just looking around for a way to do this with web-mode. They use the following: 
```
{% javascript %}
{% endjavascript %}

{% stylesheet %}
{% endstylesheet %}
```

etc.

**Comment by fxbois** [comment]
@konnorbeard I've pushed a fix

**Comment by konnorbeard** [comment]
@fxbois that's awesome, thanks so much. I just submitted #846 which adds support for the {% schema %} tags that are also present in shopify's liquid templates and contain simple json, in case that's something you guys found useful to add.
