### ISSUE TITLE
Web-mode uses space indentation in JS in some cases

### ISSUE THREAD

**Issue by deflexor** [fxbois/web-mode#806]
Here is how it works with this options enabled:
```
(setq indent-tabs-mode t)
(setq web-mode-code-indent-offset 4)
(setq web-mode-script-padding 0)
```

So these options (I hope) should give me tab-only indentation.
And here is exaple of .js file and indentation that web-mode uses: (> - tab, • - space)

```
module('msg_service')
>     .directive(function() {})
```

Looks fine, just single tab, but when prevous line conatins dot (angular.module), then web-mode decides to indent with mix of tabs and spaces:

```
angular.module('msg_service')
>     •••.directive(function() {})
```

**Comment by fxbois** [comment]
@deflexor have you used ```(web-mode-use-tabs)``` as it is explained in web-mode.org ?

**Comment by deflexor** [comment]
No, I haven't. Now I tried it and looks like it solved my problem, thank you.
