### ISSUE TITLE
Support Relay.QL in javascript

### ISSUE THREAD

**Issue by tomconroy** [fxbois/web-mode#807]
Thanks for web-mode! It is great. It would be really nice to have some simple support for indenting inside `Relay.QL` blocks, from https://facebook.github.io/relay/docs/api-reference-relay-ql.html

``` js
Relay.createContainer(Story, {
  initialVariables: {
    numCommentsToShow: 10,
    showComments: false,
  },
  fragments: {
    story: (variables) => Relay.QL`
      fragment on Story {
        comments(first: $numCommentsToShow) @include(if: $showComments) {
          edges {
            node {
              author { name },
              id,
              text,
            },
          },
        },
      }
    `,
  }
});
```

**Comment by kevinkehl** [comment]
I have also run into this. I'd be happy to take a stab at it if no one's in the middle of it, but would definitely need a pointer or two in the right direction.

**Comment by fxbois** [comment]
@tomconroy @kevinkehl the last commit includes this feature

**Comment by kevinkehl** [comment]
@fxbois awesome, thanks! It looks like with this commit, the above example is indented like so:

```
Relay.createContainer(Story, {
  initialVariables: {
    numCommentsToShow: 10,
    showComments: false,
  },
  fragments: {
    story: (variables) => Relay.QL`
      fragment on Story {
        comments(first: $numCommentsToShow) @include(if: $showComments) {
          edges {
            node {
              author { name },
              id,
              text,
              },
            },
          },
        }
      `,
  }
});
```

With the closing bracket below `text` indented at the same level, when it should be outdented one level (and so forth down the closing brackets).

**Comment by fxbois** [comment]
@kevinkehl I've pushed a fix

**Comment by kevinkehl** [comment]
Nice, LGTM. Thanks again!
