### ISSUE TITLE
JSX without parenthesis breaks next line

### ISSUE THREAD

**Issue by mostafah** [fxbois/web-mode#810]
This is what happens:

``` javascript
class C {
  render() {
    if (a)
      return <div>A</div>
return <div>B</div>
  }
}
```

This is what I expect:

``` javascript
class C {
  render() {
    if (a)
      return <div>A</div>
    return <div>B</div>
  }
}
```

In another example, this happens:

``` javascript
f() {
  const a = <div />
const b = <div />
}
```

while this is expected:

``` javascript
f() {
  const a = <div />
  const b = <div />
}
```

Writing `return <div>A</div>` as `return (<div>A</div>)` or `const a = <div />` as `const a = (<div />)` fixes the indentation, even though JSX does not require the parenthesis here.

This is `web-mode-debug`:

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(25.1) web-mode("14.0.27")
vars: engine("none") minor("none") content-type("jsx") file("/Users/mostafa/go/src/gitlab.com/mostafah/kolah/js/components/ColorPicker.js")
system: window(nil) config("x86_64-apple-darwin16.0.0")
colors: fg(nil) bg(nil)
minor modes: (global-eldoc-mode global-auto-complete-mode show-paren-mode flycheck-mode global-flycheck-mode shell-dirtrack-mode diff-auto-refine-mode)
vars:
web-mode-enable-current-column-highlight=nil
web-mode-enable-current-element-highlight=nil
indent-tabs-mode=nil
--- WEB-MODE DEBUG END ---
You can run the command ‘web-mode-debug’ with M-x w-deb RET
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
@mostafah one ```;``` would help

**Comment by mostafah** [comment]
You’re right. Using `;` fixes it too, but, again, that is not syntactically necessary. Even [Standard](http://standardjs.com) has no semicolons by default.

**Comment by aaronjensen** [comment]
Seemingly related:

```jsx
const foo =
  <div>
test
</div>
```

That doesn't indent/font-lock unless it has parens or a `;`. This means that when using `prettier --no-semi` the code is formatted to a way that web-mode doesn't understand.

**Comment by fxbois** [comment]
@aaronjensen this issue is not an easy one. I need to find time to work on it

**Comment by aaronjensen** [comment]
understood, thanks for responding. If you leave some notes here on where to get started maybe I or some other may come along and put some effort into it.

**Comment by aaronjensen** [comment]
@fxbois thanks, these all appear to be fixed other than:

```js
const Foo = () =>
  <div>
test
</div>
```

Should I open a separate issue for that?

**Comment by fxbois** [comment]
@mostafah yes please
