### ISSUE TITLE
web-mode-comment-or-uncomment exhibits different behavior when commenting and uncommenting

### ISSUE THREAD

**Issue by nega0** [fxbois/web-mode#811]
With emacs 24.5.1, web-mode-20161023.1219 and a minimal config:

``` emacs
(require 'package)
(add-to-list 'package-archives
                  '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(unless (package-installed-p 'use-package)
     (package-refresh-contents)
    (package-install 'use-package))
(eval-when-compile
    (require 'use-package))
(require 'bind-key)
(setq use-package-always-ensure t)
(show-paren-mode t)
(use-package web-mode
  :config
  (add-to-list 'auto-mode-alist '("\\.js?$" . web-mode))
  (add-to-list 'web-mode-comment-formats '("javascript" . "//")))
```

If I have a block of Javascript:

``` js
var a=1;
var b=2;
var c=3;
var d=4;
```

and I want to comment the second line, I move the point to the second line and execute `web-mode-comment-or-uncomment` (`M-;` by default). As expected this results in:

``` js
var a=1;
// var b=2;
var c=3;
var d=4;
```

Doing the inverse with:

``` js
// var a=1;
// var b=2;
// var c=3;
// var d=4;
```

If I move to the second line and execute `web-mode-comment-or-uncomment` the second line and the remaining lines are uncommented.

``` js
// var a=1;
var b=2;
var c=3;
var d=4;
```

If the "block" is "termininated", say with a blank line;

``` js
// var a=1;
// var b=2;
// var c=3;
// var d=4;

// var w=1;
// var x=2;
// var y=3;
// var z=4;
```

The uncommenting ends at the "block terminator":

``` js
// var a=1;
var b=2;
var c=3;
var d=4;

// var w=1;
// var x=2;
// var y=3;
// var z=4;
```

Similar behavior occurs when a region is selected. That is, the remainder of the "block" is uncommented, not just the selected region.

**Expected behavior**: when uncommenting, behavior should be the inverse of commenting.

**Comment by fxbois** [comment]
@nega0 sorry but I am not sure to understand what you want ... could you explain an other way please

**Comment by laampui** [comment]
similar issue https://github.com/redguardtoo/evil-nerd-commenter/issues/130
