### ISSUE TITLE
Issue with commenting Go Template snippets

### ISSUE THREAD

**Issue by kaushalmodi** [fxbois/web-mode#812]
I am using `web-mode` to edit Go Template HTML files.

I was able to set `web-mode-engines-alist` to correct set the `web-mode-engine` in the Go Template files to `"go"`.

With that, the indentation of the Go Template snippets is working great!

```html
        {{ range $.Site.Data.bookmarks.links.h1 }}
            <h1>{{ .title }}</h1>
            {{ range .h2 }}
                <h2>{{ .title }}</h2>
                <ul>
                    {{ if .base }}
                        {{ $base := .base }}
                        {{ range .l1}}
                            {{ if .slug }}
                                <li>{{ .desc }} &mdash; <a href="{{ $base }}/{{ .slug }}/{{ .slug }}.html">html</a> | <a href="{{ $base }}/{{ .slug }}/{{ .slug }}.pdf">pdf</a> | <a href="{{ $base }}/{{ .slug }}/{{ .slug }}.org">org</a></li>
                            {{ else }}
                                <li>{{ .desc }}{{ with .customhtml }} &mdash; {{ . | safeHTML }}{{ end }}</li>
                            {{ end }}           <!-- if .slug -->
                        {{ end }}           <!-- range .l1 -->
```

But, `comment-dwim` is not commenting the templates as shown on `web-mode.org`:

![Comment in gtl engine][1]

For example, if I select `{{ range .h2 }}` (or have the point inside that snippet (from above), and if I do `M-x comment-dwim`, it becomes `{{/ range .h2 }}` instead of `{{/* range .h2 */}}`.

Is this a bug, or do I need to configure some var to get commenting to work as shown in the above screenshot?

Thanks!

[1]: http://web-mode.org/images/emacs-gohtml.png

**Comment by kaushalmodi** [comment]
I don't know `go` language or the intention of `web-mode-comment-go-block`. So I am not sure if this is correct:

```el
(defun web-mode-comment-go-block (pos)
  (let (beg end)
    (setq beg (web-mode-block-beginning-position pos)
          end (web-mode-block-end-position pos))
    (web-mode-insert-text-at-pos "/" (+ beg 2))))
```

It does not match with
![image](https://cloud.githubusercontent.com/assets/3578197/19895926/02bb5db0-a029-11e6-8df3-23deedeb05b9.png)

**Comment by kaushalmodi** [comment]
These versions of the comment/uncomment defuns for `go` blocks works for me:

```el
(defun web-mode-comment-go-block (pos)
  (let (beg end)
    (setq beg (web-mode-block-beginning-position pos)
          end (web-mode-block-end-position pos))
    (web-mode-insert-text-at-pos "*/" (1- end))
    (web-mode-insert-text-at-pos "/*" (+ beg (if (web-mode-looking-at "{{" beg) 2 0)))))

(defun web-mode-uncomment-go-block (pos)
  (let (beg end)
    (setq beg (web-mode-block-beginning-position pos)
          end (web-mode-block-end-position pos))
    (web-mode-remove-text-at-pos 2 (+ beg 2))
    (web-mode-remove-text-at-pos 2 (- end 5))))
```

**Comment by kaushalmodi** [comment]
So this definitely seems like a bug because the golang.org template spec page shows the only comment syntax as `{{/* a comment */}}` [[Ref][1]].

[1]: https://golang.org/pkg/text/template/#hdr-Actions

**Comment by fxbois** [comment]
@kaushalmodi corrected with last commit
thx for the code snippet

**Comment by kaushalmodi** [comment]
Thank you. I confirm the fix.
