### ISSUE TITLE
On Marko Lang Support

### ISSUE THREAD

**Issue by CestDiego** [fxbois/web-mode#813]
Hi, I've been writing before re: a templating language called [Marko](http://markojs.com/docs/) And I've reached the point to which using web-mode is good but there is an extra tad of functionality that I think would be very awesome to get, but I feel it is a little too far of a stretch to extend web mode. I'm talking about being able to autocomplete taglibs, like in the atom package for it. https://atom.io/packages/language-marko 

I would like to know if you have any guidance on whether I should work on extending web-mode to support this and how to go in doing so.

There is also what they call `concise-syntax` which is basically Pug(ex-Jade) 's syntax, And marko can have both at the same time. But I find it hard to conceive a mode that supports such, but if you have any ideas about it I would do the work :)

**Comment by fxbois** [comment]
@CestDiego with what feature would you like to start ?
I would suggest to create a dedicated minor mode

**Comment by fxbois** [comment]
@CestDiego reopen if I can provide help
