### ISSUE TITLE
Toggle folding on children doesn't work expected with HTML

### ISSUE THREAD

**Issue by jasondf** [fxbois/web-mode#814]
When move cursor to an element and call "toggle folding on children" by press "C-c C-e f", all the following elements are folded, from the cursor to the end of file, not just fold the children elements as expected.
Currently I'm using web-mode 14.0.22, have to upgrade to make this right?

**Comment by fxbois** [comment]
@jasondf could you take two screenshots please: before and after 
(I do not manage to trigger the issue)

**Comment by jasondf** [comment]
The first picture is the screen before folding:

![image](https://cloud.githubusercontent.com/assets/9963736/19995834/e25a00ca-a295-11e6-8915-41dd5ddc42df.png)

Then move cursor to the first table tag, and press "C-c C-e f" to call command "toggle folding on children". The following picture is result.

![image](https://cloud.githubusercontent.com/assets/9963736/19995850/02d062b8-a296-11e6-86b6-de9f7c014164.png)

I expect it will just fold children elements in first table tag, not all the following content.

**Comment by fxbois** [comment]
@jasondf could you post this example on gist please

**Comment by fxbois** [comment]
@jasondf should be better with last commit

**Comment by jasondf** [comment]
@fxbois Sorry for late reply, here is my test code: https://gist.github.com/jasondf/9c5a4f226f86e50e879424c58aa0d710
and I will try the last commit.
Thanks a lot.

**Comment by jasondf** [comment]
@fxbois Thanks you, now it works perfectly, I will close this issue.
