### ISSUE TITLE
CSS Colorization when setting color variables

### ISSUE THREAD

**Issue by picandocodigo** [fxbois/web-mode#815]
I don't know if this hasn't been implemented or it doesn't work on my machine. When opening Scss files, I get CSS Colorization only when setting a property's color, but not when using variables. This is what I mean:

![Screenshot](http://i.imgur.com/nVuyTTc.png)

The `$red` variable should colorize it's `#F00` value too.

I'm using `web-mode-20161008.22` and `GNU Emacs 24.5.1`. It would be great to see the colors at least where they're defined. I generally have all of them at the top of a scss file, or in an independent one. I guess it has to do with [this regexp](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L5854)?

Thanks!

**Comment by fxbois** [comment]
@picandocodigo could you test the last commit?

**Comment by picandocodigo** [comment]
Yes, It's working with the latest commit!

Thank you very much!
