### ISSUE TITLE
SCSS color highlight doesn't work outside of a selector

### ISSUE THREAD

**Issue by hershal** [fxbois/web-mode#816]
If I create a new SCSS file and write this 
```scss
$some-color: #ff0000;
```

then `#ff0000` is not highlighted in red. However, if I write

```scss
body {
  color: #ff0000;
}
```
then `#ff0000` is properly highlighted in red.

I found out that even if you remove `body`, then the highlighting occurs within the block. However a block without a selector is not valid SCSS. I would like the highlighting to occur in a plain variable declaration, so that I may see all the colors I have defined in a `_variables.scss` file, for example. I don't know enough about web-mode to fix this all by myself, so I would appreciate any help.

Thank you for all your hard work on an amazing major mode. I really appreciate the flexibility it gives me as a fledgling web developer and emacs enthusiast. Amazing job.

**Comment by fxbois** [comment]
Have you tried the last version on github ?

**Comment by hershal** [comment]
It works! I'm perplexed to why I didn't find #815 when I initially searched for the issue. 

Regardless, an amazing major-mode just got even better. Thank you!
