### ISSUE TITLE
web-mode-element-children-fold-or-unfold doesn't fold past comments

### ISSUE THREAD

**Issue by jsamsa** [fxbois/web-mode#817]
&lt;div&gt;
  &lt;div&gt;folds&lt;/div&gt;
  &lt;div&gt;folds&lt;/div&gt;
  &lt;!-- folding will stop here --&gt;
  &lt;div&gt;won't fold&lt;/div&gt;
&lt;/div&gt;

;; Version: 14.0.29
;; Package-Version: 20161106.132

**Comment by fxbois** [comment]
@jsamsa the last commit should solve this
