### ISSUE TITLE
Font-lock-flush getting run even when not found

### ISSUE THREAD

**Issue by jondubin** [fxbois/web-mode#820]
I started getting this error when web-mode is turned on: `File mode specification error: (void-function font-lock-flush)`. The culprit seems to be this call of `font-lock-flush` https://github.com/fxbois/web-mode/blob/master/web-mode.el#L5304 

It seems that previously (before this commit https://github.com/fxbois/web-mode/commit/744777ec6e8fe2c0f3677d5dc84c54c8d9119573), `font-lock-flush` only got called if it was found. That check was commented out, and now it's getting called always.

**Comment by fxbois** [comment]
@jondubin what is you emacs version ?

**Comment by jondubin** [comment]
@fxbois 24.5, FWIW I'm also using spacemacs version ~0.200.5

**Comment by fxbois** [comment]
could you try the last version please

**Comment by jondubin** [comment]
Upgraded and it works now. Upgrading also fixed some other issues I was having. Thanks so much!
