### ISSUE TITLE
Losing color hightlight (spacemacs)

### ISSUE THREAD

**Issue by phenix-factory** [fxbois/web-mode#821]
Hello,

Sometimes, web-mode just stop hightlighting thing. I just dont understand why and how.

![selection_023](https://cloud.githubusercontent.com/assets/1810149/20786513/c992a0a8-b7a6-11e6-996c-dc3a114d2a50.png)

I'm using Spacemacs ([my conf](https://github.com/phenix-factory/config-spacemacs)) and emacs 25.1.1.

Anyone can help ?

Thank's !

**Comment by phenix-factory** [comment]
Hi,
I'm using Spacemacs ([my conf](https://github.com/phenix-factory/config-spacemacs)) and emacs 25.1.1.

**Comment by fxbois** [comment]
@phenix-factory do you have the same issue without spacemacs ?

**Comment by fxbois** [comment]
@phenix-factory please reopen when you can provide some help
