### ISSUE TITLE
Support for Vue stylus style

### ISSUE THREAD

**Issue by lukertty** [fxbois/web-mode#823]
This syntax in .vue has no highlight:
```js
<script>
...
</script>
<style lang="stylus">
.news-view
  padding-top 45px

.news-list-nav, .news-list
  background-color #fff
  border-radius 2px

...
</style>
```

[Source code](https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/components/ItemList.vue)

![image](https://cloud.githubusercontent.com/assets/11374295/20865351/2a35276e-ba4a-11e6-9c59-4c54e62d466e.png)

**Comment by fxbois** [comment]
@lukertty is there any website about this stylus language ?

**Comment by lukertty** [comment]
@fxbois
[stylus-lang.com/](http://stylus-lang.com/) 
[github.com/stylus/stylus](https://github.com/stylus/stylus)

**Comment by fxbois** [comment]
@lukertty should be available soon

**Comment by fxbois** [comment]
@lukertty the last commit adds basic compatibility to stylus parts
