### ISSUE TITLE
Support for styled-components

### ISSUE THREAD

**Issue by jstaffans** [fxbois/web-mode#824]
It would be awesome to have basic support for `styled-components`! See https://styled-components.com/

![screen shot 2016-12-05 at 17 00 46](https://cloud.githubusercontent.com/assets/1368965/20891897/6f238c22-bb0c-11e6-82d1-a4a8e05556a1.png)

Basically, CSS highlighting should be enabled between the backticks after `styled.*`. For reference, there's an [open PR for Sublime](https://github.com/babel/babel-sublime/pull/289).

**Comment by nickmccurdy** [comment]
This could be added as a CSS part, though features like interpolation and nesting could be tricky. Maybe we could cheat and use SCSS/Less language support to get the nesting.

**Comment by fxbois** [comment]
@jstaffans I've started to work on this. Indentation should work with last commit

**Comment by raymestalez** [comment]
Hey everyone! I'm using web-mode, and styled components don't seem to work for me. Was this implemented? Am I doing something wrong? Can you share any tips on how can I make it work?

**Comment by AllanJian** [comment]
indent is wrong
```
const QuestsContainer = styled.section`
  background: #fff;
  padding: 0px 20px;
  h3 {
  margin: 0;
  }
`;
```
I want margin indent 4 , but web-mode give me 2

**Comment by joeheyming** [comment]
@fxbois what was the fix that you did?

**Comment by stevemolitor** [comment]
@fxbois I'm not getting CSS syntax highlighting of style components inside a .tsx file:

![](https://cdn.zappy.app/fe07a419d688e12613952702cab63505.png)

Is that possible? Thanks.
