### ISSUE TITLE
Generator functions in javscript

### ISSUE THREAD

**Issue by grks** [fxbois/web-mode#827]
Just a small thing, it doesn't seem like javscript generator functions are highlighted as functions. Should they?

Sometimes people write them like this 
````js
   function *generator() {}
````
which works, as function gets highlighted. But this form is also not uncommon 
````js
   function* generator() {}
`````

which doesn't get highlighted (e.g. from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator)

Small thing, and not sure it's a bug, but just wanted to ping you about it =)

**Comment by fxbois** [comment]
@grks I've pushed a fix
