### ISSUE TITLE
Color CSS or HTML inside es6 template strings

### ISSUE THREAD

**Issue by TCMiranda** [fxbois/web-mode#828]
Hey, 

It is becoming common to me seeing situations where templates are written using es6 template strings.
I've also seen some javascript code editor coloring content inside them when it is recognized CSS rules or HTML content.

Examples

**Common in Angular2 small components**
![screenshot from 2016-12-10 12-31-44](https://cloud.githubusercontent.com/assets/10077439/21073997/ebc9bee2-bed4-11e6-868e-abe61072f573.png)

**Common in Angular2 and some *CSS in JS* technologies**
![screenshot from 2016-12-10 12-31-17](https://cloud.githubusercontent.com/assets/10077439/21073998/ebcd9b0c-bed4-11e6-85c4-aa2fc463dca8.png)

Would that be possible with web-mode?
Oh, also indentation is a problem... :disappointed: 

Thanks!

**Comment by fxbois** [comment]
@TCMiranda you're right ... perhaps this issue could be posted on the ES6 newsletter.

At the moment, I could rely on something like: 

``` template: /*html*/`<div>`   ```

**Comment by TCMiranda** [comment]
@fxbois Thanks for the answer!
Yea, I don't know much about that, but what you expect from posting the issue?

I wonder if there is some pattern commonly used to annotate the content of texts. Do you think so?
It would be a little sad to use something like ```template: /*html*/`<div></div>` ``` working on a team where I would be the only one benefiting from it, principally if it is not any kind of pattern or convention.

Unfortunately, if lookup to `<html>` or `.css {}` patterns inside the strings is not something doable I don't know an solution yet :sweat:

**Comment by fxbois** [comment]
@TCMiranda 'guessing' the content type inside the template string would be doable ... but not really clean.

**Comment by TCMiranda** [comment]
Uhmm right, now I see the point of posting the issue, currently we can say that template strings are way to generic... Something like php `<<<something` seems like a better approach from this perspective right?

**Comment by fxbois** [comment]
That's right. And I already use this kind of detection for php to detect sql statements.

**Comment by fxbois** [comment]
@TCMiranda Hi, have you progressed on this ?

**Comment by TCMiranda** [comment]
Hey, sorry, I didn't much. Actually, it is possible to use patterns on libraries to detect the type, but it could be exhaustive.

For example https://angular.io/docs/ts/latest/api/core/index/Component-decorator.html
Angular2 @Component decorator
```
@Component({
  styles: [ 'css here' ],
  template: `html here`
})
```

The notation at the object could be useful, but very specific. It is not a pattern beyond angular2 framework.

In a broader manner I would need help to solve this

**Comment by fxbois** [comment]
@TCMiranda html indentation should now work
