### ISSUE TITLE
Emmet support

### ISSUE THREAD

**Issue by Taariqq** [fxbois/web-mode#829]
Hi,

Does this support emmet-mode? C-j seem to produce html style tags instead of expanding the command in css mode.

**Comment by fxbois** [comment]
@Taariqq web-mode is not css-mode ... what do you mean ?

**Comment by Taariqq** [comment]
But web-mode supports CSS, right?

**Comment by fxbois** [comment]
I do not use emmet, could you describe exactly what you would like

**Comment by Taariqq** [comment]
Never mind. I just read on the website that web-mode supports CSS only embedded in html. That explains it. As far as Emmet is concerned, you have to look at it to realize what it is.
