### ISSUE TITLE
Indentation in JavaScript Promise (and other) chains.

### ISSUE THREAD

**Issue by ttmarek** [fxbois/web-mode#831]
Hi,

I've got a Promise chain in my codebase. By default, web-mode will indent it as follows:

(this is just an example)
```js
axios.get('https://some-url')
     .then(JSON.parse)
     .then(console.log)
     .catch(console.error);
```

I actually don't mind this way of indenting, but my co-workers don't like it very much. They want the indentation to match what their (lesser) code-editors give them:

```js
axios.get('https://some-url')
  .then(JSON.parse)
  .then(console.log)
  .catch(console.error);
```

I tried adding the following commands to my web-mode-hook:

```emacs-lisp
(add-to-list 'web-mode-indentation-params '("lineup-args" . nil))
(add-to-list 'web-mode-indentation-params '("lineup-calls" . nil))
(add-to-list 'web-mode-indentation-params '("lineup-concats" . nil))
(add-to-list 'web-mode-indentation-params '("lineup-ternary" . nil))
```

And it sort of worked, but now there is no indentation at all:

```js
axios.get('https://some-url')
.then(JSON.parse)
.then(console.log)
.catch(console.error);
```

@fxbois is there any way I can configure web-mode to indent these types of chains with 2 spaces?

**Comment by fxbois** [comment]
@ttmarek The useful line is ```(add-to-list 'web-mode-indentation-params '("lineup-calls" . nil))```
Could you add in your conf ```(setq web-mode-code-indent-offset 2)```

**Comment by ttmarek** [comment]
Hey @fxbois.

So I do have `(setq web-mode-code-indent-offset 2)` already, and I still get zero indentation. Here's my complete setup:

```emacs-lisp
(use-package web-mode
  :ensure t
  :mode "\\.js\\'"
  :init
  (defun web-mode-hooks ()
    "Hooks for web-mode"
    (js2-minor-mode)
    (setq web-mode-content-type "jsx")
    (setq web-mode-enable-auto-quoting nil)
    (setq web-mode-code-indent-offset 2)
    (setq web-mode-markup-indent-offset 2)
    (setq web-mode-attr-indent-offset 2)
    (add-to-list 'web-mode-indentation-params '("lineup-calls" . nil)))
  (add-hook 'web-mode-hook 'web-mode-hooks))

```

**Comment by fxbois** [comment]
the ```add-to-list``` should be out of the hook

**Comment by ttmarek** [comment]
Okay, so I pulled the `add-to-list` out of the hook, I also tossed it under `:config` in the `use-package` expression (it didn't work under `:init`). That didn't work, so I commented out `(js2-minor-mode)`, and that didn't work.  I ended up with:

```emacs-lisp
(use-package web-mode
  :ensure t
  :mode "\\.js\\'"
  :init
  (defun web-mode-hooks ()
    "Hooks for web-mode"
    ; (js2-minor-mode)
    (setq web-mode-content-type "jsx")
    (setq web-mode-enable-auto-quoting nil)
    (setq web-mode-code-indent-offset 2)
    (setq web-mode-markup-indent-offset 2)
    (setq web-mode-attr-indent-offset 2))
  (add-hook 'web-mode-hook 'web-mode-hooks)
  :config
  (add-to-list 'web-mode-indentation-params '("lineup-calls" . nil)))
```

and I'm still having the same issue?

**Comment by ttmarek** [comment]
@fxbois I made a little discovery today, with the above setup the indentation works perfectly fine as long as the promise isn't implicitly returned from an arrow function. For example:

In the following two cases, the indentation is as expected:

```js
// a promise on its own
somePromise()
  .then(...)
  .catch(...)
```

```js
// a promise returned from a function
const someFunc  = () => {
  return somePromise()
    .then(...)
    .catch(...)
```

BUT, if I implicitly return the promise from an arrow function, the indentation doesn't work:

```js
// implicit return 
const someFunc = () =>
  somePromise()
  .then(...) // no indent
  .catch(...) // no indent
```

I hope this helps.

**Comment by fxbois** [comment]
@ttmarek I've pushed a fix

**Comment by ttmarek** [comment]
@fxbois wow, so quick, that's awesome. Remind me to buy you a beer if you ever visit Toronto.
