### ISSUE TITLE
feature : delayed syntax highlight

### ISSUE THREAD

**Issue by skyer9** [fxbois/web-mode#832]
js2-mode has delayed syntax check feature.

```lisp
(setq js2-idle-timer-delay 1.0)
```

I think it is useful for web-mode.
not reparse buffer on every typing, but once after typing is delayed.

**Comment by fxbois** [comment]
Could you propose a patch ?

**Comment by skyer9** [comment]
when quail-overlay exists, point function always returns 1.
so, it needs modification like below.

'''lisp
(defun web-mode-font-lock-highlight (limit)
  (cond
   (web-mode-inhibit-fontification
    nil)
   (t
    (if (and quail-overlay (overlay-start quail-overlay))
        (web-mode-highlight-region (overlay-start quail-overlay) limit)
      (web-mode-highlight-region (point) limit))
    nil)
   ))
'''

**Comment by fxbois** [comment]
@skyer9 that was what caused slowness ?

**Comment by skyer9** [comment]
when quail-overlay exists, point function always returns 1.
it means when file size is big(for example 23000 line) and editing 20000 line of source code,
web-mode fontify 1 ~ 20000 line for every typing.

**Comment by fxbois** [comment]
@skyer9 web-mode.el has never worked like this, it only refreshed the zone needed

**Comment by skyer9** [comment]
when quail-overlay exists, point function always returns 1.
```lisp
(web-mode-highlight-region (point) limit)
;; equals
(web-mode-highlight-region 1 limit)
```

**Comment by fxbois** [comment]
@skyer9 ok, understood. I'll look at this. Thx

**Comment by skyer9** [comment]
thanks.
it will help CJK Language users(Chinese, Japanese, and Korean).

**Comment by skyer9** [comment]
if user did not use quail input method, undefined error ocurrs.
so some code need to add like below.
i found this bug after restarting Emacs.

```lisp
(defun web-mode-font-lock-highlight (limit)
  (cond
   (web-mode-inhibit-fontification
    nil)
   (t
    (if (and (boundp 'quail-overlay) quail-overlay (overlay-start quail-overlay))
        (web-mode-highlight-region (overlay-start quail-overlay) limit)
      (web-mode-highlight-region (point) limit))
    nil)))
```

**Comment by fxbois** [comment]
@skyer9 could you send me screenshots of what quail do ?

**Comment by skyer9** [comment]
tex input method also uses quail.

```
C-x C-f test.txt RET
M-x set-input-method RET tex RET
type \lambda
```

this methos shows how quail mode works.

**Comment by skyer9** [comment]
my final modification is below.

```lisp
;; disable syntax lighlight when `quail-overlay' exists.
(defadvice web-mode-font-lock-highlight (around web-mode-font-lock-highlight-around activate)
  (unless (and (boundp 'quail-overlay) quail-overlay (overlay-start quail-overlay))
    ad-do-it))

(defadvice web-mode-extend-region (around web-mode-extend-region-around activate)
  (unless (and (boundp 'quail-overlay) quail-overlay (overlay-start quail-overlay))
    ad-do-it))
```

adding advice to function solved my ploblem.
