### ISSUE TITLE
Refusing to parse with "jsx-skip ** warning **" messages

### ISSUE THREAD

**Issue by mariusk** [fxbois/web-mode#834]
I have some complex jsx layouts in React components which web-mode refuses to parse, spewing warnings in the Emacs message log. It seems related to arbitrary limits of 2000 and 100 characters in web-mode.el. The limits seem rather low and ideally should be user configurable.

**Comment by fxbois** [comment]
Hi i ll change this very soon

**Comment by fxbois** [comment]
@mariusk I've pushed a fix

**Comment by mariusk** [comment]
Thanks, that should be helpful. I had taken care of it already at my side. Be advised I think there's at least two places where the values 2000 and 100 were used. Your fix seems to only increase it from 100 to 1000 in one place, but you probably know the code better than I do so it might very well be in the one place that triggers the behaviour I described. Thanks again.

**Comment by fxbois** [comment]
@mariusk I'll no pb increasing thoses values as soon as a user triggers thoses limites
