### ISSUE TITLE
Syntax highlighting not working with /* */ comments in JavaScript 

### ISSUE THREAD

**Issue by geoyws** [fxbois/web-mode#835]
I have to `m-x font-lock-fontify-buffer` manually in order to get it right again.
![screen shot 2016-12-30 at 10 18 26](https://cloud.githubusercontent.com/assets/1738396/21558705/692e3d8c-ce79-11e6-9ff5-b07b98749a97.png)
![screen shot 2016-12-30 at 10 18 50](https://cloud.githubusercontent.com/assets/1738396/21558709/72f2984a-ce79-11e6-966c-8635b4c8f228.png)

**Comment by fxbois** [comment]
@geoyws could you describe exactly the different steps to trigger this please

**Comment by geoyws** [comment]
Odd. After restarting emacs and removing a few lines from my .emacs it doesn't happen any more. Will come back if it returns and will try to pin down the reason. It was really putting me off for a while.

**Comment by fxbois** [comment]
@geoyws ok, reopen if needed
