### ISSUE TITLE
Incorrect indentation in JS for Flow exact object types

### ISSUE THREAD

**Issue by chrisbarrett** [fxbois/web-mode#836]
Great package, thanks for the effort. 👍 

The JS indentation logic does not handle certain Flow type declarations correctly. Specifically, [exact object types](https://flowtype.org/docs/objects.html#exact-object-types) are indented incorrectly. 

Expected: 

```js
type Foo = {|
  foo: string,
  bar: string,
|}
```

Actual: 

```js
type Foo = {|
            foo: string,
            bar: string,
                |}
```

I assume the `{| ... |}` pairs are the problem here. 

I would be happy to submit a PR, so any pointers on how the indentation is calculated would be appreciated. 😸 

Is there a clean way to introduce a new set of pairs? If not, which functions should I work on?

**Comment by fxbois** [comment]
@chrisbarrett do flow scripts have a specific extension ?

**Comment by chrisbarrett** [comment]
No, they are standard JS files plus a babel blugin. However, they must contain the following comment:

```js
// @flow
```
