### ISSUE TITLE
No syntax highlighting on buffers with names starting from space

### ISSUE THREAD

**Issue by racktear** [fxbois/web-mode#838]
Web-mode doesn't highlight syntax on buffers whose names start with space.
Try opening a temporary buffer named " foo.html" (without quotes).

It prevents syntax highlighting from working in org mode, because it uses a temporary buffer starting with space for this purpose.

**Comment by racktear** [comment]
I figured out that in temporary buffers, font lock is disabled by default, and needs to be enabled by `(font-lock-ensure)`.

If i do `(font-lock-ensure)` on a temporary html-mode buffer, the syntax highlighting appears, but not in a temporary web-mode buffer.

**Comment by DoMiNeLa10** [comment]
I can confirm that the same thing happens when opening a file that has a name starting with a space. `web-mode` seems to work fine, it just doesn't do any font locking.

**Comment by racktear** [comment]
@DoMiNeLa10 neither does html-mode by default. This is a feature of emacs, that temporary buffers (starting with spaces) are not fontified. But the difference is that if you call (font-lock-ensure), in html-mode you'll get fontification even in temporary buffers, while in web-mode you won't.

**Comment by fxbois** [comment]
@racktear @DoMiNeLa10 What do you propose ?

**Comment by DoMiNeLa10** [comment]
@racktear It seems that calling `(font-lock-ensure)` in modes like `org-mode` does font locking, but it doesn't update when you start editing text in a buffer. I don't think that users are intended to edit files that have names starting with spaces.
