### ISSUE TITLE
Very slow on large files

### ISSUE THREAD

**Issue by jeffkaufman** [fxbois/web-mode#845]
I have a large file (several megabytes) that's mostly html, with a small amount of js and css mixed in.  Web Mode does well with it once it's open, but takes about 20s to open the file.  Here's a minimal example:

```
for i in $(seq 1 100000); do
  echo "<h1>here is another very long headline I'm appending to the file</h1>"
done > tmp.html
emacs tmp.html
[21 seconds before file contents are visible]
```

**Comment by fxbois** [comment]
@jeffkaufman I've looked at your example and am able to open it in less than 3 seconds on a 2014 macbookpro
I doubt I can do anything about this
