### ISSUE TITLE
HTML comment folding does not work

### ISSUE THREAD

**Issue by ramblehead** [fxbois/web-mode#849]
Default web-mode ```C-c C-p``` folding and ```hs-minor-mode``` folding solution proposed in #397 do not work with HTML comment blocks ```<!--...-->```

The problem seems to be with ```web-mode-forward-sexp``` function as it does not go from ```<!--``` to ```-->``` as, it probably should.

When in #397 ramblehead's code snippet the following

```elisp
(setq hs-forward-sexp-func 'sgml-skip-tag-forward)
```

is added to ```rh-web-hs-html``` function, and

```elisp
(setq hs-forward-sexp-func 'web-mode-forward-sexp)
```

is added to ```rh-web-hs-default``` function, the HTML comment blocks fold as expected. But then we are bringing ```sgml-mode``` dependency which might have side effects with folding "non pure HTML" templates...

Perhaps, ```web-mode-forward-sexp``` should work for comment blocks the same way as ```sgml-skip-tag-forward```.

**Comment by fxbois** [comment]
@ramblehead the last commit brings html comment folding

**Comment by ramblehead** [comment]
C-c C-f now works on comment blocks as expected! Thank you for taking time looking at this issue.

However, ```web-mode-forward-sexp``` behavior is still slightly different from ```sgml-skip-tag-forward```:

Consider the following random comment lines block, where ```*```` represents point position:

```
    <!--* sdfas asfasdfasd
         asdfasdf asdf asdf asdfasdf
         asdfasd  asdfasd
       -->
```

Running ```(sgml-skip-tag-forward 1)``` would result in signal ```(scan-error "Unbalanced parentheses" 1 1)```, while running ```(web-mode-forward-sexp 1)``` would move point to the end of the comment block:

```
    <!-- sdfas asfasdfasd
         asdfasdf asdf asdf asdfasdf
         asdfasd  asdfasd
       -->*
```

Now, consider the same comment block with point moved to its beginning:

```
    *<!-- sdfas asfasdfasd
         asdfasdf asdf asdf asdfasdf
         asdfasd  asdfasd
       -->
```

Running ```(web-mode-forward-sexp 1)``` does nothing, while running ```(sgml-skip-tag-forward 1)``` moves point to the end of the block:

```
    <!-- sdfas asfasdfasd
         asdfasdf asdf asdf asdfasdf
         asdfasd  asdfasd
       -->*
```

With all other tags which I tested ```sgml-skip-tag-forward``` and ```web-mode-forward-sexp``` behave similarly.

**Comment by fxbois** [comment]
@ramblehead the last commit should solve this

**Comment by ramblehead** [comment]
Thank you! This is excellent! Can now fold everything with ```C-S-j``` like in Dreamweaver and no sgml-mode dependency.
