### ISSUE TITLE
Auto opening does not work with newline-and-indent

### ISSUE THREAD

**Issue by kaofelix** [fxbois/web-mode#850]
I did some edebugging to figure out why auto opening was not working for me and I realized that in [this line](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L10043) it's specifying `newline` and `electric-newline-and-maybe-indent`, but my `RET` key is set to `newline-and-indent` (seems to be default on Spacemacs). Since this function is part of Emacs (it's defined in simple.el) I thought you might think it makes sense to add it to the list in there. Sorry for not making a PR, but I thought the overhead would not be worth it to just add a word in there :)

**Comment by fxbois** [comment]
@kaofelix I've pushed a fix ... thx for this perfect bug report

**Comment by kaofelix** [comment]
Got the updated package from melpa, works like a charm. Thanks for the timely update!
