### ISSUE TITLE
indent-for-tab-command don't indent region

### ISSUE THREAD

**Issue by jcubic** [fxbois/web-mode#851]
I have tab set to indent-for-tab-command (don't know if that's default) and when I select region and press tab the code is not indented correctly. You can test it using:
```
<script>
    function() {
 foo();
          }
</script>
```
or html:
```
   <div>
 <form>
       <div>
    <input/>
     </div>
  </form>
     </div>
```
the output of this is this:
```
   <div>
   <form>
   <div>
   <input/>
   </div>
   </form>
   </div>
```

**Comment by fxbois** [comment]
@jcubic perhaps try on emacs stackoverflow.
When I ```C-x h``` and ```TAB``` it works perfectly here

**Comment by jcubic** [comment]
It work when I call emacs -q probably something with my .emacs file. Thanks.
