### ISSUE TITLE
A merge?

### ISSUE THREAD

**Issue by DoMiNeLa10** [fxbois/web-mode#854]
I've had my own fork of `web-mode` for a long time now, and I added some features. I don't want to make a pull request, because the commit history is a mess in my repo, and I'd get a lot of merge conflicts if I tried.

My repository is [here](https://github.com/DoMiNeLa10/web-mode). I don't know if all of things that I've added are worth merging back, so I'm asking if anything from my repo is good enough to go to the upstream version.

**Comment by fxbois** [comment]
@DoMiNeLa10 I'll look at it
