### ISSUE TITLE
Formatting/indentation issue w/ TSX + generics

### ISSUE THREAD

**Issue by faber** [fxbois/web-mode#855]
(Originally posted here: https://github.com/ananthakumaran/tide/issues/119)

I've noticed that certain combinations of TSX and generics seem to break the indentation.  Based on the syntax coloring, I think what happens is that it incorrectly is classifying `{}` as "interpolated js inside of a TSX block", rather than regular braces... here's an example screen shot:

![screen shot 2017-02-25 at 11 58 34 am](https://cloud.githubusercontent.com/assets/43680/23334381/d9f73d8e-fb51-11e6-8388-a2d8d0f066d4.png)

(Sorry for the contrived example, I was trying to reproduce it with as little code as possible.)

Notice the closing bracket of the `MyThing` class aligns w/ the opening bracket, rather than all the way to the left.  It's the type annotation w/ a generic on the final line that triggers this case, if you either remove that line, or just do `export default MyThing;` without the annotation, the issue doesn't manifest.

Also, tho its not shown in that screen shot, if I auto indent the buffer, that final export line will be two spaces in from the left.

I can try to find some other scenarios that trigger this if its helpful, I know i've encountered others but it's been hard to see exactly what causes it.

In case its helpful for testing, here's the code above copy/pastable:

```typescript
import * as React from 'react';

interface Props {
  name: string
}

class MyThing extends React.Component<Props, {}> {
  render() {
    return <span>hi</span>;
  }
}

export default MyThing as React.ComponentClass<Props>;
```

**Comment by fxbois** [comment]
@faber should be better with last commit
