### ISSUE TITLE
Differentiate jQuery $ symbols.

### ISSUE THREAD

**Issue by tysteiman** [fxbois/web-mode#857]
It would be nice if web-mode supported a different syntax for at least the $ sign when working with JavaScript. When working within jQuery it seems somewhat standard in other editors to color the $ sign and I think it helps the jQuery stand out and become more readable. This is especially true since the $ is the same color as parens, brackets, and other variables.

Some editors actually apply color to the surrounding parens as well.

<img width="611" alt="screen shot 2017-03-03 at 3 21 29 pm" src="https://cloud.githubusercontent.com/assets/11522852/23567621/27cc0fda-0025-11e7-9fa7-9a410aa7bec5.png">

**Comment by fxbois** [comment]
@tysteiman I've pushed a fix
