### ISSUE TITLE
Tags not recognized in text/template scripts

### ISSUE THREAD

**Issue by mkleehammer** [fxbois/web-mode#859]
In a script tag like the following, tags aren't recognized, so font-lock isn't working and the automatic close always closes <script>:

    <script id="one" type="text/template">
       <div>
    </script>

For example, if I enter "</" after the div tag, it completes with "</script>":

    <script id="one" type="text/template">
       <div></script>
    </script>

I noticed this in Spacemacs, but I reproduced it running "emacs -Q" and manually loading web-mode.el with M-x load-file.  Note that the engine is "none", but in Spacemacs I set it to "ctemplate".  I can try setting that here if necessary, but wasn't immediately sure how.

--- WEB-MODE DEBUG BEG ---
versions: emacs(25.1) web-mode("14.1.2")
vars: engine("none") minor("none") content-type("html") file("c:/xxx/test.html")
system: window(w32) config("x86_64-w64-mingw32")
colors: fg(nil) bg(nil) 
minor modes: (global-eldoc-mode diff-auto-refine-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@mkleehammer use ```<script id="one" type="text/html">```

**Comment by mkleehammer** [comment]
Fair enough.  It used to work, but I also switched to Spacemacs recently.  Is there any way to configure web-mode to treat text/template as text/html?

**Comment by fxbois** [comment]
@mkleehammer in fact one user has asked me to treat text/template as markdown. Perhaps I should make this thing configurable
