### ISSUE TITLE
Support for jsont

### ISSUE THREAD

**Issue by tali713** [fxbois/web-mode#861]
What it says on the tin, squarespace uses [json-t](https://developers.squarespace.com/what-is-json-t/) for building templates.  While on the surface it seems to be very similar to other languages supported by web-mode, I was not able to easily add the language.  Would it be possible to either have a guide for extending web-mode, or support for json-t built in?

**Comment by fxbois** [comment]
@tali713 could you profile a complete example that would include all the features ?
