### ISSUE TITLE
cursor can't move when turn on web-mode-enable-engine-detection

### ISSUE THREAD

**Issue by pingz** [fxbois/web-mode#864]
You just can't move your cursor using keyboard.

emacs version:

GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 2015-03-08 on trouble, modified by Debian

how to reproduce:

1. downloaded web-mode.el from github;
2. run `emacs -q';
3. eval web-mode.el;
4. open a css/js file and enable web-mode;
5. turn on web-mode-enable-engine-detection;

**Comment by rocha** [comment]
It happens to me to, when `web-mode-enable-engine-detection` is enabled, but only when the cursor moves to the first two lines of the file. This happens regardless if there is a file variable or not. In my case the file variable is: `{# -*- engine: jinja2 -*- #}`

Typing works, but each new character is added before the previous one, resulting in reversed text.

**Comment by fxbois** [comment]
@rocha Could you update to the last version on github please.
If the issue still occurs, could you try to take a video of what happens ?

**Comment by rocha** [comment]
@fxbois it works correctly with the latest version (12a516c).

I'll try to record a video, but in the meanwhile here is a more detail description of the behavior: 

I am using this file: 
```
{# -*- engine: jinja2 -*- #}
{% extends "base.html" %}

{% block head %}
  {% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}
{% endblock %}
```

- Start emacs.
- Set `web-mode-enable-engine-detection` is to `t`.
- Open the file and enable `web-mode`.
- The cursor position is the beginning of the buffer and none of the cursor motion commands work. When typing characters, the text is being input in reverse order.
- Clicking with the mouse outside of the "death" zone does work, and it becomes responsive again. However, if the cursor is moved back into the "death" zone,  it jumps to the start of the buffer and locks again.
- The "death" zone is three lines and 8 characters from the top of the buffer.

**Comment by pingz** [comment]
I'm hoping this video could address the issue. https://youtu.be/oBzDhSN7m8A

**Comment by fxbois** [comment]
@pingz the result is the same with an html file ?

**Comment by pingz** [comment]
@fxbois yes, it is the same.

**Comment by fxbois** [comment]
@pingz do you still have the issue with the latest version ?

**Comment by danatemple** [comment]
I am seeing exactly this behavior with 15.0.16.

Open the file: cursor is stuck on top line, first char. Arrow keys don't move it.
M-> gets me out of this state, goes to bottom of file
Cursor up works fine UNTIL the top 2 lines, then the cursor jumps to the start and is stuck again.

It only happens if I have this set:
(setq-default web-mode-enable-engine-detection t)

File is JSX (GitHub won't let me attach it) but has a .js extension:

```
import React, { Component } from 'react';
import { Grid, Image, Button }  from 'semantic-ui-react';

class NavBar extends Component {

   onViewClick = (e) => {
      e.preventDefault();
      this.props.onViewChange(e.target.dataset.id);
   };

   render() {
      return (
         <div></div>
      );
   }
}
export default NavBar;
```

Emacs is 24.3.1 on Ubuntu 16.04.

My .emacs:
```
(require 'web-mode)
(setq-default web-mode-enable-engine-detection t)
(defun my-web-mode-hook ()
  (setq web-mode-markup-indent-offset 4)
  (setq web-mode-code-indent-offset   4)
)
(add-hook 'web-mode-hook  'my-web-mode-hook)

(add-to-list 'auto-mode-alist '("\\.js\\'" . web-mode))

(setq web-mode-engines-alist
      '(("php"    . "\\.php\\'")
        ("js"    . "\\.js\\'")
        ("blade"  . "\\.blade\\."))
)
```
If I manually set-web-mode-content-type to jsx, it works OK.
I'll let you know if I find out more.

**Comment by fxbois** [comment]
@pingz is it solved with the last version of web-mode ?

**Comment by pingz** [comment]
@fxbois  I've already moved to emacs 25, and I can't reproduce it with latest version of web-mode on emacs 25. I think it has been solved.

GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2017-09-15, modified by Debian
