### ISSUE TITLE
Support gql templates in javascript

### ISSUE THREAD

**Issue by tomconroy** [fxbois/web-mode#866]
It would be great to have web-mode support more general graphql queries created with https://github.com/apollographql/graphql-tag in javascript in the same way it supports Relay.QL (from https://github.com/fxbois/web-mode/issues/807)

**Comment by fxbois** [comment]
@tomconroy I've pushed a fix

**Comment by tomconroy** [comment]
Thank you!!

**Comment by tomconroy** [comment]
Relay v2 has just been announced and with it comes a new `graphql` tagged template, very similar to apollo's:

e.g.
```jsx
class TodoItem extends React.Component {
  render() {
    const item = this.props.data;

  }
}
module.exports = createFragmentContainer(
  TodoItem,
  graphql`
    fragment TodoItem on Todo {
      text
      isComplete
    }
  `,
);
```


https://facebook.github.io/relay/docs/FragmentContainer.html

**Comment by fxbois** [comment]
@tomconroy I've pushed a fix
