### ISSUE TITLE
Feature to disable all editing assistance and leave only syntax highlighting

### ISSUE THREAD

**Issue by mk-fg** [fxbois/web-mode#867]
I'm new to web-mode and as I tried to use, found a lot of issues with pretty much all the stuff it introduces to editing, including conflict with advice from minor modes, incorrect indentation, comments, etc.

After spending few hours on debugging where it all came from and disabling/patching-out all this stuff one-by-one, feel like it'd be really cool if web-mode had one master switch for "disable all editing features".

That way, I'd be able to use it with all the familiar/customized editing already there, without messing it all up, and maybe enable useful stuff from it on a per-feature basis later on.

Apologies for such a lazy feature request, but don't think I can make a good PR for it, given complexity of the code that's already there.

**Comment by fxbois** [comment]
@mk-fg why don't you look at all the web-mode-enable-* .. and set them to nil
It would avoid me some work

**Comment by mk-fg** [comment]
I think there's >20 of them, and it's not as clear (and maybe not exactly same) as one "web-mode-syntax-highlighting-only" knob, and my proposal is that having latter in addition to all the other knobs would be a nice feature (or at least would've been for my use-case).

Guess you mean that it should be easy enough as it is, fair enough, though apparently not for me.

Thanks for a quick response.
