### ISSUE TITLE
Closure {} syntax highlighting doesn't support newlines

### ISSUE THREAD

**Issue by theefer** [fxbois/web-mode#868]
`{...}` highlighting only works on single lines.

For example:
``` soy
{namespace foo.bar
  requirecss="styles"}
```

![screenshot from 2017-03-31 13 47 02](https://cloud.githubusercontent.com/assets/36964/24551001/a10d31f4-1618-11e7-932d-0549027802ec.png)
(notice the highlighting of the 'r' of `foo.bar`)

**Comment by theefer** [comment]
If anyone could give a few pointers on how to fix this (eg do other modes work on a multi-line basis?), I'd be happy to have a go at a fix myself!

**Comment by fxbois** [comment]
@theefer I'll try to look at this this weekend

**Comment by fxbois** [comment]
@theefer I've pushed a fix
