### ISSUE TITLE
Add a variable to set preferred Javascript comment style

### ISSUE THREAD

**Issue by davazp** [fxbois/web-mode#874]
Currently `M-;` (using `web-mode-comment-insert`) inserts the comment styling regarding the context,

https://github.com/fxbois/web-mode/blob/841f253e11e3c5880b357204190996c4ad98d9dc/web-mode.el#L9175

but it will always use `/*..*/` as delimiters. Can we add support to insert `//` comments for Javascript?

I can work on a pull request if there is interest.

Thanks!

**Comment by fxbois** [comment]
@davazp try ```(add-to-list 'web-mode-comment-formats '("javascript" . "//"))```

**Comment by davazp** [comment]
@fxbois that helps when I want to comment a region, but no when inserting a new comment.

I have researched a little bit more:

Creating new comments is done with `web-mode-comment-insert` (instead of `web-mode-comment`). This function has a hard-coded list of styles, it doesn't use the variable.

So I tried deleting that special case, so `web-mode-comment-or-uncomment` will only use `web-mode-comment`, and it seems to work (with the very limited tests I tried).

The only annoyance is that it does not leave the point inside new comments... but that is the current behavior for regions as well. So what if we change `web-mode-comment` to leave the point between the two characters it was?  This is the normal behavior in other modes. 

Do you know if that would break something else?

**Comment by fxbois** [comment]
@davazp Ok, I understand now. I'll look at this

**Comment by fxbois** [comment]
@davazp it is now solved
