### ISSUE TITLE
Syntax highlight of current line is not correct after using evil-paste-after

### ISSUE THREAD

**Issue by d8660091** [fxbois/web-mode#875]
![2017-04-22-235526_767x161_scrot](https://cloud.githubusercontent.com/assets/5819985/25310636/31d0d2c2-27b7-11e7-95bc-bef4f71bd096.png)
When web-mode and evil-mode are enabled, content type is set to javascript, curosr at 'o' of line 6: M-x evil-yank-line and M-x evil-paste-after would results
![2017-04-22-235657_763x183_scrot](https://cloud.githubusercontent.com/assets/5819985/25310646/65d16d34-27b7-11e7-88aa-eeccebc80899.png)

**Comment by fxbois** [comment]
@d8660091 do you confirm it works well without evil-mode ?

**Comment by d8660091** [comment]
Yes, it works with the 'yank' command if evil-paste-after is not used. Additionally, evil-paste-after works if the cursor is at the end of the current line (only characters after the cursor lose syntax highlight), which suggests an easy walk-around.

**Comment by d8660091** [comment]
This problem is solved by now:
https://github.com/emacs-evil/evil/commit/76700a90d127fbd6eb6cd4ff7cb04fc6b8f64aa3
