### ISSUE TITLE
Indentation for CSS values that span across multiple lines?

### ISSUE THREAD

**Issue by tsktsktsk64** [fxbois/web-mode#876]
Hello fxbois and first of all thanks for all the great work you, and the community, have done.

I used to use the built-in `css-mode`. It utilises the `smie` indentation engine and I can easily tweak the indentation rules one by one to get exactly what I want, like, indent for 4 spaces whenever the last line ends with a comma:

![Rules of `smie`](https://cloud.githubusercontent.com/assets/10580362/25368922/c431fc66-29b2-11e7-891b-403b665ebea0.png)

I've been reading the source code of `web-mode`, but I couldn't find anything similar to that. So would you please point out where should I look into?

The version is the latest.

**Comment by fxbois** [comment]
@tsktsktsk64 I do not rely on smie so there is no "api" like the one showed above.
Could you show an example of the kind of indentation you want ?

**Comment by tsktsktsk64** [comment]
@fxbois Thanks for your quick reply.

Below is what I want and have achieved with `css-mode`.

![The indentation I want with css-mode](https://cloud.githubusercontent.com/assets/10580362/25373191/3b3d400a-29cb-11e7-81f9-e07424018f39.png)

Below is in web-mode without configuration:

![The indentation in default web-mode](https://cloud.githubusercontent.com/assets/10580362/25373223/5c3c6740-29cb-11e7-99fc-f667fe5a2215.png)

Clearly the first one is much better, in my opinion.

Thanks for your support!

**Comment by fxbois** [comment]
@tsktsktsk64 right, I'll implement this

**Comment by fxbois** [comment]
@tsktsktsk64 on the first line avec ```src:```, is it normal that the line ends with a ```;``` ?

**Comment by tsktsktsk64** [comment]
@fxbois Sorry about that and this late response. It should be a `,`, as we expected. I think I deleted a duplicate `src:` line but forgot to change the ending.

**Comment by fxbois** [comment]
@tsktsktsk64 I've pushed a fix

**Comment by tsktsktsk64** [comment]
Tested and it worked like a charm. Thanks.
