### ISSUE TITLE
Indentation level is incorrect for React props function (multi line)

### ISSUE THREAD

**Issue by etegan** [fxbois/web-mode#877]
Actual:

    <Route
      path='/home'
      render={ (props) => (
          <Home {...props} />    <----- 4 spaces indentation
        )} />                    <----- 2 spaces indentation

Expected:

    <Route
      path='/home'
      render={ (props) => (
        <Home {...props} />    <----- 2 spaces indentation
      )} />                    <----- 0 spaces indentation

web-mode-debug:

    versions: emacs(26.0) web-mode("14.1.15")
    vars: engine("none") minor("none") content-type("jsx")
    file("/home/eric/Projects/React/PVT/FrontEnd/src/components/app/app.jsx")
    system: window(x) config("x86_64-pc-linux-gnu")
    colors: fg(nil) bg(nil) 
    minor modes: (global-eldoc-mode evil-local-mode evil-mode undo-tree-mode global-undo-tree-mode
    projectile-mode linum-mode shell-dirtrack-mode diff-auto-refine-mode)
    vars:
    web-mode-enable-current-column-highlight=nil 
    web-mode-enable-current-element-highlight=nil 
    indent-tabs-mode=nil

**Comment by fxbois** [comment]
@etegan should be solved by the end of the week

**Comment by fxbois** [comment]
@etegan I solved this with the last commit

**Comment by etegan** [comment]
I seem to still be having some propblems:

    <Route exac path='/' render={(matchProps) => (
      <DefaultLayout>                <----- Correctly indentet
      <Home {...matchProps} />       <----- Should be two more spaces indented
        </DefaultLayout>             <----- Two spaces too much
    )} />

Debug:

    --- WEB-MODE DEBUG BEG ---
    versions: emacs(26.0) web-mode("14.1.17")
    vars: engine("none") minor("none") content-type("jsx")
    file("/home/eric/Projects/React/PVT/FrontEnd/src/root.jsx")
    system: window(x) config("x86_64-pc-linux-gnu")
    colors: fg(nil) bg(nil) 
    minor modes: (global-eldoc-mode evil-local-mode evil-mode undo-tree-mode global-undo-tree-mode
    projectile-mode linum-mode shell-dirtrack-mode diff-auto-refine-mode)
    vars:
    web-mode-enable-current-column-highlight=nil 
    web-mode-enable-current-element-highlight=nil 
    indent-tabs-mode=nil 
    --- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@etegan I've pushed a new patch

**Comment by etegan** [comment]
Thanks for such quick respons! I'm however still having som problems:

      <Router>                     <------- This and...
        <Switch>                   <------- ...this encloses all Route tags.
          <Route                   <------- First tag indents correctly, however...
            exact
            path="/"
            render={matchProps => (
              <DefaultLayout>
                <Home {...matchProps} />
              </DefaultLayout>
            )} />                  <------- If closing bracket is on new line...
    /*/>     */                    <------- it aligns with next Route tag like this
      <Route                       <------- All Route-tags from here align with Router-tag (independet if closing bracket is on same line or not).
    path="/settings"
    render={matchProps => (
      <DefaultLayout>
        <Settings {...matchProps} />
      </DefaultLayout>
    )} />

Debug:

    --- WEB-MODE DEBUG BEG ---
    versions: emacs(26.0) web-mode("14.1.18")
    vars: engine(nil) minor(nil) content-type("") file("/home/eric/Projects/React/PVT/FrontEnd/src/root.jsx")
    system: window(x) config("x86_64-pc-linux-gnu")
    colors: fg(nil) bg(nil) 
    minor modes: (global-eldoc-mode evil-local-mode evil-mode undo-tree-mode global-undo-tree-mode
    projectile-mode linum-mode shell-dirtrack-mode cursor-sensor-mode diff-auto-refine-mode)
    vars:
    web-mode-enable-current-column-highlight=nil 
    web-mode-enable-current-element-highlight=nil 
    indent-tabs-mode=nil 
    --- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
@etegan do you confirm that the example bellow indents correctly ?

```class Test extends Component {
  render() {
    return (
      <Router>
        <Switch>
          <Route
            exact
            path="/"
            render={matchProps => (
              <DefaultLayout>
                <Home {...matchProps} />
              </DefaultLayout>
            )} />
          <Route
            path="/settings"
            render={matchProps => (
              <DefaultLayout>
                <Settings {...matchProps} />
              </DefaultLayout>
            )} />
        </Switch>
      </Router>
    )
  }
}```

**Comment by etegan** [comment]
Looks right to me =)

**Comment by fxbois** [comment]
So I can not trigger your bug. Could you try to give me more info ?

**Comment by etegan** [comment]
Seems to be working for me now. Must have been a mistake from my side =) Thanks so much for fixing this!

**Comment by etegan** [comment]
While I got your attention I might as well ask. Is there a way to make the brackets not align?

    <Route
      exact
      path="/"
      render={ matchProps => (
        <Home {...matchProps} />)
             }     <------ Want this to align with the 'r' in 'render'
    />

**Comment by fxbois** [comment]
@etegan I'll look at this

**Comment by fxbois** [comment]
@etegan I've pushed a fix
