### ISSUE TITLE
font-lock-extra-managed-props has no effect

### ISSUE THREAD

**Issue by DarthFennec** [fxbois/web-mode#879]
Context: DarthFennec/highlight-indent-guides#22

[`highlight-indent-guides-mode`](https://github.com/DarthFennec/highlight-indent-guides) relies on `font-lock-extra-managed-props` to automatically clear indentation guides as part of the normal `font-lock` cycle. However, `font-lock-unfontify-region-function` (which by default would normally clear these properties) is overridden by `web-mode`, so the properties are never cleared.

I realize this was overridden for a reason, but I'm wondering if there's any harm in clearing the properties listed in `font-lock-extra-managed-props` in your override, even if you aren't going to clear `font-lock-multiline` etc.

**Comment by fxbois** [comment]
@DarthFennec could you make some tests ?

**Comment by DarthFennec** [comment]
Tests? For what?

**Comment by jcs090218** [comment]
Why this issue is closed?
