### ISSUE TITLE
Feature request: please allow toggle between single and multi-line commenting

### ISSUE THREAD

**Issue by paxperscientiam** [fxbois/web-mode#881]
Hello!

Would you consider integrating a bit more flexibility for comment styling WRT to the `comment-style` variable?

I would find it useful to apply single-line style comments when working with HTML.

Perhaps this could be introduced by extending `web-mode-comment-formats` appropriately?

Thanks for your consideration.

**Comment by fxbois** [comment]
@paxperscientiam could you provide real examples please

**Comment by paxperscientiam** [comment]
@fxbois 

Gladly!

Given a block of HTML...
````HTML
  <li class="bar-graph-axis">
    <div class="bar-graph-label">100%</div>
    <div class="bar-graph-label">80%</div>
    <div class="bar-graph-label">60%</div>
    <div class="bar-graph-label">40%</div>
    <div class="bar-graph-label">20%</div>
    <div class="bar-graph-label">0%</div>
  </li>
````

...it would be useful to have the option to comment in/out any number of these list items without having to reverse the previous action beforehand.
Commenting out the first three items with the current version of web-mode yields this:
````HTML
 <li class="bar-graph-axis">
   <!-- <div class="bar-graph-label">100%</div>
        <div class="bar-graph-label">80%</div>
        <div class="bar-graph-label">60%</div> -->
    <div class="bar-graph-label">40%</div>
    <div class="bar-graph-label">20%</div>
    <div class="bar-graph-label">0%</div>
  </li>
````

What if one wants to un-comment items two and three, excluding item one? Currently, one must reverse the action of commenting out items 1-3 and then comment line one.

However, this process becomes simpler if the `comment-style` were respected. Setting `comment-style` to any of the single-line style options, would allow this:
````HTML
 <li class="bar-graph-axis">
   <!-- <div class="bar-graph-label">100%</div> -->
   <!-- <div class="bar-graph-label">80%</div> -->
   <!-- <div class="bar-graph-label">60%</div> -->
    <div class="bar-graph-label">40%</div>
    <div class="bar-graph-label">20%</div>
    <div class="bar-graph-label">0%</div>
  </li>
````

Please let me know if I am failing to be clear. Thanks.

**Comment by fxbois** [comment]
@paxperscientiam ok, I'll try to work on this

**Comment by AlexYegupov** [comment]
Also is would be great not to comment empty lines before text. For example after paragraph was selected by Alt+h standard key

**Comment by fxbois** [comment]
the command ```web-mode-element-children-comment``` will soon be available
