### ISSUE TITLE
React Layer indentation for components passed as props

### ISSUE THREAD

**Issue by dre-hh** [fxbois/web-mode#882]
advised by @robbyoconnor to submit https://github.com/syl20bnr/spacemacs/issues/8954 here

#### Description
React Layer indentation for components passed as props

#### Reproduction guide
- Start Emacs with web-mode
- Set indent consistently to 2 spaces, disable attribute alignment rules
- Edit a jsx file 
```jsx
<Foo 
  someLongValue='x'
  text={
    <Text>text</Text>
  } 
}/>
```
- Go into insert mode and add new line before the word `text`

*Observed behaviour:* 
 text is aligned to the value of previous attribute
```jsx
<Foo 
  someLongValue='x'
  text={
    <Text>
                 text
    </Text>
  } 
}/>
```

*Expected behaviour:* 
Text should be aligned according normal indent rules

```
<Foo 
  someLongValue='x'
  text={
    <Text>
       text
    </Text>
  } 
}/>
```

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git html javascript markdown org osx syntax-checking react ruby version-control yaml
                 (org :variables org-enable-reveal-js-support t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by robbyoconnor** [comment]
That was fast
