### ISSUE TITLE
More imenu entries (for javascript, vuejs style)

### ISSUE THREAD

**Issue by vindarel** [fxbois/web-mode#886]
Hi,
Currently the imenu shows some html tags. I'd like it to show javascript functions, including in vuejs files.

I've seen `web-mode-imenu-regexp-list` and `web-mode-imenu-index` and it looks to me they are specially crafted to catch html tags (as seen in http://web-mode.org/doc/imenu.txt). So it is very unclear to me how to add regular imenu entries.

I have a regexp, checked with the regexp builder:

    (setq imenu-generic-expression
             '(("methods" "^\\s-*\\([a-zA-Z0-9_]+\\): function" 1)))

(also I don't know how to override the existing entries and use just that. I tried:

    (add-hook 'web-mode-hook
           (lambda ()
              (set (make-local-variable imenu-generic-expression)
                   '(("methods" "^\\s-*\\([a-zA-Z0-9_]+\\): function" 1))
                     )))

as discussed on emacswiki and [SE](https://emacs.stackexchange.com/questions/10105/imenu-generic-regexp-for-css-less) with no luck.)

An example code:

```
    data: function() {
      return {
        page: 1,
      };
    },

    props: {
      title: String,
      url: String,
    },

    computed: {
      entries() {
        log("hello");
      },

    methods: {
      previousPage: function () {
        // ...
      },

```
there would be functions and data to catch, hence a few imenu regexps to write. We could even have a menu title with "computed", "methods" and other functions defined elsewhere.

How can we do that in web-mode ?

imenu doc: https://www.gnu.org/software/emacs/manual/html_node/elisp/Imenu.html

To try things out I also did

        ;; imenu-create-index-function 'web-mode-imenu-index
        imenu-generic-expression '(("methods" "^\\s-*\\([a-zA-Z0-9_]+\\): function" 1))

but I can't see any change…

**Comment by vindarel** [comment]
Note: by launching emacs with `emacs -Q`, web-mode shows me all the JS functions. There's a pb on my side.

This question is then a little feature request: in vue-mode, be able to see "data", "props", "computed" and "methods" entries (which are not only functions).

**Comment by fxbois** [comment]
@vindarel could you give me more details please (some examples)

**Comment by vindarel** [comment]
yes, for the little feature, given my example code, it would be to also catch "props", "entries" which are not functions and are not caught presently. Also it would be to put "entries" into a "computed" subgroup and to have a "methods" subgroup. 

Is that better ?

**Comment by fxbois** [comment]
@vindarel sorry but I won't have time to work on this. Could you provide some patch ?

**Comment by JJPandari** [comment]
@vindarel Hi, I subscribed to this issue and later found an imperfect but working solution, putting it here in case you need it: The key is, `imenu-generic-expression` only takes effect when `imenu-create-index-function` is set to `imenu--generic-function`. To have both imenus by one's own regexps and those web-mode generates, [we need to merge them](https://stackoverflow.com/a/21656063/4788022).  

Here is the merger function:  
```lisp
(defun jjpandari/merge-imenu (index-fun)
  (interactive)
  (let ((mode-imenu (funcall index-fun))
        (custom-imenu (imenu--generic-function imenu-generic-expression)))
    (append custom-imenu mode-imenu)))
```

Then config my web-mode with this function:  
```lisp
(add-hook
  'web-mode-hook
  (lambda ()
    (setq imenu-create-index-function (lambda () (jjpandari/merge-imenu 'web-mode-imenu-index)))
    (when (equal (file-name-extension buffer-file-name) "vue")
      (setq
      imenu-generic-expression
      ;; note: these regexps has hard-coded indent lengths (2 in my case)
      '(("method" "^    \\([^ ]+\\)(.*) {" 1)
        ("prop" "^  \\([^ ]+\\): {" 1)
        ("hook" "^  \\([^ ]+\\)() {" 1))))) t)
```

**Comment by vindarel** [comment]
@JJPandari Thank you very much ! This + my little regex (to list all methods) works perfectly. 

I should be able to provide a patch.
