### ISSUE TITLE
Support full set of characters permitted in XML tags

### ISSUE THREAD

**Issue by yurikhan** [fxbois/web-mode#887]
## To reproduce

`$ emacs -Q`

`M-:` `(emacs-version)` `RET`
⇒ `"GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)`
`of 2016-12-13, modified by Debian"`

`M-:` `(add-to-list 'load-path "~/.emacs.d/web-mode")` `RET`
`M-:` `(require 'web-mode)` `RET`

`M-:` `web-mode-version`
⇒ `"15.0.0"`

`C-x` `C-f` `foo.xml` `RET`
`M-x` `web-mode` `RET`

Type: `<foo_bar></`

## Expected behavior

* `foo_bar` is fontified as a local name of an XML element.
* The closing tag is autocompleted as `</foo_bar>`.

## Observed behavior

* `foo` is fontified as a local name of an XML element.
* `_bar` is not fontified.
* The closing tag is autocompleted as `</foo>`.

## Relevant specifications

In XML 1.1, the [grammar for names][1] is:

```
[4]  NameStartChar ::= ":" | [A-Z] | "_" | [a-z] | [#xC0-#xD6] | [#xD8-#xF6]
                     | [#xF8-#x2FF] | [#x370-#x37D] | [#x37F-#x1FFF]
                     | [#x200C-#x200D] | [#x2070-#x218F]
                     | [#x2C00-#x2FEF] | [#x3001-#xD7FF]
                     | [#xF900-#xFDCF] | [#xFDF0-#xFFFD]
                     | [#x10000-#xEFFFF]
[4a] NameChar ::= NameStartChar | "-" | "." | [0-9] | #xB7
                | [#x0300-#x036F] | [#x203F-#x2040]
[5]  Name ::= NameStartChar (NameChar)*
```

[1]: https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-NameStartChar

I have not tested the whole range, but `_`, `.`, `·` (U+B7) and `🔒` (U+1F512) all fail. Cyrillic letters in range U+0410–U+044F pass.

## Why this is important even though no web markup languages use underscores in element names

* `web-mode` is the logical candidate to activate for the `.j2` extension (Jinja) via `auto-mode-alist`.
* Jinja templates are used in Ansible for all kinds of templates, mainly configuration files.
* Configuration files sometimes use XML syntax and have all kinds of weird schemas.

**Comment by fxbois** [comment]
@yurikhan should be fixed

**Comment by yurikhan** [comment]
The linked commit seems to fix the underscore but not other characters. Of those, I think the full stop `.` U+002E is not perverse (as in, I can imagine myself using in an XML tag).
