### ISSUE TITLE
helm-jump-in-buffer integration

### ISSUE THREAD

**Issue by dre-hh** [fxbois/web-mode#889]
calling helm-jump-in-buffer in js2 mode shows an outline of functions . This does not happen when using webmode with react files.

Initially i reported this behaviour in spacemacs react layer config which is using webmode under the hood. https://github.com/syl20bnr/spacemacs/issues/8989

The react mode maintainer @JAremko suggested to ask for support here. 

So i am asking it would be possible to integration helm-jump-in-buffer (or imenu-list-window )

**Comment by fxbois** [comment]
@dre-hh as I do not use helm, could you describe very precisely what should be done (image and video could be useful also)

**Comment by dre-hh** [comment]
I see the spacemacs function is just calling this
https://github.com/emacs-helm/helm/blob/ea8e30436ff5f7ddc7e6d105190f3f1d06dba57c/helm-semantic.el#L179

I`ve made a short vid of the behavior

https://drive.google.com/open?id=0B2IWg6zx0-kgc1doSHE0XzRyWTA

**Comment by fxbois** [comment]
@dre-hh I only have music in this video

**Comment by dre-hh** [comment]
🤣  sorry i accidentally copy pasted a wrong link, and perhaps you have received that as mail. but i`ve updated the comment.

**Comment by fxbois** [comment]
@dre-hh I am sorry but I won't have time to work on this
