### ISSUE TITLE
Support flycheck

### ISSUE THREAD

**Issue by ojab** [fxbois/web-mode#891]
Right now `flycheck` doesn't support web-mode, so `(flycheck-add-mode 'javascript-eslint 'web-mode)
` should be used in order to make it work.
AFAIU support for `web-mode` was dropped because flycheck can't detect what language `web-mode` is used, so can't decide which checkers should be used (see https://github.com/flycheck/flycheck/issues/706#issuecomment-125929279 for example).
 It would be awesome if `flycheck` will work out of the box.

**Comment by fxbois** [comment]
@ojab You should ask some help on emacs stackoverflow ... I know people have dealt with this

**Comment by ojab** [comment]
Yeah, it could be done via `eval-after-load 'flycheck` hook and alike, but this issue is about ideal world where flycheck works out-of-the box and loads proper checker for current file automatically.

**Comment by fxbois** [comment]
@ojab I can help but won't have time to work on this

**Comment by aguynamedben** [comment]
Did anybody come up with a good config for this? I'm new to lisp and not sure how to write the hook.

It seems that flycheck only supports chosing a linter based on major mode, and there is no way to configure flycheck by file extension instead. The solution mentioned [in this article](http://codewinds.com/blog/2015-04-02-emacs-flycheck-eslint-jsx.html) works for .js/.jsx but inadvertently causes ESLint to run on .scss files.

Also see https://github.com/flycheck/flycheck/issues/663#issuecomment-415644339

**Comment by aguynamedben** [comment]
@fxbois Is there any chance the API is added so that flycheck can determine what language web-mode is currently working on? The request [here](https://github.com/flycheck/flycheck/issues/706#issuecomment-125929279) seems reasonable, is that difficult to implement?
