### ISSUE TITLE
Option to turn off indent on yank

### ISSUE THREAD

**Issue by jcubic** [fxbois/web-mode#894]
Another question about yank + indent like #703

Is it possible to turn off indent when pasting text for insiance I have this string in clipboard: `"$response->redirect("` and when I yank that text into php code everything after that line get one more indent because of unclosed `(` to fix it I need to paste that text into temp buffer, add `)`, then copy and paste. 

Another test case, I have code like this:
```
if (|
```
and I want to paste function from other part of code eg. `foo()` and after yank I've got everything after if one additional indent level because of onclosed `(`.

It would be nice if you can turn off indent on yank. the option can be turn on by default so it will be not breaking change.

**Comment by fxbois** [comment]
@jcubic Have you looked at : ```web-mode-enable-auto-indentation``` ?

**Comment by jcubic** [comment]
this works great, thanks.
