### ISSUE TITLE
[feature request] Support for Opal (Ruby to javascript compiler)

### ISSUE THREAD

**Issue by zw963** [fxbois/web-mode#895]
[This](https://github.com/opal/opal#readme)  is a seven years old project, still keep active development.

but not reach 1.0 yet.

Following is example from README:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="http://cdn.opalrb.org/opal/current/opal.js"></script>
    <script src="http://cdn.opalrb.org/opal/current/opal-parser.js"></script>
    <script type="text/javascript">Opal.load('opal-parser')</script>

    <script type="text/ruby">
      puts "hi"   # <============== Here need emacs builtin ruby-mode syntax support.
    </script>

  </head>
  <body>
  </body>
</html>
```

Thanks.

**Comment by zw963** [comment]
Following is a more complicated example:

```rb
  <script type="text/ruby">

    class Helloworld < Hyperloop::Component

      def render
        DIV do
          "hello world !"
        end
      end

    end

  </script>
```

**Comment by fxbois** [comment]
@zw963 are you aware of any other projets using this.
I do not want to invest to much time on a tech that no one uses

**Comment by zw963** [comment]
@fxbois , HI, following is a list project which use Opal.

https://github.com/fazibear/awesome-opal

Though, not every project need write `ruby` directly in view.

I think, a easy why is: maybe just need replace original `<%= ??? %>` syntax support to `<script type="text/ruby"> ??? </script>`, it should worked?

thanks

**Comment by fxbois** [comment]
@zw963 are you still using this ?

**Comment by zw963** [comment]
YES，to be honest，we very little chance to need write ruby directly in page，but，if can do like that，it awesome！

**Comment by zw963** [comment]
in fact，any even JS，we seldom write directly in page，but，for play or test，it awesome

**Comment by zw963** [comment]
hi，if you thought add this feature is need more invest，so，i think yiu can feel free to close this issue，Opal is great, and will reach 1.0 this year, but, to be honest，should few pepole direct use this

**Comment by fxbois** [comment]
@zw963 I've pushed a fix

**Comment by zw963** [comment]
Seem like indent is not correct for me.

![snapshot1.png](http://zw963.github.io/images/18901523313411.png)

**Comment by fxbois** [comment]
@zw963 post your example on gist please

**Comment by zw963** [comment]
@fxbois , Hi,  [here](https://gist.github.com/fb2fb30b3981d05c669f015d48695e14) is gist.

It not same as the snapshot picture,  (maybe other minor mode caused this), highlight is worked, but if run `(untabify (point-min) (point-max))` when cursor within ruby code,  indent is wrong.

![history.png](http://zw963.github.io/images/215171240124435.png)

**Comment by fxbois** [comment]
@zw963 I've pushed a fix

**Comment by zw963** [comment]
@fxbois , for this example, it worked!

I will try more later, if exist issue, will reopen this issue.

Thanks you very much for your hard work!!

**Comment by ylluminate** [comment]
Thank you @fxbois, several of us who learned of this today were very pleased with what you've done here.

**Comment by fxbois** [comment]
@ylluminate could you ask Opal maintainer to put on the website a note saying that emacs (with web-mode) is compatible ?

**Comment by zw963** [comment]
Yes, I will try it today.

And,  yesterday, I have sent a screenshot to Opal gitter channel.

![aaa.png](http://zw963.github.io/images/319301954128122.png)

**Comment by zw963** [comment]
@fxbois , I create a issue to https://github.com/fazibear/awesome-opal.

After emacs is added into `awesome-opal`, i think web-mode will be in `http://opalrb.com/libraries/`

**Comment by fxbois** [comment]
@zw963 thx
