### ISSUE TITLE
Indentation not working as expected

### ISSUE THREAD

**Issue by brandonparsons** [fxbois/web-mode#897]
Hi there,

I'm new to the Emacs & Spacemacs community. I'm trying to get started with Spacemacs to see if it's for me.

I've run into an issue with web-mode that I can't sort out. I've posted on SO but have not received any replies (other than it's probably worth filing an issue here).

When editing one of my html templates (myfile.html.eex), the indentation displayed in Spacemacs is not as expected.

The HTML content is displayed way over to the right of the screen. When I put my cursor onto the line with the HTML, it (temporarily) moves into the right spot. It then moves back over to the right once the cursor leaves the line.

If I access a different file, then come back again, (SPC-TAB SPC-TAB) the formatting is correct.

This behaviour is distracting/annoying. Any way to fix it?

Text floating way over to the right:

<img width="800" alt="1" src="https://user-images.githubusercontent.com/1277162/28473157-ad466248-6e00-11e7-9b9c-e511c7bcf35e.png">

Cursor over the line, it moves into the correct location: 

<img width="860" alt="2" src="https://user-images.githubusercontent.com/1277162/28473165-b69d523e-6e00-11e7-9d7f-62007754eec5.png">

Move cursor off the line, it goes back to the wrong spot on the right: 

<img width="774" alt="3" src="https://user-images.githubusercontent.com/1277162/28473175-becac37e-6e00-11e7-9216-5c8c43df4096.png">

Access a different file and come back - everything looks right: 

<img width="729" alt="4" src="https://user-images.githubusercontent.com/1277162/28473185-c9fb4016-6e00-11e7-889d-b7cdb6216b5d.png">

Any help you could provide would be greatly appreciated!

**Comment by fxbois** [comment]
@brandonparsons It is related to the minor mode that displays a vertical line.
You should disable it for web-mode.
(it is a hook priority nightmare that can not been solved properly)

**Comment by brandonparsons** [comment]
Thanks @fxbois . Are you talking about `indent-guide-mode`?
