### ISSUE TITLE
Incorrect indentation in handlebars template (and it used to be correct)

### ISSUE THREAD

**Issue by nightire** [fxbois/web-mode#898]
expected:

```htmlbars
{{example-component
  foo="bar"
  bar=(action "baz")
  baz=foo}}
```

current result:
```htmlbars
{{example-component
    foo="bar"
    bar=(action "baz")
    baz=foo}}
```

There're two more spaces on attribute indentation in new line, but it used to be correct, unfortunately I can't tell since when it is broken.

I use spacemacs and I've try stable and develop branch both, and I tested all possible configuration that web-mode provides as well.

**Comment by fxbois** [comment]
@nightire I've just tested and it seems to work ok.
Seems related to spacemacs (which I do not use)

**Comment by nightire** [comment]
@fxbois Thank you. Actually I reverse my config to original version from spacemacs, and add everything I need back one by one, and it magically works fine again. So you were right about something goes wrong with my old config, yet I can't tell exactly what it is...
