### ISSUE TITLE
Improve auto pairing of elements in JSX

### ISSUE THREAD

**Issue by amirouche** [fxbois/web-mode#900]
First, thanks for this awesome mode! It's pleasure to work with it and it would much more difficult to work with JSX if it did not exists!

Like I said I work with JSX with ReactJS. To keep the number of variables coming from imports under control, I import my components as module with the following syntax:

```js
import fw from 'forward.js'
```

This allow me to write JSX that look like the following:

```jsx
var Dashboard = function({mc, model}) {
  return (
    <Shell>
      <h1>Welcome to Socialite</h1>
      <div id="dashboard">
        <fw.Link mc={mc} href="/chat">
        </fw.Link>
      </div>
    </Shell>
  )
}
```

The issue I have is when web-mode try to close the current tag that has a dot `.` in its name (yes this is valid react component). In the above example `<fw.Link>` is completed with `</fw>` which is wrong.

Is it possible to fix that behavior?

**Comment by fxbois** [comment]
@amirouche are you aware of any other projects/modules using dots in tag names (could you provide an url to them please)

**Comment by amirouche** [comment]
> are you aware of any other projects/modules using dots in tag names 

No, I know nobody doing that. That said, I am trying to push [that feature into reactstrap](https://github.com/reactstrap/reactstrap/issues/517) (bootstrap for reactjs).

**Comment by fxbois** [comment]
@amirouche I am reluctant to slow down web-mode for every one if you are the only one using this kind of tags.
Could you use ```<fw-Link>``` or ```<fw_Link>``` or ```<fw:Link>``` ?

**Comment by amirouche** [comment]
It's ok. Tx!
