### ISSUE TITLE
Rename web-mode-content-types-alist in docs

### ISSUE THREAD

**Issue by nickmccurdy** [fxbois/web-mode#901]
It appears as if `web-mode-content-types-alist` has been renamed to `web-mode-content-types`. While both variables are supported, only the former is declared, so it would be nice to update the docs to reflect this. I was confused when I pasted this into my `.emacs` and my linter complained about `web-mode-content-types-alist`, and I could also see some potential confusion with the ordering of pairs between both variables.

**Comment by fxbois** [comment]
@nickmccurdy thank you, I've added a defvar
