### ISSUE TITLE
Markdown file support

### ISSUE THREAD

**Issue by nickmccurdy** [fxbois/web-mode#902]
I have Liquid templates in some markdown files in one of my Jekyll projects, and I would like to use `web-mode` for the Liquid support while also having basic Markdown support like syntax highlighting. I have been using `markdown-mode` but that of course does not support Liquid.

Would this be possible in `web-mode`? I tried modifying `web-mode-content-types` with the config below, but `web-mode` still only highlights HTML and Liquid code. I thought this would be possible based on #789 but I guess either my config is problematic or `web-mode` only supports the `markdown` type in parts.

```emacs
(use-package web-mode
  :ensure
  :mode
  ("\\.html?\\'" . web-mode)
  ("\\.md\\'" . web-mode)
  :config
  (setq web-mode-engines-alist '(("liquid" . "\\.html?\\'")
                                 ("liquid" . "\\.md\\'")))
  (add-to-list 'web-mode-content-types '("markdown" . "\\.md\\'")))
```

**Comment by fxbois** [comment]
@nickmccurdy web-mode can not achieve what you want to do ... web-mode "doesn't know" markdown syntax
