### ISSUE TITLE
Indents unclosed <p> tags incorrectly (valid HTML)

### ISSUE THREAD

**Issue by jocap** [fxbois/web-mode#905]
Hello!

First of all, I thank all contributors for making this great package.

My problem is that it doesn't seem to be fully compatible with HTML. More precisely, auto-indentation fails whenever I don't close a `p` tag:

```
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Example</title>
    </head>
    <body>
        <p>Example example example
            <p>Example example example
                <h2>Articles</h2>
    </body>
</html>
```

Keep in mind, that is perfectly valid HTML - if you want to see for yourself, paste the above code into the [W3C validator](https://validator.w3.org/).

Not having to close my `p` or `li` elements is the only thing keeping me sane when writing raw HTML, so I would *love* it if `web-mode` supported it.

Thanks!
\- John

**Comment by fxbois** [comment]
@jocap Hi being compatible with this 1/ would be difficult and 2/ would slow down many features (like indentation).
I will not be able to add this feature to web-mode

**Comment by jocap** [comment]
@fxbois Thanks for your response. I actually don't think this would be very hard to implement. Citing from the MDN web docs:

> **`<p>`:** "The end tag may be omitted if the `<p>` element is
> immediately followed by an `<address>`, `<article>`, `<aside>`,
> `<blockquote>`, `<div>`, `<dl>`, `<fieldset>`, `<footer>`,
> `<form>`, `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>`,
> `<header>`, `<hr>`, `<menu>`, `<nav>`, `<ol>`, `<pre>`,
> `<section>`, `<table>`, `<ul>` or another `<p>` element, or if
> there is no more content in the parent element and the parent
> element is not an `<a>` element."

> **`<li>`:** "The end tag can be omitted if the list item is
> immediately followed by another `<li>` element, or if there is
> no more content in its parent element."

A simple implementation that covers most cases might be to check, upon opening a `<p>`, whether the previous block-level element opened was also a `<p>`, and if so, resetting the indentation.

I really think this should be in web-mode. Web-mode is many people's go-to Emacs package for HTML, and there are no packages that correctly handle this very common practice. Perhaps one could write a new package that tries to be smarter about HTML, but wouldn't web-mode be a good place for it, and wouldn't you like web-mode to rise above the "competition"?

If you don't want to implement it, I might have a go. I would have to familiarize myself with the code base, though, so I can't promise anything. In any case, I really think you should consider supporting this - I've heard others complain about this on the *help-gnu-emacs* mailing list.

Thanks!
\- John

**Comment by fxbois** [comment]
@jocap not to easy
https://www.w3.org/TR/html5/syntax.html#optional-tags

I might look at it some day but if you want to try, do not hesitate !

**Comment by jocap** [comment]
@fxbois:

Yeah, all that would be impossible to implement. But implementing a small subset of it, only for `<p>` tags and possibly also for `<li>` tags - the most common use cases - would be appreciated by many.

Do you feel like the current source code of `web-mode` could easily be modified to have `<p>` elements be closed by `<p>`, `<address>`, `<article>` and so forth, in addition to `</p>`? If so, I'd be glad to implement this specific functionality.

Thank you for your time.

\- John

**Comment by fxbois** [comment]
@jocap I might try to add a simple implementation that could be finished by you. Hope to release this before the end of august

**Comment by jocap** [comment]
@fxbois That's great to hear! Thanks for being so helpful.

**Comment by fxbois** [comment]
@jocap you can now ```(setq web-mode-enable-optional-tags t)```

**Comment by jocap** [comment]
@fxbois That is fantastic! Thank you for your great work :-)

**Comment by sid-code** [comment]
I seem to be missing something. Even with `(setq web-mode-enable-optional-tags t)`, I still get the following (incorrect) indentation:

```html
<p><a href="page1.html">Page one</a>
    <p><a href="page2.html">Page two</a>
        <p><a href="page3.html">Page three</a>
```

How can I get the behavior that I want? I want the indentor to *completely ignore* the `<p>` tag.
