### ISSUE TITLE
Indentation completely off in markup

### ISSUE THREAD

**Issue by guilhermeasg** [fxbois/web-mode#906]
This is sort of hard to describe, see the GIF below for a better illustration...

![Example](https://user-images.githubusercontent.com/6297901/29036297-46dccee8-7b75-11e7-913d-9d9e36221e0e.gif)

This happens pretty reliably on any HTML or PHP template file I open. Open a new line, write in it. When the point moves to the next line, the line I just finished writing on jumps to the right. Moving the point back one line shows it back with the proper indentation. Sometimes it takes two open lines for this to happen, but no more than that.

**Comment by fxbois** [comment]
@guilhermeasg due to the minor mode that draws a vertical line.
Should disable it for web-mode
