### ISSUE TITLE
the function `font-lock-ensure' is not known to     be defined

### ISSUE THREAD

**Issue by raoulhatterer** [fxbois/web-mode#907]
`Leaving directory `/home/hatterer/.emacs.d/elpa/web-mode-20170807.903'

Compiling file /home/hatterer/.emacs.d/elpa/web-mode-20170807.903/web-mode-pkg.el at Thu Aug 10 09:21:36 2017
Entering directory `/home/hatterer/.emacs.d/elpa/web-mode-20170807.903/'

Compiling file /home/hatterer/.emacs.d/elpa/web-mode-20170807.903/web-mode.el at Thu Aug 10 09:21:36 2017

In end of data:
web-mode.el:13007:1:Warning: the function `font-lock-ensure' is not known to
    be defined.

`

**Comment by fxbois** [comment]
@raoulhatterer which emacs version ?
