### ISSUE TITLE
Licence of web-mode

### ISSUE THREAD

**Issue by brandelune** [fxbois/web-mode#909]
Hi,

In a thread in the emacs-devel maillist, the licensing situation for emacs packages provided through Emacs package archives has been under focus. I have volunteered to contact the authors of packages that have a license that is incompatible with Emacs, which is now under GPL-3+.

See https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html

So I wonder if you could consider to change the license of your package to GPL-3+?

Yours,

Jean-Christophe Helary

**Comment by fxbois** [comment]
No pb. Could you provide a patch ?

**Comment by brandelune** [comment]
I could if all the contributors to the code agreed on the move.

@rejeep @bmalehorn @ksmadsen @asok @plumdog @ahungry @davebrown @tock203 @osv @redguardtoo @jbranso @cimocimocimo @achitu @bystrano @dunn @konnorbeard @allenluce @muihlinn @keremc @xuhdev @DoMiNeLa10 @To1ne @ciju @utkarshkukreti @lunaryorn @pavloo @dochang @p-lambert @fallchildren @xaiki @thwg @mads-hartmann @jinnovation @drazenzen @hbin @kissge @NerdGGuy @jpochyla @rye @xmaillard @jaccarmac @aethanyc @OskarPersson @bgruber @zargener @NateEag @dsedivec @jkl1337 @jilen @mgalgs @xinyijun @edslocomb @bitdeli-chef @cwebber @shigi @ancane @jinwei233 @atihonruk @tadfisher @peleteiro @itoshkov @banjo-monger @bradwright 

Would you mind giving your opinion on the move to GPL3+ please ?

Jean-Christophe

**Comment by dunn** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3.

That work?

**Comment by DoMiNeLa10** [comment]
I'm fine with my code being released under GNU GPL 3+.

**Comment by rye** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3.

**Comment by plumdog** [comment]
Fine by me.

It might be worth adding a note in the description about what the current license is and - very briefly - what the change will mean. I always have to look up what the GPL versions actually mean.

**Comment by ciju** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3.

**Comment by davebrown** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3.

**Comment by brandelune** [comment]
Thank you or the replies, but please specify "GPL3 and newer" if possible.

@xinyijun @edslocomb @bitdeli-chef @cwebber @shigi @ancane @jinwei233 @atihonruk @tadfisher @peleteiro @itoshkov @banjo-monger @bradwright

**Comment by p-lambert** [comment]
I'm fine with my code being released under GNU GPL3 and newer.

**Comment by jbranso** [comment]
I agree that you can change my contributitions to GPLv3 and newer.  (Though I only ever contributed 5 or 6 lines total).  :)

**Comment by ancane** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by bgruber** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by itoshkov** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by allenluce** [comment]
Fine by me.

**Comment by konnorbeard** [comment]
Because all the cool kids are doing it - I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by utkarshkukreti** [comment]
Although my contribution is just one actual line of code, I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by bradwright** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by achitu** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by muihlinn** [comment]
I'm fine with whatever open license is choosenEl 12 ago. 2017 6:56 p. m., brandelune <notifications@github.com> escribió:I could if all the contributors to the code agreed on the move.
@rejeep @bmalehorn @ksmadsen @asok @plumdog @ahungry @davebrown @tock203 @osv @redguardtoo @jbranso @cimocimocimo @achitu @bystrano @dunn @konnorbeard @allenluce @muihlinn @keremc @xuhdev @DoMiNeLa10 @To1ne @ciju @utkarshkukreti @lunaryorn @pavloo @dochang @p-lambert @fallchildren @xaiki @thwg @mads-hartmann @jinnovation @drazenzen @hbin @kissge @NerdGGuy @jpochyla @rye @xmaillard @jaccarmac @aethanyc @OskarPersson @bgruber @zargener @NateEag @dsedivec @jkl1337 @jilen @mgalgs @xinyijun @edslocomb @bitdeli-chef @cwebber @shigi @ancane @jinwei233 @atihonruk @tadfisher @peleteiro @itoshkov @banjo-monger @bradwright
Would you mind giving your opinion on the move to GPL3+ please ?
Jean-Christophe

**Comment by dsedivec** [comment]
I agree to having my contributions to web-mode relicensed under GNU GPL 3 or newer.

**Comment by ahungry** [comment]
i agree to licensing my contributions as gplv3 or newer

**Comment by cimocimocimo** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3.

**Comment by jkl1337** [comment]
I agree to rerelease any and all contributions under terms of the GPL version 3 or newer.

**Comment by tock203** [comment]
I hereby (re)release my contributions to web-mode under the GPL3 or newer.

**Comment by NerdGGuy** [comment]
I hereby release all current and future contributions to this repository under CC0 (https://creativecommons.org/publicdomain/zero/1.0/legalcode). 

Note: this gives anyone including @fxbois permission to license my contributions to this repository as GPLv3 or later.

**Comment by dochang** [comment]
I hereby agree to (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by jaccarmac** [comment]
I hereby release my contributions to `web-mode` under the GPL v3 or newer.

**Comment by aethanyc** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by shigi** [comment]
No problem

**Comment by xuhdev** [comment]
I hereby (re)release my contributions to web-mode under the GPL, version 3 or newer.

Honestly, I'm not sure whether this is a problem, since `web-mode` is released under `GPLv2+`, not `GPLv2`. That means, one can always redistribute `web-mode` under `GPLv3+`.

**Comment by To1ne** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by rejeep** [comment]
Fine by me

**Comment by bystrano** [comment]
OK, I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by brandelune** [comment]
Apologies. As @xuhdev commented web-mode is released under GPL2+. It is just that the reference was not caught by the script that checked the packages. I'm closing the issue. Thank you all of you who replied and sorry again for the hassle.

**Comment by zargener** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by fallchildren** [comment]
Cool stuff. I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by banjo-monger** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by peleteiro** [comment]
I hereby (re)release my contributions to web-mode under the GPL, version 3 or newer. Or whatever other license web-mode choose today and any time in the future.

**Comment by mgalgs** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by mads-hartmann** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by jilen** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by drazenzen** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by asok** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

**Comment by xinyijun** [comment]
I hereby (re)release my contributions to web-mode under the GPLv3 or newer.

2017-08-14 20:19 GMT+08:00 Adam Sokolnicki <notifications@github.com>:

**Comment by jinnovation** [comment]
I hereby (re)release my contributions to web-mode under the GPL, version 3 or newer.

**Comment by tadfisher** [comment]
I hereby (re)release my contributions to web-mode under the GPL, version 3 or newer.

**Comment by kissge** [comment]
@fxbois If you could close this issue it would be nice :) (cf. https://github.com/fxbois/web-mode/issues/909#issuecomment-322038261)

**Comment by milkypostman** [comment]
please note, it seems like the individual file says: `;; License: GNU General Public License >= 2` which seems like it should continue to be compatible with v3. but it doesn't have the full preamble. Does it even require all this?
