### ISSUE TITLE
Feature request: indentation for <!--#if --> blocks in Apache server-side includes.

### ISSUE THREAD

**Issue by dse** [fxbois/web-mode#913]
I would like to have web-mode automatically indent `<!--#if -->` blocks in Apache server-side includes, like the following example:

    <p>Zero</p>
    
      
        <p>One</p>
      
    
      <p>Two</p>
    
      <p>Three</p>
    
    <p>Four</p>

`if`, `elif`, `else`, and `endif` are the only server-side include directives that would affect indentation, as the other directives are not paired with anything.

Because server-side includes can technically be mixed with other Apache modules like PHP and mod_perl (like with Mason), though that's not often the case, I would like to see this feature implemented independent of `web-mode-engine` if possible.

I have some experience writing my own Emacs Lisp but not very much experience working with other peoples'.  I'll see if I can implement this feature myself.  Maaaaaaybe.

**Comment by fxbois** [comment]
@dse is there any specific file extension to this kind of templates ?

**Comment by dse** [comment]
Apache's documentation uses `.shtml` for its [example](https://httpd.apache.org/docs/current/howto/ssi.html#configuring) configuration.

But one site I work with enables it on all `.html` files.  It's probably an edge case though.

A variable would be best, I would imagine.

**Comment by fxbois** [comment]
@dse the last commit provides this feature

**Comment by dse** [comment]
Just writing to say thank you very much!
