### ISSUE TITLE
setup indentation for twig directive

### ISSUE THREAD

**Issue by kermorgant** [fxbois/web-mode#915]
Hello,

I'm using web-mode for twig, and need to setup indentation for content between {{ form_start(...) }} and  {{ form_end(...) }}

Is there a way to do that ?

Regards
Mikael

**Comment by fxbois** [comment]
@kermorgant is it a standard directive ?

**Comment by kermorgant** [comment]
at least when working with symfony, yes.
Here's the relevant doc : http://symfony.com/doc/current/reference/forms/twig_reference.html

**Comment by kermorgant** [comment]
amazing, thanks !!! :)
