### ISSUE TITLE
Issue with indentation on line after single-line style comment

### ISSUE THREAD

**Issue by CamJN** [fxbois/web-mode#920]
When I indent my react files, I am seeing some incorrect indentation following some lines that are `//` style comments. The indentation is increased one level where it should be the same as the previous line. Some examples are given below:

```
// different option names).
	this.template = this.createTemplatet("name", templateData);
```

```
// can happen without the filterTerm changing).
	this.curFilterTerm = "";
```

```
// For each option that we have in our template, search the received application information.
	// If not found TODO we currently mark the option for debug
```

Note that not all lines that contain `//` cause this issue, some examples of lines that do not trigger the problem below:

```
// Pass the mode and the combined dataset (all integration modes), and the result will be
// a filtered dataset specific to the integration mode, with appropriate displayNames.
createTemplate(mode, dataset) {
```

```
// TODO standalone
entry.name = option.id;
```

And the output of `web-mode-debug`:

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(25.2) web-mode("15.0.11")
vars: engine("none") minor("none") content-type("jsx") file("~/Developer/Go/src/github.com/project/src/components/views/server/ServerConfiguration.js")
system: window(nil) config("x86_64-apple-darwin16.7.0")
colors: fg(nil) bg(nil) 
minor modes: (global-eldoc-mode guru-mode shell-dirtrack-mode diff-auto-refine-mode editorconfig-mode auto-image-file-mode dynamic-completion-mode linum-mode global-linum-mode icomplete-mode osx-clipboard-mode show-paren-mode which-function-mode subword-mode global-subword-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---
```

Possibly related lines from the messages buffer:
`ad-handle-definition: ‘thing-at-point’ got redefined`
`Error in pre-command-hook (completion-before-command): (wrong-type-argument number-or-marker-p nil)`

Also of note, every affected line either follows or is part of a series of multiple lines that all start with `//` but not every such block of multiple lines that start with `//` cause the issue. And as is seen in the last "affected" example it's not always the line after the last comment line that gets the incorrect indentation, it can also be one of the comment lines itself.

**Comment by fxbois** [comment]
@CamJN please post a complete example on git

**Comment by CamJN** [comment]
https://gist.github.com/CamJN/b059ab90757f5205790572eaf22170a0

When i indent that, line 7 is indenteed 1 level too far

**Comment by fxbois** [comment]
@CamJN I can not trigger this. Can you try with an empty .emacs ?

**Comment by CamJN** [comment]
I ran `emacs -q --no-splash -nw` and copied the file contents linked above into a new buffer. I then eval'd the `web-mode.el` file at `~/.emacs.d/elpa/web-mode-20170906.214/web-mode.el` set the `major-mode` to `web-mode` and then the dialect to `jsx` using `web-mode-set-content-type`. Lastly I ran `(web-mode-use-tabs)` and reindented the file and the issue reproduced.

**Comment by fxbois** [comment]
@CamJN What triggers the bug, ```web-mode-set-content-type``` or ```web-mode-use-tabs```  ?

**Comment by CamJN** [comment]
`M+: (web-mode-use-tabs)` is enough to reproduce, don't have to set content-type.

**Comment by CamJN** [comment]
Was this fixed?
