### ISSUE TITLE
Is Auto-Complete broken?

### ISSUE THREAD

**Issue by yassinphilip** [fxbois/web-mode#921]
Hi!

Recently I noticed that I don't have any completion in web-mode buffers anymore, I tried to reset my whole elpa dir but to no avail, no matter what I do, in web-mode buffer the variable `ac-sources` is always `nil` :(

```
ac-sources is a variable defined in ‘auto-complete.el’.
Its value is nil
Local in buffer nws.html; global value is 
(ac-source-words-in-buffer ac-source-symbols ac-source-abbrev ac-source-dictionary ac-source-emacs-lisp-features ac-source-features ac-source-filename ac-source-files-in-current-dir ac-source-functions ac-source-symbols ac-source-variables ac-source-words-in-all-buffer ac-source-words-in-buffer ac-source-words-in-same-mode-buffers)
```

_But_:

```
web-mode-ac-sources-alist is a variable defined in ‘web-mode.el’.
Its value is
(("css" ac-source-words-in-buffer ac-source-css-property)
 ("html" ac-source-words-in-buffer ac-source-abbrev)
 ("jsx" ac-source-words-in-buffer ac-source-words-in-same-mode-buffers))

```

Here are [my web-mode and my ac configs](https://bitbucket.org/yassinphilip/dotfiles/src/d23da6c527783c9816dbf544392406fa45441253/.emacs?at=master&fileviewer=file-view-default#.emacs-220:255).

BTW, web-mode is *fantastic*.

**Comment by NateEag** [comment]
My auto-complete config seems to still be working as I expect. You can see it [here](https://github.com/NateEag/.emacs.d/blob/master/site-lisp/mode-configs/web-mode-init.el#L71).

I'm on `web-mode-20170822.1106` from MELPA.

I do note that I set `web-mode-before-auto-complete-hooks`, which it looks like you don't. I don't think it should be necessary, but it could be relevant.

**Comment by yassinphilip** [comment]
But... I wonder what YAS version you use:

`auto-complete error: (void-function yas-deactivate-extra-mode)`

I'm using yasnippet-20170828.1908 and web-mode-20170906.214

**Comment by yassinphilip** [comment]
Hey, I managed to [get it to work](https://bitbucket.org/yassinphilip/dotfiles/src/9cad8cd9e50ecce3acfb278570f8334a3d56242b/.emacs?at=master&fileviewer=file-view-default)! I now can enjoy `ac-source-words-in-buffer` and `ac-source-words-in-same-mode-buffers` in web-mode/JS :)

**Comment by NateEag** [comment]
Nice! Glad to be of service, and glad to hear you've got it working.
