### ISSUE TITLE
closure template engine doesn't indent {case...} blocks inside of {switch} blocks

### ISSUE THREAD

**Issue by melink14** [fxbois/web-mode#923]
versions: emacs(25.2) web-mode("13.1.9")

Currently, it auto indents {case} blocks like:

```
{switch ...}
{case ...}
   <div>Some html inside of the case</div>
{case ....}
   <content>
{/switch}
```

Some people may like that but it's pretty bad for reading. Is there a way to customize it?

I'd prefer something akin to:
```
{switch ...}
  {case ...}
     <div>Some html inside of the case</div>
  {case ....}
     <content>
{/switch}
```

**Comment by fxbois** [comment]
@melink14 I've pushed a fix
