### ISSUE TITLE
Formatting doesn't work for <template /> tags

### ISSUE THREAD

**Issue by gabrielps** [fxbois/web-mode#926]
Hello!

I was developing some .vue componentes, and ran into an issue. Vue components are files that look like this:

```
<template>
    [html code]
</template>

<script>
    [js code]
</script>

<style>
    [css code]
</style>
```

I noticed the <script/> tag and <style/> tag are getting formatted just fine, but the contents of tag <template /> don't.

Is there something that can be done?

Thank you for this outstanding mode.

**Comment by fxbois** [comment]
@gabrielps please post a full example on gist

**Comment by gabrielps** [comment]
@fxbois How can I do that?

**Comment by fxbois** [comment]
@gabrielps it works well on my side. Can you post the output of ```web-mode-debug``` please.

**Comment by gabrielps** [comment]
```
--- WEB-MODE DEBUG END ---
Applied web-beautify.
Loading /home/gabriel/.emacs.d/elpa/web-mode-20170613.959/web-mode.el (source)...done
Showing all blocks ... done
 [2 times]
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("15.0.2")
vars: engine("none") minor("none") content-type("html") file("/home/gabriel/Projects/personal/api/app/controllers/test.vue")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (hs-minor-mode global-page-break-lines-mode ido-vertical-mode global-auto-revert-mode xterm-mouse-mode global-spacemacs-leader-override-mode spacemacs-leader-override-mode evil-local-mode evil-mode undo-tree-mode global-undo-tree-mode override-global-mode which-key-mode clean-aindent-mode eval-sexp-fu-flash-mode anzu-mode global-anzu-mode evil-escape-mode show-smartparens-mode show-smartparens-global-mode evil-search-highlight-persist global-evil-search-highlight-persist evil-surround-mode global-evil-surround-mode eyebrowse-mode flx-ido-mode flycheck-mode global-flycheck-mode flycheck-pos-tip-mode Info-breadcrumbs-in-mode-line-mode linum-mode global-linum-mode persp-mode popwin-mode projectile-mode projectile-rails-mode projectile-rails-global-mode helm-flx-mode shell-dirtrack-mode helm-mode helm-descbinds-mode savehist-mode spaceline-helm-mode spaceline-info-mode vi-tilde-fringe-mode global-vi-tilde-fringe-mode volatile-highlights-mode winner-mode winum-mode hl-todo-mode ranger-override-dired-mode yas-minor-mode yas-global-mode rainbow-delimiters-mode highlight-parentheses-mode highlight-numbers-mode auto-highlight-symbol-mode bug-reference-prog-mode goto-address-prog-mode company-statistics-mode evil-matchit-mode emmet-mode async-bytecomp-package-mode global-git-commit-mode diff-auto-refine-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---

```

**Comment by fxbois** [comment]
@gabrielps don't you have this ?
![vue](https://user-images.githubusercontent.com/959622/31099709-33a5c018-a7c7-11e7-926f-76821d691ca6.png)

**Comment by gabrielps** [comment]
![selection_004](https://user-images.githubusercontent.com/1233288/31127198-70154adc-a84e-11e7-8494-f4d124371725.png)

**Comment by gabrielps** [comment]
Maybe some incompatibility with some layer??

**Comment by fxbois** [comment]
@gabrielps your screenshot shoes that everything is well formatted. I do not understand your issue.

**Comment by gabrielps** [comment]
The content of the <template> tag remains unchanged: no indents before <div> tags, and no linebreak between them. Look again the screenshot I posted :)

Also, there's something funny: your CSS doesn't gets formatted whereas mine does!

**Comment by fxbois** [comment]
@gabrielps if you hit TAB when your cursor is before the first div, the indentation does not occur ?

**Comment by gabrielps** [comment]
It **does** occur, only in normal mode, and only 1 time (if I keep pressing, nothing changes)

**Comment by fxbois** [comment]
what is normal mode ?
Could you take a little video of what happens ?

**Comment by gabrielps** [comment]
I work with emacs + evil-mode (more precisely, with spacemacs and evil-mode activated), thus the Normal mode (vim mode). Here is the video you requested.
![peek 2017-10-05 10-02](https://user-images.githubusercontent.com/1233288/31216643-9d8dca68-a9b4-11e7-9b36-b8342c5d8fbe.gif)

**Comment by fxbois** [comment]
ok understood, this function ```web-beautify-html``` is not a web-mode function. If you hit ```C-x h and TAB``` the buffer is indented. You should ask the author of ```web-beautify-html```

**Comment by gabrielps** [comment]
I just noticed im using web-beautify-html command and that it doesnt belong to your project ... Just hit me in the face. Sorry for wasting your time :S
