### ISSUE TITLE
Mixed spaces and tabs in vue components

### ISSUE THREAD

**Issue by siegy22** [fxbois/web-mode#928]
Hey, I think I just found a bug (or maybe I'm missing a configuration?) when using `web-mode` and vue.

So let's assume we have the following code

```vue
<script>
export default {
  beforeRouteEnter(from, to, next) {
    EventBus.$emit(events.RENDER_SIDEBAR, {
      view: 'items',
      items: store.getters.getItems.map(m => ( // press Enter here => tab inserted
	{
          m.title,
        }
      )),
    });
  }
};
</script>
```

If you press Enter on the Line where you call `map` with an arrow function, web-mode will insert a tab character. So usually, it will insert spaces, but within this part of the code, it doesn't.

Why is that, and how can I fix that?

**Comment by fxbois** [comment]
@siegy22 perhaps related to a minor mode ... can you try with a streamlined ```.emacs```

**Comment by fxbois** [comment]
@siegy22 please reopen when you have more info
