### ISSUE TITLE
PHP: cannot comment/uncomment: "web-mode-uncomment-php-block NOT implemented in web-mode"

### ISSUE THREAD

**Issue by dennismayr** [fxbois/web-mode#931]
Hi,

when (un)commenting PHP code with `M-m ;`, I get the following error:

    defun web-mode-uncomment-php-block NOT implemented in web-mode! Fix it or report to its maintainer.

(Using latest version of `web-mode`.)

**Comment by fxbois** [comment]
@dennismayr What minor mode triggers this message ?

**Comment by dennismayr** [comment]
I tried to find that out, trying to reproduce the problem doing the same thing while in `web-mode`, commenting/uncommenting lines on a php file, but the message doesn't pop up anymore.
(it showed up several times during this morning)

Let me test it randomly during the day, otherwise this issue can be closed.

**Comment by fxbois** [comment]
@dennismayr you can reopen if needed
