### ISSUE TITLE
Support YAML as a content type?

### ISSUE THREAD

**Issue by dmaze** [fxbois/web-mode#934]
Several systems use a mix of some templating language and YAML for their configuration.  The [Ansible](http://docs.ansible.com/ansible/latest/playbooks_templating.html) configuration management system uses YAML, but individual string values can be Jinja2 templates; [SaltStack](https://docs.saltstack.com/en/latest/topics/jinja/index.html#understanding-jinja), another configuration management system, uses Jinja2 template files that produce YAML; and the Kubernetes [Helm](https://docs.helm.sh/chart_template_guide/#template-functions-and-pipelines) system uses Go template files that produce YAML to describe Kubernetes resources.

Is it possible to add YAML as a `web-mode-content-type`?  (This is pretty tangentially in the "web" space, but web-mode distinctly seems to be the best option out there for mixed `{{template}}` and markup files.)

(Currently using web-mode 15 from melpa stable on GNU Emacs 25.3.1.)

**Comment by fxbois** [comment]
@dmaze web-mode is really linked to html.
Providing YAML compatibility would require a lot of work. Finding a company that would accept to sponsor this work would greatly help.
