### ISSUE TITLE
Unintended Atoindentation on paste

### ISSUE THREAD

**Issue by deflexor** [fxbois/web-mode#935]
Example in gif file.
Is it possible to disable this, because sometimes it's undesirable and annoying.
![1](https://user-images.githubusercontent.com/1556229/32287885-382a945e-bf43-11e7-8b07-5657637458c0.gif)

**Comment by fxbois** [comment]
Sorry, but can you explain precisely what is the problem please.

**Comment by deflexor** [comment]
The problem is when I paste some markup from clipboard, reindentation happens in other part of file.

**Comment by fxbois** [comment]
Could you try with an empty .emacs

**Comment by deflexor** [comment]
Yes, with emtpy .emacs this is not happening.

**Comment by fxbois** [comment]
You should now find the minor mode that triggers your bug

**Comment by deflexor** [comment]
I checked all minor modes and disabled electric-indentation, but this still happens, none of other minor modes look related. I tried to load file in html mode or js2 mode and it worked without issue, but only in web-mode i get this autoindentaion. I guess this line is responsible for this: https://github.com/fxbois/web-mode/blob/master/web-mode.el#L10326
