### ISSUE TITLE
Coldfusion support

### ISSUE THREAD

**Issue by cuppa-t-lager** [fxbois/web-mode#936]
Is it possible to add an additional regexp trigger for JavaScript-mode. I develop in Coldfusion, using HTML-mode when writing <cfml> tags and JavaScript-mode when inside a <cfscript></cfscript> tag. I'd like the ability to switch to JavaScript-mode automatically when inside a <cfscript></cfscript>.

**Comment by fxbois** [comment]
web-mode.el is not a multi mode. Perhaps you should ask for help on stackoverflow
