### ISSUE TITLE
Replacing buffer content resets highlighting

### ISSUE THREAD

**Issue by nickmccurdy** [fxbois/web-mode#937]
## Description
I'm integrating a program I wrote that edits HTML files into my Emacs configuration. When I call `(shell-command-on-region (point-min) (point-max) ...)`, the buffer content loses its syntax highlighting and indentation. This does not happen if I open the same file in a `sgml-mode` buffer or modify the buffer's file directly with `auto-revert-mode` enabled on the `web-mode` buffer. Even though `Web` is still displayed in my mode lighter, rerunning `web-mode` manually after replacing the buffer content fixes the formatting faces.

## Reproducing
1. Open a valid, non-empty HTML document in a `web-mode` buffer.
2. `M-: (shell-command-on-region (point-min) (point-max) "cat" nil t) RET`

## Debugging
```
--- WEB-MODE DEBUG BEG ---
versions: emacs(25.3) web-mode("15.0.15")
vars: engine("django") minor("liquid") content-type("html") file("/Users/nick/Repos/danamcc.github.io/_layouts/default.html")
system: window(ns) config("x86_64-apple-darwin13.4.0")
colors: fg(nil) bg(nil) 
minor modes: (global-eldoc-mode save-place-mode savehist-mode xterm-mouse-mode override-global-mode aggressive-indent-mode global-aggressive-indent-mode auto-revert-mode global-auto-revert-mode ivy-mode counsel-mode emmet-mode flycheck-mode global-flycheck-mode flycheck-pos-tip-mode flyspell-mode shell-dirtrack-mode async-bytecomp-package-mode global-git-commit-mode magit-auto-revert-mode diff-auto-refine-mode magit-file-mode global-magit-file-mode projectile-mode proportional-mode rainbow-mode smartparens-mode smartparens-strict-mode smartparens-global-strict-mode show-smartparens-mode show-smartparens-global-mode super-save-mode tern-mode undo-tree-mode global-undo-tree-mode global-whitespace-mode npm-mode npm-global-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by DoMiNeLa10** [comment]
Resetting `web-mode` shouldn't be necessary. `M-x font-lock-fontify-buffer` should be enough to fix font locking. I've gotten used to it whenever font-locking breaks in css buffers.

**Comment by nickmccurdy** [comment]
Thanks for your help, running `(font-lock-flush)` in Emacs Lisp after my command replaces with the buffer fixes the highlighting. It turns out that the reindentation was caused by `aggressive-indent-mode`, I'm not sure if there's a way around that with `web-mode` or if I should just disable it when replacing buffer contents.

Is it expected that replacing buffer content would break highlighting for a mode like `web-mode`, in which case this is a workaround for a bug that should still be fixed?

**Comment by fxbois** [comment]
@nickmccurdy you can call ```web-mode-reload```
