### ISSUE TITLE
PHP prefix indentation weird..

### ISSUE THREAD

**Issue by jcs090218** [fxbois/web-mode#939]
![web-mode-prefix-indent-bug](https://user-images.githubusercontent.com/8685505/32535681-107ad6f0-c496-11e7-9960-55fa6e736a32.png)

In php code block, prefix increment/decrement seems to be not indent correctly. Is there any way to fix this? Thank you!

PS, my `web-mode-code-indent-offset` is set to 2.

**Comment by fxbois** [comment]
@jcs090218 I've pushed a fix
