### ISSUE TITLE
twig comment {{ }} fails to comment adequate handlebars

### ISSUE THREAD

**Issue by kermorgant** [fxbois/web-mode#940]
Hi,

Juste stumbled on this issue while trying to comment this 

`          {{ form_widget(form.address.city, {'attr': {'class': 'form-control form-control-md'}}) }}`

This is what is being commented 

`          {#{ form_widget(form.address.city, {'attr': {'class': 'form-control form-control-md'}#}) }}`

Not a big issue, but maybe it is easy to fix.
Mikael

**Comment by fxbois** [comment]
@kermorgant should be fixed

**Comment by kermorgant** [comment]
Hi,
Sorry for late reply, but yes, it's working fine for me too now.
Thanks !
