### ISSUE TITLE
Hook for custom <script> "type" attributes?

### ISSUE THREAD

**Issue by ronburk** [fxbois/web-mode#942]
<script> is a common place to store things you're going to process as text and you need the HTML parser to leave alone. My application contains HTML that resides inside <script type="text/x-LP5">. Well, it's not precisely HTML, else the type would be "HTML", but it's plenty close enough that web-mode's HTML indentation works fine. Likewise, my application has another <script> with a custom type that happens to be near-enough to CSS. 

Any chance of adding a little hook to web-mode-scan-elements so I don't have to do a local patch to handle these custom text types?

**Comment by fxbois** [comment]
@peleteiro what is the type of your "css like" language ?

**Comment by fxbois** [comment]
@ronburk please reopen when you can provide more info
