### ISSUE TITLE
Add my own faces does not apply to this mode.

### ISSUE THREAD

**Issue by jcs090218** [fxbois/web-mode#943]
I tried to add a new face so I can highlight a few keyword I wanted, but this code does not work in web-mode. Is there a way I can customize or add the new face to this mode? Thx!

P.S. other modes work fine.

```
(setq oop-highlight-modes '(c++-mode web-mode))

(make-face 'font-lock-oop-face)

(mapc (lambda (mode)
        (font-lock-add-keywords
         mode
         '(("\\<\\(TODO\\)" 1 'font-lock-oop-face t)
           )))
      oop-highlight-modes)
```

**Comment by fxbois** [comment]
perhaps look at #566
