### ISSUE TITLE
JSX multiline variable indentation

### ISSUE THREAD

**Issue by vxcamiloxv** [fxbois/web-mode#944]
I don't know if exist way to change this with own emacs indentation properties ('c-set-offset') or is related to web-mode.

When multiline variable the indentation with web-mode is:

```javascript
const varTest = hasKey(data, 'test.type') && data.test.type === 'test' ? "isTest" : 
                (hasKey(data, 'data.pest.name') && otheVar === data.test.name ? "otherTest" : null);

const isTest = hasKey(data, 'test.type') && data.test.type === 'test' &&
               hasKey(data, 'data.pest.name') && otheVar === data.test.name;
```

but if you set *eslint* to `indent = 2` show errors because expect 2 indentation spaces, like this:

```javascript
const varTest = hasKey(data, 'test.type') && data.test.type === 'test' ? "isTest" : 
  (hasKey(data, 'data.pest.name') && otheVar === data.test.name ? "otherTest" : null);

const isTest = hasKey(data, 'test.type') && data.test.type === 'test' &&
  hasKey(data, 'data.pest.name') && otheVar === data.test.name;
```

make sense if you set the indentation to 2 spaces the next line in multiline variables will be also 2 spaces.

**Comment by fxbois** [comment]
@vxcamiloxv what are the related c-set-offset options that deal with this kind of customisation ?

**Comment by vxcamiloxv** [comment]
@fxbois `(add-to-list 'web-mode-indentation-params '("lineup-ternary" . nil))` fixed my problem and put the indentation like the second example, thanks
