### ISSUE TITLE
JSDoc comment highlight support

### ISSUE THREAD

**Issue by vxcamiloxv** [fxbois/web-mode#945]
Would be cool is add support for http://usejsdoc.org/ comments.

Thanks for you great work.

**Comment by fxbois** [comment]
could you post a full example on gist please.

**Comment by vxcamiloxv** [comment]
Example: https://gist.github.com/vxcamiloxv/96d2649c5b691ddeb6855178a005060c

**Comment by fxbois** [comment]
@vxcamiloxv some code have been pushed
Use ```(setq web-mode-enable-comment-annotation t)```

**Comment by vxcamiloxv** [comment]
thanks, I test over emacs 25 and see some changes, but without color highlights
![screenshot from 2018-01-22 15-34-06](https://user-images.githubusercontent.com/14242544/35243403-bcaa20be-ff8a-11e7-9f2f-051153b56b06.png)

**Comment by fxbois** [comment]
It is up to you to customise the faces : web-mode-annotation-tag-face, web-mode-annotation-type-face
