### ISSUE TITLE
Compilation warning: looking-back

### ISSUE THREAD

**Issue by wyuenho** [fxbois/web-mode#946]
web-mode.el:10678:12:Warning: looking-back called with 1 argument, but
    requires 2-3

**Comment by fxbois** [comment]
@wyuenho the master version should be ok

**Comment by NetMage** [comment]
I got this error message when I compiled web-mode.el which I downloaded from the current project page's download link:

https://raw.github.com/fxbois/web-mode/master/web-mode.el
