### ISSUE TITLE
<script type="text/jsx"> code inherits html indentation when html elements in code

### ISSUE THREAD

**Issue by vapidlyrapid** [fxbois/web-mode#948]
if I have code that's pure JavaScript between script tags, I have no issues.  But the moment I add something like 

```
const El = (props) => (
  <div></div>
);
```
all of the code between the script tags lose indentation, with the exception of the DOM elements in the jsx formatted file.  I've also tried setting the type attribute value to "text/babel" and I get the identical unwanted behavior.

**Comment by fxbois** [comment]
@vapidlyrapid could explain more accurately your issue please (step by step)
perhaps attach a screenshot of the issue

**Comment by fxbois** [comment]
@vapidlyrapid please reopen when you can provide more info
