### ISSUE TITLE
JS prefix indentation weird..

### ISSUE THREAD

**Issue by jcs090218** [fxbois/web-mode#951]
You had fixed the PHP prefix indentation(<a href="https://github.com/fxbois/web-mode/issues/939">#939</a>), I just notice this also happen in JS block.

**Comment by fxbois** [comment]
@jcs090218 could you give me more info please (steps to trigger this issue)

**Comment by jcs090218** [comment]
When editing javascript inside html file, inside the 'script' tag.
By hitting 'indent-for-tab-command', prefix ++ operation will still be indent. On the other hand, postfix ++ operation seems to be indent correctly.

In the following gif file, '++hello' indent incorrectly, but 'hello++' indentation is fine.

![ezgif-4-6a88da56ad](https://user-images.githubusercontent.com/8685505/35015746-b2b9bc7e-fb50-11e7-9be1-036baa89c7e3.gif)

**Comment by fxbois** [comment]
@jcs090218 can not trigger this ... perhaps you do not have the last version of web-mode

**Comment by jcs090218** [comment]
Mine web-mode version is 20180116. Is this the latest version? And this still happens...

**Comment by jcs090218** [comment]
Okay, if this isn't a bug. I fixed it my own.
