### ISSUE TITLE
React-16.2.0 fragments are not supported

### ISSUE THREAD

**Issue by ojab** [fxbois/web-mode#952]
React-16.2.0 [introduced `React.Fragment`](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html), which can be written as `<></>`.
web-mode-20171118.1132 doesn't recognize it as a valid JSX syntax and indentation/etc is broken if fragments are used.

**Comment by fxbois** [comment]
@ojab the last commit should solve this

**Comment by ojab** [comment]
Thanks, work fine.
