### ISSUE TITLE
Django tags break syntax highlighting

### ISSUE THREAD

**Issue by rakanalh** [fxbois/web-mode#957]
Hello,

I noticed that syntax highlighting when web-mode is activated and the engine is set to django.
Example:
```
<html>
  <head>
  </head>
  <body>
    {{ var }}
  </body>
</html>
```
But when adding `{% extends 'base.html' %}`, at the top of the file, syntax highlighting breaks and shows everything highlighted in "red". Some tags show an error of "syntax error" or "Unterminated regular expression literal".

**Update:** 
using web-mode latest version `web-mode-20171118.1132`. 
Emacs version:
GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2017-10-15

**Comment by fxbois** [comment]
@rakanalh I can't trigger the issue. Please try with an empty .emacs

**Comment by rakanalh** [comment]
I tried by running:
`emacs -Q` and then installing web-mode from MELPA. I also couldn't reproduce the issue. Is there a way to figure out why i see this syntax error in my setup using some web-mode diagnostics?

**Comment by fxbois** [comment]
Try to add new statements gradually in your .emacs

**Comment by rakanalh** [comment]
For the record, `js2-minor-mode` was causing the issue. Disabling that solves the issue.
