### ISSUE TITLE
Allow for custom comments for sass/scss

### ISSUE THREAD

**Issue by mrcoles** [fxbois/web-mode#958]
I would love to be able to add a configuration to my `web-mode` settings like this:

```lisp
(add-to-list 'web-mode-comment-formats '("scss" . "//"))
```

The idea here is that *.scss files would use `// …` instead of `/* … */` to comment blocks. This could also be preferred for *.less file too.

Digging into the code I see that the `web-mode-comment-insert` function associates `web-mode-comment-formats` with known languages using the `web-mode-language-at-pos` function, which returns "css" for *.scss files.

Are there any thoughts on handling these types of files differently than vanilla css? Alternatively is there a configuration I could insert that would achieve this an alternative way?

Also, just in case, my `web-mode-debug`:

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(25.3) web-mode("15.0.15")
vars: engine(nil) minor(nil) content-type("") file("/Users/peter/scratch/web-mode/web-mode.el")
system: window(nil) config("x86_64-apple-darwin17.0.0")
colors: fg(nil) bg(nil)
minor modes: (global-eldoc-mode show-paren-mode save-place-mode global-auto-revert-mode savehist-mode winner-mode subword-mode global-subword-mode guide-key-mode diff-auto-refine-mode)
vars:
web-mode-enable-current-column-highlight=nil
web-mode-enable-current-element-highlight=nil
indent-tabs-mode=nil
```

**Comment by mrcoles** [comment]
Actually as a workaround for now, I’m going to just make it the default for all css and just try to remember not to comment actual css files that way!

```lisp
(add-to-list 'web-mode-comment-formats '("css" . "//"))
```

**Comment by fxbois** [comment]
```(add-to-list 'web-mode-comment-formats '("css" . "//"))``` should work with last commit
