### ISSUE TITLE
JavaScript: #959 next, Regular Expressions internal single quotes in switch stetement are not highlighted correctly

### ISSUE THREAD

**Issue by ncaq** [fxbois/web-mode#961]
It is the continuation of #959

I confirmed that I was cured in part.
However, I was not cured on my code.
After investigating a little, I found that the character string quote is erroneously recognized when putting the regular expression inside the switch.
I reopen the issue.
I do not know the cause.

example code

~~~js
const a = ["I'm", "foo"];

switch (true) {
  case /I'm foo/.test(a.join(' ')):
    console.log(true);
    break;
}
~~~

The syntax highlight of this code will also break on GitHub.
But this code is correct JavaScript code.

screenshot

![screenshot-2018-02-08-11-24-41](https://user-images.githubusercontent.com/2913112/35952395-2421444e-0cc3-11e8-8078-ad8a15fb2769.png)

web-mode-debug

~~~text
--- WEB-MODE DEBUG BEG ---
versions: emacs(25.3) web-mode("15.0.23")
vars: engine("none") minor("none") content-type("javascript") file("/home/ncaq/Documents/archive/2018-02/w.js")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (global-eldoc-mode rainbow-delimiters-mode volatile-highlights-mode savehist-mode desktop-save-mode save-place-mode auto-image-file-mode anzu-mode global-anzu-mode auto-complete-mode global-auto-complete-mode flycheck-mode global-flycheck-mode git-gutter-mode global-git-gutter-mode async-bytecomp-package-mode helm-mode helm-descbinds-mode diff-auto-refine-mode shell-dirtrack-mode auto-sudoedit-mode symbolword-mode editorconfig-mode yas-minor-mode yas-global-mode smartparens-mode smartparens-global-mode show-smartparens-mode show-smartparens-global-mode undo-tree-mode global-undo-tree-mode global-whitespace-mode recentf-remove-sudo-tramp-prefix-mode)
vars:
web-mode-enable-current-column-highlight=t 
web-mode-enable-current-element-highlight=t 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
~~~

**Comment by fxbois** [comment]
@ncaq should be solved

**Comment by ncaq** [comment]
I also looked at the Emacs Lisp code a bit but I do not know how to solve it.
As a workaround for the time being, I converted the quotes inside the regular expression literal into dots.
In our production code it did not matter but people who really need quotes may be in trouble.
