### ISSUE TITLE
web-mode is not derived from prog-mode

### ISSUE THREAD

**Issue by tttuuu888** [fxbois/web-mode#964]
First of all, I really appreciate for this great package.
I recently found out that web-mode is not properly derived from prog-mode.
I have tested like below.

1. start emacs.
2. open 'test.test' file.
3. M-x web-mode
4. M-: to evaluate (derived-mode-p 'prog-mode)
5. result says nil

Looks like the alias of web-mode-prog-mode is not working well when the alias is used for define-derived-mode.
The result of (derived-mode-p 'prog-mode) said prog-mode when I changed web-mode define as below.

(define-derived-mode web-mode prog-mode "Web" ...)

I tested this on GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.30) in Ubuntu 16.04.

Thanks a lot!

**Comment by DoMiNeLa10** [comment]
I don't like this as well, because it means hooks for `prog-mode` don't get executed in `web-mode` buffers.
