### ISSUE TITLE
void-function web-mode-define-derived-mode

### ISSUE THREAD

**Issue by DoMiNeLa10** [fxbois/web-mode#966]
Byte-compiling `web-mode` and then loading it with an autoload file causes the following error:
```
Debugger entered--Lisp error: (void-function web-mode-define-derived-mode)
  (web-mode-define-derived-mode web-mode "Web" "Major mode for editing web templates." (make-local-variable (quote web-mode-attr-indent-offset)) (make-local-variable (quote web-mode-attr-value-indent-offset)) (make-local-variable (quote web-mode-auto-pairs)) (make-local-variable (quote web-mode-block-regexp)) (make-local-variable (quote web-mode-change-beg)) (make-local-variable (quote web-mode-change-end)) (make-local-variable (quote web-mode-code-indent-offset)) (make-local-variable (quote web-mode-column-overlays)) (make-local-variable (quote web-mode-comment-formats)) (make-local-variable (quote web-mode-comment-style)) (make-local-variable (quote web-mode-content-type)) (make-local-variable (quote web-mode-css-indent-offset)) (make-local-variable (quote web-mode-display-table)) (make-local-variable (quote web-mode-django-control-blocks)) (make-local-variable (quote web-mode-django-control-blocks-regexp)) (make-local-variable (quote web-mode-enable-block-face)) (make-local-variable (quote web-mode-enable-inlays)) (make-local-variable (quote web-mode-enable-part-face)) (make-local-variable (quote web-mode-enable-sexp-functions)) (make-local-variable (quote web-mode-engine)) (make-local-variable (quote web-mode-engine-attr-regexp)) (make-local-variable (quote web-mode-engine-file-regexps)) (make-local-variable (quote web-mode-engine-open-delimiter-regexps)) (make-local-variable (quote web-mode-engine-token-regexp)) (make-local-variable (quote web-mode-expand-initial-pos)) (make-local-variable (quote web-mode-expand-initial-scroll)) (make-local-variable (quote web-mode-expand-previous-state)) (make-local-variable (quote web-mode-indent-style)) (make-local-variable (quote web-mode-indentless-attributes)) (make-local-variable (quote web-mode-indentless-elements)) (make-local-variable (quote web-mode-inhibit-fontification)) (make-local-variable (quote web-mode-is-scratch)) (make-local-variable (quote web-mode-jshint-errors)) (make-local-variable (quote web-mode-last-enabled-feature)) (make-local-variable (quote web-mode-markup-indent-offset)) (make-local-variable (quote web-mode-minor-engine)) (make-local-variable (quote web-mode-overlay-tag-end)) (make-local-variable (quote web-mode-overlay-tag-start)) (make-local-variable (quote web-mode-part-beg)) (make-local-variable (quote web-mode-scan-beg)) (make-local-variable (quote web-mode-scan-end)) (make-local-variable (quote web-mode-sql-indent-offset)) (make-local-variable (quote web-mode-time)) (make-local-variable (quote comment-end)) (make-local-variable (quote comment-region-function)) (make-local-variable (quote comment-start)) ...)
  eval-buffer(#<buffer  *load*-914470> nil "/home/user/.emacs.d/lisp/autoloads.el" nil t)  ; Reading at buffer position 9704
  load-with-code-conversion("/home/user/.emacs.d/lisp/autoloads.el" "/home/user/.emacs.d/lisp/autoloads.el" nil nil)
  load("/home/user/.emacs.d/lisp/autoloads.el")
  mapc(load ("/home/user/.emacs.d/lisp/haskell-mode/autoloads.el" "/home/user/.emacs.d/lisp/impatient-mode/autoloads.el" "/home/user/.emacs.d/lisp/js2/autoloads.el" "/home/user/.emacs.d/lisp/local/autoloads.el" "/home/user/.emacs.d/lisp/skewer/autoloads.el" "/home/user/.emacs.d/lisp/autoloads.el"))
  eval-buffer(#<buffer  *load*> nil "/home/user/.emacs.d/init.el" nil t)  ; Reading at buffer position 110
  load-with-code-conversion("/home/user/.emacs.d/init.el" "/home/user/.emacs.d/init.el" t t)
  load("/home/user/.emacs.d/init" t t)
  #[0 "\205\266
```

This problem seems to be caused by use of the `eval-and-compile` macro [here](https://github.com/fxbois/web-mode/blob/6b0b329ab5342a142d7cb2419e22278ff73ba557/web-mode.el#L2356), more specifically by [these lines](https://github.com/fxbois/web-mode/blob/6b0b329ab5342a142d7cb2419e22278ff73ba557/web-mode.el#L2378-L2383).

**Comment by tttuuu888** [comment]
I am sorry since this error is caused by my commit.

Looks like we cannot avoid this error when replacing
'define-derived-mode' to 'web-mode-define-derived-mode'. 
Because 'web-mode-define-derived-mode' part is auto loaded before the
definition of the macro is loaded.

I have shortly searched how the other packages have dealt with this
matter.  Many packages simply supports prog-mode only.
In case as yasnippet, they simply repeated 'define-derived-mode' for
prog-mode and fundamental-mode with if-else(for snippet-mode). 
However this is not likely suitable for us because the body of
'define-derived-mode' is too long.

Since web-mode even supports Emacs version below 23, I think this
should be solved properly for both of 'prog-mode' and 'fundamental-mode'. 
I will also continue to look for ways to solve this problem.

**Comment by fxbois** [comment]
@tttuuu888 I let you look at the issue

**Comment by DoMiNeLa10** [comment]
I think it would be a good idea to deprecate older version of Emacs, considering how old they are. Compatibility with versions older than 23 makes very little sense, considering the [package declaration](https://github.com/fxbois/web-mode/blob/6b0b329ab5342a142d7cb2419e22278ff73ba557/web-mode.el#L9). Definitions of newer functions are probably available in packages.

In general, these problems stem from the fact that `defmacro` and `defun` should be top-level statements, and not having them as such will break things. Unfortunately, things get hairy when things are defined as aliases or macros conditionally. I'm having trouble to get things to work properly and have everything compile without warnings because of this.

**Comment by fxbois** [comment]
I do not try to maintain compatibility with versions bellow 23.1

**Comment by tttuuu888** [comment]
prog-mode is introduced from Emacs 24.1 so if we do not have to support Emacs below 24.1, using prog-mode for define-derived-mode for web-mode would be the simple and best solution.

Though there are still some alias left for supporting Emacs below 24, this might be simple solution..

**Comment by fxbois** [comment]
There is no reason to drop compatibility with emacs >= 23.1
If there is no solution we should revet the patch.

**Comment by tttuuu888** [comment]
If we revert patch, 'web-mode' will not be derived from prog-mode again. I just asked new pull request. It does not look like the best answer but it works and support for Emacs below 24 as well. 
I would like request some tests and confirmation.
