### ISSUE TITLE
Twirl/Scala symbols aren't terminated properly

### ISSUE THREAD

**Issue by teozkr** [fxbois/web-mode#968]
Scala's (and by extension Twirl's) Symbol type is has the grammar `'<ident>` (in addition to the character literal syntax `'<char>'`), while web-mode seems to assume the scripting language convention of `'[^']'` being roughly equivalent to `"[^"]"`.

This shouldn't cause conflicts with C#/Razor, since I don't believe they have any equivalent syntax.

**Comment by fxbois** [comment]
@teozkr could you post an example on gist ?

**Comment by teozkr** [comment]
@a('foo, 'bar)

should be highlit the same as

    @a("foo", "bar")

but is highlit as

    @a("foo, "bar)

**Comment by fxbois** [comment]
@teozkr could you find on the web a page that explains how I can differentiate a string and a symbol.

**Comment by teozkr** [comment]
The Scala spec has a lexical grammar that covers both: https://www.scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html

That said, Scala strings are always double-quoted (or sextuple-quoted for multiline strings), so it's "only" a matter of distinguishing between character literals and symbols.

I believe all allowed character literals should be covered by the following regex:
```regex
'([^'\\]|\\[bfntr"'\\]|\\[0-7]{1,3}|\\u[0-9a-fA-F]{4})'
```

Symbols should be covered by adding an optional ' before the current ident/variable regex.

Character literals have higher priority than symbols, so `'a'b` is parsed as `Char('a'), Ident("b")`, not `Symbol("a"), Symbol("b")`.

**Comment by fxbois** [comment]
@teozkr C# and Scala, single quotes are used for characters and not strings ... is it ok ?

**Comment by teozkr** [comment]
Yes.

**Comment by fxbois** [comment]
@teozkr I've pushed a fix

**Comment by teozkr** [comment]
Great, thanks!

**Comment by teozkr** [comment]
Can confirm that it works beautifully now.

![image](https://user-images.githubusercontent.com/649832/36448012-748de80c-1686-11e8-850b-990535e33e46.png)

Thanks, once again!
