### ISSUE TITLE
Treat "{{-" the same as "{{" and "-}}" the same as "}}" when auto-indenting [Go templates]

### ISSUE THREAD

**Issue by kaushalmodi** [fxbois/web-mode#970]
Hello,

I use Go templates for configuring my Hugo-generated blog's layout.

As we know, Go templates use `{{` and `}}` for delimiters.

But since Go 1.6, `{{-` and `-}}` are valid delimiters too.

From [here][1],

> Go 1.6 includes the ability to trim the whitespace from either side of a Go tag by including a hyphen (`-`) and space immediately beside the corresponding `{{` or `}}` delimiter.

### Problem

This auto-indents fine:

```html
{{ with .Title }}
    {{ . }}
{{ end }}
```

This does not:

```html
{{- with .Title }}
    {{ . }}
{{ end }}
```

Trying to auto-indent above removes all indentation, and results in:

```html
{{- with .Title }}
{{ . }}
{{ end }}
```

**The `{{-` and `-}}` do not even have to be paired.**

This is also legal:

```html
{{ with .Title -}}
    {{- . }}
{{- end }}
```

*I tried looking through the code but could not figure out what part to update to fix this.*

### `web-mode-debug` output

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(27.0) web-mode("15.0.27")
vars: engine("go") minor("gtl") content-type("html") file("/home/kmodi/temp/foo.html")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (window-divider-mode global-eldoc-mode show-paren-mode shell-dirtrack-mode override-global-mode modi-mode mode-line-space-mode shackle-mode beacon-mode engine-mode async-bytecomp-package-mode global-git-commit-mode diff-auto-refine-mode hi-lock-mode global-hi-lock-mode volatile-highlights-mode hungry-delete-mode global-hungry-delete-mode keyfreq-mode keyfreq-autosave-mode global-page-break-lines-mode undo-tree-mode global-undo-tree-mode which-function-mode eros-mode smart-mark-mode winner-mode minibuffer-depth-indicate-mode save-place-mode diff-hl-mode desktop-save-mode projectile-mode which-key-mode ivy-mode hardcore-mode global-hardcore-mode minibuffer-line-mode auto-complete-mode global-auto-complete-mode ace-window-display-mode pdf-occur-global-minor-mode TeX-PDF-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

[1]: https://gohugo.io/templates/introduction/#whitespace

**Comment by kaushalmodi** [comment]
OK, I spent some time debugging, but I will need some help here.. 

- for the line `{{ with .Title }}`, `web-mode-element-is-opened` returns `t`.
- but for the line `{{- with .Title }}` (with that hyphen after braces), `web-mode-element-is-opened` returns `nil`.

That function looks very cryptic.. can you help me figure out how to make that fn return `t` for `{{- with .Title }}`?

**Comment by kaushalmodi** [comment]
That works for me, thanks! I got very close to that solution, but then ended up losing all fontification as I was tweaking `web-mode-go-font-lock-keywords`.

Do you have tips on how to tweak that variable?

**Comment by fxbois** [comment]
@kaushalmodi what do you want to do ?

**Comment by kaushalmodi** [comment]
I was just trying to fix this issue myself before you committed the fix.. but failed miserably.. I think it was this part: https://github.com/fxbois/web-mode/blob/38b7bc215fefbd2e01d25892c9579fc60a29627d/web-mode.el#L2898-L2902

**Comment by fxbois** [comment]
It is not obvious but it was needed to add ```"go"``` in the list on line 3288

https://github.com/fxbois/web-mode/blob/38b7bc215fefbd2e01d25892c9579fc60a29627d/web-mode.ell#L3288
