### ISSUE TITLE
web-mode indents code inside pre element

### ISSUE THREAD

**Issue by shivshankardayal** [fxbois/web-mode#972]
Mighty thanks for such a nice mode.

Please tell me how to tell web-mode not to indent text inside <pre></pre> elements.

**Comment by fxbois** [comment]
@shivshankardayal update ```web-mode-indentless-elements```

**Comment by paxperscientiam** [comment]
@fxbois Hate to resurrect a dead issue, but there is a bug(?) here. Child elements of `pre` are not indentless. Is there a way to override this?


Whereas the desired indentation is something like this:
```html
    <body class="crt">
        <pre>
... searching
... searching
... searching
<output>File not found</output>
<input type="text" />
        </pre>
    </body>
```

The mode indicates that indentation should be like this:
```html
        <pre>
... searching
... searching
... searching
            <output>File not found</output>
            <input type="text" />
        </pre>
    </body>
```

Thanks.
