### ISSUE TITLE
web-mode not a prog-mode after #966 fix

### ISSUE THREAD

**Issue by ojab** [fxbois/web-mode#973]
`GNU Emacs 25.3.1 (x86_64-redhat-linux-gnu) of 2017-09-14` here, after https://github.com/fxbois/web-mode/commit/b758c7d2a6204c00ef3089815819ec57148d0a61 web-mode doesn't load prog-mode hooks. Works fine with that commit reverted.

**Comment by ojab** [comment]
(I've tried web-mode from git master, 91f4a58efba1f3ddf687eb3e6051df92443d0d7c to be exact)

**Comment by DoMiNeLa10** [comment]
@ojab that "fix" broke autoloading because of how it was implemented. It seems that the best approach will be to just attempt to unroll the macro rather than making a mess like what that commit got rid of. I'll have my crack at trying to make it work later.

**Comment by zw963** [comment]
i found the same issue, i have add all my prog hook add again to web mode

2018年3月2日 上午1:08，"DoMiNeLa10" <notifications@github.com>写道：

**Comment by tttuuu888** [comment]
@fxbois Ok I will take a look at this issue.

**Comment by tttuuu888** [comment]
@ojab @DoMiNeLa10 @zw963  Could you tell me how you tested it?
I tested in the following order.

1. open a test buffer.
2. M-x web-mode
3. M-: (derived-mode-p 'prog-mode)
4. the result says "prog-mode"

My emacs version is GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.30) of 2017-09-12
and I tested with web-mode-20180226.812 from melpa.

**Comment by ojab** [comment]
Yeah, `(derived-mode-p 'prog-mode)` returns `prog-mode` indeed. The issue is — no prog-mode hooks are run nevertheless.

**Comment by DoMiNeLa10** [comment]
@tttuuu888 You're right when it comes to your test — `web-mode` claims to be derived from `prog-mode` like it should.

However, it doesn't run `prog-mode-hook`s, which is easy to test with the following snippet:

```
(add-hook 'prog-mode-hook (lambda () (message "prog-mode derived")))
```
This message won't pop up in the messages buffer after creating a `web-mode` buffer.

**Comment by tttuuu888** [comment]
Thanks for your replies.
This is my fault. As you said, prog-mode-hook for web-mode was working fine before my commit although web-mode is not derived from prog-mode.

I confused because my emacs setting was using not prog-mode-hook but something like '(when (derived-mode-p 'prog-mode)...'

I think this could be totally solved with reverting my commit except the part at the end of '(define-derived-mode web-mode)'.

Then prog-mode-hook for web-mode would work as it used to be and web-mode would remain derived from prog-mode.

I will make a pull request soon.
This time, please help me to check any missing or wrong part of my commit.

Thanks.

**Comment by fxbois** [comment]
@tttuuu888 let's revert ...

I think I'll drop emacs <= 24.1 compatibility with web-mode v16. We'll able to use prog-mode more easily

**Comment by tttuuu888** [comment]
@fxbois @ojab @DoMiNeLa10  @zw963  Please check my pull request. This is almost same as reverted version except the part making web-mode derived from prog-mode.

Well, if there is still something wrong, then it would be better to revert it instead of my pull request.
Thanks.

**Comment by ojab** [comment]
Works find here, thanks for the quick fix.

**Comment by tttuuu888** [comment]
@ojab  It is my pleasure. Thanks you for the test.

**Comment by DoMiNeLa10** [comment]
#974 works and doesn't seem to break autoloading. I'm glad this issue finally got properly resolved.

**Comment by tttuuu888** [comment]
@DoMiNeLa10 Very glad to hear that. Thanks for the test.

**Comment by zw963** [comment]
It worked now. :+1:
