### ISSUE TITLE
[twig] missing indentation of else clause in for loop 

### ISSUE THREAD

**Issue by kermorgant** [fxbois/web-mode#975]
Hello,

Twig has an "else" clause for its "for" tag (see https://twig.symfony.com/doc/2.x/tags/for.html#the-else-clause).

Its indentation is not as expected
![image](https://user-images.githubusercontent.com/10561580/36965705-1decec1e-2063-11e8-8d35-f247fd11d482.png)

Again, not a big issue, but  I thought I'd mention it as it would be nice if that was handled.

**Comment by fxbois** [comment]
@kermorgant are you sure you have the latest version of web-mode ? 
I do not have the issue here

**Comment by kermorgant** [comment]
Just updated packages (using spacemacs btw), and from what I experienced, I would say the issue is partially solved : now, when indenting the buffer or region containing the for loop, the {% else %} clause is left as is (not indented as the rest of the code, but it's not moved on the left as in the screenshot).

Does it work the same for you or is the "else" correctly indented ?

**Comment by kermorgant** [comment]
I checked again (as I had some local issues with my emacs setup) and I'm back to the original behaviour.
I'll have to take some time to review my config before taking this further as I suspect the problem is on my side...
