### ISSUE TITLE
[twig] wrong comment of {% delimiters

### ISSUE THREAD

**Issue by kermorgant** [fxbois/web-mode#976]
Hello,

Again a small thing : commenting an expression withn {% and %} delimiters is not done as expected.

Comment should start with `{#` but instead, it adds `{% /*`

![image](https://user-images.githubusercontent.com/10561580/36968034-0b378cbc-206a-11e8-9a76-0fe97f6d82bc.png)

For information, that happens in spacemacs develop branch.

**Comment by fxbois** [comment]
@kermorgant you do not seem to have the latest version

**Comment by kermorgant** [comment]
Indeed, I was using 20180303.1031, sorry.

But now on  web-mode 20180305.1059, I get the same issue.
![image](https://user-images.githubusercontent.com/10561580/37081102-12b244fe-21f1-11e8-96f6-c6381d2d5266.png)

**Comment by fxbois** [comment]
Please describe very accurately all the steps you follow

**Comment by kermorgant** [comment]
ok, here are some more details as I suspect there might be something spacemacs specific 

First write this :` {% if 1 == 1 %}`
have cursor between  `{% ` and `%}`

Then,

Calling spacemacs/comment-region-or-buffer SPC c l), which what I used as the source of this issue, gives this
![image](https://user-images.githubusercontent.com/10561580/37082046-1de48c8a-21f4-11e8-8dd9-d34412d026e5.png)
(doing it again gives the screenshot from the previous comment)

Calling web-mode-comment-or-uncomment (M-;) gives this
![image](https://user-images.githubusercontent.com/10561580/37082214-90c33dc8-21f4-11e8-8cbd-2e8367247c19.png)


Calling web-mode-comment-or-uncomment-region outpouts this : funcall-interactively: Wrong number of arguments: #[(beg end &optional arg) "Ã!	bÄÅ Æ )" [end beg mark-active push-mark t web-mode-comment-or-uncomment pop-mark] 2 nil nil], 0

**Comment by fxbois** [comment]
try ```^-;```

**Comment by kermorgant** [comment]
My bad, it works now as it should. Not sure why though...
If the fix was in the upgrade, then maybe I did not restart properly emacs. If not, maybe some mess with local project settings...
Anyway, sorry for the noise and thanks again.
