### ISSUE TITLE
Indentation after "alternative" php control structures breaks in some cases

### ISSUE THREAD

**Issue by mbroe** [fxbois/web-mode#978]
## Description

When using PHP ["alternative" control structures](https://secure.php.net/manual/en/control-structures.alternative-syntax.php) (e.g. `endif;`) indentation has some unexpected results when these control structures appear within a contiguous php block.  Here is what I would expect to happen:

```
<?php
if (true):
    echo '<p>True is true!</p>';
else:
    echo '<p>My grasp on reality is slipping</p>';
endif;
?>
```

And here's what actually happens:

```
<?php
if (true):
echo '<p>True is true!</p>';    // This line should be indented, but is not
else:
     echo '<p>My grasp on reality is slipping</p>';
endif;
?>
```

This issue does _not_ seem to occur when the control structure is followed by a PHP closing tag:

```
<?php if (true): ?>
    <p>True is true!</p>
<?php else: ?>
    <p>My grasp on reality is slipping</p>
<?php endif; ?>
```

## Gist
https://gist.github.com/mbroe/830ab4f74833190864ae8e4ab7500a58

## Output of `M-x web-mode-debug`

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(25.1) web-mode("16.0.0")
vars: engine("php") minor("php") content-type("html") file("/home/mitchell/Downloads/test.php")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (global-eldoc-mode display-battery-mode fortune-cookie-mode helm-mode immortal-scratch-mode projectile-mode server-mode xclip-mode async-bytecomp-package-mode shell-dirtrack-mode global-git-commit-mode magit-auto-revert-mode diff-auto-refine-mode pdf-occur-global-minor-mode company-mode global-company-mode)
vars:
web-mode-enable-current-column-highlight=t 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

Please let me know if anything is unclear or if there is anything I can do to help.

**Comment by fxbois** [comment]
@mbroe the fix might be difficult. I would advice to prefer normal blocks (```{}```) in this case.
