### ISSUE TITLE
Avoid greedily uncommenting lines starting with `//`

### ISSUE THREAD

**Issue by modulitos** [fxbois/web-mode#980]
### Expected:

When I want to uncomment a line that has a comment inside of it, for example:

```
// // this is a comment
```

the inner comment should be preserved, which should show a comment like so:

```
// this is a comment
```

### Actual:

Instead, the inner comment is uncommented as well, causing our original comment:

```
// // this is a comment
```

to become this:

```
this is a comment
```

### Proposal to fix:

I think we should limit the number of `//` comments that are removed to only the first match per line.

**Comment by monnier** [comment]
Not sure what's the source of the problem, but Emacs's normal `uncomment-region` seems to do what you want, so maybe web-mode doesn't currently use `(un)comment-region` and the fix is to teach it to use those built-in facilities?
