### ISSUE TITLE
Prevent escaping some entities

### ISSUE THREAD

**Issue by mvolfik** [fxbois/web-mode#985]
If I write some code in HTML, which contains `&lt;`, and then do `C-c C-d n` (Dom --> normalize), web mode replaces it with `<`, which is bad, because if I write `&lt;`, I write it because I want it to display, not to be a part of code. This also applies to `>` and `&` (and something else?).

`versions: emacs(24.5) web-mode("15.0.0")`

mvolfik (***GitHub newbie***)

P.S.: Web-Mode dropdown menu --> Dom says "normali**s**e", is it OK? :smiley:

**Comment by fxbois** [comment]
@mvolfik you're right. It is now fixed
