### ISSUE TITLE
blade indentation not working for child elements in @component block

### ISSUE THREAD

**Issue by oakular** [fxbois/web-mode#990]
As can be seen in the attached image, any child elements of a `@component` block are not indented as they ought to be. This is also happening for `@slot` elements.

I am running the latest version of web-mode from MELPA

![image](https://user-images.githubusercontent.com/18057553/39178447-a5c9f4ac-47a9-11e8-9c08-c86feab47231.png)

**Comment by fxbois** [comment]
@oakular are ```@slot``` and ```@component``` standard control blocks like ```@if``` ?

**Comment by oakular** [comment]
@fxbois they are more similar to `@section` blocks in their functionality but are part of the base Blade framework

[Here](https://laravel.com/docs/5.6/blade#components-and-slots) is the documentation

**Comment by fxbois** [comment]
@oakular should be fixed on master

**Comment by oakular** [comment]
@fxbois great! just tested it and everything works as expected, cheers!
