### ISSUE TITLE
Add an option for auto closing tags as a self tag 

### ISSUE THREAD

**Issue by ar1a** [fxbois/web-mode#991]
I'm moving over to web-mode from https://github.com/felipeochoa/rjsx-mode and wondering if it would be possible to add the behaviour rjsx-mode has?

When I type `<` it'll insert `< />` and when i type `>` before the / it'll open the tag.

for example:
```
<div class="foo" |/>
I type >
<div class="foo">|</div>
```

**Comment by fxbois** [comment]
@ar1a Could you test the last version on master ?

**Comment by gainhad** [comment]
@fxbois I just tested this and it doesn't seem to work as expected. There is always an extra closing bracket left.

**Comment by DoMiNeLa10** [comment]
What about being able to add a closing tab when typing `C-d` at the `/` of a self closing tag? I've wanted to implement this feature in `web-mode`, as I really enjoy using it in `rjsx-mode`, but I've never gotten around to it.

For example, with point where `|` is:
```
<div|/>
```
Typing `C-d` (which is normally bound to `delete-char`) would result in:
```
<div>|</div>
```
