### ISSUE TITLE
possible to combine web-mode and ng2-mode?

### ISSUE THREAD

**Issue by jmcmichael** [fxbois/web-mode#996]
I primarily work with Angular templates, and I've noticed that web-mode has difficulty with expressions within tag attributes - it doesn't do syntax highlighting and interprets equal signs as attribute name endings and inserts a double-quote after them. There exists a major mode, [ng2-mode](https://github.com/AdamNiederer/ng2-mode), that does a good job with syntax highlighting and dealing with expressions. However, it lacks many functions that web-mode provides.

Is there a way of using both modes at once so I can get the benefits of ng2-mode's syntax highlight but with web-mode's formatting, transient mode, and other features?

Thank you for developing such a useful mode, I use it daily!

**Comment by fxbois** [comment]
Can you take screenshots that illustrate the nice features of ng2-mode ?

**Comment by jmcmichael** [comment]
Sure, here's a template I'm working on currently. Highlighting features include:
- angular attributes styled differently from HTML5 attributes
- expressions within curly brackets styled (it would be nice if attribute expressions were too, not sure why the mode doesn't do that)

![screen shot 2018-05-11 at 11 21 36 am](https://user-images.githubusercontent.com/132909/39935131-a1efa018-550d-11e8-857f-8b358c5407fa.png)

When I'm using web-mode and using javascript object syntax to within an attribute, the mode inserts a double quote after I type an equal sign. This qualifies as a bug that deserves its own issue, perhaps?

![screen shot 2018-05-11 at 11 25 39 am](https://user-images.githubusercontent.com/132909/39935461-ad49b420-550e-11e8-8cb9-a4f597839df1.png)

Its syntax highlighting seems to be pretty straightforward:

https://github.com/AdamNiederer/ng2-mode/blob/master/ng2-html.el
