### ISSUE TITLE
Feature request: enable full html mode for Polymer "html" tagged template literals (backticks)

### ISSUE THREAD

**Issue by digint** [fxbois/web-mode#999]
First off, thanks for this very useful mode!

[Polymer 3.0](https://www.polymer-project.org/3.0/docs/about_30) defines a "html" tagged template, like this:

```JavaScript
// Define the element's template
static get template() {
  return html`
    <style>
      .response { margin-top: 10px; } 
    </style>
    <paper-checkbox checked="{{liked}}">I like web components.</paper-checkbox>

    <div hidden$="[[!liked]]" class="response">Web components like you, too.</div>
  `;
}
```

While web-mode enables html indentation within template literals (backticks), it would be great if full html mode was enabled for this special case.

Note that in Polymer 99% of all the HTML code is in HTML templates. Polymer 3.0 has moved from HTML Imports to ES6 Modules, so that all templates have to be defined within JavaScript code.

**Comment by fxbois** [comment]
What do you mean by « full » ?
What you are asking for is very difficult to do. I would prefer to continue to simulate some basic fearures

**Comment by ebaker** [comment]
I wanted to check in on this as it might apply to tagged template literals used in [styled-components](https://www.styled-components.com) with React. An example of a `styled-component` in JSX would be:

```
import styled from 'styled-components';

const StyledDiv = styled.div`
  color: red;
  border: 1px solid black;
  padding: 10px;
`;
```

Basically CSS is added through a tagged template literal. I have limited knowledge of configuring `web-mode` and am using spacemacs.

Is it currently possible in web-mode to have the CSS attributes be indented below the styled component? Is it possible to get CSS syntax highlighting within the styled-component's tagged template literal?

Thanks!

**Comment by vxcamiloxv** [comment]
same question about styled-components

**Comment by jaccarmac** [comment]
@fxbois I've only taken a very cursory look at the code, but it seems like these blocks could be treated like any other kind of block is by the various engines. Is that not the case?
